Core/Api/Client.GraphqlClientOperations.cs
Core/Api/Client.cs
Core/Api/Models.cs
IntegrationTests/RemoteOps.cs

- removes dependency on account manager
- fixes the stream grant/revoke permission tests & implementation

Integration Tests Upgrades

---

Core/Api/Client.GraphqlClientOperations.cs
Core/Api/Models.cs
Core/Core.csproj
Core/Kits/ISpeckleKit.cs
Core/Kits/KitDeclaration.cs
Core/Kits/KitManager.cs
Examples/Program.cs
IntegrationTests/Utils.cs
Tests/Kits.cs
Tests/TestKit.cs

WIP at the moment. Please hold.

feat(kits): adds methods for converter loading from kits

---

Core/Api/Client.GraphqlClientOperations.cs
Core/Api/Models.cs
IntegrationTests/Api.cs

Adds `StreamSearch` and `UserSearch` to the available GraphQL client operations. Tests for these methods have also been added.
This includes adding `StreamsData`, `UserSearch`, and `UserSearchData` models.

GraphQL Client Operations: Add User & Stream Search

---

Core/Serialisation/BaseObjectSerialzerUtilities.cs

fix(deserialisation): checks generic types inside lists

---

Core/Core.csproj
Core/Transports/Memory.cs
Core/Transports/SQLite.cs
DiskTransport/DiskTransport.cs
ServerTransport/Server.cs
Tests/SendReceiveLocal.cs

TODOs: Server Transport. Waiting to implement it in a GH component to understand what's needed (if anything)

fix(transports): minor fixes in transport initialisation defaults & ToString overrides

---

Core/Serialisation/BaseObjectSerializer.cs
Core/Serialisation/BaseObjectSerialzerUtilities.cs
Tests/SerializationTests.cs
Tests/TestKit.cs

adds one new test case to cover this

fix(interfaces): handles interfaces when deserialising

---

IntegrationTests/Subscriptions/Commits.cs

Seems the problem was caused because the server transport never got a streamId, and the server upload route refuses to work without one (for good reason). 
The send operation, being rather lax, was not throwing an error directly, it was invoking the `onErrorAction` which was not set in the tests.

Fixes failing tests

---

Core/Logging/Log.cs
Core/Logging/Setup.cs
Core/Logging/Tracker.cs

as discussed with @teocomi
BREAKING CHANGE: any connectors relying on track event should now switch to track page view

fix(logging): removes events, modfies string constants

---

DesktopUI/DesktopUI/Utils/StreamState.cs

quick fix for my silly mistake oops!

fix(subs): pass if created commit is a match

---

Objects/Converters/ConverterRevit/ConverterRevitShared/ConversionUtils.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/Opening.cs
Objects/Objects/BuiltElements/Opening.cs

fix(objects/revit): fixes opening tests

---

Core/.gitignore
DesktopUI/DesktopUI/Bootstrapper.cs
DesktopUI/DesktopUI/Streams/Dialogs/FilterViews/CategoryFilterView.xaml
DesktopUI/DesktopUI/Streams/Dialogs/FilterViews/CategoryFilterView.xaml.cs
DesktopUI/DesktopUI/Streams/Dialogs/ShareStreamDialogView.xaml
DesktopUI/DesktopUI/Streams/Dialogs/ShareStreamDialogViewModel.cs
DesktopUI/DesktopUI/Streams/StreamCreateDialogView.xaml
DesktopUI/DesktopUI/Streams/StreamUpdateObjectsDialogViewModel.cs
DesktopUI/DesktopUI/Streams/StreamView.xaml
DesktopUI/DesktopUI/Streams/StreamViewModel.cs
DesktopUI/DesktopUI/Streams/StreamsRepository.cs
DesktopUI/DesktopUI/Utils/Converters.cs
DesktopUI/DesktopUI/Utils/SelectionFilter.cs
DesktopUI/DesktopUI/Utils/StreamDialogBase.cs
DesktopUI/DesktopUI/Utils/StreamState.cs

This improves the terrible combo boxes UI 
Add collaborators:
This has been improved by simplifying the dialog to a single combo box that allows you to search for users and select one to add. The "add" button can has a dropdown for choosing the collaborator's role.
Select filters: 
This has been improved by getting rid of the old combo boxes and replacing them with a multiselect list box.
bonus: rounds out the avatars and uses the same robots as frontend for users with no avatar

🍱 Combo boxes: improve UI for adding collaborators and selecting filters

---

DesktopUI/DesktopUI/DesktopUI.csproj
DesktopUI/DesktopUI/Streams/AllStreamsViewModel.cs
DesktopUI/DesktopUI/Streams/Dialogs/BranchCreateDialogView.xaml
DesktopUI/DesktopUI/Streams/Dialogs/BranchCreateDialogViewModel.cs
DesktopUI/DesktopUI/Utils/StreamState.cs
DesktopUI/DesktopUI/Utils/ViewModelFactories.cs

- removes placeholder branch create functionality from stream state
- add branch create dialog view and viewmodel to handle branch creation
- handles opening the create dialog and awaiting the new branch
to switch to from the `AllStreamsViewModel`

🌿 Branch create dialog for DesktopUi

---

ConnectorRhino/ConnectorRhino.csproj
ConnectorRhino/packages.config
Objects/Converters/ConverterDynamo/ConverterDynamo/ConverterDynamo.csproj

- Added missing package to `ConnectorDynamo` project.
- Upgraded Rhino connector package.config to PackageReference
- Removed redundant nuget checks from Rhino connector csproj file

Fix Dynamo and Rhino build fail in CI

---

.circleci/config.yml

theoretically updates to respect new ~~server~~ speckle-web repo structure

Integration tests

---

ConnectorGrasshopper/ConnectorGrasshopper/Transports/Transports.Sqlite.cs

Also hardcoded default values into input parameters so they would show up on hover.
Fixes #133

fix(gh): Corrected default db in sql transport component

---

Core/Core/Api/GraphQL/Client.GraphqlClientOperations.cs
Core/Core/Api/GraphQL/Models.cs
DesktopUI/DesktopUI/Streams/StreamCreateDialogView.xaml

- add the new `role` field to the stream models and queries in core
- display role in the desktop ui when searching for a stream to add 
closes #141

🎲 DesktopUI: Show User's Role In Stream Search Results

---

ConnectorDynamo/ConnectorDynamo.sln
ConnectorDynamo/ConnectorDynamoFunctions/ConnectorDynamoFunctions.csproj
ConnectorDynamo/ConnectorDynamoFunctions/Transport.cs

Added function nodes for:
- DiskTransport
- MemoryTransport
- ServerTransport
- SQLiteTransport
Fixes #78

feat(dyn): Added nodes for transports

---

.circleci/config.yml
Core/Core/Api/GraphQL/Models.cs
Core/Core/Api/GraphQL/SubscriptionModels.cs
Core/IntegrationTests/Api.cs
Core/IntegrationTests/Fixtures.cs
Core/IntegrationTests/Subscriptions/Branches.cs
Core/IntegrationTests/Subscriptions/Commits.cs
Core/IntegrationTests/Subscriptions/Streams.cs

For future reference: 
- check nullability of optional fields! we don't control much the serialiser used by the graphql lib - this is what was borking the commit updates.
- less [copy pastes](https://github.com/specklesystems/speckle-sharp/blob/5126453b1d3e12e17aa70ff67c2de9d85298fae2/Core/Core/Api/GraphQL/Models.cs#L64) - nasty incorrect declaration.

test(integration): updates user registration fixture in integration tests

---

DesktopUI/DesktopUI/Settings/SettingsView.xaml
DesktopUI/DesktopUI/Settings/SettingsViewModel.cs
DesktopUI/DesktopUI/Utils/Converters.cs

This updates the links in the settings page and gets rid of some old logic.
It also makes sure to handle avatars correctly by supporting both bitmaps and url strings for the image source

🖼 DesktopUI Settings Page / Avatar Fixes

---

ConnectorRevit/ConnectorRevit/UI/ConnectorBindingsRevit.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/ConversionUtils.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertWall.cs

fix(revit): fixes bug on wall update basecurve location

---

ConnectorGrasshopper/ConnectorGrasshopper/Accounts/Accounts.AccountDetails.cs
ConnectorGrasshopper/ConnectorGrasshopper/Accounts/Accounts.ListAccounts.cs
ConnectorGrasshopper/ConnectorGrasshopper/Conversion/Convert.ToNativeAsync.cs
ConnectorGrasshopper/ConnectorGrasshopper/Conversion/Convert.ToSpeckleAsync.cs
ConnectorGrasshopper/ConnectorGrasshopper/Conversion/Serialisation.DeserializeObject.cs
ConnectorGrasshopper/ConnectorGrasshopper/Conversion/Serialisation.SerialiseObject.cs
ConnectorGrasshopper/ConnectorGrasshopper/Ops/Operations.ReceiveComponent.cs
ConnectorGrasshopper/ConnectorGrasshopper/Ops/Operations.ReceiveLocalComponent.cs
ConnectorGrasshopper/ConnectorGrasshopper/Ops/Operations.SendComponent.cs
ConnectorGrasshopper/ConnectorGrasshopper/Ops/Operations.SendLocalComponent.cs
ConnectorGrasshopper/ConnectorGrasshopper/Streams/StreamCreateComponent.cs
ConnectorGrasshopper/ConnectorGrasshopper/Streams/StreamDetailsComponent.cs
ConnectorGrasshopper/ConnectorGrasshopper/Streams/StreamGetComponent.cs
ConnectorGrasshopper/ConnectorGrasshopper/Streams/StreamListComponent.cs
ConnectorGrasshopper/ConnectorGrasshopper/Streams/StreamUpdateComponent.cs
DesktopUI/DesktopUI/Bootstrapper.cs
DesktopUI/DesktopUI/Streams/AllStreamsViewModel.cs
DesktopUI/DesktopUI/Streams/Dialogs/ShareStreamDialogViewModel.cs
DesktopUI/DesktopUI/Streams/StreamViewModel.cs

- gh is using the core string constants for tracking where poss
- gh and dyn now track as many of the same things as poss
- desktopui has been fixed slightly to conform with the other connectors / web

🛰 Consolidate tracking across connectors

---

Objects/Converters/ConverterDynamo/ConverterDynamoShared/ConverterDynamo.Units.Revit.cs

Dynamo for Revit not working in 2020.
- Fixes #256
Please describe the tests that you ran to verify your changes.

fix(dynamo): fixes #256

---

ConnectorDynamo/ConnectorDynamo/ReceiveNode/Receive.cs
ConnectorDynamo/ConnectorDynamo/ReceiveNode/ReceiveUi.xaml
ConnectorDynamo/ConnectorDynamo/SendNode/Send.cs
ConnectorDynamo/ConnectorDynamo/SendNode/SendUi.xaml
ConnectorGrasshopper/ConnectorGrasshopper.sln
ConnectorGrasshopper/ConnectorGrasshopper/ConnectorGrasshopper.csproj
ConnectorGrasshopper/ConnectorGrasshopper/Ops/Operations.ReceiveComponent.cs
ConnectorGrasshopper/ConnectorGrasshopper/Ops/Operations.SendComponent.cs
ConnectorRhino/ConnectorRhino/UI/ConnectorBindingsRhino.cs
DesktopUI/DesktopUI/Streams/AllStreamsView.xaml
DesktopUI/DesktopUI/Utils/Helpers.cs
DesktopUI/DesktopUI/Utils/StreamState.cs
Objects/Converters/ConverterRhinoGh/ConverterRhinoGh/ConverterRhinoGh.Geometry.cs

This PR makes all sending and receiving progress bars indeterminate and removes percentages from progress reporting.
- Fixes #260 #143 
Please describe the tests that you ran to verify your changes.

Progress reporting fix

---

DesktopUI/DesktopUI/Streams/StreamUpdateObjectsDialogViewModel.cs

fix(desktopui): #275 deselct list based filters

---

Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.DBObjects.cs
Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.Geometry.cs

- fixed closed periodic weighted spline conversion to native
Changes: **Autocad** converter spline and polycurve `ToNative` conversions
Fix:
- Polycurve ToNative conversion is now checking for arc segment bulge direction, which fixes both of the polycurve receiving conversions from the Rhino StandardGeometry test stream.
- Spline ToNative conversion removes extra control points, knots, and weights for **closed periodic nurbs curves** to fit the autocad format.
- Total Points:
- standard (closed nurbs): # control pts + degree
- autocad (closed periodic nurbs): # control pts
- Knots:
- standard: # total pts + degree + 1
- autocad (closed periodic nurbs): # control pts + 1
Notes:
- Issue #300 report item 3 is NOT resolved: (polyline::02-5-5.3d vertical segments collapsed to 2d). This will …

fix(autocad): polycurve arc segment and weighted closed nurbs bugs

---

ConnectorGrasshopper/ConnectorGrasshopper/SchemaBuilder/CreateSchemaObject.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/ConverterRevit.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/ConverterRevitShared.projitems
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/UpdateParameter.cs
Objects/Objects/BuiltElements/Revit/ParameterUpdater.cs

- Fixes #333
Manual Tests:
- updating params from gh to revit
- plugging empty lists in schema builder components
- No updates needed (the schema builder param updater will be part of new tutorials we make)

Schemabuilder

---

Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertBuildingPad.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertCeiling.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertFloor.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertMeshUtils.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertRailing.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertRoof.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertRoom.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertStair.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertWall.cs

- Fixes issue with Mesh units in Revit
- Manual Tests

fix(revit): mesh unints

---

Core/Core/Models/DynamicBase.cs
Core/Tests/BaseTests.cs

revert(core): reverts #396

---

ConnectorDynamo/ConnectorDynamo/SendNode/Send.cs

- fix(dynamo): invalide message on send

fix(dynamo): invalide message on send

---

Core/Core/Logging/Log.cs
Core/Core/Logging/Setup.cs
Core/Examples/Program.cs

refractor: simplifies sentry logging

---

ConnectorDynamo/ConnectorDynamo/ReceiveNode/ReceiveViewCustomization.cs
ConnectorDynamo/ConnectorDynamo/SendNode/Send.cs
ConnectorDynamo/ConnectorDynamo/SendNode/SendViewCustomization.cs
Core/Examples/Program.cs

feat(dynamo): adds context menu to see streams online #330

---

ConnectorDynamo/ConnectorDynamo/CreateStreamNode/CreateStreamViewCustomization.cs

- adds view stream online to create stream node
- Have already been updated

feat(dynamo): adds view stream online to create stream node

---

ConnectorAutocadCivil/ConnectorAutocadCivil/Entry/SpeckleAutocadCommand.cs
ConnectorRevit/ConnectorRevit/Entry/App.cs
ConnectorRevit/ConnectorRevit/Entry/SpeckleRevitCommand.cs
ConnectorRevit/ConnectorRevit/UI/ConnectorBindingsRevit.Receive.cs
ConnectorRevit/ConnectorRevit/UI/ConnectorBindingsRevit.cs
ConnectorRhino/ConnectorRhino/ConnectorRhinoCommand.cs
DesktopUI/DesktopUI/App.xaml
DesktopUI/DesktopUI/App.xaml.cs
DesktopUI/DesktopUI/Bootstrapper.cs
DesktopUI/DesktopUI/DesktopUI.csproj

Upgrades Stylet and removes reliance on `Application`.
Delegate for progress while converting on receive is borked tho (see latest commit in which you're tagged), but maybe teo has a magic wand and knows why it's borked now? If not, I will investigate further.
- Fixes #408
- Manual Tests in revit

Revit: Fix borkage with Rhino.Inside

---

ConnectorGrasshopper/ConnectorGrasshopper/Conversion/Convert.ToNativeAsync.cs
ConnectorGrasshopper/ConnectorGrasshopper/Conversion/Convert.ToSpeckleAsync.cs
ConnectorGrasshopper/ConnectorGrasshopper/Loader.cs
ConnectorGrasshopper/ConnectorGrasshopper/Objects/CreateSpeckleObject.cs
ConnectorGrasshopper/ConnectorGrasshopper/Objects/SelectKitAsyncComponentBase.cs
ConnectorGrasshopper/ConnectorGrasshopper/Objects/SelectKitComponentBase.cs

- Fixes unhandled exceptions on grasshopper startup for the Loader and the `ObjectManagement` component.
- Left all the `Ops` nodes and `SchemaBuilder` unfixed to be able to identify if/when this error happens and if the fix works.
- Manual Tests - Pending confirmation from Jeroen on this
- No updates needed yet

GH: Partial fix for loading issue in components using Kits

---

DesktopUI/DesktopUI/Streams/Dialogs/ShareStreamDialogView.xaml
DesktopUI/DesktopUI/Streams/Dialogs/ShareStreamDialogViewModel.cs

adds an option to open the email invite ui in the frontend 
closes #152 
- Manual Tests in standalone and Revit

feat(desktopui): email invites

---

ConnectorDynamo/ConnectorDynamo.sln
ConnectorDynamo/ConnectorDynamoFunctions/BatchConverter.cs
ConnectorDynamo/ConnectorDynamoFunctions/Functions.cs
ConnectorDynamo/ConnectorDynamoFunctions/Utils.cs
ConnectorRevit/ConnectorRevit.sln
ConnectorRevit/ConnectorRevit/ConnectorRevit.projitems
ConnectorRevit/ConnectorRevit/ConnectorRevitUtils.cs
ConnectorRevit/ConnectorRevit/RevitVersionHelper.cs
ConnectorRevit/ConnectorRevit/UI/ConnectorBindingsRevit.Selection.cs
ConnectorRevit/ConnectorRevit/UI/ConnectorBindingsRevit.cs
ConnectorRevit/ConnectorRevit2022/ConnectorRevit2022.csproj
ConnectorRevit/ConnectorRevit2022/Properties/AssemblyInfo.cs
Core/Core/Kits/Applications.cs
Objects/Converters/ConverterDynamo/ConverterDynamoRevit2021/ConverterDynamoRevit2021.csproj
Objects/Converters/ConverterDynamo/ConverterDynamoRevit2021/Properties/launchSettings.json
Objects/Converters/ConverterDynamo/ConverterDynamoRevit2022/ConverterDynamoRevit2022.csproj
Objects/Converters/ConverterDynamo/ConverterDynamoRevit2022/Properties/launchSettings.json
Objects/Converters/ConverterDynamo/ConverterDynamoShared/ConverterDynamo.Units.cs
Objects/Converters/ConverterDynamo/ConverterDynamoShared/ConverterDynamo.cs
Objects/Converters/ConverterDynamo/ConverterDynamoShared/ConverterDynamoShared.projitems
Objects/Converters/ConverterRevit/ConverterRevit2022/ConverterRevit2022.csproj
Objects/Converters/ConverterRevit/ConverterRevit2022/Properties/launchSettings.json
Objects/Converters/ConverterRevit/ConverterRevitShared/ConversionUtils.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/ConverterRevit.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertGeometry.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/Units.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/RevitVersionHelper.cs

- Add support for Revit & Dynamo 2022

Revit & Dynamo 2022

---

Objects/Converters/ConverterRevit/ConverterRevitShared/ConversionUtils.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/ConverterRevit.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertGeometry.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertView.cs
Objects/Converters/ConverterRhinoGh/ConverterRhinoGh.BuiltElements.cs
Objects/Objects/BuiltElements/View.cs

Adds ToNative view conversion for Revit. Also fixes a threading issue for named view creation in Rhino.
- Revit isometric views are buggy when received in Rhino, as well as Revit to Rhino perspective view aspect ratio. Comments included on potential avenues of improvement
- Fixes #440 
- Manual Tests: sent views in every combination for Rhino and Revit

feat(revit): adds ToNative view conversion

---

DesktopUI/DesktopUI/Streams/AllStreamsView.xaml
DesktopUI/DesktopUI/Streams/AllStreamsViewModel.cs
DesktopUI/DesktopUI/Streams/StreamCreateDialogView.xaml
DesktopUI/DesktopUI/Streams/StreamCreateDialogViewModel.cs

- Fixes #409, #459, and #465
- Manual tests in desktopui and rhino

feat(desktopui): various fixes and issues 

---

ConnectorGrasshopper/ConnectorGrasshopper/Conversion/Convert.ToNativeAsync.cs
ConnectorGrasshopper/ConnectorGrasshopper/Conversion/Convert.ToSpeckleAsync.cs
ConnectorGrasshopper/ConnectorGrasshopper/Extras/Speckle.IGH_Goo.cs
ConnectorGrasshopper/ConnectorGrasshopper/Extras/Utilities.cs
ConnectorGrasshopper/ConnectorGrasshopper/Objects/CreateSpeckleObjectAsync.cs
ConnectorGrasshopper/ConnectorGrasshopper/Objects/CreateSpeckleObjectByKeyValueAsync.cs
ConnectorGrasshopper/ConnectorGrasshopper/Objects/ExpandSpeckleObjectAsync.cs
ConnectorGrasshopper/ConnectorGrasshopper/Objects/ExtendSpeckleObjectAsync.cs
ConnectorGrasshopper/ConnectorGrasshopper/Objects/GetObjectValueByKeyAsync.cs
ConnectorGrasshopper/ConnectorGrasshopper/Objects/SelectKitAsyncComponentBase.cs
ConnectorGrasshopper/ConnectorGrasshopper/Ops/Operations.SendComponent.cs
Objects/Converters/ConverterRhinoGh/ConverterRhinoGh.Geometry.cs

- Partial changes for issue #468 
- Manual Tests: Created a test file to ensure all conversions were succeeding. File can be found in drive Standard Testing folder -> https://drive.google.com/file/d/1gJYLy3N7VVo8qKxYflKMV-MfGDaCrIb4/view?usp=sharing
- Will be updated ASAP, issue already on the board for other pending GH updates.

GH: Object Management nodes now have "Do not convert" option.

---

Core/Core/Serialisation/BaseObjectSerializer.cs
Core/Tests/SerializationTests.cs

- Fixes #379
Why is this important? Well should shave a couple of 10000s of objects every day or so from someone sending meshes. 
Added unit tests in core. 

WIP: No more empty chunks

---

Core/Core/Serialisation/BaseObjectSerializer.cs
Core/Tests/SerializationTests.cs

Reverts specklesystems/speckle-sharp#489 pending tree investigations

Revert "WIP: No more empty chunks"

---

Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertBlock.cs

Adds nested blocks to Revit converter: they are converted as nested generic model families
- Fixes #466 
- Manual Tests: sent blocks from rhino standard test file to revit

feat(revit): add nested block conversions

---

Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertRoof.cs

- partially addresses #498 
- Bug fix 
- Manual Tests to and from revit

fix(revit): roof slope angle in rad not degrees!

---

DesktopUI/DesktopUI/Streams/Dialogs/ShareStreamDialogView.xaml
DesktopUI/DesktopUI/Streams/Dialogs/ShareStreamDialogViewModel.cs

Changes old "link sharing" behaviour to a public/private toggle

Stream visibility setting in DesktopUI

---

Core/Core/Credentials/StreamWrapper.cs

fix: #520 dynamo error on save&  reopen

---

ConnectorRevit/ConnectorRevit/ConnectorRevitUtils.cs

Revit DEU hotfix

---

Core/Core/Credentials/StreamWrapper.cs
Core/Tests/Wrapper.cs

support globals in stream wrapper
NOTE: noticed bugs receiving globals - will be looking at that now
- Fixes #561 
- Unit/Integration Tests: new tests in core
- Manual Tests

feat(core): support globals in stream wrapper

---

Core/Core/Api/Helpers.cs

- adds source app and total children count to Helpers.Send

feat(core): adds source app and total children count to Helpers.Send

---

ConnectorGrasshopper/ConnectorGrasshopper/SchemaBuilder/CreateSchemaObject.cs
ConnectorGrasshopper/ConnectorGrasshopper/SchemaBuilder/CreateSchemaObjectBase.cs

Fixes #564 with @clairekuang's help 🙌🏼
Added `ShallowCopy` to prevent the node from backwards updating and that seemed to fix it.
Not really sure what the root of the issue was, but I'm happy now.

GH: Fix Freeform Element node.

---

ConnectorGrasshopper/ConnectorGrasshopper/Objects/ExpandSpeckleObjectTaskComponent.cs
ConnectorGrasshopper/ConnectorGrasshopper/Ops/Operations.ReceiveComponent.cs

Also fixed issue with Expand Speckle node running when null values where input.

Hotfix: Receiver not handling commit urls properly

---

ConnectorRhino/ConnectorRhino/BIMElements/BIMElementCommands.cs
ConnectorRhino/ConnectorRhino/UI/ConnectorBindingsRhino.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/ConversionUtils.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertAdaptiveComponent.cs
Objects/Converters/ConverterRhinoGh/ConverterRhinoGh.BuiltElements.cs
Objects/Converters/ConverterRhinoGh/ConverterRhinoGh.Utils.cs
Objects/Converters/ConverterRhinoGh/ConverterRhinoGh.cs

Adds Revit Adaptive Components to Rhino BIM. 
- "CreateAdaptiveComponent" command and toolbar icon added
- Command allows sequential adaptive component creation
- Makes a block instance and definition for every set of points, and attaches the SpeckleSchema user attribute text
- Fixes #613 
- Manual Tests: sent adaptive components created with the sample revit family file from gh to revit tutorial

Rhino: adaptive components

---

Objects/Converters/ConverterRevit/ConverterRevitShared/ConversionUtils.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/UpdateParameter.cs
Objects/Objects/BuiltElements/Revit/ParameterUpdater.cs

feat: improves param setting from excel

---

DesktopUI/DesktopUI/Settings/SettingsViewModel.cs

fix(desktopui): update docs and forum links

---

Core/Core/Api/GraphQL/Models.cs
Core/Core/Api/Helpers.cs

feat(core): sets default sourceApplication =  'c#'

---

Core/Core/Api/GraphQL/Models.cs
Core/Core/Api/Helpers.cs

refractor(core): renames default source app ".net"

---

DesktopUI/DesktopUI/Settings/SettingsView.xaml
DesktopUI/DesktopUI/Settings/SettingsViewModel.cs

Add tutorials to help links 
- Fixes #669 

feat(desktopui): update help links

---

ConnectorRevit/ConnectorRevit/Entry/App.cs
ConnectorRevit/ConnectorRevit/Entry/HelpCommand.cs

feat(revit): adds shortcut to manager

---

ConnectorGrasshopper/.config/dotnet-tools.json
ConnectorGrasshopper/ConnectorGrasshopper.sln
ConnectorGrasshopper/ConnectorGrasshopper/ConnectorGrasshopper.csproj
ConnectorGrasshopper/ConnectorGrasshopper/SchemaBuilder/CreateSchemaObject.cs
ConnectorGrasshopper/ConnectorGrasshopper/SchemaBuilder/CreateSchemaObjectBase.cs
ConnectorGrasshopper/ConnectorGrasshopper/SchemaBuilder/CreateSchemaObjectDialog.cs
ConnectorGrasshopper/ConnectorGrasshopper/SchemaBuilder/SchemaBuilderGen.cs
ConnectorGrasshopper/ConnectorGrasshopper/SchemaBuilder/SchemaBuilderGen.tt
ConnectorGrasshopper/ConnectorGrasshopperUtils/CSOUtils.cs
ConnectorGrasshopper/ConnectorGrasshopperUtils/ConnectorGrasshopperUtils.csproj
ConnectorGrasshopper/ConnectorGrasshopperUtils/Properties/AssemblyInfo.cs
ConnectorGrasshopper/README.md

- Fixes #618
Templates are now built automatically every time a restore is performed.
Myself and @teocomi made sure it actually works in both our machines.
- Have already been updated (readme)

T4 template automation

---

.circleci/config.yml
ConnectorGrasshopper/ConnectorGrasshopper/ConnectorGrasshopperInfo.cs

- Fixes issue with CI where the actual build was not being executed unless a release was requested.
- CI seems to be working again

CI: Fixes build step

---

DesktopUI/DesktopUI/RootView.xaml
DesktopUI/DesktopUI/RootViewModel.cs

feat(desktopui): adds help button with link to forum

---

ConnectorDynamo/ConnectorDynamoExtension/SpeckleExtension.cs
Core/Core/Logging/Tracker.cs

fix: disables tracking on debug & some improvments

---

ConnectorAutocadCivil/ConnectorAutocadCivil/Entry/App.cs
ConnectorAutocadCivil/ConnectorAutocadCivil/Entry/SpeckleAutocadCommand.cs
ConnectorAutocadCivil/ConnectorAutocadCivil/Storage/SpeckleStreamManager.cs
ConnectorAutocadCivil/ConnectorAutocadCivil/UI/ConnectorBindingsAutocadCivil.cs

Acad/Civil: fixes for Autodesk store

---

Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.cs

Added model curve to native conversion
Part of #680 

Acad civil: additional conversions

---

ConnectorDynamo/ConnectorDynamo/CreateStreamNode/CreateStreamViewCustomization.cs
ConnectorDynamo/ConnectorDynamo/ReceiveNode/ReceiveViewCustomization.cs
ConnectorDynamo/ConnectorDynamo/SendNode/SendViewCustomization.cs

- Fixes weird issue in Dynamo due to context menu separator

fix(dynamo): disables context menu separator

---

ConnectorAutocadCivil/ConnectorAutocadCivil/UI/ConnectorBindingsAutocadCivil.cs
ConnectorRevit/ConnectorRevit/UI/ConnectorBindingsRevit.cs

fix: adsk store fixes

---

Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertDirectShape.cs

Modified the `DirectshapeToSpeckle` method to return all values as meshes.

RVT: Fixes bug preventing Mesh direct shapes from being  properly converted.

---

Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.DBObjects.cs

Attributes are attached directly to instances (I believe this helps with dynamic blocks).
Also includes minor polyline fix for closed polylines where the .Closed prop returns false.
- Fixes #718 
- Manual Tests: tested on mucahit's file

feat(acad): added attributes to block instances

---

Core/Core/Serialisation/BaseObjectSerializerV2.cs
Core/Tests/SerializationTests.cs

Compute id for all base objects

---

ConnectorGrasshopper/ConnectorGrasshopper/Ops/Operations.ReceiveComponent.cs
ConnectorGrasshopper/ConnectorGrasshopper/Ops/Operations.SendComponent.cs

Fixes specklesystems/admin#183

GH: Remove send/receive "Added" tracking

---

DesktopUI/DesktopUI/DesktopUI.nuspec

fix: updates dui nuspec

---

ConnectorAutocadCivil/ConnectorAutocadCivil/UI/ConnectorBindingsAutocadCivil.cs

Minor refactor of autocad connector receive: commit id of latest throwing exception
- 
- Manual Tests

fix(acad): refactor latest commit during receive

---

ConnectorAutocadCivil/ConnectorAutocadCivil/UI/ConnectorBindingsAutocadCivil.cs

Deletes relevant blocks before re-receiving same commit from DUI1

fix(acad): blocks no longer duplicated when receiving same commit

---

ConnectorRevit/ConnectorRevit/Entry/App.cs

due to several fatal crashes, it was decided to remove the dui2 button for this release (2.2.4). dui2 will be reintroduced when it is more stable

feat(revit): temporarily remove dui2 button

---

ConnectorRevit/ConnectorRevit/Entry/App.cs

Reverts specklesystems/speckle-sharp#841

Revert "feat(revit): temporarily remove dui2 button"

---

ConnectorAutocadCivil/ConnectorAutocadCivil/Entry/App.cs

Reverts specklesystems/speckle-sharp#840

Revert "fix(dui2): removes dui2 button from rhino and acad"

---

ConnectorAutocadCivil/ConnectorAutocadCivil/UI/ConnectorBindingsAutocadCivil2.cs
ConnectorETABS/ConnectorETABS/UI/ConnectorBindingsETABS.Receive.cs
ConnectorRevit/ConnectorRevit/UI/ConnectorBindingsRevit2/ConnectorBindingsRevit2.Receive.cs
ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/UI/ConnectorBindingsRhino2.cs
DesktopUI2/DesktopUI2/ViewModels/StreamEditViewModel.cs

fix(dui2 connectors): selecting commit on receive no longer crashes app

---

ConnectorAutocadCivil/ConnectorAutocadCivil/Entry/SpeckleAutocadCommand2.cs
ConnectorETABS/ConnectorETABSv18/cPlugin.cs
ConnectorETABS/ConnectorETABSv19/cPlugin.cs
ConnectorRevit/ConnectorRevit/Entry/SpeckleRevitCommand2.cs
ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/ConnectorRhinoCommand2.cs
DesktopUI2/DesktopUI2/ViewModels/ProgressViewModel.cs
DesktopUI2/DesktopUI2/ViewModels/SavedStreamViewModel.cs
DesktopUI2/DesktopUI2/Views/MainWindow.xaml.cs
DesktopUI2/DesktopUI2/Views/Pages/HomeControls/SavedStream.xaml

feat(dui2): adds some of #821

---

ConnectorRevit/ConnectorRevit/ConnectorRevitUtils.cs
ConnectorRevit/ConnectorRevit/UI/ConnectorBindingsRevit.Selection.cs
ConnectorRevit/ConnectorRevit/UI/ConnectorBindingsRevit.Send.cs

- Fixes missing areas form the revit ui filter

feat(revit): adds areas and rebar to the list categories in the UI

---

ConnectorGrasshopper/ConnectorGrasshopper/Objects/ExpandSpeckleObjectTaskComponent.cs

fix(gh): Fixes problem with null values messing with Expand output paths

---

ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/UI/ConnectorBindingsRhino.cs
ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/UI/ConnectorBindingsRhino2.cs

Hotfix(rhino): Adds support for UserDictionaries

---

ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/UI/ConnectorBindingsRhino2.cs
Core/Core/Models/Extras.cs

Super small fix to add timestamp to reports. Each log operation has a date and time prepended - this can help with troubleshooting how much time has elapsed between operations as well.
- Fixes #906 821
- Manual Tests

feat(dui2): adds timestamp to report

---

ConnectorGrasshopper/ConnectorGrasshopper/Objects/ExpandSpeckleObjectTaskComponent.cs

fix(gh): Fixes bug introduced when adding nulls to output

---

ConnectorRevit/ConnectorRevit/UI/ConnectorBindingsRevit2/ConnectorBindingsRevit2.Selection.cs

Rooms schedule bug

---

ConnectorDynamo/ConnectorDynamoFunctions/Stream.cs
ConnectorGrasshopper/ConnectorGrasshopper/Streams/StreamDetailsComponent.cs
ConnectorGrasshopper/ConnectorGrasshopper/Streams/StreamGetComponent.cs
ConnectorGrasshopper/ConnectorGrasshopper/Streams/StreamUpdateComponent.cs
Core/Core/Credentials/StreamWrapper.cs

- Fixes #888
Opened exceptions file for GH and Dyn and checked that all cases were reported with a useful error message.

Alan/gh dyn/improve error messages

---

.circleci/config.yml
Core/IntegrationTests/TestsIntegration.csproj
Core/Tests/TestsUnit.csproj

add codecov reporting for Core

add codecov report and upload

---

.circleci/config.yml
ConnectorMicroStation/ConnectorMicroStation/ConnectorMicroStation.csproj
ConnectorMicroStation/ConnectorMicroStation/Properties/AssemblyInfo.cs
ConnectorMicroStation/ConnectorOpenBuildings/ConnectorOpenBuildings.csproj
ConnectorMicroStation/ConnectorOpenBuildings/Properties/AssemblyInfo.cs
ConnectorMicroStation/ConnectorOpenRail/ConnectorOpenRail.csproj
ConnectorMicroStation/ConnectorOpenRail/Properties/AssemblyInfo.cs
ConnectorMicroStation/ConnectorOpenRoads/ConnectorOpenRoads.csproj
ConnectorMicroStation/ConnectorOpenRoads/Properties/AssemblyInfo.cs

-  fixes version patching, cleans refs for bentley connectors

chore: fixes version patching, cleans refs,

---

Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertBeam.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertColumn.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertRoof.cs

- Fixes # adds missing family name to beams and columns

fix(revit): adds missing family name to beams and columns

---

DesktopUI2/DesktopUI2/ViewModels/SavedStreamViewModel.cs
DesktopUI2/DesktopUI2/Views/Pages/HomeControls/SavedStream.xaml

- Fix for issue discussed in #993 
- Manual Tests

dui2: changed popup to button cancel

---

Core/Core/Logging/Analytics.cs

- minor fix for the tracker v2

fix(core): ensure the hasing is done on a lowercase string

---

Objects/Converters/ConverterTeklaStructures/ConverterTeklaStructures2020/ConverterTeklaStructures2020.csproj
Objects/Converters/ConverterTeklaStructures/ConverterTeklaStructuresShared/ConverterTeklaStructureUtils.cs
Objects/Converters/ConverterTeklaStructures/ConverterTeklaStructuresShared/ConverterTeklaStructures.cs
Objects/Converters/ConverterTeklaStructures/ConverterTeklaStructuresShared/ConverterTeklaStructuresShared.projitems
Objects/Converters/ConverterTeklaStructures/ConverterTeklaStructuresShared/Partial Classes/ConvertBeam.cs
Objects/Converters/ConverterTeklaStructures/ConverterTeklaStructuresShared/Partial Classes/ConvertBolts.cs
Objects/Converters/ConverterTeklaStructures/ConverterTeklaStructuresShared/Partial Classes/ConvertContourPlate.cs
Objects/Objects/BuiltElements/Beam.cs
Objects/Objects/BuiltElements/TeklaStructures/Enums.cs
Objects/Objects/BuiltElements/TeklaStructures/TeklaContourPlate.cs

- Added conversion for Tekla contour plates to Speckle. 
- Added getting of more profile types from Tekla.

Added ContourPlate and other fixes

---

ConnectorAutocadCivil/ConnectorAutocadCivil/ConnectorAutocadCivilShared.projitems
ConnectorAutocadCivil/ConnectorAutocadCivil/Entry/App.cs
ConnectorAutocadCivil/ConnectorAutocadCivil/Storage/SpeckleStreamManager.cs
ConnectorAutocadCivil/ConnectorAutocadCivil/Storage/SpeckleStreamManager2.cs
ConnectorAutocadCivil/ConnectorAutocadCivil/UI/ConnectorBindingsAutocadCivil2.cs
ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/UI/ConnectorBindingsRhino2.cs
DesktopUI2/DesktopUI2/ConnectorBindings.cs
DesktopUI2/DesktopUI2/ViewModels/SavedStreamViewModel.cs

Adds event subscription in acad to DUI2 to also improve DUI2 responsiveness to document and window changes
- Fixes #990 
- Fixes #974 
- Manual Tests: received and saved a bunch of stuff

fix(dui2): streams saved properly in acad and rhino, crash prevention

---

ConnectorAutocadCivil/ConnectorAutocadCivil/UI/ConnectorBindingsAutocadCivil2.cs

This was happening when trying to receive old commits with objects with deprecated props.
- Part of  #939 
- Manual Tests: [old commit](https://speckle.xyz/streams/d45ef8e4c7/commits/2a780760cf) with previous block props no longer crashing acad (DUI2) on receive

fix(acad): try catch around deserialize to prevent app crash

---

ConnectorGrasshopper/ConnectorGrasshopper/Conversion/ToNativeTaskCapableComponent.cs

We were using a custom `CancellationToken` that was incorrectly initialised in the `ToNative` component.
I switched to using the component default (which works automatically when inputs change)
Partially fixes #971

hotfix(gh): Handle cancelation with TaskCapable token instead of custom

---

ConnectorGrasshopper/ConnectorGrasshopper/ConnectorGrasshopper.csproj
ConnectorGrasshopper/ConnectorGrasshopper/Extras/SendReceiveDataParam.cs
ConnectorGrasshopper/ConnectorGrasshopper/Ops/Operations.UpgradeUtils.cs
ConnectorGrasshopper/ConnectorGrasshopper/Ops/Operations.VariableInputReceiveComponent.cs
ConnectorGrasshopper/ConnectorGrasshopper/Ops/Operations.VariableInputSendComponent.cs

Send and Receive nodes should allow to set multiple properties in the commit object.
- Fixes #957

GH: Variable input Send/Receive nodes

---

ConnectorRevit/ConnectorRevit/UI/ConnectorBindingsRevit2/ConnectorBindingsRevit2.Receive.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/ConversionUtils.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertView.cs

- Fixes crash in Revit due to null reference exception on skipped conversions `ToNative``
- Fixes issue with receiving views in Revit causing the entire operation to be cancelled and no useful explanation.

Revit: Receive Fixes

---

ConnectorTeklaStructures/ConnectorTeklaStructures2020/Properties/AssemblyInfo.cs
ConnectorTeklaStructures/ConnectorTeklaStructures2021/ConnectorTeklaStructures2021.csproj

fix: tekla build

---

ConnectorGrasshopper/ConnectorGrasshopper/SchemaBuilder/SchemaBuilderGen.cs
ConnectorRevit/ConnectorRevit/Entry/SpeckleRevitCommand2.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertGridLine.cs
Objects/Objects/BuiltElements/GridLine.cs

- adds support for gridline labels
- avalonia owner fix in Revit (it was never merged!)

Revit gridline

---

ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/UI/ConnectorBindingsRhino2.cs
Core/Core/Api/Helpers.cs
DesktopUI2/DesktopUI2/Styles/ComboBox.xaml
DesktopUI2/DesktopUI2/ViewModels/SavedStreamViewModel.cs
DesktopUI2/DesktopUI2/ViewModels/StreamEditViewModel.cs
DesktopUI2/DesktopUI2/Views/Pages/StreamEditControls/Receive.xaml

Dui2 release fixes

---

ConnectorGrasshopper/ConnectorGrasshopper/SchemaBuilder/SchemaBuilderGen.cs
Objects/Objects/BuiltElements/Room.cs

feat(revit): create rooms with parameters from GH BIM #1069

---

ConnectorGrasshopper/ConnectorGrasshopper/Ops/Operations.VariableInputReceiveComponent.cs
ConnectorGrasshopper/ConnectorGrasshopper/Ops/Operations.VariableInputSendComponent.cs

- adds tracking to the new variable input nodes

feat(gh): adds tracking to the new variable input nodes

---

ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/UI/ConnectorBindingsRhino2.cs

Uses latest commit id instead of "latest" in parent layer name for receiving commits in Rhino.
Checks for commit container name being a rhino path to prevent nesting on repeated receives of the same commit.
- Fixes #1005 

fix(rhino): nested layer bug

---

ConnectorGrasshopper/ConnectorGrasshopper/Loader.cs

fix(gh): Missing tekla from disable tabs option list

---

Core/Core/Credentials/AccountManager.cs
Core/Core/Logging/Analytics.cs
Core/Core/Transports/SQLite.cs
DesktopUI2/DesktopUI2/ViewModels/DesignViewModels/DesignHomeViewModel.cs
DesktopUI2/DesktopUI2/ViewModels/HomeViewModel.cs
DesktopUI2/DesktopUI2/Views/Pages/HomeView.xaml

- adds methods in `AccountManager` for logging in and out Speckle without manager
- exposes those methods in DUI 

Connector auth

---

ConnectorAutocadCivil/ConnectorAutocad2021/ConnectorAutocad2021.csproj
ConnectorAutocadCivil/ConnectorAutocad2022/ConnectorAutocad2022.csproj
ConnectorAutocadCivil/ConnectorAutocadCivil.sln
ConnectorAutocadCivil/ConnectorAutocadCivil/UI/ConnectorBindingsAutocadCivil.cs
ConnectorAutocadCivil/ConnectorAutocadCivil/UI/ConnectorBindingsAutocadCivil2.cs
ConnectorAutocadCivil/ConnectorAutocadCivil/Utils.cs
ConnectorAutocadCivil/ConnectorCivil2021/ConnectorCivil2021.csproj
ConnectorAutocadCivil/ConnectorCivil2022/ConnectorCivil2022.csproj
Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.Civil.cs
Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.Geometry.cs
Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.cs
Objects/Converters/ConverterAutocadCivil/ConverterCivil2021/ConverterCivil2021.csproj
Objects/Converters/ConverterAutocadCivil/ConverterCivil2022/ConverterCivil2022.csproj

Adds property sets to civil elements
Also includes volume and area on meshes generated from solids and surfaces
Updates nuget packages to include property set db
- Fixes #1109 
- Manual Tests: corridor file from arkitema

feat(civil3d): adds property sets to all civil elements

---

DesktopUI2/DesktopUI2/ViewModels/OneClickViewModel.cs

- changes oneClick=true to method=OneClick

chore(revit): changes oneClick=true to method=OneClick

---

ConnectorGrasshopper/ConnectorGrasshopper/SchemaBuilder/SchemaBuilderGen.cs

Grasshopper was pending a full rebuild to regenerate some of the new components (and deprecate the old) in the Structural classes.

fix(gh): Regenerated schema nodes for grasshopper

---

ConnectorRevit/ConnectorRevit/UI/ConnectorBindingsRevit2/ConnectorBindingsRevit2.Events.cs
DesktopUI2/DesktopUI2/ViewModels/HomeViewModel.cs
DesktopUI2/DesktopUI2/ViewModels/MainWindowViewModel.cs
DesktopUI2/DesktopUI2/ViewModels/StreamViewModel.cs
DesktopUI2/DesktopUI2/Views/Pages/StreamEditView.xaml

Matteo dui

---

Objects/Converters/ConverterRevit/ConverterRevitShared/ConversionUtils.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertDuct.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertFamilyInstance.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertPipe.cs

See https://github.com/specklesystems/speckle-sharp/pull/1106

Revit MEP Materials

---

Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertMeshUtils.cs

- Fixes  major performance bottleneck with Revit ToSpeckle conversion
- The problem was introduced in 2.4.0-beta with code that was resizing lists super frequently.
- This PR fixes it by resizing face and vertices list ONCE before filling them.
- Should see a ~30% speed up in Revit ToSpeckle conversion performance!
closes #1154 
see #1153

Revit Converter: Fixed performance bottle neck in list resizing

---

Core/Core/Transports/ServerUtils/ParallelServerAPI.cs
Core/Core/Transports/ServerUtils/ServerAPI.cs
Core/Core/Transports/ServerV2.cs

- Fixes #1031
- Fixes #1113
- Fixes #1049
- Manual Tests

Small fixes to server transport

---

Core/Core/Api/Operations/Operations.Receive.cs
Core/Core/Serialisation/BaseObjectDeserializerV2.cs

small fixes on deserialization

cleanup on receive errors, don't throw AggregateExceptions

---

Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertColumn.cs

was assuming all revit columns have location point which was throwing errors

fix(revit): column error on receive

---

DesktopUI2/DesktopUI2/ViewModels/ProgressViewModel.cs
DesktopUI2/DesktopUI2/ViewModels/StreamViewModel.cs

- adds tracking for quick op cancel
- improves tracking for send and receive cancel
- enables notification without action
- better notification for send and receive cancel, as well as failed send
- Manual Tests

cancellation notifications

---

ConnectorRevit/ConnectorRevit/Entry/SpeckleRevitCommand2.cs
DesktopUI2/DesktopUI2/ViewModels/StreamViewModel.cs
DesktopUI2/DesktopUI2/Views/Scheduler.xaml

Prerelease hotfixes

---

ConnectorRevit/ConnectorRevit/ConnectorRevitUtils.cs
ConnectorRevit/ConnectorRevit/UI/ConnectorBindingsRevit2/ConnectorBindingsRevit2.Events.cs
DesktopUI2/DesktopUI2/ViewModels/StreamViewModel.cs
DesktopUI2/DesktopUI2/Views/Filters/ManualFilterView.xaml
Objects/Converters/ConverterRevit/ConverterRevitShared/Categories.cs

feat(dui): #1188 improve manual selection filter

---

Core/Core/Api/GraphQL/Client.GraphqlClientOperations.cs
Core/Core/Api/GraphQL/Models.cs
DesktopUI2/DesktopUI2/Styles/MenuItem.xaml
DesktopUI2/DesktopUI2/ViewModels/DesignViewModels/DesignHomeViewModel.cs
DesktopUI2/DesktopUI2/ViewModels/HomeViewModel.cs
DesktopUI2/DesktopUI2/Views/Converters/EnumBooleanConverter.cs
DesktopUI2/DesktopUI2/Views/Pages/HomeControls/SavedStreams.xaml
DesktopUI2/DesktopUI2/Views/Pages/HomeView.xaml
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertFamilyInstance.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertProfileWall.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertWall.cs
Objects/Objects/BuiltElements/Column.cs

- adds support for filtering streams by ownership and favorite

Dui filters

---

.circleci/config.yml

omfg y r there so many lil things to edit and fix in dis huge ci file 😭

ci(archicad): add archi tag to deploy filters

---

.circleci/config.yml
ConnectorArchicad/ConnectorArchicad/ConnectorArchicad.csproj
ConnectorRevit/ConnectorRevit/Entry/SpeckleRevitCommand2.cs

- sets product verison correctly in archicad

fix: set product version correctly on ci

---

DesktopUI2/DesktopUI2/ViewModels/StreamViewModel.cs
DesktopUI2/DesktopUI2/Views/AttachedProperties/BlockSelection.cs
DesktopUI2/DesktopUI2/Views/Pages/HomeControls/SavedStreams.xaml

feat(dui): asks for confirmation before deleting a stream #1230

---

Core/Core/Models/Extras.cs

- Fixes issue reported in the Forum where Expand Speckle Object (now Deconstruct Speckle Object) and some others would fail on the `BeforeSolveInstance` call due to accessing the Conversion Report lists in a non thread-safe way.
We are now locking the access to the list so that this no longer happens.
This change should not break any of our existing connectors, as they all work in sequence. The only connector where this could possibly happen was Grasshopper, with the introduction of TaskCapableComponents.
The issue is difficult to reproduce, but I managed to reproduce it in my machine quite qickly by just generating a high number of inputs.
Once the fix was in place, the error no longer …

fix(core): Made Report thread safe :)

---

Core/Core/Core.csproj

fix(core): downgrades sqlite to 1.0.115

---

ConnectorAutocadCivil/ConnectorAutocad2023/ConnectorAutocad2023.csproj
ConnectorAutocadCivil/ConnectorAutocad2023/Properties/AssemblyInfo.cs
ConnectorAutocadCivil/ConnectorAutocadCivil.sln
ConnectorAutocadCivil/ConnectorAutocadCivil/UI/ConnectorBindingsAutocadCivil.cs
ConnectorAutocadCivil/ConnectorAutocadCivil/Utils.cs
ConnectorAutocadCivil/ConnectorCivil2023/ConnectorCivil2023.csproj
ConnectorAutocadCivil/ConnectorCivil2023/Properties/AssemblyInfo.cs
Objects/Converters/ConverterAutocadCivil/ConverterAutocad2023/ConverterAutocad2023.csproj
Objects/Converters/ConverterAutocadCivil/ConverterAutocad2023/Properties/launchSettings.json
Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/Converter.AutocadCivil.Utils.cs
Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.Civil.cs
Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.cs
Objects/Converters/ConverterAutocadCivil/ConverterCivil2023/ConverterCivil2023.csproj
Objects/Converters/ConverterAutocadCivil/ConverterCivil2023/Properties/launchSettings.json

Adds autocad and civil3d 2023 projects.
- Fixes #1172 
- 
- Manual Tests: sent some basic geometry from autocad

feat(civil3d/autocad): add 2023 support

---

ConnectorRevit/ConnectorRevit/Entry/App.cs
ConnectorRevit/ConnectorRevit/Entry/SpeckleRevitCommand2.cs
ConnectorRevit/ConnectorRevit/UI/ConnectorBindingsRevit2/ConnectorBindingsRevit2.Events.cs
ConnectorRevit/ConnectorRevit/UI/ConnectorBindingsRevit2/ConnectorBindingsRevit2.cs
ConnectorRevit/ConnectorRevit/UI/Panel.xaml
ConnectorRevit/ConnectorRevit/UI/Panel.xaml.cs
DesktopUI2/AvaloniaHwndHost/AvaloniaHwndHost.cs

- Fixes issue with doc changes in Revit and dockable panels

fix(revit): supports document changes properly within the dockable panel

---

ConnectorArchicad/ConnectorArchicad/Program.cs

fix(archicad): class rename

---

ConnectorGrasshopper/ConnectorGrasshopper/Objects/DeconstructSpeckleObjectTaskComponent.cs

fix(gh): Fix output path mismatch by always generating a task

---

ConnectorRevit/ConnectorRevit/Entry/App.cs
ConnectorRevit/ConnectorRevit/Entry/SpeckleRevitCommand2.cs
ConnectorRevit/ConnectorRevit/UI/ConnectorBindingsRevit2/ConnectorBindingsRevit2.Events.cs
DesktopUI2/DesktopUI2/DesktopUI2.csproj

- Fixes DUI borkage because of csproj settings
- Revit Dockable panels go back to being Windows bc of some Text Input issues :(

Dui hotfixes

---

ConnectorCSI/ConnectorCSIShared/cPlugin.cs
Objects/Converters/ConverterCSI/ConverterCSIShared/Partial Classes/Geometry/ConvertPier.cs

Release 2.6.0 CSI fixes

---

ConnectorDynamo/ConnectorDynamoFunctions/BatchConverter.cs

Aligns DYN with fix made in #1320

fix(dyn): Align isDataTree condition with GH fix on #1320

---

Objects/Converters/ConverterRevit/ConverterRevitShared/ConversionUtils.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertFloor.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertGeometry.cs

- Fixes issue with Ellipse curves not working as floor voids
- Fixes issue with Nurbs curves not working as floor outlines.

RVT: Fix floor curve conversion

---

Objects/Objects/Organization/Model.cs

A super generic `Setting` class that contains:
- Name (string)
- Selected (List<Base>)
Can be added optionally to the model class as List<Setting>

feat(objects): tentative setting class added to org objects

---

ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/Entry/Plugin.cs

- Fixes Rhino panel first load issue fix

fix(rhino): panel first load issue fix

---

ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/BIMElements/BIMElementCommands.cs
ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/BIMElements/BIMElementFilter.cs
Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.BuiltElements.cs
Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.cs

-Adds `CreateTopography` command to rhino
-Adds button to toolbar
-no schema validation except for disallowing assignment to closed meshes
- Fixes #1344 
- Manual Tests: sent basic meshes as topo to revit

feat(rhino): adds topography to rhino bim

---

Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertTopography.cs

- Fixes #1355 
- Manual Tests: topography from grasshopper

fix(revit): update topography conversion with mesh faces

---

ConnectorRevit/ConnectorRevit/Entry/SpeckleRevitCommand2.cs
ConnectorRevit/ConnectorRevit/UI/Panel.xaml.cs
DesktopUI2/DesktopUI2/Views/MainUserControl.xaml.cs

- Fixes text input in dockable panels in Revit

fix(revit): text input in dockable panels

---

ConnectorDynamo/ConnectorDynamo.sln
ConnectorRevit/ConnectorRevit/UI/Panel.xaml.cs
Objects/Converters/ConverterDynamo/ConverterDynamoRevit2023/ConverterDynamoRevit2023.csproj
Objects/Converters/ConverterDynamo/ConverterDynamoRevit2023/Properties/launchSettings.json
Objects/Converters/ConverterDynamo/ConverterDynamoShared/ConverterDynamo.Units.cs

- Fixes #1357  adds converter for dynamo revit 2023

Dynamo 2023

---

ConnectorGrasshopper/ConnectorGrasshopper/BaseComponents/SelectKitTaskCapableComponentBase.cs
ConnectorGrasshopper/ConnectorGrasshopper/Extras/Utilities.cs
ConnectorGrasshopper/ConnectorGrasshopper/Objects/DeconstructSpeckleObjectTaskComponent.cs
Objects/Objects/Other/MaterialQuantity.cs

Merges changes from `all/2.6.3`

---

DesktopUI/DesktopUI/App.config
DesktopUI/DesktopUI/DesktopUI.csproj
DesktopUI/DesktopUI/Properties/Resources.Designer.cs
DesktopUI/DesktopUI/Properties/Settings.Designer.cs
DesktopUI2/AvaloniaHwndHost/AvaloniaHwndHost.cs

Hotfix for an old bug that we re-introduced!

fix(revit): multiple projects crash fix

---

ConnectorDynamo/ConnectorDynamo.sln
Objects/Converters/ConverterDynamo/ConverterDynamoRevit2021/ConverterDynamoRevit2021.csproj
Objects/Converters/ConverterDynamo/ConverterDynamoRevit2022/ConverterDynamoRevit2022.csproj
Objects/Converters/ConverterDynamo/ConverterDynamoRevit2023/ConverterDynamoRevit2023.csproj

- Fixes Dynamo Revit converter builds. Currently failing on CI
- CI

dyn: Adds ConverterDXF to DynamoRevit converters

---

ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/Entry/ConnectorRhinoCommand.cs
DesktopUI2/DesktopUI2/ViewModels/HomeViewModel.cs

- Fixes issue at startup when the Application is still null, could only replicate while debugging so far

fix(rhino): race condition at startup when app is null

---

Core/Core/Credentials/AccountManager.cs
Core/Core/Credentials/Responses.cs

- adds stream and commit count to User query

feat: adds stream and commit count to User query

---

DesktopUI2/DesktopUI2/ViewModels/AccountViewModel.cs

- Fixes avatar not showing up if manually uploaded

fix(dui): avatars can also be base64strings

---

ConnectorCSI/ConnectorCSIShared/UI/ConnectorBindingsCSI.cs
ConnectorTeklaStructures/ConnectorTeklaStructuresShared/UI/ConnectorBindingsTeklaStructures.cs

- Fixes long selection time process
- 

fix(TeklaStructures + CSI) Selection Object Fix for Tekla Structures and CSI

---

ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/BIMElements/BIMElementCommands.cs
Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.BuiltElements.cs
Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.Utils.cs

Adds default direct shape assignment on `Enter` command and fixes bug on invalid directshape string
- Fixes #1424 
- Manual Tests

fix(rhino): directshape schema default assignment

---

ConnectorRevit/ConnectorRevit/ConnectorRevitUtils.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Categories.cs

feat(revit): adds missing categories #1308 #1416

---

.circleci/scripts/config-generator.py
.circleci/scripts/config-template.yml

- Fixes issue with new deployment mechanism looking for `.exe` files instead of `.zip`
Added a `extension` parameter to the job that will be set on the config generator.
Ran the validation and generator loally.

fix(ci): Added extension parameter to distinguish between zip and exe

---

Objects/Converters/ConverterTeklaStructures/ConverterTeklaStructuresShared/Partial Classes/ConvertBeam.cs
Objects/Converters/ConverterTeklaStructures/ConverterTeklaStructuresShared/Partial Classes/ConvertBolts.cs
Objects/Converters/ConverterTeklaStructures/ConverterTeklaStructuresShared/Partial Classes/ConvertContourPlate.cs
Objects/Converters/ConverterTeklaStructures/ConverterTeklaStructuresShared/Partial Classes/ConvertPolyBeam.cs
Objects/Converters/ConverterTeklaStructures/ConverterTeklaStructuresShared/Partial Classes/ConvertPolygonWelds.cs
Objects/Converters/ConverterTeklaStructures/ConverterTeklaStructuresShared/Partial Classes/ConvertRebar.cs
Objects/Converters/ConverterTeklaStructures/ConverterTeklaStructuresShared/Partial Classes/ConvertSpiralBeam.cs
Objects/Converters/ConverterTeklaStructures/ConverterTeklaStructuresShared/Partial Classes/ConvertWelds.cs
Objects/Objects/BuiltElements/TeklaStructures/Bolts.cs
Objects/Objects/BuiltElements/TeklaStructures/TeklaContourPlate.cs
Objects/Objects/BuiltElements/TeklaStructures/Welds.cs

- Small fixes 
- Manual Tests  from send + recieve

(fix ~ Tekla Structures  ) ~ displayMesh change to displayValues

---

Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.Other.cs

Now concatenates all dynamic block simple props into definition name
- Closes #1444 
- 

fix(autocad): dynamic block name improved

---

Objects/Converters/ConverterRevit/ConverterRevitShared/ConversionUtils.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertGeometry.cs
Objects/Objects/Other/Transform.cs

Applies the transform / scaling factor to revit pointclouds before sending
- Fixes #1458
- Manual Tests: revit sample pc file

fix(revit): pointclouds now scaled appropriately

---

.circleci/scripts/config-generator.py

- Fixes https://github.com/specklesystems/admin/issues/314
Ran the python script and checked that the slugs were properly set.

fix(ci): Removes -mac suffix from slug as OS is now it's own parameter

---

ConnectorRevit/ConnectorRevit/Entry/App.cs
ConnectorRevit/ConnectorRevit/Entry/SpeckleRevitCommand2.cs
ConnectorRevit/ConnectorRevit/UI/ConnectorBindingsRevit2/ConnectorBindingsRevit2.Events.cs
ConnectorRhino/ConnectorRhino.sln
ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/Entry/Plugin.cs
ConnectorRhino/ConnectorRhino6/Properties/AssemblyInfo.cs
ConnectorRhino/ConnectorRhino7/Properties/AssemblyInfo.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/ConversionUtils.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertFamilyInstance.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertWall.cs

Just your average update from `main` to `release/2.8` with a twist.
Since there were merge conflicts that needed to be resolved but **not included in `main`**, I created an auxiliary branch to fix these.

Pull changes from `main` into `release/2.8`

---

ConnectorTeklaStructures/ConnectorTeklaStructures2020/Properties/AssemblyInfo.cs
ConnectorTeklaStructures/ConnectorTeklaStructures2021/Properties/AssemblyInfo.cs

Tekla: Fix AssemblyVersion for Installer

---

.circleci/scripts/config-template.yml
ConnectorArchicad/ConnectorArchicad/ConnectorArchicad.csproj

Just your normal updating PR... nothing to see here :)

Update `main` with changes from `release/2.7`

---

Core/Core/Credentials/Account.cs
Core/Core/Logging/Analytics.cs
Core/Core/Logging/Setup.cs

Minor improvements for our analytics class

Mixpanel connectors

---

ConnectorRevit/ConnectorRevit/UI/ConnectorBindingsRevit2/ConnectorBindingsRevit2.Send.cs
Core/Core/Logging/Analytics.cs
DesktopUI2/DesktopUI2/Styles/TextBox.xaml
DesktopUI2/DesktopUI2/ViewModels/ApplicationObjectViewModel.cs
DesktopUI2/DesktopUI2/ViewModels/CommentViewModel.cs
DesktopUI2/DesktopUI2/ViewModels/HomeViewModel.cs
DesktopUI2/DesktopUI2/ViewModels/StreamViewModel.cs
DesktopUI2/DesktopUI2/Views/Pages/StreamEditControls/Report.xaml

Some ui fiddles + a fix in the report

Report fiddles

---

Objects/Converters/ConverterRevit/ConverterRevitShared/RevitVersionHelper.cs

Due to changes in the Revit API, if a commit is sent or received in version <=2021, then the parameters are set with a DisplayUnitType value. If a commit is sent or received in version  >=2022, then the parameters are set with a ForgeTypeId value.
This makes it so that if you send a commit in Revit 2021 and then receive it in Revit 2022, then some parameters will not set properly. Here are two example streams
https://speckle.xyz/streams/445f21d47d/commits/01a748dc60
https://speckle.xyz/streams/5a087f4c9a/commits/78267ed4ce
Here are some screenshot of receiving these two commits (sent from Revit 2021) in 2022 before this PR:
Here are some screenshot of receiving these two commits after this PR (these are correct):

fix unit type change from <=2021 to >=2022

---

Core/Core/Credentials/AccountManager.cs
DesktopUI2/DesktopUI2/Views/Windows/Dialogs/NewStreamDialog.xaml.cs

Account updates

---

Core/Core/Logging/Log.cs
Core/Core/Logging/Setup.cs

Removes the deprecated SUUID, we are now using the hashed user email instead.

feat: removes suuid

---

ConnectorRevit/ConnectorRevit/UI/ConnectorBindingsRevit2/ConnectorBindingsRevit2.Receive.cs
DesktopUI2/DesktopUI2/ViewModels/ProgressViewModel.cs

Fixes importing objects so the Revit UI doesn't freeze and so objects appear as they are baked as opposed to seeing noting happen and then seeing all the objects appear all at once.
Fixes https://github.com/specklesystems/speckle-sharp/issues/1414 and https://github.com/specklesystems/speckle-sharp/issues/1376

Better looking imports

---

.circleci/scripts/config-template.yml
.circleci/scripts/connector-jobs.yml

PR open just for testing purposes. If it works I'll fill in a propper description!

fix(ci): Testing from the last working commit instead

---

ConnectorRhino/ConnectorRhino7/ConnectorRhino7.csproj

Fixes failing mac build introduced in #1542

fix(rh): Bumped mac ref to dylib in Rhino csproj

---

.circleci/config.yml
Core/Tests/Fixtures.cs

ci flag was wrong which meant core tests were never run
making a PR mainly to test/trigger the ci since core tests were passing on my server invites pr before i merged in 2.8 and am now having issues

fix(ci): core test flag

---

Core/Core/Api/Helpers.cs
Core/Core/Credentials/AccountManager.cs

fix(core): fixed stack overflow when no sentry and no default account ie CI

---

ConnectorRevit/ConnectorRevit/UI/ConnectorBindingsRevit2/ConnectorBindingsRevit2.Receive.cs

The switch from the Windows dispatcher to the avalonia dispatcher saves a bit of time according to some benchmarks I ran. Also I was having a couple issue. 
- Sometimes the import would seemingly go all the way through and then it would delete everything and Revit would stall. That was happening because the Revit api was being passed null in Doc.GetElements(). Now fixed.
- The process would break when switching views. This was fixed by changing the way that the view is refreshed. Now it is a bit more view agnostic.
- Replaced windows dispatcher with Avalonia
- Added condition obj.CreatedIds.Count cannot equal 0 in DeleteObjects
- Replaced `view.getcorners` and `view.zoomandcenter(corners)` to just `view.zoom(1)`
Manual tests and benchmarks to compare performance …

fix: better build optimization and bug fix

---

ConnectorRevit/ConnectorRevit/Entry/App.cs
ConnectorRevit/ConnectorRevit/Entry/HelpCommand.cs
ConnectorRevit/ConnectorRevit/Entry/SpeckleRevitCommand2.cs
Core/Core/Api/GraphQL/Client.GraphqlClientOperations.cs
Core/Core/Api/GraphQL/Client.cs
Core/Core/Api/GraphQL/Models.cs
Core/Core/Api/Helpers.cs
DesktopUI2/DesktopUI2/ViewModels/HomeViewModel.cs

fix: updates some old manager links and paths

---

ConnectorAutocadCivil/ConnectorAutocadCivil/UI/ConnectorBindingsAutocadCivil.cs
ConnectorAutocadCivil/ConnectorAutocadCivil/Utils.cs

Adds property sets to received objects in civil3d if they exist
Closes #1551
Civil3d connector bindings
Sent and received some objects with property sets

feat(civil3d): adds propertysets on receive

---

Core/Core/Logging/Setup.cs

Adds a mutex inside the Setup method so that Manager can easily detect if a process running the connector is running.

feat(core): adds mutex in Setup

---

Objects/Converters/ConverterRevit/ConverterRevitShared/ConversionUtils.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertColumn.cs

Certain types of objects are failing to import due to a null value exception
- fix null value exception
- fixed edge case where column length is temporarily 0 which causes the whole transaction to rollback
All objects in the RevitTestStream (excluding the adaptive component objects which I have not checked) now import

fix(Revit): Certain objects failing to import

---

Core/Core/Credentials/AccountManager.cs

Prevents invalid accounts from being included in the GetAccounts() result.

fix(core): Prevent invalid account from slipping out

---

Objects/Converters/ConverterCSI/ConverterCSIShared/ConverterCSI.cs
Objects/Converters/ConverterCSI/ConverterCSIShared/ConverterCSIShared.projitems
Objects/Converters/ConverterCSI/ConverterCSIShared/Partial Classes/Analysis/ConvertBuiltElementModel.cs

quick fix for receiving new Revit commits for analytical models
tested : manually

fix (CSI) - receiving new Analytical models from revit

---

Core/Tests/ExceptionTests.cs
Core/Tests/Helpers.cs

Adds tests for `TimeAgo` helper function.

feat(core): Added test for TimeAgo function

---

ConnectorRevit/ConnectorRevit/UI/ConnectorBindingsRevit2/ConnectorBindingsRevit2 .Settings.cs
ConnectorRevit/ConnectorRevit/UI/ConnectorBindingsRevit2/ConnectorBindingsRevit2.Mappings.cs
DesktopUI2/DesktopUI2/DesktopUI2.csproj
DesktopUI2/DesktopUI2/ViewModels/ImportFamiliesDialogViewModel.cs
DesktopUI2/DesktopUI2/ViewModels/MainViewModel.cs
DesktopUI2/DesktopUI2/ViewModels/MappingViewModel.cs
DesktopUI2/DesktopUI2/ViewModels/StreamViewModel.cs
DesktopUI2/DesktopUI2/Views/Windows/Dialogs/ImportFamiliesDialog.xaml
DesktopUI2/DesktopUI2/Views/Windows/Dialogs/ImportFamiliesDialog.xaml.cs
DesktopUI2/DesktopUI2/Views/Windows/Dialogs/MappingViewDialog.xaml
DesktopUI2/DesktopUI2/Views/Windows/Dialogs/MappingViewDialog.xaml.cs

Previously, the import functionality would only import family symbols that had the exact name of specific type that the user was trying to import. This PR creates a UI for the user to navigate in order to select specific family types to import.
- added individual family symbol import functionality
- gave mapping setting a default value
Manual test of importing different families in different mapping contexts

Feature(Revit): adds a way to import specific family types during mapping

---

Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertAnalyticalStick.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertStructuralModel.cs

- set units on analytical stick columns in order to have the offsets set properly
Before:
After:
Speckle was throwing errors before when receiving the ETABS test stream and now it isn't

hotfix(Revit): Set units for analytical stick

---

ConnectorGrasshopper/ConnectorGrasshopper/Loader.cs
ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/UI/ConnectorBindingsRhino.cs
ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/Utils.cs

Just your average update of Release

Merge main into release branch

---

ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/UI/ConnectorBindingsRhino.cs
Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.cs

Adds an update receive mode for Rhino connector.
This will remove any existing objects on receive that have the same guid or application id as an incoming base object
part of #1530
Rhino connector and converter
Tested on rhino to rhino and revit to rhino basic workflows

feat(rhino): adds update receive setting

---

.github/ISSUE_TEMPLATE/papercut.yml

Added a papercut issue template.

chore: Added paper-cut issue template

---

Core/Core/Kits/ISpeckleKit.cs
Objects/Converters/ConverterDynamo/ConverterDynamoRevit/ConverterDynamoRevit.csproj
Objects/Converters/ConverterRevit/ConverterRevit2019/ConverterRevit2019.csproj
Objects/Converters/ConverterRevit/ConverterRevit2020/ConverterRevit2020.csproj
Objects/Converters/ConverterRevit/ConverterRevit2021/ConverterRevit2021.csproj
Objects/Converters/ConverterRevit/ConverterRevit2022/ConverterRevit2022.csproj
Objects/Objects/Geometry/Arc.cs
Objects/Objects/Geometry/Box.cs
Objects/Objects/Geometry/Brep.cs
Objects/Objects/Geometry/Point.cs
Objects/Objects/Geometry/Vector.cs
Objects/Objects/Interfaces.cs
Objects/Objects/ObjectsKit.cs

Adds XML documentation comments to:
- Arc
- Vector
- Box
- BREP
- Point
As well as all common interfaces (IHasVolume, IHasArea, IHasBoundingBox), ISpeckleKit and the ObjectsKit.
This is intended to act as an example for hacktoberfest PRs that fill in XML comments.
**Bonus:** Added a condition in Revit's csproj to run the copy step only on Windows. It can now be built on mac too :)

feat(Objects): Adds XML comments to some geometry classes + minor cleanup

---

ConnectorGrasshopper/ConnectorGrasshopper/Ops/Operations.VariableInputReceiveComponent.cs
ConnectorGrasshopper/ConnectorGrasshopper/Ops/Operations.VariableInputSendComponent.cs
ConnectorGrasshopper/ConnectorGrasshopper/Streams/StreamGetComponent.cs
ConnectorGrasshopper/ConnectorGrasshopper/Streams/StreamListComponent.cs
Core/Core/Api/GraphQL/Client.GraphqlClientOperations.cs
Core/Core/Api/Helpers.cs
Core/Core/Credentials/StreamWrapper.cs
Objects/Objects/BuiltElements/Revit/FreeformElement.cs

- Fixes #1712 
Added `Api.Helpers.UserHasInternet` which uses the new `Api.Helpers.Ping` to determine if the user has an internet connection.
Adds use of `UserHasInternet` in the Send and Receive nodes of Grasshopper.
- Fixes #1724 
Flagged `BaseGeometry` as Obsolete

GH: Bug fixes for 2.9 release

---

ConnectorCSI/ConnectorETABS/ConnectorETABS.csproj
Objects/Converters/ConverterCSI/ConverterCSIShared/Partial Classes/Materials/ConvertMaterials.cs

fix to receiving some materials which was stalling the sending and receiving

fix(ETABS): Sending/receiving fix

---

ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/Utils.cs

Removes invalid `{}` characters from layer names in Rhino: this was previously preventing receives from Grasshopper **after the GH commit structure was changed to use branch paths**
Fixes #1746
Now receives the GH test stream

fix(rhino): handles invalid chars in layer name

---

ConnectorGrasshopper/ConnectorGrasshopper/Ops/Operations.VariableInputReceiveComponent.cs

This was detected by Bilal during testing, but somehow had no issue for it so it fell through the cracks! 🙇🏼‍♂️🙇🏼‍♂️
Fixes an edge case where the `ResetApiClient` function had not finished, hence `ApiClient` as null. If a user would press the `Send` button while in this state, he would receive a `Null Reference Exception`.
This would only happen **the first time** as once the `ApiClient` is set, receiving would work as expected.
This behaviour has existed as is for a while but gone undetected. My guess is that `ResetApiClient` also validates the stream against the accounts, and this has been somewhat slower lately, giving the user the window for this to happen.

fix(gh): `DoWork` should wait for `apiReset` before using the ApiClient

---

DesktopUI2/DesktopUI2/Models/ConfigManager.cs
DesktopUI2/DesktopUI2/ViewModels/StreamViewModel.cs
DesktopUI2/DesktopUI2/Views/Controls/StreamEditControls/Receive.xaml
DesktopUI2/DesktopUI2/Views/Controls/StreamEditControls/Receive.xaml.cs

Adds 360 previews just like in the web app.

feat(dui): 360 previews

---

.circleci/scripts/config-template.yml
Core/.gitignore
Core/Core/Api/GraphQL/Client.GraphqlClientOperations.cs
Core/Core/Api/GraphQL/Models.cs
Core/Examples/ExampleApp.csproj
Core/IntegrationTests/Api.cs
Core/IntegrationTests/Fixtures.cs
Core/IntegrationTests/Subscriptions/Branches.cs
Core/IntegrationTests/Subscriptions/Commits.cs
Core/IntegrationTests/Subscriptions/Streams.cs
Core/IntegrationTests/TestsIntegration.csproj
Core/IntegrationTests/Usings.cs
Core/Tests/TestsUnit.csproj
DesktopUI/DesktopUI/Streams/Dialogs/ShareStreamDialogViewModel.cs
DesktopUI/DesktopUI/Utils/Converters.cs
DesktopUI/DesktopUI/Utils/StreamDialogBase.cs
DesktopUI2/DesktopUI2/ViewModels/AccountViewModel.cs

- update test and example projects to net6
- add asdf ignore to gitignore
- add limited and activeUser queries
- add implicit usings
- update tests for limited/otherUser query

feat(core): Updated user queries to with new `limitedUser` or `activeUser`

---

ConnectorRevit/ConnectorRevit/UI/ConnectorBindingsRevit2/ConnectorBindingsRevit2.Events.cs
DesktopUI2/DesktopUI2/ConnectorBindings.cs
DesktopUI2/DesktopUI2/DummyBindings.cs
DesktopUI2/DesktopUI2/ViewModels/CommentViewModel.cs
DesktopUI2/DesktopUI2/ViewModels/HomeViewModel.cs
DesktopUI2/DesktopUI2/ViewModels/StreamViewModel.cs
DesktopUI2/DesktopUI2/Views/Controls/StreamEditControls/Comments.xaml
DesktopUI2/DesktopUI2/Views/MainUserControl.xaml.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/ConverterRevit.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertView.cs

Adds support for #1585 in Revit.

feat(revit): open comments in 3D view

---

DesktopUI2/DesktopUI2/Models/Filters/SelectionFilterConverter.cs
DesktopUI2/DesktopUI2/Models/Settings/MultiSelectBoxSetting.cs
DesktopUI2/DesktopUI2/Models/Settings/SettingsConverter.cs
DesktopUI2/DesktopUI2/Models/StreamState.cs
DesktopUI2/DesktopUI2/ViewModels/HomeViewModel.cs
DesktopUI2/DesktopUI2/ViewModels/MainViewModel.cs
DesktopUI2/DesktopUI2/ViewModels/StreamViewModel.cs
DesktopUI2/DesktopUI2/Views/Controls/SavedStreams.xaml
DesktopUI2/DesktopUI2/Views/Pages/HomeView.xaml

Fixes #1809 although in the case of the `MultiSelectBoxSetting` I could not restore the selection of the list via the `SelectionModel`. This does not affect the functionality of the filter, it's more of a UX problem.

fix(dui): advanced settings not preserved 

---

Core/Core/Api/GraphQL/Client.GraphqlClientOperations.cs
Core/Core/Api/GraphQL/Client.Subscriptions.Stream.cs
Core/Core/Api/GraphQL/Client.cs
Core/Core/Api/GraphQL/Models.cs
DesktopUI2/DesktopUI2/Styles/NotificationCard.xaml
DesktopUI2/DesktopUI2/Styles/NotificationManager.xaml
DesktopUI2/DesktopUI2/ViewModels/AccountViewModel.cs
DesktopUI2/DesktopUI2/ViewModels/CommentViewModel.cs
DesktopUI2/DesktopUI2/ViewModels/HomeViewModel.cs
DesktopUI2/DesktopUI2/ViewModels/PopUpNotificationViewModel.cs
DesktopUI2/DesktopUI2/ViewModels/StreamViewModel.cs
DesktopUI2/DesktopUI2/Views/Controls/StreamEditControls/Receive.xaml
DesktopUI2/DesktopUI2/Views/Pages/StreamEditView.xaml

Adds subs for the main stream, branch, commit and comment events

feat(dui): adds subscriptions and popup notifications

---

ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/Entry/Plugin.cs
ConnectorRhino/ConnectorRhino6/ConnectorRhino6.csproj
ConnectorRhino/ConnectorRhino6/Properties/AssemblyInfo.cs
ConnectorRhino/ConnectorRhino7/ConnectorRhino7.csproj
ConnectorRhino/ConnectorRhino7/Properties/AssemblyInfo.cs
DesktopUI2/DesktopUI2/ViewModels/StreamViewModel.cs
DesktopUI2/README.md
Objects/Converters/ConverterRhinoGh/ConverterGrasshopper7/ConverterGrasshopper7.csproj
Objects/Converters/ConverterRhinoGh/ConverterGrasshopper7/Properties/AssemblyInfo.cs
Objects/Converters/ConverterRhinoGh/ConverterRhino6/Properties/launchSettings.json
Objects/Converters/ConverterRhinoGh/ConverterRhino7/ConverterRhino7.csproj
Objects/Converters/ConverterRhinoGh/ConverterRhino7/Properties/AssemblyInfo.cs

Reverses an hotfix that was merged from main that should have not gone in 2.10

Reverse changes

---

DesktopUI2/DesktopUI2/App.xaml
DesktopUI2/DesktopUI2/Views/Windows/Dialogs/ImportFamiliesDialog.xaml

Resolve some Waring error format markup not allow with rider.

Fix(DUI): clean up incorrect syntax

---

DesktopUI2/DesktopUI2/ViewModels/DesignViewModels/DesignHomeViewModel.cs

Should be use get set in this case with `HasSavedStreams` property

Fix binding value default

---

ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/Entry/Plugin.cs
ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/UI/MappingBindingsRhino.cs
DesktopUI2/DesktopUI2/DesktopUI2.csproj
DesktopUI2/DesktopUI2/ViewModels/MappingTool/MappingsViewModel.cs
DesktopUI2/DesktopUI2/ViewModels/MappingTool/Schemas.cs
DesktopUI2/DesktopUI2/Views/Mappings/Controls/RevitBasic.xaml
DesktopUI2/DesktopUI2/Views/Mappings/Controls/RevitBasic.xaml.cs
DesktopUI2/DesktopUI2/Views/MappingsControl.xaml
Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.cs

Adds Beam and Brace elements to the mapping too in Rhino>Revit

feat(mappings): adds beam and brace support

---

ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/UI/ConnectorBindingsRhino.cs

feat(rhino): open comments view with shaded mode

---

ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/UI/MappingBindingsRhino.cs
DesktopUI2/DesktopUI2/ViewModels/CommentViewModel.cs
DesktopUI2/DesktopUI2/ViewModels/MappingTool/MappingsViewModel.cs
DesktopUI2/DesktopUI2/ViewModels/MappingTool/Schemas.cs
DesktopUI2/DesktopUI2/Views/MappingsControl.xaml
Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.Other.cs
Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.cs
Objects/Objects/Other/Transform.cs

Adds Family Instance from point or block

feat(mappings): family instance

---

Core/Core/Logging/Analytics.cs
DesktopUI2/DesktopUI2/ViewModels/MappingTool/MappingsViewModel.cs
DesktopUI2/DesktopUI2/Views/MappingsControl.xaml.cs

feat(mappings): tracks basic events

---

ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/UI/ConnectorBindingsRhino.cs

Margins of the `SpeckleCommentView` set before by copying the active one. Those margins are resetted.
Additionally all other views that maximized is forced to minimized except `SpeckleCommentView`.

fix(rhino): reset-margins-of-comment-view

---

ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/Entry/Plugin.cs
DesktopUI2/DesktopUI2/ViewModels/MappingTool/MappingsViewModel.cs
DesktopUI2/DesktopUI2/Views/MappingsControl.xaml

Better handling of the rhino idele event
Correctly applies the Dark style to the user control

fix(mapping): idele and styles

---

ConnectorAutocadCivil/ConnectorAutocad2021/Properties/AssemblyInfo.cs
ConnectorAutocadCivil/ConnectorAutocad2022/Properties/AssemblyInfo.cs
ConnectorAutocadCivil/ConnectorAutocad2023/ConnectorAutocad2023.csproj
ConnectorAutocadCivil/ConnectorAutocad2023/Properties/AssemblyInfo.cs
ConnectorAutocadCivil/ConnectorCivil2021/Properties/AssemblyInfo.cs
ConnectorAutocadCivil/ConnectorCivil2022/Properties/AssemblyInfo.cs
ConnectorAutocadCivil/ConnectorCivil2023/Properties/AssemblyInfo.cs

adds post build event to acad 2023

chore(acad): adds post build event to acad 2023

---

ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/Entry/Plugin.cs
Core/Core/Api/Helpers.cs
DesktopUI2/DesktopUI2/App.xaml.cs
DesktopUI2/DesktopUI2/ViewModels/CollaboratorsViewModel.cs
DesktopUI2/DesktopUI2/ViewModels/HomeViewModel.cs
DesktopUI2/DesktopUI2/ViewModels/StreamViewModel.cs

fix(dui): better offline state management & fix for #1888

---

Core/Core/Api/GraphQL/Client.cs
DesktopUI2/DesktopUI2/ViewModels/HomeViewModel.cs

Fix: ensure subscriptions are disposed in DUI when changing document.

fix(dui): dispose subscriptions when changing doc

---

Core/Core/Api/Helpers.cs

Adds helper method for pinging websites

feat(core): adds extra method to ping and get website

---

DesktopUI2/DesktopUI2/ViewModels/OneClickViewModel.cs
DesktopUI2/DesktopUI2/Views/Pages/OneClickView.xaml

fixes #1908 by informing the user if send was not successful in the one click send

fix(dui): fixes #1908 by informing the user if send was not succesful

---

Objects/Converters/ConverterCSI/ConverterCSIShared/Partial Classes/Geometry/ConvertArea.cs

very simple exception fix
- remove unsafe cast

Fix(CSI): Invalid cast exception

---

ConnectorGrasshopper/ConnectorGrasshopperShared/Loader.cs
DesktopUI2/DesktopUI2/ViewModels/HomeViewModel.cs

Also, aligns the Rhino version with the new manager app name

fix(gh/rh): Fixes crash when trying to open manager in GH

---

ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/UI/ConnectorBindingsRhino.cs

Fixed the regression introduced by #1916
I've commented the code with a short explanation of the problem
targeting #1922 for @clairekuang to review

fix(rhino): Fixed regression converting elements from connector bindings

---

Core/Core/Kits/KitManager.cs

Receiving operations in ETABS (and maybe other applications) were failing when assemblies were failing to load.
- add try catch to "Assembly.Load()" operation and move on to the next assembly if the operation fails
Receiving in ETABS now works as expected when specific assemblies fail to load

Fix(Core): operations failing after assembly failed to load

---

Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertAnalyticalStick.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertAnalyticalSurface.cs

fixes exception that is being thrown when material asset is null
- fix for setting releases for element1D
- fixes materialAsset null reference
- delete duplicated code
manual testing
this PR combines and adds on to these two PRs https://github.com/specklesystems/speckle-sharp/pull/1896 https://github.com/specklesystems/speckle-sharp/pull/1931

Fix(Revit): check material asset for null

---

Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertAnalyticalStick.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertAnalyticalSurface.cs

- move name assignment into check for invalid element id
- use same method for material assignment for 1D and 2D structural elements
- check for null materialAsset
- if material has no name, set the name to the name of the material (i.e. wood, concrete, steel, etc.)
- able to receive structural elements of Revit house with no errors thrown
Builds on top of many other PRs
https://github.com/specklesystems/speckle-sharp/pull/1940
https://github.com/specklesystems/speckle-sharp/pull/1931
https://github.com/specklesystems/speckle-sharp/pull/1896

Fix(Revit): Structural materials error

---

ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/UI/ConnectorBindingsRhino.cs

Minor hickup while merging a hotfix, I did not realize the target was set to `release/2.10`, merging into `main` now as it will be released from there.

Merged #1959 into the wrong branch, merging to main now

---

DesktopUI2/DesktopUI2/ViewModels/StreamViewModel.cs
DesktopUI2/DesktopUI2/Views/Controls/StreamEditControls/Receive.xaml
DesktopUI2/DesktopUI2/Views/Controls/StreamEditControls/Receive.xaml.cs

Fixes preview issues in DUI: #1961 #1960
A bit hacky but it gets the job done :)

fix(dui): preview issues #1961 #1960

---

Objects/Converters/ConverterRevit/ConverterRevit2023/Properties/launchSettings.json

Some config debug for revit 2023 is not correct.

Fix config debug revit 2023

---

.circleci/scripts/config-template.yml

update all installers to net6

---

ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/UI/MappingBindingsRhino.cs
DesktopUI2/DesktopUI2/DummyMappingsBindings.cs
DesktopUI2/DesktopUI2/MappingsBindings.cs
DesktopUI2/DesktopUI2/ViewModels/MappingTool/MappingsViewModel.cs
DesktopUI2/DesktopUI2/ViewModels/StreamViewModel.cs
DesktopUI2/DesktopUI2/Views/Filters/ManualFilterView.xaml
DesktopUI2/DesktopUI2/Views/MappingsControl.xaml
DesktopUI2/DesktopUI2/Views/MappingsControl.xaml.cs
Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.cs

- improved selection flow
- fixed rhino hang on send if exception occurs
- meshes handled correctly in the DS option

feat: mappings work

---

.circleci/config.yml
.circleci/scripts/connector-jobs.yml
.circleci/scripts/parameters.json
ConnectorNavisworks/ConnectorNavisworks2020/ConnectorNavisworks2020.csproj
ConnectorNavisworks/ConnectorNavisworks2021/ConnectorNavisworks2021.csproj
ConnectorNavisworks/ConnectorNavisworks2022/ConnectorNavisworks2022.csproj
ConnectorNavisworks/ConnectorNavisworks2023/ConnectorNavisworks2023.csproj

Repeating approved Navisworks CI Config changes from a speckle systems branch

updated: Navis ci config into Release/2.11

---

ConnectorNavisworks/ConnectorNavisworks/Bindings/ConnectorNavisworksBindings.Filters.cs
ConnectorNavisworks/ConnectorNavisworks/Bindings/ConnectorNavisworksBindings.Objects.cs
ConnectorNavisworks/ConnectorNavisworks/Bindings/ConnectorNavisworksBindings.Selections.cs
ConnectorNavisworks/ConnectorNavisworks/Bindings/ConnectorNavisworksBindings.Send.cs
ConnectorNavisworks/ConnectorNavisworks/Utils.cs
ConnectorNavisworks/ConnectorNavisworks2020/Properties/launchSettings.json
ConnectorNavisworks/ConnectorNavisworks2021/Properties/launchSettings.json
ConnectorNavisworks/ConnectorNavisworks2022/Properties/launchSettings.json
ConnectorNavisworks/ConnectorNavisworks2023/Properties/launchSettings.json
Objects/Converters/ConverterNavisworks/ConverterNavisworks/ConverterNavisworks.Geometry.cs
Objects/Converters/ConverterNavisworks/ConverterNavisworks/ConverterNavisworks.Other.cs
Objects/Converters/ConverterNavisworks/ConverterNavisworks/ConverterNavisworks.Properties.cs
Objects/Converters/ConverterNavisworks/ConverterNavisworks/ConverterNavisworks.ToSpeckle.cs
Objects/Converters/ConverterNavisworks/ConverterNavisworks/ConverterNavisworksShared.projitems

Implements additional items on the initial roadmap for alpha
- SavedStream specifying SavedSearches and SavedSelections now adds these as Objects to convert and send
- Better Object Conversion reporting
- Correct Units conversion
- Non-geometric nodes conversion
- Full property translation and addition

enhancement(Navisworks): Updates for alpha2

---

ConnectorNavisworks/ConnectorNavisworks/Bindings/ConnectorNavisworksBindings.Events.cs
ConnectorNavisworks/ConnectorNavisworks/Bindings/ConnectorNavisworksBindings.Send.cs
ConnectorNavisworks/ConnectorNavisworks/Bindings/ConnectorNavisworksBindings.cs
ConnectorNavisworks/ConnectorNavisworks2020/ConnectorNavisworks2020.csproj
ConnectorNavisworks/ConnectorNavisworks2021/ConnectorNavisworks2021.csproj
ConnectorNavisworks/ConnectorNavisworks2022/ConnectorNavisworks2022.csproj
ConnectorNavisworks/ConnectorNavisworks2023/ConnectorNavisworks2023.csproj
Objects/Converters/ConverterNavisworks/ConverterNavisworks/ConverterNavisworks.Geometry.cs
Objects/Converters/ConverterNavisworks/ConverterNavisworks/ConverterNavisworks.ToSpeckle.cs
Objects/Converters/ConverterNavisworks/ConverterNavisworks/ConverterNavisworks.cs

**Converter**
- Fixes #2015. 
- General renaming of class, static and callback methods for code legibility
- Refactoring out duplicate code for code legibility
**Connector**
- Adds capability to the selected object tree traversal to cover more cases than Can/Cannot convert
- Aligns Kit loading logic to other connectors
Manual conversion testing with models of both Up Vector scenarios.

Fix (navisworks): Model YZ orientation

---

ConnectorArchicad/AddOn/CMakeLists.txt
ConnectorArchicad/AddOn/Sources/AddOn/AddOnMain.cpp
ConnectorArchicad/AddOn/Sources/AddOn/Commands/CreateColumn.cpp
ConnectorArchicad/AddOn/Sources/AddOn/Commands/CreateColumn.hpp
ConnectorArchicad/AddOn/Sources/AddOn/Commands/GetColumnData.cpp
ConnectorArchicad/AddOn/Sources/AddOn/Commands/GetColumnData.hpp
ConnectorArchicad/AddOn/Sources/AddOn/FieldNames.hpp
ConnectorArchicad/AddOn/Sources/AddOn/ResourceIds.hpp
ConnectorArchicad/ConnectorArchicad/Communication/Commands/Command_CreateColumn.cs
ConnectorArchicad/ConnectorArchicad/Communication/Commands/Command_GetColumnData.cs
ConnectorArchicad/ConnectorArchicad/Converters/Converters/ColumnConverter.cs
ConnectorArchicad/ConnectorArchicad/Converters/ElementConverterManager.cs
ConnectorArchicad/ConnectorArchicad/Converters/ElementTypeProvider.cs
Objects/.editorconfig
Objects/Objects/BuiltElements/Beam.cs
Objects/Objects/BuiltElements/Column.cs

Column exchange for Archicad.
New `class ArchicadColumn : Objects.BuiltElements.Column` added, should not break compatibility.

Feature: Add Archicad Column exchange

---

ConnectorTeklaStructures/ConnectorTeklaStructuresShared/UI/ConnectorBindingsTeklaStructure.Send.cs
ConnectorTeklaStructures/ConnectorTeklaStructuresShared/UI/ConnectorBindingsTeklaStructures.ClientOperations.cs
ConnectorTeklaStructures/ConnectorTeklaStructuresShared/UI/ConnectorBindingsTeklaStructures.Receive.cs
Objects/Converters/ConverterTeklaStructures/ConverterTeklaStructuresShared/Partial Classes/ConvertBeam.cs
Objects/Converters/ConverterTeklaStructures/ConverterTeklaStructuresShared/Partial Classes/ConvertContourPlate.cs
Objects/Converters/StructuralUtilities/PolygonMesher/PolygonMesher.cs

Found a few issues when investigating sending a large model (courtesy of B&G) from Tekla Structures to Speckle
- add check for number of points before trying to make a mesh in polygonMesher
- wrap convertToSpeckle in try catch so entire operation doesn't fail when encountering future bugs
- clear saved document streams before recreating them so we don't end up with 50 of the same saved stream state
- add some null checks for materials and profiles
- large model sent from B&G now sends with no conversion failures
https://latest.speckle.dev/streams/96765a5c41/commits/f8afe96e60
https://speckle.community/t/exchange-speckle-bollinger-grohmann/3551

fix(tekla): miscellaneous fixes

---

Objects/Converters/ConverterRevit/ConverterRevitShared/ConversionUtils.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/ConverterRevit.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertCeiling.cs
Objects/Objects/BuiltElements/Ceiling.cs

- return true from ShouldConvertHostedElement if the host element is a level because the level will definitely not be responsible for converting the element
- don't exclude height offset from level prop and don't store seperately for ceilings. This change is in line with existing behavior of floors and roofs
- depricate offset property of ceiling because it was only ever being set, not used.
manually sending and receiving led to correct location for ceiling objects
https://speckle.community/t/isses-with-attached-walls-in-revit/4171

fix(revit): incorrect ceiling locations and don't allow level as host

---

ConnectorRevit/ConnectorRevit/UI/ConnectorBindingsRevit.Events.cs
DesktopUI2/DesktopUI2/ViewModels/MainViewModel.cs
DesktopUI2/DesktopUI2/Views/Pages/LogInView.xaml

A bug was introduced a while back that caused the Revit connector to appear blank when no accounts were present instead of presenting the Log In page
- when document is loaded, go to default page instead of going to the home page.
Before 
After:
log in page is now displayed instead of empty page

fix(revit): no accounts bug

---

.github/workflows/close-issue.yml
.github/workflows/open-issue.yml

Updates github actions to use the ones stored in the new actions repo

ci: update GitHub actions

---

Objects/Converters/ConverterRevit/ConverterRevitShared/ConversionUtils.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/ConverterRevit.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/ConverterRevitShared.projitems
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertBeam.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertColumn.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertFamilyInstance.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertGroup.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertRevitElement.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertStructuralConnectionHandlers.cs
Objects/Objects/BuiltElements/Revit/StructuralConnectionHandler.cs

support more Revit <-> Speckle conversions 
- dig into hosted elements of generic revit elements to support objects such as beam systems
- add conversion to Speckle for StructuralConnectionHandler elements (conversion to native not yet supported)
- add custom conversion for Revit Groups
- change the way we get meshes for beams, braces, and columns if it has steel modifiers or structuralConnectionHandlers attached to it because those elements are view-specific and need to be passed in a view in order to return the correct mesh
Revit model 1
Before this commit
After this commit - https://latest.speckle.dev/streams/85bc4f61c6/commits/ec70e7e979
Revit model 2
Before this commit
After this commit - https://latest.speckle.dev/streams/85bc4f61c6/commits/904a92a51f
see images above + manual tests …

feat(revit): support new objects

---

ConnectorCSI/ConnectorCSIShared/UI/ConnectorBindingsCSI.Selection.cs

refresh existing object ids in the model when using selection and group sending modes
Sending selection now works after major changes have been made to the model

fix(csi): refresh object Ids for selection and group modes

---

ConnectorNavisworks/ConnectorNavisworks2020/ConnectorNavisworks2020.csproj
ConnectorNavisworks/ConnectorNavisworks2021/ConnectorNavisworks2021.csproj
ConnectorNavisworks/ConnectorNavisworks2022/ConnectorNavisworks2022.csproj
ConnectorNavisworks/ConnectorNavisworks2023/ConnectorNavisworks2023.csproj
Objects/Converters/ConverterNavisworks/ConverterNavisworks2020/ConverterNavisworks2020.csproj
Objects/Converters/ConverterNavisworks/ConverterNavisworks2021/ConverterNavisworks2021.csproj
Objects/Converters/ConverterNavisworks/ConverterNavisworks2022/ConverterNavisworks2022.csproj
Objects/Converters/ConverterNavisworks/ConverterNavisworks2023/ConverterNavisworks2023.csproj
Objects/Converters/ConverterRevit/ConverterRevit2022/ConverterRevit2022.csproj
Objects/Converters/ConverterRevit/ConverterRevit2023/ConverterRevit2023.csproj

Post build event fixes for the NuGet CI

Navis postbuild

---

ConnectorRevit/ConnectorRevit/UI/ConnectorBindingsRevit.Receive.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/ConversionUtils.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/ConverterRevit.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertFloor.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertLocation.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertOpening.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertRoof.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertWall.cs

- pass transaction from connector to converter using converter.setContextDocument because there are certain api calls (editing a wall profile is one of them) that are required to start their own transaction which cannot happen if a transaction is already open. 
- add voids to walls via profile lines for Revit 22&23
- fix broken logic for adding rectangular opening to walls
- get the location of line-base (slanted) columns differently than upright columns
- add conversion of sloped floors using slope arrow
Original Revit model:
Sent and received back before this PR
- Slanted columns now vertical
- Walls have no openings
- Floors failed to convert
Sent and received back after this PR
- Bottom left floor doesn't have original subelements
Manual sending and receiving …

fix(revit): support Revit <-> Speckle conversions

---

.circleci/scripts/config-template.yml

ci: remove -v param as not supported

---

Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertFamilyInstance.cs

- on send, if a family instance is two level based in Revit then we add the topLevel param
- on receive, set the top level param if it exists on the objects
two level based family instances now properly receive with the correct top and bottom level set with the correct top and bottom level offsets
https://speckle.community/t/revit-2-levels-family/4703
closes https://github.com/specklesystems/speckle-sharp/issues/2081

fix(revit): assign topLevel to family instances if applicable

---

Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertFloor.cs

the floor property of the RevitFloor object was never being set.
- set family property in the FloorToSpeckle method
https://speckle.community/t/no-families-for-revit-floors/4850

Fix(Revit): add family to RevitFloors

---

.circleci/scripts/config-generator.py
.circleci/scripts/config-template.yml

What the title says :)
Not sure if my python edits will werk...

ci: discord nofitication

---

ConnectorCSI/DriverPluginCSharp/DriverPluginCSharp.csproj
ConnectorCSI/DriverPluginCSharp/packages.config

Addresses https://github.com/specklesystems/speckle-sharp/pull/2073 by updating the project to the new SDK style.

feat: upgrades DriverPlugin to PackageReference, fixes #2073

---

.circleci/scripts/config-generator.py
.circleci/scripts/config-template.yml

Reverts specklesystems/speckle-sharp#2104

Revert "ci: discord nofitication"

---

Core/Core/Credentials/AccountManager.cs
DesktopUI2/DesktopUI2/Utils.cs
DesktopUI2/DesktopUI2/ViewModels/HomeViewModel.cs
DesktopUI2/DesktopUI2/Views/Pages/HomeView.xaml

Brings the accounts hotfix into `dev`.
* fix: prevents multiple account flows running at the same time, properly reports error
* fix(dui): prevent multiple add account flows
* fix(core): better disposal of listener
* fix(core): prevent double error reporting
* chore: comment cleanup

Matteo/core/account flow (#2140)

---

ConnectorNavisworks/ConnectorNavisworks/Bindings/ConnectorNavisworksBindings.Events.cs
ConnectorNavisworks/ConnectorNavisworks/Bindings/ConnectorNavisworksBindings.Filters.cs
ConnectorNavisworks/ConnectorNavisworks/Bindings/ConnectorNavisworksBindings.Objects.cs
ConnectorNavisworks/ConnectorNavisworks/Bindings/ConnectorNavisworksBindings.Receive.cs
ConnectorNavisworks/ConnectorNavisworks/Bindings/ConnectorNavisworksBindings.Selections.cs
ConnectorNavisworks/ConnectorNavisworks/Bindings/ConnectorNavisworksBindings.Send.cs
ConnectorNavisworks/ConnectorNavisworks/Bindings/ConnectorNavisworksBindings.Settings.cs
ConnectorNavisworks/ConnectorNavisworks/Bindings/ConnectorNavisworksBindings.cs
ConnectorNavisworks/ConnectorNavisworks/Commands/Commands.cs
ConnectorNavisworks/ConnectorNavisworks/Entry/Ribbon.xaml.cs
ConnectorNavisworks/ConnectorNavisworks/Entry/SpeckleHostPane.xaml.cs
ConnectorNavisworks/ConnectorNavisworks/Entry/SpeckleNavisworksCommand.cs
ConnectorNavisworks/ConnectorNavisworks/Other/Utils.cs
ConnectorNavisworks/ConnectorNavisworks/Other/ViewProxy.cs
Objects/Converters/ConverterNavisworks/ConverterNavisworks/ConverterNavisworks.Geometry.cs
Objects/Converters/ConverterNavisworks/ConverterNavisworks/ConverterNavisworks.Other.cs
Objects/Converters/ConverterNavisworks/ConverterNavisworks/ConverterNavisworks.Properties.cs
Objects/Converters/ConverterNavisworks/ConverterNavisworks/ConverterNavisworks.Settings.cs
Objects/Converters/ConverterNavisworks/ConverterNavisworks/ConverterNavisworks.ToNative.cs
Objects/Converters/ConverterNavisworks/ConverterNavisworks/ConverterNavisworks.ToSpeckle.cs
Objects/Converters/ConverterNavisworks/ConverterNavisworks/ConverterNavisworks.Utils.cs
Objects/Converters/ConverterNavisworks/ConverterNavisworks/ConverterNavisworks.cs

This PR adopts the code style stored in .editorconfig in Speckle/Core

chore(Navisworks): Codestyle changes, no functional change

---

.circleci/scripts/config-template.yml

fix(ci): make sure brew install is not trying to update dependent packages

---

.circleci/config.yml
.circleci/scripts/config-template.yml
.circleci/scripts/connector-jobs.yml

Archicad Connector .net project on Windows was not set to self-contained.
Closes:
* https://speckle.community/t/archicad-connector-fails-to-load/4987
* https://speckle.community/t/archicad-pop-up-blocked/4492

Archicad self contained connector on Windows

---

ConnectorArchicad/AddOn/Sources/AddOn/Commands/CreateWall.cpp
ConnectorArchicad/AddOn/Sources/AddOn/Commands/GetWallData.cpp
ConnectorArchicad/AddOn/Sources/AddOn/FieldNames.hpp
ConnectorArchicad/AddOn/Sources/AddOn/TypeNameTables.cpp
ConnectorArchicad/AddOn/Sources/AddOn/TypeNameTables.hpp
ConnectorArchicad/AddOn/Sources/AddOn/Utility.cpp
ConnectorArchicad/AddOn/Sources/AddOn/Utility.hpp
Objects/Objects/BuiltElements/Wall.cs

Improve Archicad Wall exchange:
* All API fields are sent and received
* Walls can be transferred between Archicads without losses

Wall improvements

---

ConnectorArchicad/ConnectorArchicad/Converters/ElementConverterManager.cs

fix(archicad): Use application id

---

Core/Core/Serialisation/BaseObjectDeserializerV2.cs
Core/Core/Serialisation/BaseObjectSerializerV2.cs

https://speckle.xyz/streams/e3dd265803/commits/53cd1db921
Community provided a floor that was sent to Speckle yet was failing to deserialize on receive back into Revit. Upon further investigation, we found that this object has a property "Analytical heat transfer coefficient" that has a value of 1 * 10^30. Turns out newtonsoft is serializing this as a big integer which is a struct in the system.numerics namespace. On deserialize, our custom deserializer is trying to explicitly cast this value to a long which fails because this value is much larger than long.MaxValue.
- if a number fails to deserialize as a long, deserialize it as a bigInt
This floor in the stream mentioned above now deserializes and receives in Revit
Issues like this are a reason to make a move on this issue …

fix(core): deserialize as big int when long fails

---

Core/Core/Serialisation/BaseObjectDeserializerV2.cs
Core/Core/Serialisation/BaseObjectSerializerV2.cs

Update `main` into `dev`

---

Core/Core/Serialisation/BaseObjectDeserializerV2.cs
Core/Core/Serialisation/BaseObjectSerializerV2.cs

Reverts specklesystems/speckle-sharp#2219

Revert "Update `main` into `dev`"

---

Core/Core/Serialisation/BaseObjectDeserializerV2.cs
Core/Core/Serialisation/BaseObjectSerializerV2.cs

Updating dev from main. THIS SHOULD NOT BE SQUASH MERGED.

Update `dev` from `main`

---

ConnectorNavisworks/ConnectorNavisworks/Bindings/ConnectorNavisworksBindings.Filters.cs
ConnectorNavisworks/ConnectorNavisworks/Bindings/ConnectorNavisworksBindings.Objects.cs
ConnectorNavisworks/ConnectorNavisworks/Bindings/ConnectorNavisworksBindings.Send.cs
ConnectorNavisworks/ConnectorNavisworks/Entry/Ribbon.xaml.cs
ConnectorNavisworks/ConnectorNavisworks/Storage/SpeckleStreamManager.cs
Objects/Converters/ConverterNavisworks/ConverterNavisworks/ConverterNavisworks.cs

Numerous exceptions and errors were difficult to trace, debug, and correct for or caused hard fatal crashes to the host application.
This PR encapsulates several improvements rather than addressing a reported bug/issue.
ConnectorNavisworksBindings.Filters:
- Addition of an 'all' filter. This wasn't included previously because it was considered dangerous to offer it, while the Connector wasn't 100% stable or incomplete to manage user expectations of a meaningful commit. However, a lack of an Everything filter causes a hard crash in the One-Click-Send mode.
- The selection of the Everything filter is still non-functional, but UI labelling and a fallback error message communicate this ahead of Selection and on unsuccessful Send.
SpeckleStreamManager:
- Added checks for a missing ActiveSheet. …

fix(Navisworks): Various stability improvements

---

Objects/Objects/BuiltElements/AdvanceSteel/AdvanceSteelBolt.cs

fix(advancesteel): adds empty constructors

---

ConnectorAutocadCivil/ConnectorAutocadCivil/UI/ConnectorBindingsAutocadCivil.cs
ConnectorAutocadCivil/ConnectorAutocadCivil/Utils.cs
Core/Core/Models/Extras.cs
Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.AdvanceSteel.cs
Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.DxfNames.cs
Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.cs
Objects/Objects/BuiltElements/AdvanceSteel/AdvanceSteelBolt.cs
Objects/Objects/BuiltElements/AdvanceSteel/AdvanceSteelSpecialPart.cs

- Convert Advance Steel Special Part to Speckle
- Update the ApplicationObject with the FilerObject type in the descriptor property because without it all objects were shown with the description 'Autodesk.AutoCAD.DatabaseServices.ImpObject'
- Use Dynamic in ConvertASToSpeckle instead of switch condition.

feat(AdvanceSteel): Special Part To Speckle Object

---

All.sln
ConnectorAutocadCivil/ConnectorAutocadCivil/UI/ConnectorBindingsAutocadCivil.cs
ConnectorBentley/ConnectorBentleyShared/UI/Bindings.cs
ConnectorCSI/ConnectorCSIShared/UI/ConnectorBindingsCSI.Recieve.cs
ConnectorGrasshopper/ConnectorGrasshopperShared/SchemaBuilder/SchemaBuilderGen.cs
ConnectorRevit/ConnectorRevit/UI/ConnectorBindingsRevit.Receive.cs
ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/UI/ConnectorBindingsRhino.cs
ConnectorTeklaStructures/ConnectorTeklaStructuresShared/UI/ConnectorBindingsTeklaStructures.Receive.cs
DesktopUI2/DesktopUI2/Models/StreamState.cs
DesktopUI2/DesktopUI2/ViewModels/StreamViewModel.cs

Helps us track if ppl receive in multiplayer or not.

feat(dui): tracks if isMultiplayer on receive

---

Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.AdvanceSteel.cs
Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.DxfNames.cs
Objects/Objects/BuiltElements/AdvanceSteel/AdvanceSteelGrating.cs

- Convert Advance Steel Grating to Speckle

feat(AdvanceSteel): Grating To Speckle Object

---

Objects/Converters/ConverterCSI/ConverterCSIShared/ConverterCSI.cs
Objects/Converters/ConverterCSI/ConverterCSIShared/ConverterCSIShared.projitems
Objects/Converters/ConverterCSI/ConverterCSIShared/Partial Classes/Geometry/ConvertBeam.cs
Objects/Converters/ConverterCSI/ConverterCSIShared/Partial Classes/Geometry/ConvertBuiltElement.cs
Objects/Converters/ConverterCSI/ConverterCSIShared/Partial Classes/Geometry/ConvertFrame.cs
Objects/Converters/ConverterCSI/ConverterCSIShared/Partial Classes/Properties/Convert1DProperty.cs

- add beams, braces, and columns from the builtelements namespace to the CanConvertToNative method
- added function to convert 1D built element to CSI frame element
- split the frameToNative and Property1DToNative methods into smaller methods in order to make it more reusable
Was able to receive [this commit](https://speckle.xyz/streams/422f7f13d4/commits/fa82434aaf) that has beam and column schemas applied to different to rhino objects. See screenshot above.

feat(csi): add support for recieving built elements

---

ConnectorGrasshopper/ConnectorGrasshopperShared/Streams/StreamGetComponentV2.cs
ConnectorGrasshopper/ConnectorGrasshopperShared/Streams/StreamUpdateComponentV2.cs

This prevents it from locking the thread on await calls or .Result
Reported through our Discord by ARUP peeps 🙌🏼

fix(gh): StreamGet and StreamUpdate were missing Task.Run

---

ConnectorNavisworks/ConnectorNavisworks/Entry/SpeckleNavisworksCommand.cs
ConnectorRevit/ConnectorRevit/Entry/App.cs

- hook up OnAssemblyResolve logic to load dlls before any other logic
https://speckle.community/t/speckle-2-for-revit-could-not-load/5301/5

fix(Revit,Navis): resolve unsafe dll error

---

ConnectorRevit/ConnectorRevit.sln
Objects/Converters/ConverterRevit/ConverterRevitShared/ConversionUtils.cs

Addresses all cases of linked models and shared coordinates, kudos to @clairekuang for nailing this one!
Test models:
[Revit_linked_model_test_project-20230328T152535Z-001.zip](https://github.com/specklesystems/speckle-sharp/files/11119863/R
[LinkedProject.zip](https://github.com/specklesystems/speckle-sharp/files/11119866/LinkedProject.zip)
evit_linked_model_test_project-20230328T152535Z-001.zip)
Results: https://latest.speckle.dev/streams/58e8ba5320

Linked models & shared coords improvements

---

ConnectorRevit/ConnectorRevit.sln
Objects/Converters/ConverterRevit/ConverterRevitShared/ConversionUtils.cs

Reverts specklesystems/speckle-sharp#2369

Revert "Linked models & shared coords improvements (#2368)"

---

.editorconfig
All.sln
DesktopUI2/DesktopUI2.Launcher/DesktopUI2.Launcher.csproj
DesktopUI2/DesktopUI2.WPF/DesktopUI2.WPF.csproj
Directory.Build.props

All.sln now contains a folder of `Solution Items` for convenience:
- .editorconfig
- Directory.Build.props
- Directory.Build.targets
Modified basic Props file with complete analyzer ruleset
Added some missing config options to .editorconfig
Upgraded net5.0 DUI projects to Net6.0

cleanup(all): Minor changes in EditorConfig, All.sln, DUI and Props file

---

ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/UI/MappingBindingsRhino.cs

Fixes #2379 
Adds support for mapping a planar non-linear curved to Beam in Revit

feat(mapping): Added support for planar curve -> beam

---

ConnectorGrasshopper/ConnectorGrasshopper7/ConnectorGrasshopper7.csproj
ConnectorRhino/ConnectorRhino7/ConnectorRhino7.csproj

Attempt of fixing the DUI3 failing CI

fix(rhino): Attempt to fix CI failing builds on DUI3 branch

---

DesktopUI2/DesktopUI2/Models/ConfigManager.cs
DesktopUI2/DesktopUI2/Styles/Button.xaml
DesktopUI2/DesktopUI2/ViewModels/CommentViewModel.cs
DesktopUI2/DesktopUI2/ViewModels/HomeViewModel.cs
DesktopUI2/DesktopUI2/ViewModels/StreamViewModel.cs
DesktopUI2/DesktopUI2/Views/Controls/SavedStreams.xaml
DesktopUI2/DesktopUI2/Views/Controls/StreamDetails.xaml
DesktopUI2/DesktopUI2/Views/Controls/StreamEditControls/Receive.xaml
DesktopUI2/DesktopUI2/Views/Controls/StreamEditControls/Send.xaml
DesktopUI2/DesktopUI2/Views/Converters/Fe2TextValueConverter.cs
DesktopUI2/DesktopUI2/Views/Pages/HomeView.xaml

- adds toggle in DUI to use FE2 links and strings
- does not navigate to report page by default anymore

DUI FE2 toggle

---

ConnectorCSI/ConnectorCSIBridge/ConnectorCSIBridge.csproj
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertFloor.cs

Update dev from main

---

.circleci/scripts/common-jobs.yml
.circleci/scripts/config-generator.py
.circleci/scripts/config-template.yml
.circleci/scripts/connector-jobs.yml
ConnectorRhino/ConnectorRhino6/ConnectorRhino6.csproj
ConnectorRhino/ConnectorRhino7/ConnectorRhino7.csproj
Objects/Tests/Tests.csproj

Trying to build with dotnet instead

Attempt at fixing our CI on mac after the reformat

---

.config/dotnet-tools.json
.husky/pre-commit
.husky/task-runner.json
Core/Core/Core.csproj

New dotnet tool to handle automatic formatting of changed files on pre-commit.
Weird formatting, begone! 🙈

feat(repo): Added husky for pre-commit formatting + auto-install on NugetRestore

---

Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertAnalyticalStick.cs

- ApplicationId property will be set on Property1D and Material conversion to Speckle.
- Allow Element1D to convert to analytical stick successfully (assigning default family/type) when Property1D name is not set, instead of throwing an exception [on this line](https://github.com/specklesystems/speckle-sharp/blob/dev/Objects/Converters/ConverterRevit/ConverterRevitShared/Partial%20Classes/ConvertAnalyticalStick.cs#L125) and skipping conversion of the object.
- If Property1D name is null, we can rely on [GetElementType](https://github.com/specklesystems/speckle-sharp/blob/dev/Objects/Converters/ConverterRevit/ConverterRevitShared/ConversionUtils.cs#L607) to assign the default family/type existing in the Revit model.
**Related issues:**
#2333 
#2354 
- Add unique ids for Material and …

fix(revit): analytical stick conversion improvements

---

Objects/Converters/ConverterRevit/ConverterRevitShared/ConversionUtils.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertFloor.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertGroup.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertRoof.cs

Bring significant performance improvement to models with a lot of floors
- don't use the delete element hack to get the slope arrow, it can be obtained through GetDependentElements()
- Rename custom function "GetDependentElementIds" to "GetHostedElementIds" because that name better matches what the function does
Here is a screenshot of the profiling flame graph before this PR.
Total time of sending was 6:37 and the FloorToSpeckle method took 107354 ticks
Here is a screenshot of the profiling flame graph after this PR.
Total time of sending was 2:37 and the FloorToSpeckle method took 1868 ticks
See above screenshots for validation of changes. Tests were run on a model that is under an NDA, so I can't share it
https://speckle.community/t/revit-to-etabs-groups/5419
This PR -> …

fix(Revit): change get floor slope method

---

Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertFloor.cs

Incoming ellipses and circles must be flattened in order to make an acceptable Revit outline.
- add case for creating flattened circles and ellipses
- I created working tests for these changes, but those tests depend changes in dev. They will be merged into dev after https://github.com/specklesystems/speckle-sharp/pull/2452 is merged
https://speckle.community/t/revit-connector-ellipse-issue/5481

Hotfix(Revit): add floor conversion for ellipse and circle

---

Objects/Converters/ConverterRevit/ConverterRevitShared/ConverterRevit.cs

[This change to ContexObjects](https://github.com/specklesystems/speckle-sharp/pull/2454) was problematic for elements coming from Blender etc that don't have an `applicationId`, this PR fixes that with a fallback on Speckle `Id`.
Internal convo: https://discord.com/channels/726756379083145269/990984136103723089/1098223681009897585

fix(revit): fallback to speckle id when applicationId is null

---

Objects/Converters/ConverterRevit/ConverterRevitShared/ConversionUtils.cs

- converter should skip an object if it is not in context objects. Context objects is the list of all objects that are going to be sent. If an element is missing from context objects, then we assume it has already converted itself, therefore the parent should not convert it
- wrap subelement conversion in try catch so that if a single hosted element fails to convert, the rest of the hosted elements will continue to convert.
This is the PR that originally broke this behavior https://github.com/specklesystems/speckle-sharp/pull/2454

Fix(Revit): Recent change to context objects broke groups

---

.circleci/scripts/config-template.yml
.circleci/scripts/connector-jobs.yml

Adds advance steel to CI pipeline

CI: AdvanceSteel build and installer

---

DesktopUI2/DesktopUI2/ViewModels/CollaboratorsViewModel.cs
DesktopUI2/DesktopUI2/ViewModels/StreamViewModel.cs

Adds some safety guards in DUI, potentially fixes: #2281

fix(dui): adds some try catches

---

Objects/Converters/ConverterRevit/ConverterRevitShared/ConverterRevit.cs

fix(revit): usign the wrong variable

---

Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertLocation.cs

- change to getting BIM baseLine from getting analytical model baseLine for non-analytical columns
https://speckle.community/t/revit-rhino-column-baselines/4184/12

Fix(Revit) : Send BIM base line instead of analytical baseline

---

Objects/Converters/ConverterRevit/ConverterRevitShared/ConversionUtils.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertAdaptiveComponent.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertAnalyticalStick.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertAnalyticalSurface.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertBeam.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertBlock.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertCableTray.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertCeiling.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertColumn.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertCurves.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertDirectShape.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertDuct.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertFaceWall.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertFamilyInstance.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertFloor.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertGridLine.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertOpening.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertPipe.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertProfileWall.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertRailing.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertRebar.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertRoof.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertRoom.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertSpace.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertTopography.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertWall.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertWire.cs

attempting to update pinned elements in Revit was causing the transaction to fail and be rolled back. This fixes that issue.
- stop conversion if element is pinned
- remove out parameter that is only there because I didn't understand reference types

Fix(Revit): don't update pinned elements

---

DesktopUI2/DesktopUI2/ViewModels/HomeViewModel.cs

Teamp fix to: https://github.com/specklesystems/speckle-sharp/issues/2574
Currently disabled in DUI only as nothing seems to be wrong in the subscription itself, and as well it's not used anywhere else by us.

fix(dui): disable stream added and removed subscriptions

---

ConnectorRevit/ConnectorRevit/UI/ConnectorBindingsRevit.Send.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertFamilyInstance.cs
Objects/Converters/ConverterRevit/ConverterRevitTests/ConverterRevitTests2021/ConverterRevitTests2021.csproj
Objects/Converters/ConverterRevit/ConverterRevitTests/ConverterRevitTests2023/ConverterRevitTests2023.csproj
Objects/Converters/ConverterRevit/ConverterRevitTests/ConverterRevitTestsShared/SpeckleConversionTest.cs

Fixes #2581
- move mirroring before flipping because the mirroring operation may alter the flipping values
- remove assumption that all instance start with a basisX in the global direction. That is untrue. Get x basis from currentTransform
- modify tests to act like the connectors which skip already converter objects (we should refector both in order to reuse more code)
integration tests still work to the extent that they worked before as well as file provided from claire with several other types of instances. (Integrations tests to be added soon)

Fix(Revit): fix rotation and mirroring of instances

---

ConnectorRhino/ConnectorRhino7/ConnectorRhino7.csproj
Core/Core/Core.csproj
Core/IntegrationTests/TestsIntegration.csproj
Core/Tests/TestsUnit.csproj
Core/Transports/MongoDBTransport/MongoDBTransport.csproj
DesktopUI2/AvaloniaHwndHost/AvaloniaHwndHost.csproj
DesktopUI2/DesktopUI2.Launcher/DesktopUI2.Launcher.csproj
DesktopUI2/DesktopUI2.WPF/DesktopUI2.WPF.csproj
DesktopUI2/DesktopUI2/DesktopUI2.csproj
Objects/Tests/Tests.csproj

updates sentry, avalonia and other packages minor verisons

chore(core): updates sentry, avalonia and other packages minor verisons

---

ConnectorArchicad/AddOn/Sources/AddOn/Commands/CreateObject.cpp

Creation of library part as definitions speed regression fix

fix(Archicad): Creation of library part as definitions speed regression fix

---

.circleci/scripts/config-template.yml
Core/Examples/ExampleApp.csproj
Core/IntegrationTests/TestsIntegration.csproj
Core/Tests/TestsUnit.csproj
Core/docker-compose.yml
DesktopUI2/DesktopUI2.Launcher/DesktopUI2.Launcher.csproj
DesktopUI2/DesktopUI2.WPF/DesktopUI2.WPF.csproj
Objects/Tests/Tests.csproj

Duplicate of #2630 from a renamed branch just to have the CI fully run

fix(ci): use dockerize wait to run the server

---

DesktopUI2/DesktopUI2/ViewModels/CollaboratorsViewModel.cs

fixes: #2605 handles exceptions during search

fix(dui): #2605 handles exceptions during search

---

Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.Mappings.cs

Improves the wall conversion method for mapped extrusions in Rhino. Previously, the logic assumed all `Wall` mappings were extrusion geometry which have been created by extruding a line upwards. The new logic should take into account:
- `Wall` mapped breps
- `Wall` mapped extrusions that were created from top to bottom direction, or a side to side direction.
Fixes an issue reported by @bimgeek where revit could not successfully receive mapped walls due to incorrect wall baseline and heights.

fix(rhino): mapper wall logic for extrusions

---

ConnectorRevit/ConnectorRevit/UI/ConnectorBindingsRevit.Receive.cs

Sometimes elements were trying to be deleted that were pinned or didn't exist and the api call would throw an error. This is a simple fix for that issure

Fix(Revit) : fix element delete

---

ConnectorGrasshopper/ConnectorGrasshopperShared/Accounts/Accounts.ServerAccount.cs
Core/Core/Credentials/Account.cs
Core/Core/Credentials/AccountManager.cs
Core/Core/Credentials/Responses.cs

Just your typical update to `dev` branch before testing release.

Update `dev` with changes in `main`

---

Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertMeshUtils.cs

Fixes #2551 by excluding solid and meshes by their graphic style ID.
The Style is also temporarily cached as it can be costly retrieving it from the document for every solid/mesh in the document.
Before:
https://latest.speckle.dev/streams/d127c8cdfe/commits/9fcb02190d
After:
https://latest.speckle.dev/streams/d127c8cdfe/commits/e882badd67

feat(revit): exclude light source cones #2551

---

Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertRoom.cs

Mini bug-fix/enhancement sets the phase on Revit rooms: https://speckle.community/t/model-parameters-strategy/6158/8

feat(revit): set phases on rooms when sending to speckle

---

ConnectorGrasshopper/ConnectorGrasshopperShared/Streams/StreamUpdateComponentV2.cs

This prevents accidental toggling when the default value was different from the original stream value.
Reported in Notion testing page by Kat! 🙌🏼 https://www.notion.so/speckle/Grasshopper-1d0064e3d80d4589a4baf622bca13490?pvs=4#5fe81eaa01364dac960d11ad8f5050c1

fix(gh): StreamUpdate now uses nullable boolean

---

ConnectorCSI/ConnectorCSI.sln
ConnectorCSI/ConnectorCSIShared/ConnectorCSIShared.projitems
ConnectorCSI/ConnectorCSIShared/UnusedClass.cs
ConnectorCSI/ConnectorETABS/ConnectorETABS.csproj
ConnectorCSI/ConnectorSAFE/ConnectorSAFE.csproj
ConnectorCSI/DriverCSharp/DriverCSharp.csproj

- polygonMesher is a dependency of the csi converter. However, we're only copying the converter itself to the objects kit. This was resulting in the conversions failing due to a missing dependency.
- I made a bit of a bandaid fix where I added a class that uses the converter dependency in the connector. Therefore the dependency will be there for the converter to use. We should probably make a policy for what to do with converter dependencies.
- 2d objects used to fail to send, but now they do not
https://speckle.community/t/specklepy-receiving-commit-data-from-etabs/5831/12

Fix(CSi) : add polygon mesher

---

ConnectorTeklaStructures/ConnectorTeklaStructuresShared/MainForm.cs

- initialize logger in tekla to get better logs in seq

Fix(Tekla) : initialize logger

---

ConnectorTeklaStructures/ConnectorTeklaStructures.sln
ConnectorTeklaStructures/ConnectorTeklaStructures2020/ConnectorTeklaStructures2020.csproj
ConnectorTeklaStructures/ConnectorTeklaStructures2021/ConnectorTeklaStructures2021.csproj
ConnectorTeklaStructures/ConnectorTeklaStructures2022/ConnectorTeklaStructures2022.csproj
ConnectorTeklaStructures/ConnectorTeklaStructuresShared/ConnectorTeklaStructuresShared.projitems
ConnectorTeklaStructures/ConnectorTeklaStructuresShared/PolygonMesherReferencer.cs

Same issue and resolution as https://github.com/specklesystems/speckle-sharp/pull/2714

Fix(Tekla) add polygon mesher dep

---

Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertWall.cs

Doing some profiling revealed that the method ```revitWall.ChangeTypeId(wallType.Id);``` is quite expensive. Previously, when we were creating a wall, we were using a method that did not take the wallType as an argument. As a result, we were having to call the expensive ```ChangeTypeId``` method for every wall.
This PR changes the method of wall creating to one that uses the WallType as an argument so that we never need to change the wall type after creating it. 
Receiving [this commit](https://latest.speckle.dev/streams/580b2a4664/commits/19a55c3d4b) that contains 283 walls took ~31 seconds using the old method and ~18 using the new method.
Wall conversion tests still pass

Performance(Revit) : use different method for wall creation

---

ConnectorRevit/RevitSharedResources/Helpers/Categories.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertDuct.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertFamilyInstance.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertPipe.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/RevitElementTypeUtils.cs

* fix retrieving types for mep elements
* check for family match if the speckle object has a family prop
---------

Fix(Revit) : retrieving types for mep elements (#2758)

---

ConnectorRevit/ConnectorRevit/UI/ConnectorBindingsRevit.Previews.cs

Fix(Revit): disable preview receive

---

Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertFamilyInstance.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertMeshUtils.cs

- if an element is being converted as an instance, then first try to get the mesh from a geometry instance object on the top level of the Revit element's GeometryObject 
- add logging to make sure that our assumptions about the way element's GeometryElements are structured
Before this PR
After this PR
All tested element's look the same in the viewer as in Revit

Fix (Revit): fix for nested geometry instances

---

ConnectorTeklaStructures/ConnectorTeklaStructuresShared/UI/ConnectorBindingsTeklaStructures.Receive.cs
Core/Core/Models/GraphTraversal/DefaultTraversal.cs
Objects/Converters/ConverterTeklaStructures/ConverterTeklaStructures2022/ConverterTeklaStructures2022.csproj
Objects/Converters/ConverterTeklaStructures/ConverterTeklaStructuresShared/ConverterTeklaStructures.cs
Objects/Objects/Other/Instance.cs

- Use standardized GraphTraversal to flatten commit instead of previous traversal method
- Check if object is instance before converting the object's mesh
- The two decendents of Instance, blockInstance and RevitInstance, both has a method called GetTransformedGeometry(). As far as I can tell, this method is never used. I moved this to the base class with a couple virtual methods so each implementation can tweak the behavior of the method.
Instance meshes now receive correctly in Tekla

Feat(Tekla) : receive instances in Tekla

---

ConnectorRevit/RevitSharedResources/Helpers/Categories.cs

Add Air Terminal category to UI.
Add relevant built in category
Manually tested sending air terminals using category.

feat(revit): add revit air terminal category

---

ConnectorNavisworks/ConnectorNavisworks/Bindings/ConnectorNavisworksBindings.Send.cs
Core/Core/Transports/SQLite.cs
Objects/Converters/ConverterNavisworks/ConverterNavisworks/ConverterNavisworks.ToSpeckle.cs

Fixes conflicts between `main` and `dev`

Updates `dev` with changes from `main` after conflict resolution

---

ConnectorRevit/ConnectorRevit/ConnectorRevit.projitems
ConnectorRevit/ConnectorRevit/UI/ConnectorBindingsRevit.Send.cs
ConnectorRevit/RevitSharedResources/Interfaces/IRevitCommitObjectBuilder.cs
ConnectorRevit/RevitSharedResources/Interfaces/IRevitCommitObjectBuilderExposer.cs
ConnectorRevit/RevitSharedResources/RevitSharedResources.projitems
Core/Core/Models/CommitObjectBuilder.cs
Core/Core/Models/NestingInstructions.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/ConverterRevitShared.projitems
Objects/Converters/ConverterRevit/ConverterRevitShared/RevitCommitObjectBuilder.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/RevitCommitObjectBuilderExposer.cs

- commit builder can now know about objects and can nest elements via calling methods instead of always just appending the child to a list of elements
- moved commit object builder from connector project into converter project
- changed commitBuilder parent info from a list of (parent appId, string propName) to a NestingInstructions struct that has a parentAppId and an Nest action that takes a parent base and a child base

Feat(Revit) : more flexible commit builder

---

Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertBeam.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertColumn.cs

I added code a long time ago dealing with the fact that structural stiffeners modify the geometry of columns and beams. The beam and column conversion to Speckle would check to see if the element had any dependent elements of the structural stiffener type and then it would send view specific geometry to accurately show the column.
The GetDependentElements() call turns out is very expensive. This code also is no longer needed because now you can send a view and that will retreive the view specific geometry for the modified beams and columns.
This small change took the conversion of a large Revit model to Speckle down from 1:40s to 1:10s

Fix(Revit) : mesh gathering performance

---

ConnectorRevit/ConnectorRevit/TypeMapping/ElementTypeMapper.cs

(cherry picked from commit 5ceda7582b2decb576b1ed2d45f7f6cb7c924a2c)

chore: track if the user accepts the mapping dialog or not

---

ConnectorNavisworks/ConnectorNavisworks/Bindings/ConnectorNavisworksBindings.Send.cs
Core/Core/Transports/Exceptions.cs
Core/Core/Transports/SQLite.cs
Objects/Converters/ConverterNavisworks/ConverterNavisworks/ConverterNavisworks.ToSpeckle.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertBlock.cs

Just your regular update to keep `dev` in line with the latest hotfixes in `main`

Updates `dev` with changes in `main`

---

Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertMEPFamilyInstance.cs
Objects/Objects/BuiltElements/Revit/MEPFamilyInstance.cs

Matches behavior of dynamo for extracting element curves
Fixes https://github.com/specklesystems/speckle-sharp/issues/1436
- add curves prop to MEPFamilyInstance
- populate curves from coarse geometry
Curves from dynamo
Curves from Speckle

Fix(Revit) : add curves for mep fitting

---

Objects/Objects/Structural/ApplicationSpecific/ETABS/Geometry/CSINode.cs

Forum thread: https://speckle.community/t/csi-node-and-csielement-2d/6676/2
Fix:

fix(gh): null check on CSI node

---

Objects/Converters/ConverterCSI/ConverterCSIShared/Partial Classes/Properties/Convert1DProperty.cs

currently we have bad checks the allow null values to break our conversions. 
- Properly guard against null values
Instead of throwing an exception and not creating a frame, we are now getting a warning that the profile section was unable to be created, but the frames still show up.

Fix(csi) : more stable section creation

---

ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/UI/MappingBindingsRhino.cs
DesktopUI2/DesktopUI2/ViewModels/MappingTool/MappingsViewModel.cs
DesktopUI2/DesktopUI2/ViewModels/MappingTool/Schemas.cs
DesktopUI2/DesktopUI2/Views/MappingsControl.xaml
Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.Mappings.cs

Adds `Ceiling`, `Default Ceiling`, `FootprintRoof`, and `Default Roof` mappings for planar horizontal surfaces.
Closes #2835 
- Rhino connector and converter
- DUI2 mappings

feat(rhino): adds ceiling and footprint roof mappings

---

Objects/Converters/ConverterRevit/ConverterRevitShared/ConversionUtils.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/ConverterRevitShared.projitems
Objects/Converters/ConverterRevit/ConverterRevitShared/Extensions/ParameterExtensions.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Models/ParameterToSpeckleData.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/Units.cs
Objects/Objects/BuiltElements/Revit/Parameter.cs

- adds support for sending parameters that do not have a value and parameters that point to element ids
- introduce struct to hold parameter data in the cache so subsequent parameters can be built up more quickly.
- GetValue extension method for parameters that will get the value or return null if the "parameter.HasValue" flag is false
- This method minimizes the use of the "HasValue" call because apparently it is decently expensive
- skip setting value for null value parameters on receive 
all integration tests pass

Fix(Revit) : add params with null values and element ids

---

ConnectorAutocadCivil/ConnectorAutocadCivil.sln
Objects/Objects.sln

chore: adds missing csprojs to slns

---

ConnectorRevit/ConnectorRevit/ConnectorRevit.projitems
ConnectorRevit/ConnectorRevit/UI/ConnectorBindingsRevit.Settings.cs
DesktopUI2/DesktopUI2/Views/Windows/Dialogs/MissingIncomingTypesDialog.xaml

Clarifies some dialog messages and settings descriptions

chore(revit): update some settings description and dialog message

---

Objects/Converters/ConverterRevit/ConverterRevitShared/ConverterRevitShared.projitems
Objects/Converters/ConverterRevit/ConverterRevitShared/Extensions/CategoryExtensions.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertFamilyInstance.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertWall.cs

- check if family symbol is mullion or panel before baking
- use fuller error preprocessor for wall conversions than the dummy one we were using before

Fix(Revit) : dont bake standalone mullions or panels

---

Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertWall.cs

Sending entire view for large models was hanging. That is because, for view specific send operations, we were retrieving (and converting) all curtain panels and mullions in the view every time that we were sending a curtain wall.
- for view specific send, query document for all curtain wall subelements in the active view, cache that, and compare it to the subelements of the wall being converted

Fix (Revit) : curtain wall subelements fix

---

ConnectorRevit/ConnectorRevit/UI/ConnectorBindingsRevit.Send.cs

Fixes https://github.com/specklesystems/speckle-sharp/issues/2918
Alternative to https://github.com/specklesystems/speckle-sharp/pull/2919

Fix(Revit) : Fix modification forbidden error

---

Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertAnalyticalStick.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertAnalyticalSurface.cs

Due to changes in our beam, column, floor, and wall conversion, Revit-Speckle elements (RevitWall, RevitFloor, etc.) are now treated differently than the default objects (Wall, Floor, etc.). The revit objects are expected to have level properties and offsets from those levels (which they would if they were actually from Revit).
Therefore instead of creating Revit-Speckle objects to create the physical elements associated with analytical sticks and surfaces, we need to make Generic Speckle objects.
Currently receiving on dev
Receiving on this branch

Fix(Revit) : analytical stick and surface fixes

---

Objects/Converters/ConverterRevit/ConverterRevitShared/ConverterRevit.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/ConverterRevitShared.projitems
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertGeometry.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertToposolid.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertView.cs
Objects/Objects/BuiltElements/Toposolid.cs

Early, not quite functional, Toposolid support - WIP and will need refactor if we are to provide Toposolid and RevitToposolid

Toposolid WIP

---

ConnectorRevit/ConnectorRevit/UI/ConnectorBindingsRevit.Selection.cs

Schedules caused slowness in the sending process, and are usually redundant when sending the entire model.

fix(rvt): Exclude Schedules from Everything filter, only send when category is selected

---

All.sln
ConnectorDynamo/ConnectorDynamo.sln
ConnectorDynamo/ConnectorDynamo.slnf
ConnectorDynamo/ConnectorDynamo/ConnectorDynamo.csproj
ConnectorDynamo/ConnectorDynamo/Properties/launchSettings.json
Objects/Converters/ConverterDynamo/ConverterDynamoRevit2024/ConverterDynamoRevit2024.csproj
Objects/Converters/ConverterDynamo/ConverterDynamoRevit2024/Properties/launchSettings.json
Objects/Converters/ConverterDynamo/ConverterDynamoShared/ConverterDynamo.Units.cs
Objects/Converters/ConverterDynamo/ConverterDynamoShared/ConverterDynamo.cs
Objects/Objects/ObjectsKit.cs

Adds support for Dynamo in Revit 2024.

feat(dynamo): revit 2024 support

---

Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivilShared.projitems

Fixed case sensitive problem that was breaking our CI

fix(advancedsteel): Fixed issue with advanced steel breaking nuget CI

---

Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivilShared.projitems
Objects/Converters/ConverterRevit/ConverterRevitShared/AllRevitCategories.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Categories.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/ConversionUtils.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertBlock.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertDirectShape.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertDisplayableObject.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertFreeformElement.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertRailing.cs
Objects/Objects/BuiltElements/Revit/DirectShape.cs

Just your normal `dev` update.

Update `dev` with changes from `main`

---

ConnectorRevit/ConnectorRevit/UI/ConnectorBindingsRevit.Settings.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/ConverterRevit.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertAdaptiveComponent.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertAnalyticalSurface.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertBeam.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertBuildingPad.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertCableTray.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertCeiling.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertColumn.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertConduit.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertDuct.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertFamilyInstance.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertFloor.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertMeshUtils.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertPipe.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertRailing.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertRevitElement.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertRoof.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertStair.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertTopRail.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertTopography.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertWall.cs

Implement setting to dictate which mesh detail level to extract from the model
- Remove options parameter from GetElementDisplayValue calls unless it is necessary to retreive a certain detail level.
- Introduce setting to control detail level of GetElementDisplayValue method

Hotfix(Revit) : change detail level settings via advanced settings

---

.circleci/scripts/config-template.yml
Automate/Speckle.Automate.Sdk/AutomationContext.cs
Automate/Speckle.Automate.Sdk/Schema/AutomationResult.cs
Automate/Speckle.Automate.Sdk/Schema/AutomationRunData.cs
Automate/Tests/Speckle.Automate.Sdk.Tests.Integration/SpeckleAutomate.cs

This is a reflection of the changes included in specklepy https://github.com/specklesystems/specklepy/pull/309/files
Adds a couple new inputs to `ReportRunStatus` graphql query.
Adds new tests for `CreateVersionInProject` to verify correct behaviour both succeeding and failing.

feat: Updates Automate.SDK with new API changes

---

Core/Core/Helpers/Http.cs

Reverts specklesystems/speckle-sharp#3005

Revert "Suppress CRL checking"

---

Automate/Speckle.Automate.Sdk/Runner.cs
Automate/Tests/Speckle.Automate.Sdk.Tests.Integration/SpeckleAutomate.cs

fix(automate): Adds return code to automate Runner

---

Core/Core/Helpers/Http.cs
Core/docker-compose.yml

Merging the CRL check removal back into dev

Merging the CRL check removal back into dev

---

ConnectorArchicad/ConnectorArchicad/Converters/ElementConverterManager.cs

[#2396](https://github.com/specklesystems/speckle-sharp/issues/2396)
In the Archicad Connector a `Collection` is used as a root commit object, and under that, elements are attached to separate `Collections` based on their Archicad Element Type.

feat(Archicad): Collections support

---

ConnectorArchicad/AddOn/Sources/AddOn/Commands/CreateCommand.cpp
ConnectorArchicad/ConnectorArchicad/Communication/Commands/Command_GetShellData.cs
ConnectorArchicad/ConnectorArchicad/Converters/Converters/ColumnConverter.cs
ConnectorArchicad/ConnectorArchicad/Converters/Converters/FloorConverter.cs
ConnectorArchicad/ConnectorArchicad/Converters/Converters/Utils.cs

Receiving stories from Revit->Archicad direction, extension to https://github.com/specklesystems/speckle-sharp/issues/2956.
Stories are created on Archicad side, based on elevation.

Create Archicad levels based on elevation

---

Core/Core/Credentials/Account.cs
Core/Core/Credentials/AccountManager.cs

Changes default server URL to: https://app.speckle.systems/

feat: changes the default server URL

---

ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/UI/ConnectorBindingsRhino.Receive.cs
Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.BuiltElements.cs
Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.cs
Objects/Objects/BuiltElements/Revit/DirectShape.cs

The Rhino converter has a direct conversion for Revit `DirectShape`, which just converted values found in the `displayValue` property of the direct shape. This PR removes the direct conversion, since fallback behavior to converting display values is already supported in the connector.
The added benefit is directshapes should now be converted with materials properly.
Also includes a minor bug fix in the connector during object baking, for handling `renderMaterial` and `displayStyle`.
- Rhino connector
- Rhino converter

refactor(rhino): removes DirectShapeToNative conversion

---

Objects/Converters/ConverterRevit/ConverterRevitShared/ConversionUtils.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/Units.cs

units set manually in other applications such as GH were not being correctly picked up and scaled
Don't use the Speckle.Core.Kits.Units.IsUnitSupported(units) method, which expects a very specific unit string format (i.e. returns true for "mm" but not for "millimeter"). Instead, we use our "UnitsToNative" method which will attempt to parse many variations of the unit string.
receiving a model, https://speckle.xyz/streams/9ff64f51e6/commits/06c8bd7bec, now correctly sets the floor offsets which it wasn't correctly doing before

Fix(Revit) : correctly parse units coming from other applications

---

ConnectorGrasshopper/ConnectorGrasshopperShared/Collections/FlattenCollectionComponent.cs
ConnectorGrasshopper/ConnectorGrasshopperShared/Objects/CreateSpeckleObjectTaskComponent.cs
ConnectorGrasshopper/ConnectorGrasshopperShared/SchemaBuilder/CreateSchemaObjectBase.cs
ConnectorGrasshopper/ConnectorGrasshopperShared/SchemaBuilder/SchemaBuilderGen.tt
ConnectorGrasshopper/ConnectorGrasshopperUtils/UserInterfaceUtils.cs
ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/Entry/Plugin.cs
ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/Entry/SpeckleCommandMac.cs
ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/Entry/SpeckleCommandWin.cs
ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/Entry/SpeckleMappingsCommandMac.cs
ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/Entry/SpeckleMappingsCommandWin.cs
ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/UI/ConnectorBindingsRhino.Send.cs
ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/UI/ConnectorBindingsRhino.Settings.cs
Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.Mappings.cs
Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.Organization.cs
Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.Other.cs
Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.Structural.cs
Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.cs

Fixes redundant using statements for:
- Rhino connector
- Grasshopper connector
- Rhino/Grasshopper converter

fix(rhino/grasshopper): Fix IDE0005 Redundant Using Statements 

---

ConnectorRhino/ConnectorRhinoWebUI/Bindings/ReceiveBinding.cs
ConnectorRhino/ConnectorRhinoWebUI/Bindings/SendBinding.cs
DesktopUI3/DUI3/Bindings/ISendBinding.cs
DesktopUI3/DUI3/Models/ModelCard.cs
DesktopUI3/DUI3/Settings/CardSetting.cs

Settings info pass to UI via `SendBinding` and `ReceiveBinding` as below. And UI will be handle to render and store them accordingly into per card.
```c#
new CardSetting()
{
Id = "mergeCoplanarFaces",
Title = "Merge Coplanar Faces",
Value = true, // default value of the setting
Type = "boolean"
}
```

Feat (DUI3): Advanced settings for send and receive

---

Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.Civil.cs

Adds design speeds to `Alignment` `Station`s, for both sending and receiving.
Also includes some warn fixes.
-Autocadcivil converter
Sending:
Receiving:

feat(civil3d): CNX-8013 adds design speeds to alignments

---

ConnectorNavisworks/ConnectorNavisworks/Entry/Ribbon.xaml.cs

Worked on CI bc `RELEASE` mode did not require it.

fix(navisworks): Local build was missing a using statement

---

Objects/Converters/ConverterRevit/ConverterRevitShared/PartialClasses/ConvertGeometry.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/PartialClasses/ConvertRebar.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/RevitVersionHelper.cs

Fix CA1806 for Revit

---

Objects/Converters/ConverterRevit/ConverterRevitShared/PartialClasses/ConvertProjectInfo.cs

fixes https://spockle.atlassian.net/browse/CNX-7577?atlOrigin=eyJpIjoiZGEzODk0YThmY2U4NGI1MDlhM2JhZWQ3NzlmZTNmZWIiLCJwIjoiaiJ9
- add custom properties to the "project info" property that gets sent from Speckle

Feat(Revit): CNX-7577 project info custom props

---

ConnectorArchicad/ConnectorArchicad/Communication/AsyncCommandProcessor.cs
ConnectorArchicad/ConnectorArchicad/ConnectorBinding.cs

Some missed out fixes from https://github.com/specklesystems/speckle-sharp/pull/3122.

fix(Archicad): CNX-8392 Handle CA1031 warnings in ArchiCAD projects #2

---

Automate/Speckle.Automate.Sdk/Runner.cs
Automate/Speckle.Automate.Sdk/Schema/FunctionRunData.cs
Automate/Speckle.Automate.Sdk/Schema/FunctionRunDataParser.cs
Automate/Tests/Speckle.Automate.Sdk.Tests.Integration/SpeckleAutomate.cs

Read function run data from provided path via CLI argument on `run` command.

Feat (Automate): CNX-8636 automate sdk breaking change

---

Directory.Build.props

https://learn.microsoft.com/en-us/dotnet/core/compatibility/sdk/8.0/source-link

IncludeSourceRevisionInInformationalVersion false

---

ConnectorArchicad/AddOn/Sources/AddOnResources/RINT/AddOn.grc

Removing "Alpha" from UI.
https://spockle.atlassian.net/browse/CNX-8844

CNX-8844 - remove alpha flag from Archicad

---

ConnectorAutocadCivil/AutocadCivilDUI3/Autocad2022/ConnectorAutocad2022DUI3.csproj
ConnectorAutocadCivil/AutocadCivilDUI3/Autocad2023/ConnectorAutocad2023DUI3.csproj

`<UseWPF>true</UseWPF>` property was needed for proper build.

Fix (DUI3): CNX-8930 Add UseWPF prop to AutoCAD projects

---

Objects/Converters/ConverterRevit/ConverterRevitShared/ConversionUtils.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/PartialClasses/ConvertProjectInfo.cs

Retrieving project info can throw if the project info object has custom attributes with characters that are not allowed for base property names. This pr fixes that issue.
We may want to consider wrapping this whole operation in a try catch because throwing here will kill the entire send operation

Fix(Revit) : getting project info can throw and kills conversion

---

Core/Core/Kits/Units.cs

GetUnitsFromString method was throwing when passed empty strings. Because this method already returns null for null strings, it makes sense to extend this to return null for empty strings.
This was the most minimal change possible. We could consider making the method return null instead of throwing. In my opinion, it doesn't really make sense to both return null and to throw.

Fix(Core) : expect empty strings in "GetUnitsFromString"

---

ConnectorRhino/ConnectorRhinoWebUI/Bindings/BasicConnectorBinding.cs
ConnectorRhino/ConnectorRhinoWebUI/Bindings/ReceiveBinding.cs
DesktopUI3/DUI3/Bindings/IBasicConnectorBinding.cs
DesktopUI3/DUI3/BridgeV2.cs
DesktopUI3/DUI3/Operations/Operations.cs

feat(dui3): quite a few fixes, do sync with with dui3 web

---

Core/Core/Credentials/AccountManager.cs
Core/Tests/Speckle.Core.Tests.Unit/Credentials/AccountServerMigrationTests.cs

BACK MERGE MAIN -> DEV

---

ConnectorAutocadCivil/AutocadCivilDUI3/AutocadCivilDUI3Shared/Bindings/ReceiveBinding.cs
ConnectorAutocadCivil/AutocadCivilDUI3/AutocadCivilDUI3Shared/Bindings/SendBinding.cs
ConnectorAutocadCivil/AutocadCivilDUI3/AutocadCivilDUI3Shared/Utils/Objects.cs
ConnectorRhino/ConnectorRhinoWebUI/Bindings/ReceiveBinding.cs
ConnectorRhino/ConnectorRhinoWebUI/Bindings/SendBinding.cs
DesktopUI3/DUI3/Utils/Traversal.cs

Adds some fast layer props for workflows:
Also fixes a fatal crash in acad when trying to highlight previously deleted objects. 
tl;dr: fast experiments

feat(dui3): layer color support acad, rh

---

Objects/Converters/ConverterCSI/ConverterCSIBridge/ConverterCSIBridge.csproj
Objects/Converters/ConverterCSI/ConverterETABS/ConverterETABS.csproj
Objects/Converters/ConverterCSI/ConverterSAFE/ConverterSAFE.csproj
Objects/Converters/ConverterCSI/ConverterSAP2000/ConverterSAP2000.csproj

CNX-9176 remove relative paths from csprojects

---

DUI3-DX/Connectors/Rhino/Speckle.Connectors.Rhino7/DependencyInjection/AutofacRhinoModule.cs
DUI3-DX/Connectors/Rhino/Speckle.Connectors.Rhino7/Operations/Receive/RhinoHostObjectBuilder.cs
DUI3-DX/Converters/Rhino/Speckle.Converters.Rhino7/ToSpeckle/Raw/PolylineToSpeckleConverter.cs
DUI3-DX/Converters/Rhino/Speckle.Converters.Rhino7/ToSpeckle/TopLevel/RhinoExtrusionObjectToSpeckleConversion.cs
DUI3-DX/DUI3/Speckle.Connectors.DUI/Bridge/SyncToCurrentThread.cs

- Fixed incorrect layer check on receive
- Fixed polyline conversion not sending `closed` property
- Added extrusion conversion because there was no reason not to
- Fixed the ISyncToMain issue that I had already fixed in the receive fix branch but I'd rather have this sooner in.

fix(rhino): CNX-9309 Mix fixes reported by Dim

---

DUI3-DX/Connectors/Revit/Speckle.Connectors.RevitShared/Bindings/SendBinding.cs
DUI3-DX/Connectors/Revit/Speckle.Connectors.RevitShared/DependencyInjection/AutofacUIModule.cs
DUI3-DX/Connectors/Revit/Speckle.Connectors.RevitShared/Operations/Send/RootObjectBuilder.cs
DUI3-DX/Connectors/Revit/Speckle.Connectors.RevitShared/Operations/Send/SendOperation.cs
DUI3-DX/Converters/Revit/Speckle.Converters.Revit2023.DependencyInjection/AutofacRevitConverterModule.cs

- inject uow factory instead of singleton sendOperation in the sendBinding
- change sendOperation ioc container registration to scoped
- remove uow factory from send operation and replace it with scoped implementaion of RootObjectBuilder

CNX-9289 apply unit of work for revit send binding

---

DUI3-DX/Connectors/ArcGIS/Speckle.Connectors.ArcGIS3/Bindings/ArcGISSelectionBinding.cs
DUI3-DX/Connectors/ArcGIS/Speckle.Connectors.ArcGIS3/Bindings/ArcGISSendBinding.cs
DUI3-DX/Connectors/ArcGIS/Speckle.Connectors.ArcGIS3/DependencyInjection/AutofacArcGISModule.cs
DUI3-DX/Connectors/ArcGIS/Speckle.Connectors.ArcGIS3/Filters/ArcGISSelectionFilter.cs
DUI3-DX/Connectors/ArcGIS/Speckle.Connectors.ArcGIS3/Operations/Send/RootObjectBuilder.cs
DUI3-DX/Connectors/ArcGIS/Speckle.Connectors.ArcGIS3/Operations/Send/SendOperation.cs
DUI3-DX/Converters/ArcGIS/Speckle.Converters.ArcGIS3/Features/GeometryToSpeckleBase.cs
DUI3-DX/Converters/ArcGIS/Speckle.Converters.ArcGIS3/Features/GisFeatureToSpeckleConverter.cs

CNX-9243  ArcGIS selection filter

---

DUI3-DX/Connectors/ArcGIS/Speckle.Connectors.ArcGIS3/Bindings/ArcGISReceiveBinding.cs
DUI3-DX/Connectors/ArcGIS/Speckle.Connectors.ArcGIS3/Bindings/ArcGISSendBinding.cs
DUI3-DX/Connectors/ArcGIS/Speckle.Connectors.ArcGIS3/DependencyInjection/AutofacArcGISModule.cs
DUI3-DX/Converters/ArcGIS/Speckle.Converters.ArcGIS3.DependencyInjection/AutofacArcGIS3ConverterModule.cs

CNX-9291 Implement Unit of Work for ArcGIS Send and Receive bindings

---

DUI3-DX/Connectors/Autocad/Speckle.Connectors.AutocadShared/HostApp/AutocadDocumentModelStore.cs

This is how it is working now.

CNX-9358 Fix write to file with DocumentToBeDeactivated event

---

DUI3-DX/Connectors/Revit/Speckle.Connectors.RevitShared/Plugin/CefSharpPanel.xaml
DUI3-DX/Connectors/Revit/Speckle.Connectors.RevitShared/Plugin/RevitPlugin.cs
DUI3-DX/DUI3/Speckle.Connectors.DUI.WebView/DUI3ControlWebView.xaml
DUI3-DX/DUI3/Speckle.Connectors.DUI/Url.cs

CNX-9364 revit connector UI not up to date

---

DUI3-DX/Connectors/Autocad/Speckle.Connectors.AutocadShared/Bindings/AutocadReceiveBinding.cs
DUI3-DX/Connectors/Autocad/Speckle.Connectors.AutocadShared/Bindings/AutocadSendBinding.cs
DUI3-DX/Connectors/Autocad/Speckle.Connectors.AutocadShared/DependencyInjection/AutofacAutocadModule.cs
DUI3-DX/Connectors/Autocad/Speckle.Connectors.AutocadShared/Operations/Receive/HostObjectBuilder.cs
DUI3-DX/Connectors/Autocad/Speckle.Connectors.AutocadShared/Operations/Send/RootObjectBuilder.cs

UoWs added for receive and send. And UoWs in builders replaced with `ISpeckleConverterToSpeckle _converter` and `ISpeckleConverterToHost _converter` dependency.

CNX-9292 apply unit of work for auto cad

---

DUI3-DX/Connectors/Revit/Speckle.Connectors.RevitShared/DependencyInjection/AutofacUIModule.cs

Hides load button from the connector UI.

CNX-9375 remove load button from connector UI rvt

---

DUI3-DX/Connectors/Revit/Speckle.Connectors.RevitShared/Bindings/SendBinding.cs
DUI3-DX/Connectors/Rhino/Speckle.Connectors.Rhino7/DependencyInjection/AutofacRhinoModule.cs

https://spockle.atlassian.net/browse/CNX-9376

CNX-9376 Remove all filters besides Selection in all host apps

---

DUI3-DX/Connectors/Revit/Speckle.Connectors.RevitShared/Operations/Send/RootObjectSender.cs
DUI3-DX/Connectors/Revit/Speckle.Connectors.RevitShared/Plugin/RevitExternalApplication.cs

Commit source application previously was copy pasted probably from Rhino. Now injected from `RevitSettings`

CNX-9378 Pass source app from RevitSettings

---

DUI3-DX/Converters/Revit/Speckle.Converters.Revit2023.DependencyInjection/AutofacRevitConverterModule.cs
DUI3-DX/Converters/Revit/Speckle.Converters.RevitShared/Helpers/ISlopeArrowExtractor.cs
DUI3-DX/Converters/Revit/Speckle.Converters.RevitShared/Helpers/SlopeArrowExtractor.cs
DUI3-DX/Converters/Revit/Speckle.Converters.RevitShared/Speckle.Converters.RevitShared.projitems
DUI3-DX/Converters/Revit/Speckle.Converters.RevitShared/ToSpeckle/FloorConversionToSpeckle.cs

Adds floor converter. See this commit https://latest.speckle.systems/projects/85bc4f61c6/models/6cd9058fba for examples of the send behavior

CNX-9227 send floors from Revit

---

DUI3-DX/Connectors/Revit/Speckle.Connectors.RevitShared/Plugin/RevitIdleManager.cs
DUI3-DX/Converters/Revit/Speckle.Converters.RevitShared/Raw/BraceToSpeckleConverter.cs
DUI3-DX/Converters/Revit/Speckle.Converters.RevitShared/RevitConverterToSpeckle.cs
DUI3-DX/Converters/Revit/Speckle.Converters.RevitShared/Speckle.Converters.RevitShared.projitems
DUI3-DX/Converters/Revit/Speckle.Converters.RevitShared/ToSpeckle/FamilyInstanceConversionToSpeckle.cs
Objects/Objects/BuiltElements/Revit/RevitBrace.cs

Added brace conversion for Revit.

CNX-9224 Added brace

---

DUI3-DX/Connectors/Revit/Speckle.Connectors.RevitShared/Bindings/BasicConnectorBindingRevit.cs
DUI3-DX/Connectors/Revit/Speckle.Connectors.RevitShared/Bindings/SelectionBinding.cs
DUI3-DX/Connectors/Revit/Speckle.Connectors.RevitShared/Bindings/SendBinding.cs
DUI3-DX/Connectors/Revit/Speckle.Connectors.RevitShared/Operations/Send/RootObjectBuilder.cs
DUI3-DX/Converters/Revit/Speckle.Converters.RevitShared/Helpers/SendSelection.cs

centralises id operations across on element ids. note, it would be better do to do it the other way around, but the change events in revit give us plain ids rather than unique ids.
The underlying issue was that we were using element ids (coming from change events in revit) and for the rest we were using the unique ids of elements. 
What I am not fully aware of is whether relying on the element ids rather than the unique ids will cause future problems down the line regarding selecting objects from linked models. This though currently seems a far off problem.

CNX-9366 [RVT] Object Tracking not working

---

DUI3-DX/Converters/Revit/Speckle.Converters.RevitShared/ToSpeckle/FloorConversionToSpeckle.cs

Floor converter was throwing an exception due to a mismatch between the type registered in the container and the type injected.
Also the slope parameter may be null, so treat it as such

Fix(Revit): fix slope arrow injection and use nullable slope parameter

---

DUI3-DX/Converters/Revit/Speckle.Converters.RevitShared/Helpers/ParameterValueExtractor.cs
DUI3-DX/Converters/Revit/Speckle.Converters.RevitShared/RevitConverterToSpeckle.cs
DUI3-DX/Converters/Revit/Speckle.Converters.RevitShared/ToSpeckle/HostedElementConversionToSpeckle.cs

Sometimes multiple objects in revit can host the same sub element. In our current connector, we are just converting these items multiple times. However, in this connector an exception is being thrown. For now, I am just silencing this exception until we can address the issue more completely https://spockle.atlassian.net/browse/CNX-9402.
I also made a change to make the "TryGetValueAsDocumentObject" safer

CNX-9408 - Fix(Revit): silence exception throw by duplicate conversions

---

DUI3-DX/Converters/Autocad/Speckle.Converters.AutocadShared/ToHost/Raw/AutocadPolycurveToHostPolyline2dRawConverter.cs

Fixes tangent issues with polyline2ds.
Commit: [https://app.speckle.systems/projects/b53a53697a/models/66aca735ab](https://app.speckle.systems/projects/b53a53697a/models/66aca735ab)
- autocad polyline2dtohostconverter

fix(autocad): CNX-9398 acad received splines are not accurate in some cases

---

DUI3-DX/Converters/Rhino/Speckle.Converters.Rhino7/Speckle.Converters.Rhino7.csproj
DUI3-DX/Converters/Rhino/Speckle.Converters.Rhino7/ToHost/TopLevel/SpeckleFallbackToHostConversion.cs

CNX-9411 Rhino unit conversions not working on fallback conversions

---

DUI3-DX/Connectors/Rhino/Speckle.Connectors.Rhino7/HostApp/RhinoSettings.cs
DUI3-DX/Sdk/Speckle.Connectors.Utils/Operations/RootObjectSender.cs

* Replaced Func<> delegate with factory for generic RootObjectSender
* Replaced ToString() with Location for assembly due to incorrect path being returned :/

RCNX-9409 - Rhino Setting and factory delegate

---

DUI3-DX/Connectors/Revit/Speckle.Connectors.RevitShared/Bindings/BasicConnectorBindingRevit.cs
DUI3-DX/Connectors/Revit/Speckle.Connectors.RevitShared/Operations/Send/RootObjectBuilder.cs
DUI3-DX/DUI3/Speckle.Connectors.DUI/Models/DocumentInfo.cs

* Users cannot begin to publish or receive if in Revit Family Environment
* We may be able to show a custom message, but requires server side change
* Custom message already in this version, words can be amended/improved - Oguzhan may add later on

CNX-9405 rvt family environment not supported

---

DUI3-DX/Connectors/ArcGIS/Speckle.Connectors.ArcGIS3/Bindings/ArcGISSendBinding.cs
DUI3-DX/Connectors/Rhino/Speckle.Connectors.Rhino7/Bindings/RhinoSendBinding.cs
DUI3-DX/DUI3/Speckle.Connectors.DUI/Bindings/IBinding.cs
DUI3-DX/DUI3/Speckle.Connectors.DUI/Bridge/BrowserBridge.cs
DUI3-DX/DUI3/Speckle.Connectors.DUI/Models/Card/ModelCard.cs
DUI3-DX/DUI3/Speckle.Connectors.DUI/Settings/CardSetting.cs
DUI3-DX/DUI3/Speckle.Connectors.DUI/Utils/DiscriminatedObject.cs
DUI3-DX/DUI3/Speckle.Connectors.DUI/Utils/DiscriminatedObjectConverter.cs
Directory.Build.props

Any warning that is not related to nullability has been removed.
Only nullability issues persist now.

bonus: Remove some DUI3 project warnings, excluding the ones related to nullability

---

DUI3-DX/Connectors/ArcGIS/Speckle.Connectors.ArcGIS3/Config.daml

align DUI3 naming

---

DUI3-DX/Converters/ArcGIS/Speckle.Converters.ArcGIS3/Utils/NonNativeFeaturesUtils.cs

Try catch per object converted

---

DUI3-DX/Converters/ArcGIS/Speckle.Converters.ArcGIS3/Geometry/GisFeatureGeometriesToHost/MeshListToHostConverter.cs
DUI3-DX/Converters/ArcGIS/Speckle.Converters.ArcGIS3/Geometry/PointSingleToHostConverter.cs

Cnx 9507 Arcgis scaling on receive

---

Objects/Converters/ConverterRevit/ConverterRevitShared/Extensions/ParameterExtensions.cs

Previously we were sending elementId base parameters as just the elementId which is pretty much useless because we are not doing anything with these on receive. A user asked us to send the name instead which both @JR-Morgan and I think is an improvement over the existing functionality.
This change is causing us to add a lot of document queries that we weren't previously doing. Profiling the performance model that we have, this functionality causes the conversion process to go from 28ish seconds to 29ish seconds which seems acceptable (admittedly these tests were done in debug mode).
Before (left) and after (right) for wall parameters

CNX 9442 Incorrect Export of 'Room Type' Parameter from Revit to Speckle

---

DUI3-DX/Converters/ArcGIS/Speckle.Converters.ArcGIS3/ArcGISToSpeckleUnitConverter.cs

On merge to alpha, these changes from Adam were accidentally reverted, and now it's changed back.

unit converter fix

---

ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/UI/DuiPanel.xaml.cs

https://spockle.atlassian.net/browse/CNX-9586
Fixes text input not working by applying the same fix as in #1362

CNX-9586 Text input not working in Rhino 8

---

ConnectorArchicad/ConnectorArchicad/ConnectorBinding.cs

feat(Archicad): Add default commit message

---

.circleci/scripts/config-template.yml
.github/workflows/ci.yml
global.json

Update global.json to 8.0.200 + rollForward patch versions only

---

DUI3-DX/DUI3/Speckle.Connectors.DUI/Bridge/BrowserBridge.cs
DUI3-DX/Sdk/Speckle.Autofac/DependencyInjection/UnitOfWorkFactory.cs

Also do not throw speckle exception in UnitOfWorkFactory. Registration issues in resolving service will be red flag on UI.

Do not catch speckle exception at top

---

DUI3-DX/Converters/Revit/Speckle.Converters.Revit2023.DependencyInjection/Speckle.Converters.Revit2023.DependencyInjection.csproj
DUI3-DX/Converters/Revit/Speckle.Converters.Revit2023.Tests/Speckle.Converters.Revit2023.Tests.csproj
DUI3-DX/Converters/Revit/Speckle.Converters.Revit2023.Tests/packages.lock.json
DUI3-DX/Converters/Revit/Speckle.Converters.Revit2023/Speckle.Converters.Revit2023.csproj
DUI3-DX/Converters/Revit/Speckle.Converters.RevitShared/Helpers/DisplayValueExtractor.cs
DUI3-DX/Converters/Revit/Speckle.Converters.RevitShared/Helpers/ParameterObjectAssigner.cs
DUI3-DX/Converters/Revit/Speckle.Converters.RevitShared/Raw/LocationConversionToSpeckle.cs
DUI3-DX/Sdk/Speckle.Converters.Common/Speckle.Converters.Common.csproj

casting was optional and a minor rework of the cache

DUI3-149 Skippable GraphicsStyle clean up

---

DUI3-DX/Converters/Revit/Speckle.Converters.RevitShared/Helpers/IParameterValueExtractor.cs
DUI3-DX/Converters/Revit/Speckle.Converters.RevitShared/Helpers/ParameterValueExtractor.cs
DUI3-DX/Converters/Revit/Speckle.Converters.RevitShared/Raw/BeamConversionToSpeckle.cs
DUI3-DX/Converters/Revit/Speckle.Converters.RevitShared/Raw/ColumnConversionToSpeckle.cs
DUI3-DX/Converters/Revit/Speckle.Converters.RevitShared/ToSpeckle/CeilingTopLevelConverterToSpeckle.cs
DUI3-DX/Converters/Revit/Speckle.Converters.RevitShared/ToSpeckle/ExtrusionRoofToSpeckleTopLevelConverter.cs
DUI3-DX/Converters/Revit/Speckle.Converters.RevitShared/ToSpeckle/FloorTopLevelConverterToSpeckle.cs
DUI3-DX/Converters/Revit/Speckle.Converters.RevitShared/ToSpeckle/FootPrintRoofToSpeckleTopLevelConverter.cs
DUI3-DX/Converters/Revit/Speckle.Converters.RevitShared/ToSpeckle/WallTopLevelConverterToSpeckle.cs

DUI3-149 Level conversions should be optional?  Not all!

---

DUI3-DX/Connectors/ArcGIS/Speckle.Connectors.ArcGIS3/Bindings/BasicConnectorBinding.cs
DUI3-DX/Connectors/ArcGIS/Speckle.Connectors.ArcGIS3/Operations/Receive/HostObjectBuilder.cs

On Receive, the created layers will be nested in groups. 1st group: name of Project and Model. Following group levels: the replicated structure of the received Commit object (e.g. Rhino Model > Layer1 > Polylines).

Nesting arc gis layers on receive

---

Core/Tests/Speckle.Core.Tests.Integration/ServerTransportTests.cs

MAIN -> Dev

---

.github/workflows/main.yml

Part of https://spockle.atlassian.net/browse/DUI3-37

Disable the installer trigger for alpha branch

---

ConnectorGrasshopper/ConnectorGrasshopperShared/Conversion/ToSpeckleTaskCapableComponent.cs
ConnectorGrasshopper/ConnectorGrasshopperShared/Extras/Utilities.cs

https://spockle.atlassian.net/browse/CNX-9438
Additionally, fixes null reference exception on non-supported types.

CNX-9438 Grasshopper in Rhino 8 - New Types Support for Text, User Attributes, and Hatches

---

Core/Tests/Speckle.Core.Tests.Integration/Speckle.Core.Tests.Integration.csproj
Core/Tests/Speckle.Core.Tests.Unit/Speckle.Core.Tests.Unit.csproj

Merge `main` -> `dev`

---

.circleci/scripts/config-template.yml

https://spockle.atlassian.net/browse/CNX-9818

Disable signed builds on non-main/dev branches

---

Objects/Converters/ConverterCSI/ConverterCSIShared/PartialClasses/Geometry/ConvertFrame.cs
Objects/Converters/ConverterCSI/ConverterCSIShared/PartialClasses/Geometry/ConvertLinks.cs
Objects/Objects/Structural/CSI/Geometry/CSIElement1D.cs

update ETABS converters to use proper constructors for element1ds. This allows the element1ds to show up in the viewer properly
https://latest.speckle.systems/projects/85bc4f61c6/models/6cd9058fba
Here is a commit sent from this branch

use constructors to generate element1ds

---

Objects/Converters/ConverterCSI/ConverterCSIShared/ConverterCSIUtils.cs

Two community issues related to the SAP 2000 Connector doing nothing (both **Send** and **Receive**). For more context, the community issues are linked here:
- https://speckle.community/t/why-receiving-and-sending-model-dont-work-on-sap2000/12245/4
- https://speckle.community/t/question-is-it-possible-for-me-to-use-the-sap2000-connector-with-v25-2-0/12032
When reviewing the Report, the following failed message was noted: `Unable to retrieve valid length units from the ETABS document`, giving an indication of the error source.
- Re-introducing the old method for obtaining model units, this change happened in #3410. The 'old method' is needed for SAP 2000 and CSIBridge (`GetPresentUnits()`).
- The change from the aforementioned PR remains relevant for ETABS and SAFE (`GetPresentUnits_2()`) …

CNX-9877-units-fix

---

Core/Core/Models/DynamicBase.cs

https://spockle.atlassian.net/browse/CNX-9776

Cnx 9776 rhino 8 issue with non concurrent collections

---

Core/Core/Api/Operations/Operations.Send.cs

When attempting to debug issues between connector and the server, we need to be able to correlate requests. The correlation ID must be printed to the console to allow the user to report this.
Having the correlation ID speeds up the ability to find the exact log messages.
- amends log messages for operation send to print the correlation ID to the console.

chore(send operation): print correlation ID in error & success messages

---

Objects/Converters/ConverterRevit/ConverterRevitShared/PartialClasses/ConvertView.Schedule.cs

See https://github.com/specklesystems/speckle-sharp/pull/3500 for problem and solution details

Support shared parameter in schedules

---

Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.Civil.cs

tl;dr: `basecurve` property on pipes is fake news and the line/arc needs to be retrieved directly from the pipe class
bonus: I believe we were misconverting arc pipes previously, and this pr fixes it.
Before:
After:

bug(civil3d) : fixes pipe base curve conversion bc civil3d api sucks

---

Objects/Converters/ConverterRevit/ConverterRevitShared/ConverterRevit.cs
Objects/Converters/ConverterRevit/ConverterRevitShared/PartialClasses/ConvertPolygonElement.cs

formatting

---

.circleci/scripts/config-template.yml

Change regex to Sign rc builds

---

ConnectorNavisworks/ConnectorNavisworks/Other/SelectionBuilder.cs

- Extracted `ExtractSelectionSets` method from LINQ query for improved reusability and testability
- Added comprehensive XML documentation to `ExtractSelectionSets` method
- Implemented robust error handling with null checks
- Optimized LINQ query for extracting SelectionSets from GUIDs
These changes address several key areas:
1. **Navsiworks 2025 API Changes**: Folders of `SelectionSets` used to be typed the same as `SelectionSets` now the COM Interop returns `FolderItems`
1. **Code Quality**: We've improved code organisation by extracting the `ExtractSelectionSets` method and made it easier to maintain and test.
2. **Documentation**: The added XML comments provide clear information about the method's purpose, inputs, outputs, and behaviour, enhancing readability and ease of use for …

fix(Navisworks) - Improve SelectionSet extraction with error handling and documentation

---

ConnectorArchicad/AddOn/Sources/AddOn/Commands/CreateCommand.cpp
ConnectorArchicad/AddOn/Sources/AddOn/Commands/CreateDoor.cpp
ConnectorArchicad/AddOn/Sources/AddOn/Commands/CreateGridElement.cpp
ConnectorArchicad/AddOn/Sources/AddOn/Commands/CreateObject.cpp
ConnectorArchicad/AddOn/Sources/AddOn/Commands/CreateSkylight.cpp
ConnectorArchicad/AddOn/Sources/AddOn/Commands/CreateWindow.cpp

Restored helper function for faster library/object creation

Restored helper function for faster library/object creation

---

Automate/Speckle.Automate.Sdk/AutomationContext.cs

- Same as specklesystems/specklepy#346 but C#-flavored

fix(automate): remove extra slash

---

Core/Core/Api/GraphQL/Client.cs
Core/Core/Helpers/Http.cs
Core/Core/Transports/Server.cs
Core/Core/Transports/ServerUtils/ServerAPI.cs
Core/Core/Transports/ServerV2.cs

Changes from https://github.com/specklesystems/speckle-sharp-sdk/pull/89 bought to v2

Resiliency

---

Core/Core/Kits/Units.cs
Core/Tests/Speckle.Core.Tests.Unit/Kits/UnitsTest.cs

v2 copy of https://github.com/specklesystems/speckle-sharp-sdk/pull/93

Fixed issue with Meters to Km unit scalling

---

ConnectorGrasshopper/ConnectorGrasshopperShared/BaseComponents/ComponentTracker.cs
ConnectorGrasshopper/ConnectorGrasshopperShared/Ops/Operations.SyncReceiveComponent.cs
ConnectorGrasshopper/ConnectorGrasshopperShared/Ops/Operations.VariableInputReceiveComponent.cs
ConnectorRhino/ConnectorRhino8/ConnectorRhino8.csproj
Core/Core/Core.csproj
Core/Core/Logging/SpeckleLog.cs
Core/docker-compose.yml
Objects/Converters/ConverterRhinoGh/ConverterRhino8/ConverterRhino8.csproj

Update `main` to `dev`

---

Objects/Converters/ConverterRevit/ConverterRevitShared/PartialClasses/ConvertCeiling.cs

- Pull request related to linked floors not sending #3634 and #3635
- Same thing needs to be done for ceilings
- Linked roofs work (no action needed)
- Same changes for linked floors applied to linked ceilings
- Floor and ceiling failed (before using latest main)
- No items failed
- Created a small model with a floor, ceiling and roof
- Linked that model into a new model
- Sent linked model in advanced settings
- No objects failed

CNX-640 Sending Linked Ceiling

---

Core/Core/Logging/SpeckleLog.cs

see https://speckle.community/t/godot-parameter-path-is-empty-exception/14629/8

Fix: Potential fix for godot issue

---

ConnectorNavisworks/ConnectorNavisworks/Other/Elements.cs

minor(navis): coalesced properties to reflect instance as dominant on duplicate

---

DesktopUI2/DesktopUI2/Views/MainUserControl.xaml.cs

The event is polluting our MP metrics and not adding much value.

Remove Launched Event

---

Automate/Speckle.Automate.Sdk/AutomationContext.cs
Automate/Speckle.Automate.Sdk/Schema/ObjectResultLevel.cs
Automate/Speckle.Automate.Sdk/Schema/ObjectResultLevelMapping.cs

see specklesystems/specklepy#355

fix(automate): add success object level

---

Objects/Converters/ConverterCSI/ConverterCSIShared/PartialClasses/Geometry/ConvertFrame.cs

- Linked to: [Revit - SAP 2000 Issue](https://speckle.community/t/revit-sap-2000-issue/16577).
- Unexpected behaviour in receiving a SAP 2000 model in Revit. All analytical members were being received as generic models.
- This was due to an etabs-specific api call being used in the csi shared project
- Previously, `GetDesignOrientation` was being used in `ConnectorCSIShared` project. This is, however an ETABS-specific api call.
- Preprocessor directives to allow the etabs-specific api call for etabs to retrieve the orientation (beam / column / brace).
- For sap, some basic coordinate checks were introduced to determine the orientation of a frame element
Previously, all SAP elements were coming in with `type` = 13. This was `null` frame element.
Now, we get the actual frame `type`. In this …

fix(sap2000): sap model being received as generic models in revit

---

ConnectorCore/DllConflictManagement/DllConflictManager.cs
ConnectorCore/DllConflictManagement/DllConflictUserNotifier.cs

@JR-Morgan are we targeting to main for hotfix?

Chore(mixpanel): Remove DllConflictsDetected event

---

All.sln
Core/Core/Api/GraphQL/Enums/ProjectVisibility.cs
Core/Tests/Speckle.Core.Tests.Integration/Api/GraphQL/Resources/ProjectResourceExceptionalTests.cs
Core/Tests/Speckle.Core.Tests.Integration/Api/GraphQL/Resources/ProjectResourceTests.cs
DesktopUI2/DesktopUI2/Models/ConfigManager.cs
DesktopUI2/DesktopUI2/ViewModels/CollaboratorsViewModel.cs
DesktopUI2/DesktopUI2/ViewModels/HomeViewModel.cs
DesktopUI2/DesktopUI2/ViewModels/MainViewModel.cs
DesktopUI2/DesktopUI2/ViewModels/OneClickViewModel.cs
DesktopUI2/DesktopUI2/ViewModels/StreamViewModel.cs
DesktopUI2/DesktopUI2/Views/Pages/CollaboratorsView.xaml.cs
DesktopUI2/DesktopUI2/Views/Pages/HomeView.xaml
DesktopUI2/DesktopUI2/Views/Pages/OneClickView.xaml.cs
DesktopUI2/DesktopUI2/Views/Pages/StreamEditView.xaml

Removed collaborator, comments, and one click send

---

Core/Core/Api/GraphQL/Models/ModelExtensions.cs
DesktopUI2/DesktopUI2/Models/StreamAccountWrapper.cs
DesktopUI2/DesktopUI2/ViewModels/HomeViewModel.cs
DesktopUI2/DesktopUI2/ViewModels/StreamViewModel.cs
DesktopUI2/DesktopUI2/Views/Converters/BoolToBrushConverter.cs
DesktopUI2/DesktopUI2/Views/Converters/RoleCanReceiveValueConverter.cs
DesktopUI2/DesktopUI2/Views/Converters/RoleValueConverter.cs
DesktopUI2/DesktopUI2/Views/Pages/HomeView.xaml
DesktopUI2/DesktopUI2/Views/Pages/StreamEditView.xaml

A better (imo) alternative to https://github.com/specklesystems/speckle-sharp/pull/3702
Instead of hiding reviewer streams, we will show them, greyed out, with a tool tip.

feat(dui2): Reviewer streams greyed out with better feedback to user

---

.circleci/scripts/config-template.yml

Same as https://github.com/specklesystems/connector-installers/pull/94 but for v2

Fix(CI): Fixed broken digicert windows cert syncing

---

ConnectorAutocadCivil/ConnectorAutocadCivil/Entry/SpeckleAutocadCommand.cs

feat(Rhino): Rename AutoCAD/Civil3d command to avoid conflict with v3

---

Core/Core/Api/GraphQL/Enums/ProjectVisibility.cs
Core/Tests/Speckle.Core.Tests.Integration/Api/GraphQL/Resources/ProjectInviteResourceTests.cs
Core/Tests/Speckle.Core.Tests.Integration/Api/GraphQL/Resources/ProjectResourceTests.cs
DesktopUI2/DesktopUI2/ViewModels/HomeViewModel.cs

same as https://github.com/specklesystems/speckle-sharp-sdk/pull/307 but for v2 
I'll make a hotfix shortly after

Added Workspace project visibility
