specklesystems/speckle-sharp

- Core/Kits/LengthUnits.cs
This fixes the spelling of `LengthUnits.Millimeters` and adds international + American spellings to the `GetUnitsFromString` for consistency.
> Spellings for LengthUnits

- Core/Kits/ISpeckleConverter.cs
- Core/Kits/KitManager.cs
- Core/Serialisation/BaseObjectSerializer.cs
this will break current converters!  `SetContextDocument` will need to be implemented in:
> fix(converter): add `SetContextDocument` to `ISpeckleConverter`

- Core/Api/Models.cs
For user interfaces, it would make sense to add the `avatar` property to things like `Commit` and `Collaborator` so an additional user query doesn't have to happen to get and display this info.
This is a WIP: it simply adds the props to the models in core so work can continue in the DekstopUI, but the necessary changes in Server have not been made to reflect this.
TODO:
- add these to return types in Server
- add them to `Core.ClientOperations`
> feat(models): avatar prop in commit & collaborator

- .circleci/config.yml
- Core/Api/Client.GraphqlClientOperations.cs
- Core/Api/Models.cs
- Core/Api/Operations/Operations.Receive.cs
- Core/Api/Operations/Operations.Send.cs
- Core/Api/Operations/Operations.Serialize.cs
- Core/Api/Operations/Operations.cs
- Core/Credentials/AccountManager.cs
- Core/Credentials/StreamWrapper.cs
- Core/Logging/Setup.cs
- Core/Serialisation/BaseObjectSerializer.cs
- Core/Serialisation/BaseObjectSerialzerUtilities.cs
- Core/Transports/ITransport.cs
- Core/Transports/Memory.cs
- Core/Transports/SQLite.cs
- DiskTransport/DiskTransport.cs
- MongoDBTransport/MongoDB.cs
- ServerTransport/Server.cs
- Tests/Kits.cs
- Tests/SendReceiveLocal.cs
- Tests/TestsUnit.csproj
Changes in a nutshell: 
- transports can be cancelled (re #35)
- send can be cancelled (re #35)
- transports can bubble up errors (closes #4)
- gql api calls can be cancelled
- adds StreamWrapper class for ease of use of (stream, account) structs in dynamo/gh
> WIP: Dim/dev transport cancellation

- Core/Models/Base.cs
Quick and short PR! Just added the `ShallowCopy()` functionality to the base class so we can reuse it elsewhere.
This was added to prevent passing the same pointer in Visual Programming interfaces (mainly Grasshopper), as it was backward updating the entire node graph.
> feat(base): Added ShallowCopy() method to Base

- Transports/ServerTransport/Server.cs
One major hotfix in queue processing and handling 😬
Improvements: 
- can gzip payloads (upload size reduced 3x to 10x)
- flag for compression, in case some might want to set it to false (ie, local network scenarios where latency is a secondary concern)
Includes other tweaks and balancing acts in the server transport: 
- MAX_BUFFER_SIZE: set 100k to avoid over-pressuring mem/cpu on server
- MAX_MULITPART_COUNT: set to 500
- PollInterval increased to 100ms to ensure higher chunks being sent
Measurements (benchmarks):
A) heterogenous payload (approx 10k objs for "slider @ 5000"):
```
57s - slider @ 5000; MBF = 2mb, MPC = 10
85s - slider @ 5000, MBF = 1mb, MPC = 3
56s - slider @ 5000, MBF = 1mb, MPC = 20
48s - slider @ 5000, MBF = 1mb, MPC = 50
50s - slider @ 5000, MBF = 2mb, MPC = 100
48s - …
```
> Server Transport Improvements

- Core/Models/Base.cs
now it can shallow copy any base-derived types
fix #61
> fix(copy): fixes the shallow copy func to not change type

- ConnectorDynamo/ConnectorDynamo/ConnectorDynamo.csproj
this was throwing off the GetConverterForApp func as it was looking inside the plugin folder rather than the kits folder.
> fix(dynamo): removes objects.dll reference

- Core/Core/Credentials/AccountManager.cs
- DesktopUI/DesktopUI/Accounts/AccountsRepository.cs
- DesktopUI/DesktopUI/RootView.xaml
- DesktopUI/DesktopUI/RootViewModel.cs
- DesktopUI/DesktopUI/Settings/SettingsView.xaml
- DesktopUI/DesktopUI/Streams/AllStreamsViewModel.cs
- DesktopUI/DesktopUI/Streams/StreamsHomeView.xaml
- DesktopUI/DesktopUI/Streams/StreamsHomeViewModel.cs
- DesktopUI/DesktopUI/Streams/StreamsRepository.cs
- DesktopUI/DesktopUI/Utils/Events.cs
- DesktopUI/DesktopUI/Utils/StreamState.cs
This adds an overlay to the DesktopUI home page if there are no local accounts on the machine. This is likely caused by not having installed manager, so the overlay directs the user to download the manager and try again.
This includes a small change in core: `AccountManager` was using `CaptureAndThrow` when no default account was found. I assume the intended behaviour was to `CaptureException` but allow it to continue and return null, so I have made this change.
> 👌 Show user if there are no local accounts

- Core/Core/Serialisation/BaseObjectSerializer.cs
- Objects/Objects/Geometry/Brep.cs
Hey @AlanRynne, here's the gist: loopy refs are bad and will be perpetually ignored in speckle land, but there's a way around that! I've put down [some kit class defs 101s here ](https://www.notion.so/speckle/Kit-Class-Definitions-101s-99cf5a1839ce402e97e99d3f7f894d49), inc. a quick overview of the workaround re the brep class!
> fix(breps): reworks classes to bypass self-refencing loop problems

- DesktopUI/DesktopUI/DesktopUI.csproj
- DesktopUI/DesktopUI/Streams/AllStreamsView.xaml
- DesktopUI/DesktopUI/Streams/AllStreamsViewModel.cs
- DesktopUI/DesktopUI/Utils/SelectionFilter.cs
- DesktopUI/DesktopUI/Utils/StreamState.Events.cs
- DesktopUI/DesktopUI/Utils/StreamState.cs
This resolves the issue of streams not being refreshed when a document with a saved stream is reopened and the stream is deserialised. The stream is now refreshed upon initialisation after being deserialised.
An issue regarding deserialisation of selection filters has also been resolved with a json converter.
This also resolves other issues with the branches / commits:
- commits and branches now update consistently including when they have been edited from the web, from another connector, or from the document itself (previously branches and commits would not update if you were modifying the stream from the document itself - they would only update if the stream was modified elsewhere)
- a bug with the commit list compiling commits from different branches has been squashed
- branch …
> 🌀 Refresh stream cards when the stream is modified elsewhere

- ConnectorGrasshopper/ConnectorGrasshopper/Conversion/Convert.ToNativeAsync.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Extras/Utilities.cs
- ConnectorGrasshopper/ConnectorGrasshopper/InternalTestFiles/AsyncObjectManagementTests.ghx
- ConnectorGrasshopper/ConnectorGrasshopper/Objects/ExpandSpeckleObjectAsync.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Objects/GetObjectValueByKeyAsync.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Ops/Operations.SendLocalComponent.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Streams/StreamDetailsComponent.cs
Turns out, we didn't have preview in our nodes due to some lack of consistency on our part. Everything was being wrapped into `GH_ObjectWrapper` classes instead of allowing `GH_Convert.ToGoo` to do the hard work.
I left a fallback that returns an object wrapper if this fails.
> GH: `TryConvertToNative` now returns appropriate IGH_Goo for preview

- ConnectorGrasshopper/ConnectorGrasshopper/Ops/Operations.ReceiveComponent.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Ops/Operations.SendComponent.cs
The issue was related with overriding `GH_ComponentAttributes`. It appears inheriting from this class does not do all the magic one would have expected it to.
I'll leave the issue open and contact the McNeel guys to see if this is a bug or we're just missing something.
> GH: Temporary fix for "green cables" issue.

- ConnectorGrasshopper/ConnectorGrasshopper/Ops/Operations.ReceiveComponent.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Ops/Operations.SendComponent.cs
As discussed in issue #135, I removed the double click behaviour and allowed for the send/receive button to always be clickable.
Fixes #135
> Removes double-click behaviour in sender/receiver button

- ConnectorGrasshopper/ConnectorGrasshopper/Ops/Operations.ReceiveComponent.cs
Issue was due to receiver input being optional. Enforcing input now prevents the component from running and ending up in an `expired` state.
Fixes #169
> fix(gh): Fixed initial state on receiver

- ConnectorDynamo/ConnectorDynamoFunctions/Functions.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Ops/Operations.SendComponent.cs
- ConnectorRevit/ConnectorRevit/UI/ConnectorBindingsRevit.Send.cs
- ConnectorRhino/UI/ConnectorBindingsRhino.cs
- Core/Core/Api/GraphQL/Client.GraphqlClientOperations.cs
- Core/Core/Api/GraphQL/Models.cs
- Core/Core/Api/GraphQL/SubscriptionModels.cs
- adds `sourceApplication`, `totalChildrenCount`, and `parents` to core commit models
- depreciates `previousCommitIds`
- populates `sourceApplication` and `parents` in grasshopper, dynamo, rhino, and revit connectors
closes #162
> 🏷 Update Commit Models & Populate New Props in Connectors

- ConnectorDynamo/ConnectorDynamo/AccountsNode/Accounts.cs
- ConnectorDynamo/ConnectorDynamo/AccountsNode/AccountsViewCustomization.cs
- ConnectorDynamo/ConnectorDynamo/CreateStreamNode/CreateStream.cs
- ConnectorDynamo/ConnectorDynamo/CreateStreamNode/CreateStreamViewCustomization.cs
- ConnectorDynamo/ConnectorDynamoFunctions/Account.cs
- ConnectorDynamo/ConnectorDynamoFunctions/Stream.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Accounts/Accounts.ListAccounts.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Streams/StreamDetailsComponent.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Streams/StreamGetComponent.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Streams/StreamListComponent.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Streams/StreamUpdateComponent.cs
Handled cases for Dynamo and GH nodes. For consistency, all account nodes, and any other node that may use the default account automatically, will display a warning directing the user to the Speckle Manager.
Fixes #101
> Fixes #101: Alert user if no default account is set, or no account is found.

- ConnectorDynamo/ConnectorDynamo/ReceiveNode/Receive.cs
- ConnectorDynamo/ConnectorDynamoFunctions/Functions.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Ops/Operations.ReceiveComponent.cs
- ConnectorRevit/ConnectorRevit/UI/ConnectorBindingsRevit.Receive.cs
- ConnectorRevit/ConnectorRevit/UI/ConnectorBindingsRevit.Send.cs
- ConnectorRhino/UI/ConnectorBindingsRhino.cs
- Core/Core/Api/GraphQL/Client.GraphqlClientOperations.cs
- Core/Core/Api/GraphQL/Models.cs
- Core/IntegrationTests/Api.cs
- DesktopUI/DesktopUI/Streams/StreamCreateDialogViewModel.cs
- DesktopUI/DesktopUI/Streams/StreamUpdateObjectsDialogViewModel.cs
- DesktopUI/DesktopUI/Streams/StreamsRepository.cs
- DesktopUI/DesktopUI/Utils/StreamState.Events.cs
- DesktopUI/DesktopUI/Utils/StreamState.cs
This breaks down the stream queries into:
`StreamGet`: returns the stream info and basic branch info (id, name, description, and total commit count)
`StreamGetCommits`: returns a list of the latest commits on a given stream
`CommitGet`: returns a commit via `streamId` and `commitId`
`StreamGetBranches`: returns a list of branches on a given stream _including_ commit info
`BranchGet`: returns a commit via `streamId` and `branchName`
The collection queries and the item queries are named with different convention to avoid accidental autocomplete of the wrong one 🙃 
In theory, this also propagates these changes to all the connectors. They should now be using a more specific query or a combination of queries (eg `StreamGet` + `StreamGetBranches`) to get what they need.
Bonus points: simplifies …
> 🏭 Core & Connectors: Rework StreamGet query and propagate to connectors

- Core/Core/Serialisation/BaseObjectSerializer.cs
- Core/Tests/SerializationTests.cs
Adds the option of creating chunkable props on the fly 😎
```cs
myBase["@(666)ChunkyOne"]     // chunkable prop with max chunk size of 666 items
myBase["@()ChunkyTwo"]        // chunkable prop with the default max chunk size (1000 items)
```
Closes #170
> 🧀 Dynamic Chunking of Base Properties

- ConnectorDynamo/ConnectorDynamo/ConnectorDynamo.csproj
- ConnectorDynamo/ConnectorDynamo/ReceiveNode/Receive.cs
- ConnectorDynamo/ConnectorDynamo/SendNode/Send.cs
- ConnectorDynamo/ConnectorDynamoFunctions/Functions.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Ops/Operations.ReceiveComponent.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Ops/Operations.SendComponent.cs
- Core/Core/Credentials/StreamWrapper.cs
`StreamWrapper` can now handle `commit`, `branch` and `stream` types.
GH/Dyn -> Both sender and receiver now support new improvements in StreamWrapper.
- Created a `Type` property on the `StreamWrapper` class to indicate what type of stream it is holding.
- Sender and receiver no longer have a `branch` input, it is deduced  automatically by introducing a branch/commit/stream url.
- Modified behaviour of sender to be same as in GH and Dyn: Sender supports streams and transports. Will only output commit for serverTransports/streams.
Fixes #167
> 🌳  DYN/GH: Support for branch url's in Sender/Receiver

- ConnectorGrasshopper/ConnectorGrasshopper/Ops/Operations.ReceiveComponent.cs
- Core/Core/Api/GraphQL/Client.Subscriptions.Commit.cs
Fixes #92
Minor changes in the way the receiver works:
- Upon a document becoming active, receiver will compare it's receiving commit with the previous one (if exists), and handle notifications or fetching accordingly.
- When a document becomes inactive, any receivers in it will `Dispose` of the ApiClient to prevent subscription calls being called in the background.
- Same as above, but also when the receiver is removed from the document.
- Minor fix preventing a "Receive" operation when no objectID was present.
- Minor fix in Commit subscription: now checks if an event has been assigned before invoking `OnCommitCreated`
> GH: Receiver checks for new commits on file open

- DesktopUI/DesktopUI/Utils/SelectionFilter.cs
- DesktopUI/DesktopUI/Utils/StreamState.cs
- Objects/Converters/ConverterDynamo/ConverterDynamoShared/ConverterDynamo.Geometry.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/ConverterRevit.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertDirectShape.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertGeometry.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertLocation.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertOpening.cs
- Objects/Converters/ConverterRhinoGh/ConverterRhinoGh/ConverterRhinoGh.Geometry.cs
- Objects/Objects/Geometry/ControlPoint.cs
- Objects/Objects/Geometry/Line.cs
- Objects/Objects/Geometry/Point.cs
- Objects/Objects/Geometry/Vector.cs
`Line`, `Point`, `Vector` and `ControlPoint` were all storing the coordinates in a list of doubles named `value`.
`value` field is now obsolete, but instead of deleting it I modified it to populate the desired fields when setting int.
Tested serialization/deserialization of old and new serialized formats and both work correctly.
Fixed a minor issue in Revit regarding a null check when setting materials in the converter.
Fixes #86
> Models cleanup: Line, point, vector and controlPoint

- ConnectorGrasshopper/ConnectorGrasshopper/ConnectorGrasshopper.csproj
- Objects/Converters/ConverterRhinoGh/ConverterRhinoGh/ConverterRhinoGh.csproj
Updated `GH_AsyncComponent` nuget package to 0.2.1.
Bumped Rhino related packages to latest version `6.33` to align with GH_AsyncComponent versions.
Fixes issue with `CreateSpeckleObject` component getting stuck half way through the cycle.
kudos to @didimitrie for finding and fixing that one!
> fix(gh): Updated async component nuget with latest hotfix

- ConnectorGrasshopper/ConnectorGrasshopper/Extras/Speckle.IGH_Goo.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Extras/SpeckleBaseParam.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Extras/SpeckleStreamParam.cs
Fixes #216 
Main cause was a missing case check on the `CastFrom` methods in our `SpeckleBaseParam` and `GH_SpeckleStream` classes.
> fix(gh): Goo to SpeckleBase and SpeckleStream conversion

- Core/Core/Api/GraphQL/Client.GraphqlClientOperations.cs
added collaborator avatar field to `StreamGet` and `StreamsGet` queries so they appear correctly in desktop ui
previously, they weren't showing up on the Stream Details page
> fix(core): return collaborator avatar in gql ops

- ConnectorGrasshopper/ConnectorGrasshopper/ConnectorGrasshopper.csproj
Account Details node was there all along, next merge in apparently replaced the line.
https://github.com/specklesystems/speckle-sharp/commit/2ba7f827f8940f72ba4c435f530e4dab3844497a#diff-dff20b243514d6c12f91b7010ce4c6891b6fb7135461b2aa9697847bfc6e2d9e
Fixes #122
> fix(gh): Account details missing from csproj!

- ConnectorDynamo/ConnectorDynamo/AccountsNode/Accounts.cs
- ConnectorDynamo/ConnectorDynamo/CreateStreamNode/CreateStream.cs
- ConnectorDynamo/ConnectorDynamo/ReceiveNode/Receive.cs
- ConnectorDynamo/ConnectorDynamo/SendNode/Send.cs
- ConnectorDynamo/ConnectorDynamoFunctions/Account.cs
- ConnectorDynamo/ConnectorDynamoFunctions/Functions.cs
- ConnectorDynamo/ConnectorDynamoFunctions/Stream.cs
- ConnectorDynamo/ConnectorDynamoFunctions/Utils.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Accounts/AccountDetails.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Accounts/Accounts.AccountDetails.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Accounts/Accounts.ListAccounts.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Ops/Operations.ReceiveComponent.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Ops/Operations.SendComponent.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Streams/StreamCreateComponent.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Streams/StreamDetailsComponent.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Streams/StreamGetComponent.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Streams/StreamListComponent.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Streams/StreamUpdateComponent.cs
- Core/Core/Credentials/AccountManager.cs
- Core/Core/Credentials/StreamWrapper.cs
- Core/Core/Models/Base.cs
- Core/Core/Serialisation/BaseObjectSerializer.cs
- Core/Tests/BaseTests.cs
- Core/Tests/Wrapper.cs
Fixes: 
- stream wrappers around branch names (now are un-escaped)
- total children count now approximates chunk numbers too (should fix sender progress reports)
- minor bug in dynamo
- major bug in core serialisation
- bug in grasshopper receiver
Refactor:
- switches account handling to be based on user ids rather than account ids in gh & dynamo
Features: 
- adds wrapper case for an object url (eg, `https://staging.speckle.dev/streams/d631b3eecc/objects/4deba0f5e0e74b421cf8c130bc250fe2`)
- add possibility to receive a single object in gh from an object based wrapper
- add possibility to receive a single object in dynamo from an object based wrapper
> WIP: Dim/children count corrections

- ConnectorAutocadCivil/ConnectorAutocadCivil/Entry/App.cs
- ConnectorAutocadCivil/ConnectorAutocadCivil/UI/ConnectorBindingsAutocadCivil.cs
- Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.DBObjects.cs
- Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.cs
- Objects/Objects/Geometry/Circle.cs
- Objects/Objects/Geometry/Ellipse.cs
-converter using circle.plane.origin instead of circle.center
-deprecated objects circle.center and ellipse.center properties
-added try catch for failed conversions
-added try catch for add-in initialize()
closes #245 #246
> fix(autocad): failed conversion handling

- ConnectorDynamo/ConnectorDynamo/ReceiveNode/Receive.cs
- ConnectorDynamo/ConnectorDynamo/SendNode/Send.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Ops/Operations.ReceiveComponent.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Ops/Operations.SendComponent.cs
- Core/Core/Credentials/StreamWrapper.cs
From issue #226.
Grasshopper was not correctly displaying account/stream errors in sender and receiver. This should work now.
Also, after a conversation with @didimitrie, we decided to also add `branch` name validation to the `GetAccount` method in the StreamWrapper class. It was currently only checking for stream existence.
This change also required to update the way Dynamo's send/receive nodes handled the `GetAccount` exceptions, and some other minor tweaks.
> GH/DYN: Handling incorrect account/stream in sender/receiver

- ConnectorDynamo/ConnectorDynamo/ConnectorDynamo.csproj
- ConnectorDynamo/ConnectorDynamoExtension/ConnectorDynamoExtension.csproj
- ConnectorDynamo/ConnectorDynamoFunctions/ConnectorDynamoFunctions.csproj
Dynamo bug fix: a `System.Windows.Interactivity` dll slipped into the bin folder, because one of the Dynamo nugets didn't have `copy local = false`
> fix(dynamo): sets copy local == false on Dynamo nugets

- DesktopUI/DesktopUI/Streams/AllStreamsView.xaml
- DesktopUI/DesktopUI/Utils/StreamState.cs
disable swapping to sender if user role is reviewer
closes #271 
- Fixes # (issue)
- [ x ] New feature (non-breaking change which adds functionality)
- [ x ] Manual Tests by adding read only streams to the ui
> feat(desktopui): card swapping

- ConnectorDynamo/ConnectorDynamo/SendNode/Send.cs
- ConnectorDynamo/ConnectorDynamoFunctions/BatchConverter.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Ops/Operations.SendComponent.cs
- ConnectorRevit/ConnectorRevit/UI/ConnectorBindingsRevit.Send.cs
- ConnectorRhino/ConnectorRhino/UI/ConnectorBindingsRhino.cs
Rhino and Revit already disallow commits with 0 objects. This should also be enforced in:
- Fixes #255 
Commits will now not be created if you try and send with no data, so this will no longer be allowed:
> feat(grasshopper): disallow 0 obj commits

- ConnectorGrasshopper/ConnectorGrasshopper/Objects/SelectKitAsyncComponentBase.cs
- Core/Core/Kits/Units.cs
- Objects/Converters/ConverterRhinoGh/ConverterRhinoGh/ConverterRhinoGh.Units.cs
Grasshopper nodes were not properly updating the `ModelUnits` when the Document units in Rhino changed.
Added missing switch case for `km` and `kilometer` to be converted to Speckle Units.
Initially, @teocomi suggested to create a new `IConverter` every time we wanted to run a conversion, which would guarantee the proper units were set. This turned out to be a bigger change than intended, so I settled for a fast and simple check on the `ModelUnits` getter.
Previous behaviour was checking `_modelUnits` for `null` or `empty` values, we now also check if the saved value corresponds to the document's model units.
Added `Converter.Set` call on the `BeforeSolveInstance` method of `SelectKitComponentBase`, so that it would propagate to any components inheriting from it. This ensures correct …
> fix(rhino): Model unit converter now checks for unit change.

- DesktopUI/DesktopUI/RootView.xaml
- DesktopUI/DesktopUI/RootViewModel.cs
- DesktopUI/DesktopUI/Settings/SettingsView.xaml
- DesktopUI/DesktopUI/Streams/AllStreamsView.xaml
- DesktopUI/DesktopUI/Streams/AllStreamsViewModel.cs
- DesktopUI/DesktopUI/Streams/StreamView.xaml
- DesktopUI/DesktopUI/Utils/Converters.cs
- DesktopUI/DesktopUI/Utils/Events.cs
This is a collection of smol bug fixes for the DesktopUI
- refactor nav bar logic to make it simpler and fix the bug with the nav bar text not updating after removing a stream
- catch and handle exception on settings page if the server is down 
- fix the overlay issue on stream cards that have been disabled because no local account was found 
- add option to remove a stream that has been disabled
- add refresh button to menu bar
- add stream id to details page
closes #276 
in desktopui and in revit
> 🐛 DesktopUI Bug Fixes

- .circleci/config.yml
- ConnectorAutocadCivil/ConnectorAutocad2021/Properties/AssemblyInfo.cs
- ConnectorAutocadCivil/ConnectorCivil2021/Properties/AssemblyInfo.cs
Fixes a CI bug that prevented the correct release of the Autocad and Civil connectors.
Please describe the tests that you ran to verify your changes.
> ci: adds correct dll name for patching

- ConnectorRevit/ConnectorRevit/Entry/App.cs
- ConnectorRevit/ConnectorRevit/Revit/ErrorEater.cs
- ConnectorRevit/ConnectorRevit/UI/ConnectorBindingsRevit.Receive.cs
- DesktopUI/DesktopUI/Streams/StreamsRepository.cs
- DesktopUI/DesktopUI/Utils/StreamState.cs
This swallows failures with level `DocumentCorruption` which before were not swallowed by our `ErrorEater`. I was not able to fully fix this to allow the commit to continue, so will open a separate issue for this. For now, the failure will try to be resolved and if it can't (eg in the popup for the user, the only option is "Cancel" not "Ok") the commit is rolled back. The conversion errors are cleared and the error shown to the user is the fatal one that failed during commit. 
closes #189
> feat(revit): swallow document corruption errors 

- .gitignore
- ConnectorGrasshopper/ConnectorGrasshopper/SchemaBuilder/CreateSchemaObject.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertCurves.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertGeometry.cs
Added recursive conversion in `PolyCurves`. Since they do not exist in Revit, each segment will be created as an individual `Curve`. 
Also added support for `PolyCurves` when converting:
- ModelCurves
- DetailCurves
- Fixes #296
- Minor fix in CreateSchemaObject (GH)
Please describe the tests that you ran to verify your changes. 
- Ran curve conversion tests with all passing.
- Sent several polycurves from GH to Revit as **model curves**, **detail curves**, native Speckle curves and floors with polycurves as outlines.
> Revit: PolyCurve support

- ConnectorRevit/ConnectorRevit/Revit/ErrorEater.cs
- Core/Core/Logging/SpeckleException.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertGeometry.cs
Length params in geometry conversions are now scaled appropriately when converting to speckle
- Fixes #303
All relevant xUnitRevit tests pass  (breps fail due to unrelated isssue) and manual testing sending to server
> fix(revit): scale lengths when converting to speckle

- Objects/Converters/ConverterRevit/ConverterRevitShared/ConversionUtils.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertColumn.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertLocation.cs
This was a super ez fix! Just some small changes to fix column conversion issues
- uncomments handling of case `ElementId` in `ParameterToSpeckle()`
- adjusts line creation logic for vertical columns with the "top level" at the bottom of the column
before:
after:
[the commit](https://speckle.xyz/streams/4a8efa56a8/commits/176028dfb7) if you're curious
- Fixes #309 and #310 
Ran all xUnitRevit tests and tested manually using the revit connector
> fix(revit): resolve issues with column conversions

- Objects/Converters/ConverterRhinoGh/ConverterRhinoGh/ConverterRhinoGh.Geometry.cs
- Objects/Converters/ConverterRhinoGh/ConverterRhinoGh/ConverterRhinoGh.cs
Failing to convert BREPs will now try to extract the displayValue instead of returning a `null` object.
- Fixes #334 
Please describe the tests that you ran to verify your changes. 
Forced conversion to fail and ensured that meshes where being assigned to the output and warnings were being shown to the user.
> fix(gh): Brep conversion fallback to mesh.

- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertStair.cs
- Objects/Objects/BuiltElements/Beam.cs
- Objects/Objects/BuiltElements/Brace.cs
- Objects/Objects/BuiltElements/Ceiling.cs
- Objects/Objects/BuiltElements/Column.cs
- Objects/Objects/BuiltElements/Duct.cs
- Objects/Objects/BuiltElements/Floor.cs
- Objects/Objects/BuiltElements/Level.cs
- Objects/Objects/BuiltElements/Opening.cs
- Objects/Objects/BuiltElements/Revit/AdaptiveComponent.cs
- Objects/Objects/BuiltElements/Revit/BuildingPad.cs
- Objects/Objects/BuiltElements/Revit/DirectShape.cs
- Objects/Objects/BuiltElements/Revit/FamilyInstance.cs
- Objects/Objects/BuiltElements/Revit/ModelCurves.cs
- Objects/Objects/BuiltElements/Revit/RevitRailing.cs
- Objects/Objects/BuiltElements/Revit/RevitStair.cs
- Objects/Objects/BuiltElements/Roof.cs
- Objects/Objects/BuiltElements/Room.cs
- Objects/Objects/BuiltElements/Topography.cs
- Objects/Objects/BuiltElements/View.cs
- Objects/Objects/BuiltElements/Wall.cs
Adds xml comments to builtelements constructors that expect units due to length props. Also includes:
- reformatting for consistency
- minor typo fix in stair property spelling and ceiling schema name
- commented template for a new revit shaft constructor using bottomlevel and height (in addition to current constructor using bottom and top levels)
- Fixes #319
Sent a shaft from GH to Revit
> Objects builtelements cleanup

- ConnectorGrasshopper/ConnectorGrasshopper/Conversion/Convert.ToNativeAsync.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Conversion/Convert.ToSpeckleAsync.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Conversion/Serialisation.DeserializeObject.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Conversion/Serialisation.SerialiseObject.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Extras/Utilities.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Objects/CreateSpeckleObjectByKeyValueAsync.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Objects/ExpandSpeckleObjectAsync.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Objects/ExtendSpeckleObjectAsync.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Ops/Operations.ReceiveLocalComponent.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Ops/Operations.SendLocalComponent.cs
- Fixes #289: several error reporting issues with some of the `dev` nodes. All that was fixed is specified in the linked issue.
Introduced the same behaviour as in the `Send/Receive` nodes. A new  `RuntimeMessages` property in the worker keeps track of the worker's errors and reports them on `SetData()`.
This requires that `Done()` must always be called (as was already recommended).
- Fixes #290: Local send/receive now properly reporting all errors, and local receiver no longer gets _stuck_ after first error was thrown.
- Fixes smaller error reporting issues in:
- Create Speckle Object by Key/Value
- ExpandSpeckleObject
- ExtendSpeckleObject
Please describe the tests that you ran to verify your changes. 
Added edge cases to the Grasshopper …
> GH: Fix error reporting on nodes

- ConnectorGrasshopper/ConnectorGrasshopper/ConnectorGrasshopper.csproj
- ConnectorGrasshopper/ConnectorGrasshopper/Extras/GenericAccessParam.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Extras/SpeckleStateTag.cs
Refactored all state tag code into a `SpeckleStateTag` class, and derived the following:
- ListAccessStateTag
- DetachStateTag
- OptionalStateTag
These represent the small icons appearing at the side of the parameter name.
Implemented custom `Render` function to get nice Speckle style colors. 
Please describe the tests that you ran to verify your changes.
> feat(gh): Added fancy rendered state tags, no more pixels!!

- ConnectorAutocadCivil/ConnectorAutocadCivil/UI/ConnectorBindingsAutocadCivil.cs
- ConnectorRhino/ConnectorRhino/ConnectorRhino.csproj
- ConnectorRhino/ConnectorRhino/UI/ConnectorBindingsRhino.cs
- ConnectorRhino/ConnectorRhino/Utils.cs
- Objects/Converters/ConverterRhinoGh/ConverterRhinoGh/ConverterRhinoGh.BuiltElements.cs
- Objects/Converters/ConverterRhinoGh/ConverterRhinoGh/ConverterRhinoGh.cs
- Objects/Objects/BuiltElements/Revit/DirectShape.cs
Rhino:
- Refactored receiving commit obj logic and layer creation
- Fixed bug that created bake layers even if no objects where converted (empty layers currently still will be created if base is successfully converted but not successfully added to doc)
- Added correct warnings for failure to bake supported and unsupported objects with no dynamic props
- Added  `ModelCurve` (basecurve) and `DirectShape` (displaymesh) ConvertToNative handling
Autocad:
- Added correct warnings for failure to bake unsupported objects with no dynamic props
Objects:
- DirectShape class now inheriting from `IDisplayMesh`
Fixes #341 
Fixes #342
Fixes #347 
Rhino:
Tested receiving Rhino test streams …
> fix(Rhino,Autocad): error handling

- ConnectorGrasshopper/ConnectorGrasshopper/SchemaBuilder/CreateSchemaObject.cs
- ConnectorGrasshopper/ConnectorGrasshopper/SchemaBuilder/CreateSchemaObjectDialog.cs
- Objects/Objects/Other/RenderMaterial.cs
Render material support for schemabuilder:
-  Objects: Added schemabuilder constructor. Constructor uses `System.Color` for diffuse and emissive props and converts to int internally to make GH component easier to use.
-  GH: Added default value to Create Schema Object optional params
-  GH: Added Nullable type checking for descriptive type text
Fixes #315
- Manual Tests: sent [rendermaterial from gh](https://latest.speckle.dev/streams/dc5e51ffd4/commits/c51c1c0919) and created a few other [schemabuilder objects with render material](https://latest.speckle.dev/streams/dc5e51ffd4/commits/f76972e2d3)
> Feat: add render material support for schemabuilder

- ConnectorGrasshopper/ConnectorGrasshopper/Extras/SpeckleStreamParam.cs
- Core/Core/Credentials/StreamWrapper.cs
- Previously: only throwing exception for uri count < 3. Now throws `SpeckleException` in all cases of incorrect uri segment count (anything other than 3 or 5).
- `GH_SpeckleStream` class throws `SpeckleException` on failure to cast string to stream instead of returning false on cast method.
Fixes #329
- Manual Tests: tested with Grasshopper Stream Details component
> bug(core): improve stream wrapper uri parsing logic

- DesktopUI/DesktopUI/Utils/StreamState.Events.cs
- DesktopUI/DesktopUI/Utils/StreamState.cs
previously, commit created and deleted were handled by the same event
as the handler just updates the branches.
however, we now show a notification with info on the event.
branch name is only returned on commit created, so a diff handler is
now needed for commit deleted. this is the fix!
tested manually in both Rhino & Revit
closes #371
> fix(desktopui): handle commit deleted event

- Core/IntegrationTests/Api.cs
- Core/IntegrationTests/Fixtures.cs
- Core/IntegrationTests/Subscriptions/Branches.cs
- Core/IntegrationTests/Subscriptions/Commits.cs
- Core/IntegrationTests/Subscriptions/Streams.cs
Refactor tests to use our new testing server. Also extracts the individual `testServer` definitions and consolidates them to one place - fixtures. `SeedUser` no longer takes server as an argument and just uses the server defined in the fixtures.
- Unit/Integration Tests (which?)
NOTE: cannot merge this right now as tests fail when using `https://latest.speckle.dev` despite working with `https://testing.speckle.dev`. this is because the register post request returns a 400 error on `latest`
> refactor(tests): move server info to fixtures

- ConnectorRhino/ConnectorRhino/SchemaBuilder/SchemaObjectFilter.cs
- Objects/Converters/ConverterRhinoGh/ConverterRhinoGh/ConverterRhinoGh.BuiltElements.cs
- Improves Rhino SchemaBuilder wall bottom curve logic
- Removes `Ceiling` from support types
- Manual Tests: sent various schema objects from Rhino
> Rhino schemabuilder fixes

- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertColumn.cs
Disallows joins on column ends
- Manual Tests: sent some columns from rhino
> fix(revit):disallowing column joins

- ConnectorRevit/ConnectorRevit/UI/ConnectorBindingsRevit.Receive.cs
Let users cancel the receive during conversion. We were previously not checking for cancellation while objects were being converted. This checks and rolls back the commit if cancellation was requested.
- Fixes issue reported by Alan
-  Manual tests in Revit with the stream Alan reported 
> fix(revit): check for cancellation when converting

- ConnectorRhino/ConnectorRhino/SchemaBuilder/SchemaObjectFilter.cs
- ConnectorRhino/ConnectorRhino/UI/ConnectorBindingsRhino.cs
- Objects/Converters/ConverterRhinoGh/ConverterRhinoGh/ConverterRhinoGh.BuiltElements.cs
- Objects/Converters/ConverterRhinoGh/ConverterRhinoGh/ConverterRhinoGh.cs
Improves the beams and columns builtelements conversion logic slightly by accounting for "flipped" endpoints. Also removes deprecated ceiling methods.
- Will be updated ASAP (remove ceiling from supported conversions)
> rhino(fix): better column and beam conversions

- DesktopUI/DesktopUI/Streams/AllStreamsView.xaml
- DesktopUI/DesktopUI/Streams/AllStreamsViewModel.cs
- DesktopUI/DesktopUI/Utils/StreamState.cs
make commit message ui more prominent to encourage usage!
- closes #314
- Manual Tests in standalone ui and revit
> feat(desktopui): make commit message ui more prominent

- ConnectorGrasshopper/ConnectorGrasshopper/ConnectorGrasshopper.csproj
- ConnectorGrasshopper/ConnectorGrasshopper/Objects/SelectKitAsyncComponentBase.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Objects/SelectKitComponentBase.cs
- ConnectorRevit/ConnectorRevit/Revit/ErrorEater.cs
- ConnectorRhino/ConnectorRhino/ConnectorRhino.csproj
- Core/Core/Api/GraphQL/Client.GraphqlClientOperations.cs
- Core/Core/Api/GraphQL/Client.Subscriptions.Branch.cs
- Core/Core/Api/GraphQL/Client.Subscriptions.Commit.cs
- Core/Core/Api/GraphQL/Client.Subscriptions.Stream.cs
- Core/Core/Api/Operations/Operations.Receive.cs
- Core/Core/Api/Operations/Operations.Send.cs
- Core/Core/Core.csproj
- Core/Core/Credentials/Account.cs
- Core/Core/Credentials/AccountManager.cs
- Core/Core/Kits/KitManager.cs
- Core/Core/Logging/Log.cs
- Core/Core/Logging/SpeckleException.cs
- Core/Core/Serialisation/BaseObjectSerializer.cs
- Core/Core/Serialisation/BaseObjectSerialzerUtilities.cs
- Objects/Converters/ConverterRhinoGh/ConverterRhinoGh.csproj
- Objects/Objects/ObjectsKit.cs
- Updates sentry dependency, it now no longer depends on Newtonsoft.Json, yay!
- Quick tests in Revit & Rhino
> feat(core): updates Sentry, downgrades gh and rhino deps to 6.33

- DesktopUI/DesktopUI/Streams/StreamCreateDialogView.xaml
- DesktopUI/DesktopUI/Streams/StreamCreateDialogViewModel.cs
- catch exception when adding a stream and the server appears to be offline
- Fixes #377
- Manual Tests in standalone and rhino 
> fix(desktopui): catch when adding stream offline

- Objects/Converters/ConverterRhinoGh/ConverterRhinoGh.Geometry.cs
- Objects/Objects/Geometry/Brep.cs
- Objects/Objects/Geometry/Surface.cs
two issues were at hand: 
- surfaces came through with wrong units (defaulted to meteres)
- vertices had no units
- Fixes unlogged issue
Received claire's amazing stadium in a variety of doc units in rhino. 
> fix(objects): fixes scaling issue related from brep serialisation optimisations

- ConnectorRhino/ConnectorRhino/UI/ConnectorBindingsRhino.cs
- Objects/Converters/ConverterRhinoGh/ConverterRhinoGh.BuiltElements.cs
- Objects/Converters/ConverterRhinoGh/ConverterRhinoGh.Utils.cs
- Objects/Converters/ConverterRhinoGh/ConverterRhinoGh.cs
- Objects/Objects/BuiltElements/View.cs
Adds named view conversions to Rhino:
- Added `Target` point prop to `View3d` Base class
- Added `Project Info` filter for Rhino to include named views, and included views in the `All` filter
- Uses a dispatcher for converting and baking named views since those operations require synchronous modifications to Rhino GUI. Otherwise causes issues if trying to bake with the Named Views Rhino panel open.
- Note: some named views have a different zoom after converting to native, though all properties match the original view. This is not dependent on projection type. Annoying but not essential to fix, just requires user to adjust zoom on the view
Fixes #390 
- Manual Tests: Sent a few models with named views from Rhino to Rhino, and …
> feat(rhino):  named view conversions

- ConnectorGrasshopper/ConnectorGrasshopper/Accounts/Accounts.ListAccounts.cs
- Fixes #385 
Originally, the account list was only refreshed upon node creation, and when user requested it by "right-clicking" the node. This caused other users to see the _node creator's_ account list, instead of their own.
Now, the list will be refreshed every time the account list is **added to a document**, and a fallback value has been added at index 0 of the list as `No account selected` to revert to it when necessary.
It also prevents the "default account" from being selected as last resort, as this could cause confusion to users.
- Creating new account nodes will automatically select the default account.
- Upon opening a document, the previously selected account should be …
> GH: Fix private data issue in Account List node

- ConnectorRhino/ConnectorRhino/UI/ConnectorBindingsRhino.cs
Tries to convert the displayMesh or displayValue if it exists and the Base conversion is not supported. Also includes fix for dangling issue (failure to bake "bad" geometry) by adding a warning and no longer creating layers on failure.
- Fixes #442 
- Fixes #340 
- Manual Tests: received sample architecture file from Revit
> fix(rhino): converts display mesh for builtelements

- Objects/Converters/ConverterRhinoGh/ConverterRhinoGh.Geometry.cs
- Objects/Converters/ConverterRhinoGh/ConverterRhinoGh.cs
- Objects/Objects/Geometry/Pointcloud.cs
- Objects/Objects/Objects.csproj
Adds a `Pointcloud` class to Objects. 
- Based on researching cad, unity, unreal, three.js, and PCL, current implementation includes points (all), colors (all), and sizes ( three.js, unity, unreal). Autocad api does not support pointcloud creation, and afaik neither does Revit. Ignores the ordered/unordered categorization from PCL for now.
Adds `Pointcloud` conversions for RhinoGh converter.
- Conversion adds a custom prop for point normals
Includes minor refactoring, removes unnecessary double array to point helper methods in the RhinoGh converter.
Fixes #367
Fixes #338 
- Manual Tests: pointcloud conversions to/from Rhino https://latest.speckle.dev/streams/dc5e51ffd4/commits/e387efa5a6
> feat(objects,rhino): added pointcloud  and pointcloud conversions

- ConnectorRevit/ConnectorRevit/Revit/ErrorEater.cs
Example problematic stream [here](https://latest.speckle.dev/streams/27bcb1c57b).
This issue is being laid to rest for now. All I've done is improve the error message so the user knows what is likely the problem (units).
- Fixes #299 
**log:**
Tried subtransactions as per ADN's suggestion, but found out that failures are _not_ processed when committing subtransactions - the event isn't fired until the parent transaction is committed. This means wrapping all element conversions in subtransactions and rolling back the ones that failed isn't an option.
Another thing you can do is collect the element ids for the failing elements, roll back the whole commit, then re-do the transaction without those elements. However, after discussing w teo we decided this was not ideal as 1. element ids will …
> refactor(revit): better failure warning

- All.sln
- ConnectorAutocadCivil/ConnectorAutocad2021/ConnectorAutocad2021.csproj
- ConnectorAutocadCivil/ConnectorAutocad2022/ConnectorAutocad2022.csproj
- ConnectorAutocadCivil/ConnectorAutocad2022/Properties/AssemblyInfo.cs
- ConnectorAutocadCivil/ConnectorAutocadCivil.sln
- ConnectorAutocadCivil/ConnectorAutocadCivil/UI/ConnectorBindingsAutocadCivil.cs
- ConnectorAutocadCivil/ConnectorAutocadCivil/Utils.cs
- ConnectorAutocadCivil/ConnectorCivil2021/ConnectorCivil2021.csproj
- ConnectorAutocadCivil/ConnectorCivil2022/ConnectorCivil2022.csproj
- ConnectorAutocadCivil/ConnectorCivil2022/Properties/AssemblyInfo.cs
- ConnectorAutocadCivil/README.md
- Objects/Converters/ConverterAutocadCivil/ConverterAutocad2022/ConverterAutocad2022.csproj
- Objects/Converters/ConverterAutocadCivil/ConverterAutocad2022/Properties/launchSettings.json
- Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.Civil.cs
- Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.cs
- Objects/Converters/ConverterAutocadCivil/ConverterCivil2022/ConverterCivil2022.csproj
- Objects/Converters/ConverterAutocadCivil/ConverterCivil2022/Properties/launchSettings.json
- Objects/Objects.sln
Adds 2022 projects for Autocad and Civil3D. Includes minor change of connector color method to be compatible in both 2021 and 2022 versions.
- Fixes #417 
- Manual Tests: sent and received standard geometry in 2022 connectors (autocad, civil, civil as autocad)
- Have already been updated
> feat(autocadcivil): add 2022 projects

- ConnectorAutocadCivil/ConnectorAutocad2021/ConnectorAutocad2021.csproj
- ConnectorAutocadCivil/ConnectorAutocad2022/ConnectorAutocad2022.csproj
- ConnectorAutocadCivil/ConnectorCivil2021/ConnectorCivil2021.csproj
- ConnectorAutocadCivil/ConnectorCivil2022/ConnectorCivil2022.csproj
- Objects/Converters/ConverterAutocadCivil/ConverterAutocad2021/ConverterAutocad2021.csproj
- Objects/Converters/ConverterAutocadCivil/ConverterAutocad2022/ConverterAutocad2022.csproj
- Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.Civil.cs
- Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.DBObjects.cs
- Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.Geometry.cs
- Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.cs
- Objects/Converters/ConverterAutocadCivil/ConverterCivil2021/ConverterCivil2021.csproj
- Objects/Converters/ConverterAutocadCivil/ConverterCivil2022/ConverterCivil2022.csproj
- Objects/Converters/ConverterRhinoGh/ConverterRhinoGh.Geometry.cs
- Objects/Objects/Geometry/Brep.cs
Adds TinSurface, GridSurface, Alignment, Profile, Structure, and Pipe conversions to Speckle.
All are sent as Meshes or Curves with attached props.
- Fixes #439 
- Manual Tests: sending elements from autocad to rhino, checking for previous functionality by sending & receiving standard test file geometry
> feat(acad civil): additional conversions

- Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.DBObjects.cs
- Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.cs
- Objects/Converters/ConverterRhinoGh/ConverterRhinoGh.Other.cs
- Objects/Objects/Geometry/Polyline.cs
Adds Nested Block conversions for autocad and rhino.
Also includes a minor polyline fix in autocad: polyline conversions were changed in rhino to add last point of closed polylines, had to update autocad conversions to match. Added comment in Objects Polyline class to prevent confusion in the future
- Part of #466 
- Manual Tests: sent autocad and rhino test files in all permutations between eachother.
**Note** During testing, Rhino->Rhino standard file had a trimmed surface edge error 👇
> feat(autocad,rhino): convert nested blocks

- Core/Core/Serialisation/BaseObjectSerializer.cs
- Core/Tests/SerializationTests.cs
- Fixes #379, but for real now (wraps up the saga of #490 and #489)
- Fixes an potentially dangerous bug whereby if you had a chunkable list prop followed by a non-chunkable list prop, the second list would get chunked too - and any subsequent lists. It happened because the streaming context would not get cleared of the chunkable flag. Now ensuring this is happening, and the test for empty list serialisation should catch this if it's going to happen again. 
Adds a new unit test which encodes the expected behaviour. 
> fix(core): resolves merge conflicts

- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertGeometry.cs
- Objects/Objects/Geometry/Brep.cs
- Objects/Objects/Geometry/Line.cs
Revit was crashing when sending Standard geometry. This was caused by missing domain props on various curves during surface conversion, creating a null exception in .ToList() methods in Objects.
- Fixes #494 
- Manual Tests: standard geometry file sending without crash now
> bug(revit): fix crash on sending directshapes

- ConnectorGrasshopper/ConnectorGrasshopper.sln
- ConnectorGrasshopper/ConnectorGrasshopper/ConnectorGrasshopper.csproj
- ConnectorGrasshopper/ConnectorGrasshopper/Conversion/Convert.ToNativeAsync.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Conversion/Convert.ToSpeckleAsync.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Extras/Utilities.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Objects/CreateSpeckleObjectAsync.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Objects/CreateSpeckleObjectByKeyValueAsync.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Objects/ExpandSpeckleObjectAsync.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Objects/ExtendSpeckleObjectAsync.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Objects/GetObjectValueByKeyAsync.cs
- Objects/Converters/ConverterRhinoGh/ConverterRhinoGh.cs
- Objects/Converters/ConverterRhinoGh/ConverterRhinoGh.csproj
Fixes testing issues:
- Added new GRASSHOPPER constant to distinguish between GH and Revit conversions.
- Prevented GH from converting DirectShapes, ModelCurves, Blocks and Views, which are not supported or would cause loss of data.
- Added conversion error reporting to conversion nodes. It was only reporting big fails.
- Added catch to `TryConvertItem` to prevent it from going 💥
- Manual Tests (please write what did you do?): This issues where caught when doing the test for release 2.1.12, testing was done manually receiving from different apps.
> GH: 2.1.12 testing fixes

- ConnectorGrasshopper/ConnectorGrasshopper.sln
- Objects/Converters/ConverterRhinoGh/ConverterRhinoGh.cs
Removes `GRASSHOPPER` preprocessor directive for now.
> fix(gh): Removed preprocessor directives!

- Core/Core/Credentials/StreamWrapper.cs
Fixed the parsing logic to account for `/` characters in the branch name, such as: 
https://latest.speckle.dev/streams/c544db35f5/branches/1%20standard%20geometry%20%2F%20from%20rhino
**WARNING**: Tests were passing in Core but failing in NetFramework due to a mismatch in the `Uri` class in `System`.
> Core: Fix Streamwrapper url parsing

- DesktopUI/DesktopUI/Streams/StreamCreateDialogViewModel.cs
in stream create dialog:
refreshing the accounts when toggling the accounts dropdown was
deselecting the selected acct. resetting it will always refresh the ui
which is an unpleasant experience, so i've opted to just take it out.
we have a refresh button and in theory the accts should reload anyway
if you close and reopen the dialog.
closes #474
also no acct issue here shouldn't crash anymore thanks to #480
> fix(desktopui): don't reload accts on toggle

- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertDuct.cs
not sure why this disappeared, but it's back now
> fix(revit): put display mesh back in ducts

- ConnectorAutocadCivil/ConnectorAutocadCivil/UI/ConnectorBindingsAutocadCivil.cs
- ConnectorAutocadCivil/ConnectorAutocadCivil/Utils.cs
- Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.DBObjects.cs
- Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.Geometry.cs
- Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.cs
- Objects/Converters/ConverterRhinoGh/ConverterRhinoGh.Geometry.cs
Two fixes: 
Large arcs where not being correctly converted from acad to rhino due to differing angle conventions. Added alternative method in Rhino to create an arc from start, end, and midpoint in the case of failure to convert with existing method.
Manually imported dwgs in Autocad appear correct in modelspace, but polycurve segments may not be all aligned in the same direction resulting in incorrect conversion when sent to speckle. Now the autocad converter contains a segment direction check.
- Fixes #504 
- Manual Tests: sent standard geo file back and forth
> fix(autocad/rhino): arc and polycurve conversions fixes

- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/Units.cs
Adds support for:
- feet and fractional inches
- fractional inches
Note: did not require any changes in core - all internal unit conversions are thankfully handled by revit
- Fixes #482
- Manual Tests: sent revit models in above units and tested against the same models sent in meters 
> fix(revit): add support for feet and fractional inches

- Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.DBObjects.cs
- Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.cs
Sends surfaces to Speckle as meshes, since breps are not yet supported in autocad.
Also adds region conversions to mesh.
- Fixes #425 
- Manual Tests: sending standard geometry files from autocad 
> feat(autocad): handles surface to speckle conversions as mesh

- Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.Civil.cs
- Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.cs
Adds corridor to speckle conversion: sends the corridor's baseline featurelines/alignments as a list along with station info. Could *not* extract baseline curve directly, might try further testing with baseline splines.
- Fixes #534 
- Manual Tests: sent corridors from civil3d to rhino
> feat(civil3d): adds corridor conversions

- ConnectorGrasshopper/ConnectorGrasshopper/ConnectorGrasshopper.csproj
- ConnectorRhino/ConnectorRhino/ConnectorRhino.csproj
- Objects/Converters/ConverterRhinoGh/ConverterRhinoGh.csproj
- Fixes #541 
- nuget version downgrade
- Manual Tests: Manually built all affected projects and ran several commands to ensure rhino/gh launched properly
> Rhino/GH: Downgrade nugets to 6.28

- Objects/Converters/ConverterRevit/ConverterRevitShared/ConversionUtils.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertColumn.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertOpening.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertWall.cs
- Objects/Converters/ConverterRevit/ConverterRevitTests/BeamTests.cs
- Objects/Converters/ConverterRevit/ConverterRevitTests/ColumnTests.cs
- Objects/Converters/ConverterRevit/ConverterRevitTests/SpeckleConversionTest.cs
- unconnected shaft openings are getting the correct height (previously we were not passing units, so this was not getting scaled)
- slanted columns checked if curve driven before trying to mess with endpoints 
- errors no longer thrown on receive of slanted columns
- support [stacked walls](https://latest.speckle.dev/streams/0c6ad366c4/objects/c07a424ffad5837c5bc927fc3eee9046)
- previously, stacked wall members were not being converted so nothing showed up in the viewer and receiving back would just be a regular wall
- now wall members are added to `elements` list of host wall
- remove unsupported exception for hosted elements
- exclude nonconverted nested elements in tests 
- was throwing errors bc flat list of elements was longer than the list of converted elements
- smol typo fixes …
> fix(revit): resolve failing unit tests

- Objects/Converters/ConverterRevit/ConverterRevitShared/ConversionUtils.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertGeometry.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertView.cs
Revit XYZ class can be points or vectors: in the case of a transformed base point (translation, angle from north), the ToInternalCoordinates() and ToExternalCoordinates() was working properly but not for vectors. This was resulting in faulty view conversions where camera location was correct but direction was incorrect.
1.  Added TotalTransform property to BetterBasePoint class
2.  Modified Point and Vector conversions to use TotalTransform
3.  Fixed View conversions to use Point and Vector conversions for all props
- Fixes #559
- Manual Tests: sent sample arch and structure file from Revit with views, some light additional testing with current test streams 
> fix(revit): better base point transformation for XYZ vectors, improved views

- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertCurves.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertGeometry.cs
[the offending curves](https://latest.speckle.dev/streams/0c6ad366c4/commits/2290a4a5c1)
helps deal with the following issues:
- revit api doesn't support closed periodic curves
(ty claire for help, boo autodesk for sucking)
- non-planar nurbs aren't supported
fixes #497
- Unit/Integration Tests: all xunit tests pass with this + the revit fixes PR that is pending (#556)
- Manual Test: receive standard geometry file from revit
> fix(revit): use displayvalue for failed curves

- Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.DBObjects.cs
- Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.Geometry.cs
- Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.cs
- Objects/Converters/ConverterRhinoGh/ConverterRhinoGh.Other.cs
- Objects/Converters/ConverterRhinoGh/ConverterRhinoGh.cs
- Objects/Objects/Other/Hatch.cs
Adds hatch conversions to Rhino and Autocad:
- Hatch base class added to Objects: includes curves, pattern name, scale, and rotation
- Hatch conversions added to rhino and autocad converters
- If hatch name isn't found, will use default solid hatch instead
- Fixes #551 
- Manual Tests: sent standard test files between rhino and autocad
> feat(rhino & acad): adds hatch conversions

- Core/Core/Logging/Log.cs
Caused by incorrect call order. First should be Init, followed by ConfigureScope.
Fixes specklesystems/admin#109
> fix(core): Sentry now properly records user id's

- DesktopUI/DesktopUI/RootView.xaml
- DesktopUI/DesktopUI/RootViewModel.cs
- DesktopUI/DesktopUI/Settings/SettingsView.xaml
it's back 🥳
- Fixes #584 
- Manual Tests in Revit & Rhino
> feat(desktopui): the pin is back baby! 📌📍

- Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/Converter.AutocadCivil.Utils.cs
- Objects/Converters/ConverterDynamo/ConverterDynamoShared/ConverterDynamo.Units.Revit.cs
- Objects/Converters/ConverterDynamo/ConverterDynamoShared/ConverterDynamo.Units.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/Units.cs
- Objects/Converters/ConverterRhinoGh/ConverterRhinoGh.Utils.cs
This should be a pretty innocuous change - just changing the error message you get in the connectors when the unit system isn't supported.
Here the units are none so it's just "" lol. Didn't really wanna add another case for this to minimise adding repeated code, but can do if desired. imho tho, "" conveys that there are no units p clearly.
- closes #601
- Bug fix 
- Manual Tests in revit and rhino
> feat(logging): print unsupported units in errormsg

- Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.DBObjects.cs
Previously resulted in application crash if attempting to send a block from external reference
> added handler for blocks from external references

- ConnectorGrasshopper/ConnectorGrasshopper/ConnectorGrasshopper.csproj
- ConnectorGrasshopper/ConnectorGrasshopper/Extras/DebounceDispatcher.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Objects/CreateSpeckleObjectTaskComponent.cs
Create speckle object node was not properly recomputing when the input name was changed.
Added `DebounceDispatcher` for dependency free `Debounce`. Needed to prevent us from expiring the solution on every character typed.
Current behaviour is:
- If you start writing on an input text field, `ExpireSolution` call will be debounced until no call has been invoked for 400ms.
- If you press enter, this is considered a `NickName Accepted` event, and we'll recompute directly, no debouncing.
> fix(gh): CSO not recomputing on input rename

- ConnectorRhino/ConnectorRhino/UI/ConnectorBindingsRhino.cs
Adds applicationId to schemabuilder objects before send. This is for updating functionality in Revit.
- Fixes #619
- Manual Tests
> RH: Add applicationId to Speckle Schema objects

- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertView.cs
Adds the target prop back into Revit views. Testing on sample files seem to be *more or less* comparable to views sent without target, when received in Rhino.
Helps resolve part of [https://github.com/specklesystems/speckle-server/issues/328](https://github.com/specklesystems/speckle-server/issues/328), as views are now registered in the viewer, but their id instead of the name is being used for display. See:
[https://speckle.xyz/streams/5dfbeb49c9/commits/dc5c07302f](https://speckle.xyz/streams/5dfbeb49c9/commits/dc5c07302f)
- Manual Tests : views sent back and forth from revit arch sample file 
> Added target prop back into revit views

- Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.Civil.cs
- Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.DBObjects.cs
- Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.Geometry.cs
- Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.cs
- Objects/Converters/ConverterRhinoGh/ConverterRhinoGh.cs
- Objects/Objects/BuiltElements/Alignment.cs
- Objects/Objects/BuiltElements/Station.cs
Adds Station and Alignment BuiltElements base classes to the Objects kit. Also updates Alignment conversions in the C3D connector. Includes a bug fix where CurveToSpeckle method was not differentiating between line-only polylines and polylines with arc segments.
- Fixes #599 
- Manual Tests: tested sending alignments from C3D and receiving them in grasshopper, dynamo, rhino, autocad. Receiving in Revit currently not supported
> C3D: add alignments and stations to Objects Kit

- ConnectorAutocadCivil/ConnectorAutocadCivil/UI/ConnectorBindingsAutocadCivil.cs
- ConnectorAutocadCivil/ConnectorAutocadCivil/Utils.cs
- Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/Converter.AutocadCivil.Utils.cs
- Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.DBObjects.cs
Fixed crash issue when trying to receive block definitions with invalid chars. Also includes minor improvement for determining line styles while sending.
- Manual Tests
> AcadCivil: block names with invalid chars causes app to crash when receiving

- Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.DBObjects.cs
- Objects/Converters/ConverterRhinoGh/ConverterRhinoGh.cs
Adds a Curve.TryGetEllipse() method to Rhino converter so that ellipses are now sent as ellipses rather than Objects.Geometry.Curve
Also includes a bug fix in AutoCAD to send the correct ellipse plane when converting rotated ellipses from rhino
- Fixes #646
- Manual Tests: sent and received various orientation ellipses between rhino, autocad, and checked on receive in Revit
> RH: send ellipses as Objects.Geometry.Ellipse instead of Curve

- Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.Civil.cs
- Objects/Objects/BuiltElements/Alignment.cs
Alignment base class was previously using a list of arrays for the station equation property. This was causing deserialization issues in core, so temporarily fixing by using a flattened list instead.
- Manual Tests
> Civil: alignments base class using flat station equation list

- Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.Civil.cs
- Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.Geometry.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertPipe.cs
- Objects/Objects/BuiltElements/Pipe.cs
- Objects/Objects/BuiltElements/Structure.cs
Modified pipe base class (originally line based) to accommodate Civil3D pipes (line or curve based).
Added structure base class.
Changed pipe and structure conversions in Civil3D to return pipe and structure base classes.
Modified pipe conversions in Revit to only convert line based pipes
- Fixes #640 
- Manual Tests: sent pipes and structures out of civil, received pipes in Revit
> Civil3D: added pipe and structure conversions

- ConnectorGrasshopper/ConnectorGrasshopper/Extras/Utilities.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Ops/Operations.SendComponent.cs
Fixes #580
This fixes an error when optional arguments existed but had no data (or were null) were making the sender get stuck and throw a 'Null Exception'. Right now, it will ignore any non-set properties (just like the 'Expand Speckle Object'  works, but I'm aware this may not sit well with some users.
We've had other petitions to keep the null items when being sent to the server, so I'm not sure if we should tackle this now, or in a separate issue.
Bonus: Better error handling when sender performs conversions.
> fix(gh): Empty optional arguments no longer block sender

- Objects/Converters/ConverterRevit/ConverterRevitShared/ConversionUtils.cs
Retrieves the proper base point coordinates and applies just a translation transform to all ToInternal and ToExternal conversions.
Behaviorally, this should mean that all geometry from Revit to Rhino should arrive *aligned to Rhino's xy axis and origin*, and all geometry modelled in Rhino should arrive *aligned to Revit's project base point and project north*
- Fixes #659 
- Manual Tests : revit sample arch file and some basic files with different combinations of survey and base point mutations.
> Revit: better base point v2

- ConnectorGrasshopper/ConnectorGrasshopper/Objects/SelectKitTaskCapableComponentBase.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Ops/Operations.ReceiveComponent.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Ops/Operations.ReceiveComponentSync.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Ops/Operations.ReceiveLocalComponent.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Ops/Operations.SendComponent.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Ops/Operations.SendComponentSync.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Ops/Operations.SendLocalComponent.cs
Fixes #690
As reported in the forum thread linked in #686, when no kit was found (due to corrupted install, missing dll or any other reason), the `Send` and `Receive` nodes will display an unhelpful message, and also **cannot be deleted from the canvas**
There was an error being thrown in the `Read` method of the `Send/Receive` nodes that was preventing proper deletion.
They also now prevent further execution and report a clearer error message.
> GH (fix): Handle "no kit found" scenario gracefully

- Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.DBObjects.cs
- Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.cs
Added conversion method to handle polycurves with spline segments: Autocad will convert these to splines.
**NOTE** this method can be used to handle 3d polycurves with nonlinear segments, but the Polycurve base class needs a `IsPlanar` property to make this reasonable to implement
- Fixes #592
> Autocad: polycurve to spline conversion

- ConnectorAutocadCivil/ConnectorAutocadCivil/UI/ConnectorBindingsAutocadCivil.cs
- Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/Converter.AutocadCivil.Utils.cs
- Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.DBObjects.cs
- Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.cs
Enables mesh to native conversion due to **running all AutoCAD API calls on the main thread**. Previously this was causing errors with large meshes because it was necessary to add the mesh to modelspace before adding vertices, faces, etc.
Now all calls to API (all conversions) run on the main thread.
Also includes a minor hatch boundary bug found during testing.
- Fixes #680 
- Manual Tests: sent and received test files between autocad and rhino
> fix(acad): finally adding mesh to native conversion

- ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/UI/ConnectorBindingsRhino.cs
- Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.Geometry.cs
Fixes invalid polycurves when converting to native, due to very small segment endpoint mismatches from arc to native conversions. Figured out that **arcs should be constructed using midpoint, startpoint, and endpoint instead of angles** since model angle tolerance (used for angles) can be different from model space tolerance (used for points).
- Fixes #645 
- Manual Tests
> fix(rhino): invalid polycurve due to segment endpoint tolerance

- ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/UI/ConnectorBindingsRhino.cs
- Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.Other.cs
- Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.Utils.cs
- Objects/Objects/Other/Block.cs
-No longer deletes commit layer before receiving commit.
-Discovered that sketchup sends block instance transforms where the translation vector is not necessarily [x,y,z,1]: the last value can be a non-1 divisor value. Rhino is now handling division in ToNative conversions.
-Discovered that sketchup sends block instance transforms where the last row is not necessarily the identity row: it's sometimes [0,0,0,0] instead of [0,0,0,1]. This usually indicates vector transform (not a point transform), **need to figure out why sketchup is sending these**. For now, rhino is changing the last row from [x,y,z,0] to [x,y,z,1] which seems to fix it for now.
**NOTE**
When testing, Sketchup > Rhino and Sketchup > Acad work well.
Sketchup > Acad > Rhino works well.
Sketchup > Rhino > Acad has a few …
> bug(rhino): handle block transforms with sketchup conventions

- Objects/Objects/Geometry/Brep.cs
- Fixes #810 
The root of the issue was that in the new deserialiser, any objects with the same `speckle id` will become references to the same object in C#. This caused classes like `BrepLoop` or `BrepEdge` to deserialize with an incorrect Brep reference, as the exact values of these classes can coincide, but they should not be the same reference.
- Bug fix
- Manual Tests: Tested receiving multiple objects of the same geometry in different postions. Can no longer reproduce the error after this fix.
> fix(objects): Brep OnDeserialize properly sets it's circular references

- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertAdaptiveComponent.cs
Fixes adaptive components not being received back into Revit
The family name was getting set as `type` on `ToSpeckle` but the property being checked in `ToNative` is `family`.
- 
- xUnittRevit test for AC now pass (as well as manual tests with the Revit Test Stream
> fix(revit): set family (not type) on `ToSpeckle`

- ConnectorAutocadCivil/ConnectorAutocadCivil/UI/ConnectorBindingsAutocadCivil.cs
- Core/Core/Kits/Units.cs
- Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/Converter.AutocadCivil.Utils.cs
Adds support for US Survey units: inches, feet, yards, miles
Approximates them to International inches, feet, yards, miles. 
For more info on the difference: https://www.pobonline.com/articles/98788-us-survey-feet-versus-international-feet
lol
- Fixes #827 
Also removes units from the commit obj in the acad/c3d connector - this seems to align with other connectors. Can reinstate if consensus is reached on whether commit objs should have units.
- Manual Tests
> feat(acad/c3d): US Survey unit support

- ConnectorGrasshopper/ConnectorGrasshopper/Objects/ExpandSpeckleObjectTaskComponent.cs
- Fixes #629 
`ExpandSpeckleObject` node now detects if there has been a single parameter rename. If so, we'll skip the entire process of generating outputs and just rename the corresponding parameter.
I also skipped sorting to prevent the outputs from reorganising while a user is renaming. They would be re-sorted on the next solution regardless.
Same tests as in the original issue:
- Rename a single input
- Change object to expand to a completely different one (no shared inputs) should preserve empty connections.
> GH: Fix confusing behaviour in ExpandSpeckleObject

- ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/UI/ConnectorBindingsRhino.cs
- ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/UI/ConnectorBindingsRhino2.cs
- Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.Geometry.cs
- Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.cs
As part of 2.2.4 beta release testing for Rhino:
- adds DUI2 button to rhino speckle toolbar
- fixes DUI2 crashing rhino when sending named views via filter
- refactored connector sending for old and new UI bindings for better error handling
- added extrusion rhino BIM handling to main converter logic
- Manual Tests: sent and received standard and rhino bim test files
> fix(rhino): dui2 issues and rhino bim extrusions

- ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/UI/ConnectorBindingsRhino.cs
Rhino: Deletes layers and blocks from previous receive if receiving the same commit again
- Manual Tests
> fix(rhino): added block and layer purge before receive

- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertAdaptiveComponent.cs
tests look for `type` not `family` so need to set that instead
in order to pass
- continues to fix the adaptive component issue that came up in testing
- unit and manual tests
> fix(revit): pass adaptive component test

- ConnectorDynamo/ConnectorDynamo/SendNode/Send.cs
- ConnectorDynamo/ConnectorDynamoFunctions/BatchConverter.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Extras/Utilities.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Objects/CreateSpeckleObjectTaskComponent.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Objects/Deprecated/CreateSpeckleObjectAsync.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Objects/Deprecated/ExtendSpeckleObjectAsync.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Objects/ExpandSpeckleObjectTaskComponent.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Objects/ExtendSpeckleObjectTaskComponent.cs
- Fixes #491 🥳  
Null values are now allowed everywhere in GH and Dyn.
Tested sending nulls along with other objects to/from Grasshopper/Dynamo in all directions. Null values got properly serialised and deserialised on each program.
Also ensured that receiving in DUI connectors like Rhino/Revit did not break anything.
- No updates needed as there is no reference of this anywhere in the docs.
> Gh/Dyn: `null` value alignment

- Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.Other.cs
- Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.Other.cs
- Objects/Objects/Other/Block.cs
Deprecates the `insertionPoint` class prop by:
- adding an obsolete flag on the prop
- adding a `GetInsertionPoint()` convenience method
- using the convenience method as the obsolete prop getter
- removing prop assignment in Acad and Rhino converters
- removing prop in Acad ToNative conversion
part of #746 
- Manual Tests: blocks to and from autocad
> fix(objects): deprecates insertion point from block instance class

- ConnectorAutocadCivil/ConnectorAutocadCivil/UI/ConnectorBindingsAutocadCivil.cs
- ConnectorAutocadCivil/ConnectorAutocadCivil/UI/ConnectorBindingsAutocadCivil2.cs
- ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/UI/ConnectorBindingsRhino.cs
- ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/UI/ConnectorBindingsRhino2.cs
- Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.Geometry.cs
- Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.Other.cs
- Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.Other.cs
- Objects/Objects/Other/Hatch.cs
- Adds `HatchLoop` class and 'HatchLoopType` enum to Objects. Makes `Hatch.curves` obsolete: shouldn't be a breaking change, but code in rhino and autocad converters should be updated after a few releases to no longer handle old hatches that only have the curves prop and no loops prop.
- Rhino now returns `Hatch[ ]` in `HatchToNative( )` conversion to handle autocad hatchs with multiple external curves
Part of #746
- Manual Tests : sent and received standard test file between acad and rhino, sent and received some blocks with hatches in acad and rhino
> fix(acad/rhino): better hatch handling

- ConnectorETABS/ConnectorETABS/Util/ConnectorETABSUtils.cs
- Objects/Converters/ConverterETABS/ConverterETABSShared/ConverterETABSShared.projitems
- Objects/Converters/ConverterETABS/ConverterETABSShared/ConverterETABSUtils.cs
- Objects/Converters/ConverterETABS/ConverterETABSShared/Partial Classes/Geometry/ConvertArea.cs
- Objects/Converters/ConverterETABS/ConverterETABSShared/Partial Classes/Results/ConvertResultSet2D.cs
- Objects/Converters/ConverterETABS/ConverterETABSShared/Partial Classes/Results/ConvertResults.cs
- Adds 2d results
- Adds local axis orientation to ConvertAreaToSpeckle
- Manual Tests - pushed results from ETABS to speckle
> ETABS 2d results

- Objects/Objects/Other/Block.cs
Previous convenience method was not multiplying transform and base pt correctly
- Manual Tests: autocad, revit tested
> Objects: correct block insertion point method

- Objects/Objects/Geometry/Mesh.cs
- Objects/Objects/Other/Block.cs
- Fixes issue with Mesh and Block conveniance properties from being serialised.
> Added json-ignore to computed properties in Objects

- ConnectorDynamo/ConnectorDynamo/CreateStreamNode/CreateStream.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Streams/StreamCreateComponent.cs
- Default to making streams private when they are created with the Dynamo and Gh connectors (since all other connectors, through DUI/DUI2, currently default to making streams private on creation)
- Manual Tests (created new streams with Dynamo and Gh connectors)
> Make streams private on their creation in Dynamo and Gh connectors

- ConnectorGrasshopper/ConnectorGrasshopper/Extras/Utilities.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Ops/Operations.ReceiveComponent.cs
This happens only when the commit is not from GH/Dynamo, or when conversions are disabled.
Fixes #643
> fix(gh): Adds remark bubble to remind user to expand an object

- ConnectorGrasshopper/ConnectorGrasshopper/Accounts/Accounts.AccountDetails.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Conversion/Convert.ToNativeAsync.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Conversion/Convert.ToSpeckleAsync.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Conversion/Serialisation.DeserializeObject.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Conversion/Serialisation.SerialiseObject.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Objects/CreateSpeckleObjectByKeyValueTaskComponent.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Objects/CreateSpeckleObjectTaskComponent.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Objects/ExpandSpeckleObjectTaskComponent.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Objects/ExtendSpeckleObjectByKeyValueTaskComponent.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Objects/ExtendSpeckleObjectTaskComponent.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Objects/GetObjectValueByKeyTaskComponent.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Ops/Operations.ReceiveComponent.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Ops/Operations.ReceiveComponentSync.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Ops/Operations.ReceiveLocalComponent.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Ops/Operations.SendComponent.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Ops/Operations.SendComponentSync.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Ops/Operations.SendLocalComponent.cs
- ConnectorGrasshopper/ConnectorGrasshopper/SchemaBuilder/CreateSchemaObject.cs
- ConnectorGrasshopper/ConnectorGrasshopper/SchemaBuilder/CreateSchemaObjectBase.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Streams/StreamCreateComponent.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Streams/StreamDetailsComponent.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Streams/StreamGetComponent.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Streams/StreamListComponent.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Streams/StreamUpdateComponent.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Transports/SendReceiveTransport.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Transports/Transports.Disk.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Transports/Transports.Memory.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Transports/Transports.Sqlite.cs
- Fixes #743
Moved tracking from "BeforeSolveInstance" to the actual function that does the work (depending on the component, that may be `SolveInstance` or the `DoWork` in the worker.
Tracker will only log when the node performs some operation, as opposed to the previous behaviour, that allowed for pages to be tracked when `F5` was pressed, even if the node had no inputs connected.
Set breakpoints on tracker lines and ensured they were:
- Never called twice in the same operation
- Never get called if the node does not perform an …
> GH: Reduce calls to `Tracker.TrackPageView`

- Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/Converter.AutocadCivil.Utils.cs
- Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.Other.cs
This was a blocker for Bilal's acad to revit workflow - the files he's using has dynamic blocks.
- Fixes #893
> fix(autocad): add block attributes as a dictionary

- Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.Civil.cs
- Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.Geometry.cs
- Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.cs
- Objects/Converters/ConverterDynamo/ConverterDynamoShared/ConverterDynamo.Geometry.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/ConverterRevit.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertCurves.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertGeometry.cs
- Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.BuiltElements.cs
- Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.cs
- Objects/Objects/BuiltElements/Alignment.cs
- Deprecates `baseCurve` prop and replaces with `curves` prop
- Adds `AlignmentToNative` conversions to Acad/C3D/rhino/revit
- Improves `AlignmentToSpeckle` conversion in C3D to include spiral segments
**Blocker** Arup's Bentley connectors aren't merged, waiting to improve OpenRoads Alignment conversions and test C3D <-> OpenRoads conversions until they are merged
- Fixes #788
- Manual Tests: sent and received Alignments between C3D and other applications. **Note** `AlignmentToNative` conversion in C3D segments deviate slightly from original despite having correct endpoints per segment. Need to be improved in the future. 
> Alignments: modifies class and adds ToNative conversions

- ConnectorDynamo/ConnectorDynamo/ViewNode/View.cs
- Core/Core/Credentials/StreamWrapper.cs
- Fixes #850
This did not affect end users at all, but devs (such as myself) would find it very confusing to get "Could not get stream" errors only to finally have it working in the end.
This was due to the validation checking first for the default account, and then for any account from that server. That first check would be unnecessary if the `ServerUrl` is already different from the `Account.serverInfo.url`
Added a quick check to ensure account and url are from the same server and throw and more appropriate error if it doesn't.
Discussed this with @izzylis and will open an issue in `specklepy` to keep the `StreamWrapper` behaviour aligned.
- Breaking change (fix or feature …
> Fix confusing error in StreamWrapper.ValidateWithAccount()

- ConnectorGrasshopper/ConnectorGrasshopper/SchemaBuilder/SchemaBuilderGen.cs
- ConnectorGrasshopper/ConnectorGrasshopper/SchemaBuilder/SchemaBuilderGen.tt
- Core/Core/Kits/Attributes.cs
- Core/Core/Models/Base.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertFreeformElement.cs
- Objects/Objects/BuiltElements/Revit/FreeformElement.cs
- Objects/Objects/BuiltElements/Roof.cs
- Fixes #859
Adds support for `baseGeometries` instead of a single `baseGeometry`.
The prior property has been kept as a setter-only prop for backwards compatibility purposes.
There's also a new `SchemaDeprecated` attribute to flag schemas that should be generated as GH nodes, but hidden from the user, as there should be a new version of them if possible. This is with the intention of removing them in an unspecified amount of time in the future.
Sent simple FreeformElements with multiple geometries to Gh->Gh and Gh->Revit without any issues.
Made sure previous format with `baseGeometry` still deserializes correctly into new `baseGeometries` list.
- No updates needed as they are not …
> Freeform Elements support for multiple geometries.

- ConnectorAutocadCivil/ConnectorAutocadCivil/UI/ConnectorBindingsAutocadCivil.cs
- Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.Other.cs
Nested branches introduce a "/" into block names when receiving, causing acad to fail.
Also fixes small issue when re-receiving after a failed receive, where the document userdata already contains a commit key
- Fixes #911
> fix(acad): nested branches causing receiving blocks to fail

- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertAdaptiveComponent.cs
- Objects/Converters/ConverterRevit/ConverterRevitTests/SpeckleConversionTest.cs
Fixes error reported in the Forum where revit could not find the provided adaptive family.
> fix(rvt): Fixed Adaptive Family conversion + tests

- Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.Other.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/ConversionUtils.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertBlock.cs
- Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.Other.cs
- Objects/Objects/Geometry/Brep.cs
- Objects/Objects/Geometry/ControlPoint.cs
- Objects/Objects/Geometry/Curve.cs
- Objects/Objects/Geometry/Line.cs
- Objects/Objects/Geometry/Mesh.cs
- Objects/Objects/Geometry/Plane.cs
- Objects/Objects/Geometry/Point.cs
- Objects/Objects/Geometry/Pointcloud.cs
- Objects/Objects/Geometry/Polycurve.cs
- Objects/Objects/Geometry/Polyline.cs
- Objects/Objects/Geometry/Surface.cs
- Objects/Objects/Geometry/Vector.cs
- Objects/Objects/Interfaces.cs
- Objects/Objects/Other/Block.cs
- Objects/Objects/Other/Transform.cs
This is a rework of Blocks to open the door for support in applications that don't properly support them (eg Revit).
TLDR: `Transform` is now a speckle object rather than a list of doubles representing the transform matrix. It allows you to apply the transform to points and vectors. Speckle objects can now implement `ITransformable` which involves writing a `TransformTo()` method. Meshes and some `ICurves` have been implemented as `ITransformable` and the Revit connector now supports them. The Revit connector does not truly support the concept of blocks, so new Groups are created for each `BlockInstance` with the transform baked into the source geometry. Note that this is p slow and could use optimisation.
- Fixes #608 indirectly
---
A new class `Objects.Other.Transform` as well as the …
> `Block` and `Transform` reworks

- ConnectorGrasshopper/ConnectorGrasshopper/Loader.cs
- ConnectorGrasshopper/ConnectorGrasshopper/SchemaBuilder/CreateSchemaObjectBase.cs
- ConnectorGrasshopper/ConnectorGrasshopper/SpeckleGHSettings.cs
Out of pure boredom this Sunday, I implemented a switch to disable specific Speckle BIM and Structural tabs when the user does not have the need for them.
Changing this settings requires a full GH restart to take effect.
> bonus(gh): Added settings to hide unwanted tabs

- .circleci/config.yml
Removes the trailing `-beta` at the end of the build version to comply with Semver format
> Semver: Remove `-beta` ending from build version

- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertDirectShape.cs
Fixes issue when receiving DirectShapes made of Solids from Revit into any other application.
> fix(rvt): Missing units in directshape solidToMesh conversion

- Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.Geometry.cs
- Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.Geometry.cs
- Objects/Objects/Utils/MeshTriangulationHelper.cs
- Objects/Tests/Utils/MeshTriangulationHelperTests.cs
Related to:  #780
Objects:
- Adds Triangulation functions for triangulating n-gon faces in connectors with no native support for n-gons or n-gon triangulation (functions are encapsulated in [`Objects.Utils.MeshTriangulationHelper`](https://github.com/specklesystems/speckle-sharp/blob/jrm/triangulation/Objects/Objects/Utils/MeshTriangulationHelper.cs))
AutoCAD:
- Fixes issue with receiving n-gons causing stream to fail
- Adds support for receiving n-gon faces. (using aforementioned triangulation)
- Adds support for receiving faces with 3/4 cardinality indicators. 
Rhino:
- Switched N-gon triangulation to now use `MeshTriangulationHelper` as it is computationally faster and more consistent than the previous method of using `RH.Mesh.CreateFromClosedPolyline`
Unity:
- Not part of this PR (or …
> N-gon Triangulation

- ConnectorGrasshopper/ConnectorGrasshopper/SchemaBuilder/SchemaBuilderGen.cs
- ConnectorRevit/ConnectorRevit/UI/ConnectorBindingsRevit2/ConnectorBindingsRevit2.Send.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Categories.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/ConversionUtils.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/ConverterRevit.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertDuct.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertGeometry.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertPipe.cs
- Objects/Objects/BuiltElements/Duct.cs
- Objects/Objects/BuiltElements/Pipe.cs
Adds `FlexDuct` and `FlexPipe` conversions to Revit. Includes the following changes:
- Generally, FlexDuct and FlexPipe elements inherit from `MEPCurve` which contains a set of `XYZ` points and a start/end tangent. To support non-line based ducts and pipes, we are now capturing the point information as a generated `Polyline` in `ToSpeckle` conversions.
- `Objects`: change in `Duct` class property `Line baseLine` to `ICurve baseCurve`. The old property has been marked as deprecated and backwards compatibility with generated GH components preserved. This now aligns the Duct and Pipe classes to enable support for polyline base curves.
- Objects`: new `RevitFlexPipe` and `RevitFlexDuct` classes which inherit from `RevitPipe` and `RevitDuct`
- Fixes #920
- New feature (non-breaking change …
> feat(revit): add flex duct and flex pipe conversions

- ConnectorAutocadCivil/ConnectorAutocadCivil/UI/ConnectorBindingsAutocadCivil2.cs
- ConnectorAutocadCivil/ConnectorAutocadCivil/Utils.cs
- Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/Converter.AutocadCivil.Utils.cs
- Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.Civil.cs
- Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.cs
Discovered a few bugs that were resulting in crashes in Civil3d:
- Some civil3d docs have `Units.Undefined` returned from the Doc.Insunits property, needed to add a aec.interop class to retrieve valid units from the test file (used for civil files only).
- Featurelines with a site were attaching `ObjectId` to the base property rather than the string, this is fixed
- The file contained invisible null `Solids`, may have been a result from manual conversion of civil elements to 3d solids. Added a `Solid.IsNull` check to solid conversions.
- Fixes #996 
- Manual Tests:[https://speckle.xyz/streams/bff55266ce/commits/9a1bc290d1?c=%5B1911513.56621,562366.17512,753.00251,1911579.97933,562925.48915,-29.93577,0,1%5D]( …
> fix(civil3d): crash issues from community-contributed civil file

- ConnectorGrasshopper/ConnectorGrasshopper/Objects/GetObjectValueByKeyTaskComponent.cs
- ConnectorGrasshopper/ConnectorGrasshopper/SchemaBuilder/CreateSchemaObject.cs
- Fixes #980
- Fixes #979
Nodes were assuming that all props that are lists will be `IList<object>`, It seems that wasn't generic enough so now we're using IEnumerable, so people can shove in whatever they want, as long as it can be enumerated.
Also, many thanks to the forum user who reported it and suggested a fix! 🙌🏼 
Added support for `double[]` and other types of arrays by changing our implementation to use `IEnumerable` instead of `IList<object>``
Should be backwards compatible all the way.
Made sure that old classes that used lists still work.
Made sure that arrays also work now.
> Improve support for non `IList<object>` props.

- ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/UI/ConnectorBindingsRhino2.cs
- Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.Other.cs
- Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.cs
On receiving, moves the display style property assignment from the connector to the converter.
Adds a `DisplayStyleToNative` method to the converter
- Manual Tests: sent and received from rhino
> refactor(rhino): moved displaystyle assignment to converter

- ConnectorGrasshopper/ConnectorGrasshopper/Extras/Utilities.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Ops/Operations.VariableInputReceiveComponent.cs
- ConnectorGrasshopper/ConnectorGrasshopper/SchemaBuilder/SchemaBuilderGen.cs
The new `Variable Output Receive` component was defaulting to always expanding the output.
This was not ideal when the commit object had too many keys to handle.
- Tested both functionalities (expand and no-expand) with new nodes and existing ones.
> GH: Adds right-click option to disable automatic expand in receive node

- ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/UI/ConnectorBindingsRhino.cs
- ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/UI/ConnectorBindingsRhino2.cs
- Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.Other.cs
- Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.Utils.cs
- Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.cs
- Added Render material conversion ToNative.
- If incoming geometry has no `displayStyle` property, we will try and use the `renderMaterial`'s diffuse colour.
- Fixes #1030 
- Receiving the [PBR test stream](https://latest.speckle.dev/streams/2158263a8f) 
- The rhino docs don't currently mention render materials at all.
> Rhino: Render material

- ConnectorAutocadCivil/ConnectorAutocadCivil/UI/ConnectorBindingsAutocadCivil2.cs
- ConnectorAutocadCivil/ConnectorAutocadCivil/Utils.cs
- Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/Converter.AutocadCivil.Utils.cs
- Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.Other.cs
- Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.cs
-added displaystyle conversions ToSpeckle and ToNative
-applies displaystyle with rendermaterial as fallback to block definitions
Part of release testing
> acad: displaystyle refactor

- ConnectorGrasshopper/ConnectorGrasshopper/Extras/GenericAccessParam.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Extras/Utilities.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Objects/ExpandSpeckleObjectTaskComponent.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Ops/Operations.ReceiveComponent.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Ops/Operations.SendComponent.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Ops/Operations.VariableInputReceiveComponent.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Ops/Operations.VariableInputSendComponent.cs
Grasshopper part of https://github.com/specklesystems/admin/issues/246
- Adds single rename handling for Variable Input Receiver
- Hides old Send/Receive nodes
- Fixes bug where Variable Input Sender would not sync name and nickname (causing wrong prop names when sending)
- Fixes Expand Speckle Object so that it shows detached props with state tag instead.
Tested manually each case to ensure all input/outputs were being updated properly. Also tested against the old send/receive nodes to ensure backwards compatibility with older commits.
> GH: 2.4.0 Release fixes

- ConnectorGrasshopper/ConnectorGrasshopper/Extras/GenericAccessParam.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Extras/SendReceiveDataParam.cs
- Adds new feature to extract a parameter from an output node (this is possible by default in Grasshopper inputs, but not outputs for some reason).
- This allows the user to extract the param name and data without having to modify the output names (which come from the expanded/received object)
> GH: Adds `extract parameter` option to speckle related output nodes.

- ConnectorGrasshopper/ConnectorGrasshopper/Extras/GenericAccessParam.cs
Fixes #1067
Wrong condition was skipping the CSO options. Will release GH 2.4.1 after this.
> fix(gh): Incorrect condition on GenericAccessParam menu was hidding options

- ConnectorGrasshopper/ConnectorGrasshopper/SchemaBuilder/CreateSchemaObjectBase.cs
- Fixes duplicate applicationId issue reported on community [forum](https://speckle.community/t/grasshopper-component-duplicates-application-id/2249)
- Manual Tests (testing in GH script)
> Check for duplicate seed when CreateSchemaObjectBase comp is added

- ConnectorGrasshopper/ConnectorGrasshopper/Extras/Utilities.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Ops/Operations.VariableInputReceiveComponent.cs
Fixes #1045 
Added handling of case where a commit referenced object that was convertible `toNative` (such as a point, line, mesh...) was never converted.
It will now default to convert it regardless of the `expandOutput` setting.
If user wishes to not convert it and expand it instead, they should use the `doNotConvert` flag along side the `expandOutput` flag.
> GH: Receive handles case where referencedObject is convertible

- Objects/Converters/ConverterRevit/ConverterRevitShared/ConverterRevit.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/ConverterRevitShared.projitems
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertCableTray.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertWall.cs
- Objects/Objects/BuiltElements/CableTray.cs
Adds `CableTray` class to Core
Adds `CableTrayToSpeckle` and `CableTrayTonative` conversions to Revit
- Fixes #975 
- Manual Tests: sent and received basic cable trays in revit
> feat(core&revit): adds cabletray

- ConnectorGrasshopper/ConnectorGrasshopper/Ops/Operations.VariableInputReceiveComponent.cs
Adds released hotfix in `grasshopper/2.4.2` to `main`.
This is the exact same commit as 54e83787ff77fc2fbffa324a6ff4343cc1dd2f79, but was not directly merged as the prior changes were squashed into `main`.
I'm cherrypicking this change and applying it directly to prevent any weird merge history conflicts from happening.
Reported in the forum: https://speckle.community/t/speckle-grasshopper-stream-receive-broken/2501
> fix(gh): Search for Name instead of nickname as it is consistent across UI settings

- ConnectorGrasshopper/ConnectorGrasshopper.sln
- ConnectorGrasshopper/ConnectorGrasshopper/Extras/Utilities.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Loader.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Objects/Deprecated/SelectKitAsyncComponentBase.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Objects/SelectKitComponentBase.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Objects/SelectKitTaskCapableComponentBase.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Ops/Operations.ReceiveComponent.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Ops/Operations.ReceiveComponentSync.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Ops/Operations.ReceiveLocalComponent.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Ops/Operations.SendComponent.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Ops/Operations.SendComponentSync.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Ops/Operations.VariableInputReceiveComponent.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Ops/Operations.VariableInputSendComponent.cs
- ConnectorRhino/ConnectorRhino6/ConnectorRhino6.csproj
- ConnectorRhino/ConnectorRhino7/ConnectorRhino7.csproj
- Core/Core/Kits/Applications.cs
- Objects/Converters/ConverterRhinoGh/ConverterGrasshopper6/ConverterGrasshopper6.csproj
- Objects/Converters/ConverterRhinoGh/ConverterGrasshopper7/ConverterGrasshopper7.csproj
- Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.cs
- Objects/Objects.sln
Splits the Rhino converter into 2 new Grasshopper specific converters for each specific version of Rhino (6 and 7)
This allows for support of SubD geometry, and also prevents conversion for un-supported types in Grasshopper, or conversions that required baking to Rhino, that used to throw errors in GH; such as BlockInstance, BlockDefinition, RenderMaterial, Views, Hatches, etc.
Individual conversions can be added in the future to deal with this
- Fixes #923
- Fixes #952
Grasshopper connector no longer shares the converter with Rhino6, instead, it now will be packaged with it's own versioned converters for Rhino 6 and 7 (`Objects.Converters.Grasshopper6.dll`...)
This is not that much of a …
> GH: Split rhino converter into Grasshopper specific one.

- .circleci/config.yml
- ConnectorGrasshopper/ConnectorGrasshopper/ConnectorGrasshopper.csproj
- ConnectorGrasshopper/ConnectorGrasshopper/Conversion/Deprecated/Convert.ToNativeAsync.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Conversion/Deprecated/Convert.ToSpeckleAsync.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Extras/SpeckleStateTag.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Objects/Deprecated/CreateSpeckleObjectAsync.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Objects/Deprecated/CreateSpeckleObjectByKeyValueAsync.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Objects/Deprecated/ExpandSpeckleObjectAsync.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Objects/Deprecated/ExtendSpeckleObjectAsync.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Objects/Deprecated/ExtendSpeckleObjectByKeyValueAsync.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Objects/Deprecated/GetObjectValueByKeyAsync.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Objects/Deprecated/ObjectsUpgradeUtils.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Objects/Deprecated/SelectKitAsyncComponentBase.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Properties/AssemblyInfo.cs
- ConnectorGrasshopper/ConnectorGrasshopper/packages.config
- ConnectorGrasshopper/README.md
- Core/Core/Core.csproj
- Added grasshopper build to CI in native macos vm
- Upgraded Grasshopper project to be a dotnet sdk to play better with mono.
- Modified some of the Grasshopper types to enable building in mac.
- New `grasshopper-mac/x.y.z` tag can be created to only release grasshopper for mac (this was done for testing purposes, but i'm keeping it since it may be useful)
- Releases will be uploaded to `installers/grasshopper-mac/grasshopper-mac-x.y.z.zip` and consumed by the manager. The yaml will also be updated to reflect the latest and beta versions properly.
- CI Build is generic and should be used for Rhino and other mac builds in the future for this repo.
Just a new build, all code remains the same :)
- Manual Tests (please write what …
> GH: Adds mac build and deploy to CI

- DesktopUI2/DesktopUI2/Models/Filters/FilterUtils.cs
Found bug where saved receivers weren't properly deserilizing since filter prop on streamstate is null.
- Manual Tests
> fix(dui): catches invalid jobject on filter deserialize

- ConnectorGrasshopper/ConnectorGrasshopper.sln
- ConnectorGrasshopper/ConnectorGrasshopper/Extras/Utilities.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Objects/ExpandSpeckleObjectTaskComponent.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Ops/Operations.ReceiveComponentSync.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Ops/Operations.ReceiveLocalComponent.cs
- Fixes #1148
Fixes Sychronous receiver null error that prevented it from working.
Fixes same issue in Local receiver.
Added case to deal with nested lists in expand speckle object, as it was necessary for the synchronous receiver to work.
- Unit/Integration Tests (which?)
- Have already been updated
> Fix Synchronous receiver null error

- ConnectorGrasshopper/ConnectorGrasshopper/Extras/Utilities.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Objects/CreateSpeckleObjectTaskComponent.cs
Fixes #1103 
This works with some caveats, as the parameters loose track of whose referenced:
Some geometries like lines can never be referenced in a `GH_Line` param, which will cause it to fail to assign the applicationId's. 
For curves, surfaces, breps and meshes it will always work as expected.
> fix(gh): Referenced rhino objects now have applicationId set

- Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.Geometry.cs
Because meshes no longer need unique vertices, can remove costly methods in the Brep/Surface to Mesh conversion.
- Manual Tests
> refactor(autocad): better performance for mesh creation

- ConnectorGrasshopper/ConnectorGrasshopper/Loader.cs
New CSI category was auto-generated without adding the new category on the disable tabs menu.
Just added the missing category to the list.
P.S.: I should talk to Jedd about best way's of automating this without much trouble.
> fix: Added missing CSI toggle in top-menu

- ConnectorGrasshopper/ConnectorGrasshopper/Objects/ExpandSpeckleObjectTaskComponent.cs
- Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.Geometry.cs
- Fixes #1112
Polycurves from Revit where incorrectly rendered in Rhino due to revit outputing each curve in a different direction.
In Rhino, we were using `AppendSegment`, which does not check if the curve needs reversing when it's added.
We now use `Append`, which will check the curve for continuity and reverse it if necessary, producing a valid PolyCurve in Rhino
Tested with provided stream, and several manually generated polycurves in GH
> GH: Fixes 1112

- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertFamilyInstance.cs
- Objects/Objects/BuiltElements/Revit/FamilyInstance.cs
- Related to #1126
Displays an error when receiving a family instance that should be mirrored, as Revit has no easy way of doing so without having a duplicate object; and also does not provide an easy way to get the `id` of that newly duplicated object.
Added new `mirrored` prop to the `FamilyInstance` class in `Objects`.
Added new error to report specifying which objects failed to be mirrored and why.
Sent and received mirrored family instances and made sure report was generated.
> fix(rvt): FamilyInstances would be incorrectly placed with no error shown to the user

- ConnectorGrasshopper/ConnectorGrasshopper/ConnectorGrasshopper.csproj
- ConnectorGrasshopper/ConnectorGrasshopper/SchemaBuilder/SchemaBuilderGen.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertOpening.cs
- Objects/Objects/BuiltElements/Opening.cs
- Fixes #970
Added new Schema nodes for `Opening` and `RevitWallOpening`.
Modified the wall opening conversions to throw better errors (it assumed curve was polyline, but that's not necessarily the case)
Improved edge-case where host element was set in the opening, but opening was not part of the wall's elements list.
If a RevitWallOpening is contained in the `elements` list of a wall **and** has it's host set to the wall, the converter will prioritize the parent (i.e.: the object owning the element list). Only when there is no set object we will  try to find the specified host in the document.
If the host is not found, the operation is aborted.
Manually sent/received walls with …
> GH/RVT: Add support for wall openings

- Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.Geometry.cs
- Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.cs
Previously, nonplanar polycurve with nonlinear segments were being squashed into planar curves. Now they are converted as splines, or individual segments if spline conversion fails.
- Fixes #701
> fix(autocad): improves polycurve conversions

- Objects/Converters/ConverterRevit/ConverterRevitShared/ConversionUtils.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertDuct.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertPipe.cs
- Fixed issue with MEP elements that do not have a system will fail to convert ToSpeckle.
- Bug fix (non-breaking)
- Autodesk MEP sample file on Revit 2021. (which contains ducts with a null system)
> Fixed issue with MEP elements with null or unknown MEP systems

- Core/Core/Api/Operations/Operations.Receive.cs
closes DUI2: Type error on deserialisation crashes host application #1164
- catch in `Operations.Receive` and use `onErrorAction` if exists
- if there isn't an action, then we can throw the exception
- none of the connectors expect the deserialisation to throw an exception
and I don't wanna add a catch in each and every one of them
so this is the fix for now
- need to ping @teocomi re the logging bc it is super unhelpful atm
- i tried so long to get this to be handled within the deserialisation so that
you don't fail the whole receive, but it didn't work and i cba
and cristi agreed this is fine for now
- cristi want's to look @ why it's so slow for some reason
- this is the unhelpful logging i get; will fix when teo is free to chat
- Fixes #1164
- Bug fix (non-breaking change which fixes …
> fix(core): catch failed deserialization 🙅‍♀️🥣

- Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.Other.cs
This issue:
- Rhino materials often don't follow a Physically Based shading workflow. And yet, materials have PBR like properties.
- Previously, our ToSpeckle conversion was trying to use these properties, and also trying to fit them into our "metalic/roughness" workflow, which lead to some highly undesirable results (like "plaster" and "plastic" materials having a metalness of 100%)
- See https://speckle.community/t/speckle-2-4-0-connector-changes-enhanced-material-support/2442/9
The Fix:
- In Rhino 7, there are functions exposed for converting Rhino preset materials into Rhino PBR materials. This PR updates ToSpeckle conversion to use these. This also removes the need for the hacky opacity work around for glass/gem material (atleast, just for Rhino 7)
- For Rhino 6 API, these functions …
> Rhino 7 will now output the correct PBR material properties

- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertAdaptiveComponent.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertBeam.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertLevel.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertLocation.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertSpace.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertWire.cs
- Fixes issue with sending linked document from Revit
- There were still a few places where we were using the main (current) document when converting elements ToSpeckle.
- For elements in linked documents, this was leading to a variety of null reference exceptions etc.
- Also fixed an issue with sending family Instances that use a `LocationCurve` instead of a `LocationPoint`
> Revit: Fixed references to document field in ToSpeckle conversion functions

- ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/UI/ConnectorBindingsRhino.cs
Fixes Rhino crashing when baking multiple layers on Mac.
Bake objects call is now done on the UI thread.
> fix(rh-mac): Fix crash when baking layers

- .circleci/config.yml
- ConnectorGrasshopper/ConnectorGrasshopper/ConnectorGrasshopper.csproj
Fixes GH crash reported on the forum: https://speckle.community/t/grasshopper-with-speckle-connection-crashes/2795
This was caused by the GH build not properly renaming the `dll` to `gha`,  causing it to either be missing, or not override the existing one.
- If it didn't override the existing one, it would cause a crash.
- If it was named `dll` instead of `gha`, Speckle would not be loaded.
Tested both mac and rhino builds to ensure files where compiled correctly and connectors ran as expected.
> Fixes 2.5.1 GH crash

- Core/Core/Models/DynamicBase.cs
- Core/Tests/BaseTests.cs
- Objects/Objects/Geometry/Brep.cs
- Fixes #1223
Added some `SchemaIgnore` attributes in the Brep class to hide unnecessary value lists.
`DynamicBase.GetMembers` and `DynamicBase.GetMemberNames` will no longer return properties flagged as `Deprecated`. This was introduced recently on our object model for `displayMesh` properties, but will be used in the future for other fields.
- Unit/Integration Tests (which?)
- Have already been updated
> Filter Deprecated members from GetMembers and GetMemberNames

- ConnectorAutocadCivil/ConnectorAutocadCivil/UI/ConnectorBindingsAutocadCivil.cs
- ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/UI/ConnectorBindingsRhino.cs
Changed sending with the manual selection filter to send the saved selection instead of currently selected objs
- Fixes #1238
> fix(rhino/acad): sends saved selection objs from manual filter

- ConnectorGrasshopper/ConnectorGrasshopper/ConnectorGrasshopper.csproj
- ConnectorGrasshopper/ConnectorGrasshopper/SchemaBuilder/SchemaBuilderGen.cs
- ConnectorGrasshopper/ConnectorGrasshopperUtils/CSOUtils.cs
- Objects/Objects/BuiltElements/Opening.cs
Fixes #1199
Marked `RevitWallOpening` constructor as obsolete and created a new one that only takes a `Polyline` as outline.
Also added basic validity checks on the polyline.
Fixed issue with `tt` template not picking up deprecated nodes and rebuilt all nodes.
> fix: Opening constructor now takes a polyline instead

- ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/UI/ConnectorBindingsRhino.cs
- Fixes #1250 
We now deal with object color using Rhino's `ObjectColorByMaterial` default, preventing the case were the alpha channel of a color would be used as the display color of an object, causing it to be invisible on non-render visualisation nodes.
Reviewed live with @clairekuang and @JR-Morgan 
> fix(rh): changes behaviour of objects to inherit color from material.

- .circleci/config.yml
- Objects/Converters/ConverterAutocadCivil/ConverterAutocad2021/ConverterAutocad2021.csproj
- Objects/Converters/ConverterAutocadCivil/ConverterAutocad2022/ConverterAutocad2022.csproj
- Objects/Converters/ConverterAutocadCivil/ConverterCivil2021/ConverterCivil2021.csproj
- Objects/Converters/ConverterAutocadCivil/ConverterCivil2022/ConverterCivil2022.csproj
- Objects/Converters/ConverterCSI/ConverterCSIBridge/ConverterCSIBridge.csproj
- Objects/Converters/ConverterCSI/ConverterETABS/ConverterETABS.csproj
- Objects/Converters/ConverterCSI/ConverterSAFE/ConverterSAFE.csproj
- Objects/Converters/ConverterCSI/ConverterSAP2000/ConverterSAP2000.csproj
- Objects/Converters/ConverterMicroStation/ConverterMicroStation/ConverterMicroStation.csproj
- Objects/Converters/ConverterMicroStation/ConverterOpenBuildings/ConverterOpenBuildings.csproj
- Objects/Converters/ConverterMicroStation/ConverterOpenRail/ConverterOpenRail.csproj
- Objects/Converters/ConverterMicroStation/ConverterOpenRoads/ConverterOpenRoads.csproj
- Objects/Converters/ConverterRhinoGh/ConverterGrasshopper6/ConverterGrasshopper6.csproj
- Objects/Converters/ConverterRhinoGh/ConverterGrasshopper7/ConverterGrasshopper7.csproj
- Objects/Converters/ConverterRhinoGh/ConverterRhino6/ConverterRhino6.csproj
- Objects/Converters/ConverterRhinoGh/ConverterRhino7/ConverterRhino7.csproj
- Objects/Converters/ConverterTeklaStructures/ConverterTeklaStructures2020/ConverterTeklaStructures2020.csproj
- Objects/Converters/ConverterTeklaStructures/ConverterTeklaStructures2021/ConverterTeklaStructures2021.csproj
- Fixes #1258 
Modified the project and the build step so that it would play nicely with netstandard and netframework projects (Grasshopper and Rhino 7 require `net48`) to compile, which  is why it broke the nuget publish in the first place.
Our `dotnet pack` step was not compatible with `net48`, so we've switched to msbuild  with packing flags.
Ran an alpha version and it went smoothly (including using the nugets)
> Nugets: Fixes Rhino7 and Grasshopper 7 publish step

- Objects/Converters/ConverterRevit/ConverterRevitShared/ConversionUtils.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertCurves.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertGeometry.cs
- Objects/Objects/Geometry/Line.cs
- Fixes issue in Revit where Polyline's with very short segments would completely fail to convert.
- Fixes an issue were we were assuming a `Curve` in a cast, but should have been an `IDisplayable<Polyline>` instead.
- Adds length calculation to `Line` class constructor. This is used during polyline creation to ensure no short segments are converted to Revit.
Original offending commit: https://speckle.xyz/streams/35cc66339a/commits/cb564be587
> RVT: Improved polyline conversions

- ConnectorGrasshopper/ConnectorGrasshopper/Objects/GetObjectKeysComponent.cs
- Fixes reporting issue due to wrong inheritance in Get object keys
> fix(gh): Get object keys reporting

- ConnectorGrasshopper/ConnectorGrasshopper/ConnectorGrasshopper.csproj
- ConnectorGrasshopper/ConnectorGrasshopper/Objects/DeconstructSpeckleObjectTaskComponent.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Objects/Deprecated/ExpandSpeckleObjectTaskComponent.cs
- Objects/Objects/BuiltElements/Wall.cs
- Fixes #1311 
- Fixes #1309 
- Adds null check to WallByFace constructor.
Old ESO nodes properly upgrade to new DSO with param type change.
DSO no longer throws null error on BeforeSolveInstance
> GH: DSO release fixes

- Objects/Converters/ConverterRevit/ConverterRevitShared/ConversionUtils.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertDuct.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/Units.cs
Adds an optional `units` param to `ScaleToSpeckle` in order to allow for particular unit conversions when necessary.
Uses this in the `GetParamValue` and `ParameterToSpeckle` when needing to override the display units in order to get the value in model units.
in imperial, internal duct dimensions such as height, width, diameter are in inches while the model units are in feet.
this meant that eg 12 was set as the diameter for a duct which would be received as 12 feet instead of 12 inches.
as far as i can tell, this only affects mechanical. however keep an eye out for other possible scenarios like this where we are setting the value of a parameter to the actual speckle object
- Manual Tests with the built elements test file
- No updates …
> fix(revit): duct internal dimensions from imperial units

- Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.Geometry.cs
- Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.cs
Improves conversion `ToNative` of `Brep` geometries by attempting to extract the RenderMesh from Rhino if available.
This step is restricted to only the RhinoObjects that are `BrepObject`, in order to only call this when needed.
The render mesh may not be found (Rhino only calculates the ones it needs, i.e. the ones you've seen or are seeing on a viewport in the current session), in this case we will default to the behaviour we were having already.
This can lead to around 30% reduction in conversion time when Breps are complex.
Not really a new feature, rather a small improvement.
Tested with the exploded cathedral and the motor model we have in Drive. Both seemed to be faster in …
> RH: Adds faster mesh extraction when available

- ConnectorGrasshopper/ConnectorGrasshopper/Extras/Utilities.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Objects/DeconstructSpeckleObjectTaskComponent.cs
- Fixes #1319
IsDataTree check was assuming an object with 0 dynamic props was a DataTree, when it obviously is not.
Reproduced error consistently, found root cause and unable to repro after fix.
> fix(gh): Fixes #1319

- Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.Other.cs
> fix(autocad): dynamic block visibility state value not always string

- ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/UI/ConnectorBindingsRhino.cs
User string dictionary is now correctly type checked on receive.
Also, *deprecates check for `SpeckleSchema` user string* - breaking change!
- Fixes #1330 
> fix(rhino): user strings not properly assigned on receive

- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertDirectShape.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertGeometry.cs
- Adds support for materials in BrepToNative conversion, and it's respective MeshToNative conversion if it fails
Tested it working on compatible BREPs that are successfully converted to Solids, and also some who's conversion fails and it's displayValue is used instead.
> fix(gh): Handle renderMaterial in breps, with Solid and Mesh output handled

- ConnectorDynamo/ConnectorDynamoFunctions/BatchConverter.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Extras/Utilities.cs
- Rolls back dynamic chunking while we look into #1339
- Revert change
- Manual Tests:
Tested dynamo and grasshopper against chunked data trees and new non-chunked data trees while we look into the issue.
> Revert GH DataTree dynamic chunking

- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertGeometry.cs
- Fixes small bug discovered in Arc conversion, where an arc with 360 degrees would throw an error, as the default conversion method uses the 3 point arc approach.
Tested arcs, and solids that were composed of arcs, to ensure it was working on all cases.
> fix(rvt): Create circle if arc has 360 deg

- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertTopography.cs
Previous Revit topo pr wrongly assumed the new `Create()` method was only available starting Revit 2022: this updates the preprocessor directive to apply for all versions later than 2019
> fix(revit): updated preprocessor directives for revit topo

- ConnectorGrasshopper/ConnectorGrasshopper/BaseComponents/SelectKitTaskCapableComponentBase.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Extras/Utilities.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Objects/DeconstructSpeckleObjectTaskComponent.cs
- Objects/Objects/Other/MaterialQuantity.cs
- Fixes #1366
MaterialQuantity class did not have a default empty constructor, which made deserialisation fail for all objects that had an instance as a child.
- Fixes #1367 
DSO BeforeSolveInstance call assumed a converter was available, but disabling conversion would null it and would raise an exception when it attempted to use it.
Fixed `TryConvertToSpeckle` to not assume a Converter will be provided, and check for null there.
This fixes any issues in any other nodes that used this.
Manually tested provided streams in the forum to reproduce the error, and can no longer reproduce after fix.
> HOTFIX: Release included broken feature expected for 2.7 + DSO BeforeSolveInstance fix

- ConnectorTeklaStructures/ConnectorTeklaStructuresShared/Util/ConnectorTeklaStructuresUtils.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/ConverterRevit.cs
- Objects/Converters/ConverterTeklaStructures/ConverterTeklaStructuresShared/ConverterTeklaStructures.cs
- Objects/Converters/ConverterTeklaStructures/ConverterTeklaStructuresShared/Partial Classes/ConvertDirectShapeMesh.cs
- Fixed receiving objects as Brep shapes in Tekla Structures.
- Added proposed method to set OST category of DirectMesh object in Revit Connector
- Manual Tests: Sending and receiving models using the DirectMesh setting between Tekla Structures and Revit
> Fixes and addtion for receving as mesh in Tekla and Revit

- ConnectorAutocadCivil/ConnectorAutocad2023/ConnectorAutocad2023.csproj
- ConnectorAutocadCivil/ConnectorCivil2023/ConnectorCivil2023.csproj
- Bumps version of Acad and Civil 2023 projects to Avalonia 0.10.16
- 
Potentially breaking in some ways, requires further testing in the release.
> fix: Avalonia version bump was missing 2023 Acad and Civil projects

- ConnectorAutocadCivil/ConnectorAutocad2021/ConnectorAutocad2021.csproj
- ConnectorAutocadCivil/ConnectorAutocad2022/ConnectorAutocad2022.csproj
- ConnectorAutocadCivil/ConnectorCivil2021/ConnectorCivil2021.csproj
- ConnectorAutocadCivil/ConnectorCivil2022/ConnectorCivil2022.csproj
- ConnectorCSI/ConnectorCSIBridge/ConnectorCSIBridge.csproj
- ConnectorCSI/ConnectorETABS/ConnectorETABS.csproj
- ConnectorCSI/ConnectorSAFE/ConnectorSAFE.csproj
- ConnectorCSI/ConnectorSAP2000/ConnectorSAP2000.csproj
- ConnectorCSI/DriverCSharp/DriverCSharp.csproj
- ConnectorRevit/ConnectorRevit2019/ConnectorRevit2019.csproj
- ConnectorRevit/ConnectorRevit2020/ConnectorRevit2020.csproj
- ConnectorRevit/ConnectorRevit2021/ConnectorRevit2021.csproj
- ConnectorRevit/ConnectorRevit2022/ConnectorRevit2022.csproj
- ConnectorRevit/ConnectorRevit2023/ConnectorRevit2023.csproj
- ConnectorRhino/ConnectorRhino6/ConnectorRhino6.csproj
- ConnectorRhino/ConnectorRhino7/ConnectorRhino7.csproj
- ConnectorTeklaStructures/ConnectorTeklaStructures2020/ConnectorTeklaStructures2020.csproj
- ConnectorTeklaStructures/ConnectorTeklaStructures2021/ConnectorTeklaStructures2021.csproj
- Core/Core/Core.csproj
- DesktopUI2/AvaloniaHwndHost/AvaloniaHwndHost.csproj
- DesktopUI2/DesktopUI2.Launcher/DesktopUI2.Launcher.csproj
- DesktopUI2/DesktopUI2.WPF/DesktopUI2.WPF.csproj
- DesktopUI2/DesktopUI2/DesktopUI2.csproj
This reverts commit 9d302eec86543dffd2f18569b9d7fef8cd0cabca.
This is being reverted because it has been already squashed into the `release/2.7` branch, and should not live in `main` unless we're planning to release this as a hotfix (which I think may be dangerous, this should be tested first).
Changes are here b2e0ec8aa56ed37b4df186ee4263dc92008c5b0b
> Revert "feat(dui): updates to Avalonia 0.10.16"

- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertLevel.cs
- Fixes https://speckle.community/t/speckle-revit-levels-bug-old-levels-not-replaced/2378/7
Currently, a level is being created for each imported object. In the gif below you can see that I import a commit and then highlight what seems to be only a few levels
The text may be difficult to read in the gif, but Revit is showing that I actually have 104 levels highlighted.
This behavior is now almost identical except Speckle will skip levels that already exist
There are now only 4 highlighted levels
- Received several streams to check to make sure duplicate levels were not being created
> assign value to variable 'existingLevelWithSameElevation'

- DesktopUI/DesktopUI/Utils/DummyBindings.cs
- DesktopUI2/DesktopUI2/DummyBindings.cs
Changes were made and a new 2.6.5 release was triggered.
This PR is to keep `main` up to date with these changes
> Update main with changes from 2.6.X

- ConnectorGrasshopper/ConnectorGrasshopper/Conversion/ToSpeckleTaskCapableComponent.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Extras/Speckle.IGH_Goo.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Extras/SpeckleBaseParam.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Extras/Utilities.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Objects/GetObjectValueByKeyTaskComponent.cs
- ConnectorGrasshopper/ConnectorGrasshopper/SchemaBuilder/SchemaBuilderGen.cs
- Objects/Converters/ConverterDynamo/ConverterDynamoShared/ConverterDynamo.Geometry.cs
- Objects/Converters/ConverterDynamo/ConverterDynamoShared/ConverterDynamo.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertBlock.cs
- Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.Other.cs
- Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.cs
- Objects/Objects/Geometry/Arc.cs
- Objects/Objects/Geometry/Brep.cs
- Objects/Objects/Geometry/ControlPoint.cs
- Objects/Objects/Geometry/Curve.cs
- Objects/Objects/Geometry/Line.cs
- Objects/Objects/Geometry/Mesh.cs
- Objects/Objects/Geometry/Plane.cs
- Objects/Objects/Geometry/Point.cs
- Objects/Objects/Geometry/Pointcloud.cs
- Objects/Objects/Geometry/Surface.cs
- Objects/Objects/Geometry/Vector.cs
- Objects/Objects/Interfaces.cs
- Objects/Objects/Objects.csproj
- Objects/Objects/Other/Block.cs
- Objects/Objects/Other/RenderMaterial.cs
- Objects/Objects/Other/Transform.cs
- Adds support for `Transform` conversions in Grasshopper and Dynamo
- Grasshopper: ToNative and ToSpeckle (to support schema node)
- Dynamo: ToNative (as Coordinate System)
- Adds new computed property in `Block` -> `transformedGeometry` that returns the transformed geometry for that block instance
- Adds a new computed property in Block -> `insertionPlane` that returns a `Plane` already transformed into the insertion position of that Block Instance
- Improves support for `ITransformable` and makes `ITransformable<T>` inherit from it.
- Fixes some minor issues with Line and Brep transform logic.
- Adds transform support to `Arc`
- Adds new Schema constructors to `BlockInstance` and `BlockDefinition`, with its corresponding Schema nodes in Grasshopper. 
- Adds …
> DYN/GH: Adds better Block and Transform support

- ConnectorDynamo/ConnectorDynamoFunctions/BatchConverter.cs
- Objects/Converters/ConverterDynamo/ConverterDynamoShared/ConverterDynamo.Geometry.cs
- Adds support for NGON meshes in Dynamo. Ngon faces **will be triangulated**.
- Modified batch converter to extract all keys from a non-convertible base object on receive, not only the dynamic ones.
Receiving blocks from Sketchup (which usually contain ngon faces) works now
> DYN: Add Ngon mesh support

- Objects/Converters/ConverterDynamo/ConverterDynamoShared/ConverterDynamo.Geometry.cs
- Fixes #1428 
BoundingBox in dynamo can be flat, but Cuboid cannot. Created a new overload of `BoxToSpeckle` to deal with BBox directly and removed any references of `ToCuboid()` for safety.
> DYN: Added BBox to Speckle Box conversion and replaced everywhere

- Core/Core/Models/DynamicBase.cs
- Core/Tests/BaseTests.cs
+ other minor cleanups: caches reflection calls & DRYs the GetProperties() calls. 
Regarding the `Item` prop discussions, please see this discourse thread: https://speckle.community/t/why-do-i-keep-forgetting-base-objects-cant-use-item-as-a-dynamic-member/3246/4
- 
- Unit Tests + Added new tests to cover both dynamic and typed `Item` props
> CORE: Allows for `Item` to be set as a dynamic or typed prop in `Base`-derived objects

- Objects/Objects/Other/Block.cs
- Fixes minor issue discovered when testing, where an incompatible geometry or incorrectly transformed would lead to a null reference error while expanding the object in Grasshopper.
Surely this happened in Dynamo too.
> fix(objects): Null reference error in GetTransformedGeometry

- .circleci/scripts/config-template.yml
- Fixes version picking bash command grabbing the prefix `nugets` instead of the actual version number. This caused the build to not create a nuget package, and the upload step would fail.
> FIX(ci): Nuget version picking nuget prefix instead of version.

- Objects/Converters/ConverterCSI/ConverterCSIShared/ConverterCSIUtils.cs
- Objects/Converters/ConverterCSI/ConverterCSIShared/Partial Classes/Geometry/ConvertArea.cs
- Objects/Converters/ConverterCSI/ConverterCSIShared/Partial Classes/Geometry/ConvertFrame.cs
- Objects/Converters/ConverterCSI/ConverterCSIShared/Partial Classes/Geometry/ConvertLine.cs
- Objects/Converters/ConverterCSI/ConverterCSIShared/Partial Classes/Geometry/ConvertPoint.cs
Receiving in ETABS always defers to the default units in the program. Which leads to most of my models coming from Revit (in feet) to be 1/12 of their actual size when received in ETABS (which defaults to inches for imperial units)
Receiving and sending different models to make sure everything works as expected
> using units from speckle instead of etabs default

- ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/UI/ConnectorBindingsRhino.cs
- Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.Utils.cs
- Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.cs
Previously, user strings and user dictionaries were being sent as dictionaries in Rhino. They are now attached as `Base`.
Also checks for `name` prop on receive.
Attaching user info has been moved from the connector to the converter
- Fixes #1333
- Manual Tests: user strings, names, and dicts in rhino
> rhino: changes user attributes from dict to base

- ConnectorRhino/ConnectorRhino.sln
- ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/Entry/Plugin.cs
- ConnectorRhino/ConnectorRhino6/Properties/AssemblyInfo.cs
- ConnectorRhino/ConnectorRhino7/Properties/AssemblyInfo.cs
- Fixes an initialization error in Rhino
I was not able to consistently reproduce this, but it seemed to happen on first load, right after install.
Since the connector and DUI2 were initialized in the Plugin constructor, I think this caused some sort of race condition.
Initialization logic has been moved to the `loaded` event, this means the plugin will only be started when users call the `Speckle` command or have the Panel open.
> fix(rhino): init issue fix attempt

- ConnectorRevit/ConnectorRevit/Entry/App.cs
- ConnectorRevit/ConnectorRevit/Entry/SpeckleRevitCommand2.cs
- ConnectorRevit/ConnectorRevit/UI/ConnectorBindingsRevit2/ConnectorBindingsRevit2.Events.cs
- Workaround for #1469
This is a workaround just to let the user know Revit cannot correctly register Dockable panels when launched from a file, instead of showing an error message.
Other possible solutions:
- try to create/open a doc in the background (i tried and failed)
- launch the old windowed UI (possible conflicts)
We should merge this in 2.7 and release a hotfix.
> fix(revit): workaround for #1469

- ConnectorGrasshopper/ConnectorGrasshopper/Loader.cs
- Fixes issue where Mixpanel was not receiving the events from Grasshopper properly tagged, leading to non-realistic a massive drop in MAU on our dashboard.
I did a quick test and ended up keeping the reflection call, but fixed it so that it would work as expected. This should not be an issue unless a 3rd party plugin that uses speckle has an older version of core that did not contain `Setup.Init` (quite old, but can happen)
We should be back to normal MAU tracking in no time
> fix(gh): Fixed Setup.Init call on Loader.cs + added comments

- ConnectorGrasshopper/ConnectorGrasshopper/SchemaBuilder/CreateSchemaObject.cs
- ConnectorGrasshopper/ConnectorGrasshopper/SchemaBuilder/CreateSchemaObjectBase.cs
- Fixes issue where non-english installations of Rhino would cause an error as we expect english named units.
The solution is to use the `ToString()` method of the `UnitSystem` which will always be in english regardless of the language it was installed in.
Reported in the forum: https://speckle.community/t/how-create-revit-geometry-from-grasshopper/3351
Tested the fix in isolation and also some schema nodes while having Rhino set to Spanish.
> fix(gh): Switched to using unit name from Enum instead of localised units

- ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/BIMElements/BIMElementCommands.cs
- ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/BIMElements/BIMElementFilter.cs
- Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.BuiltElements.cs
- Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.Geometry.cs
- Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.cs
Allows users to assign topography schema to non-solid breps and subds
Also fixed a null error bug on rhino bim schema conversions
- Closes #1485 
- Fixes #1486 
- Manual Tests
> feat(rhino): add brep and subd support for rhino bim topography

- ConnectorCSI/ConnectorCSIShared/UI/ConnectorBindingsCSI.Recieve.cs
- ConnectorTeklaStructures/ConnectorTeklaStructuresShared/UI/ConnectorBindingsTeklaStructures.Receive.cs
- Fixes receiving objects not showing a progress bar
> fix for receiving objects

- ConnectorGrasshopper/ConnectorGrasshopper/Extras/GenericAccessParam.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Extras/SpeckleStatefulParam.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Ops/Operations.VariableInputReceiveComponent.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Ops/Operations.VariableInputSendComponent.cs
- Core/Core/Api/GraphQL/Client.GraphqlClientOperations.cs
Closes #1499
- Account details issue was related to the `StreamsGet` function in Core not expecting the user to be `null`, which can be if there are no provided credentials, the credentials are invalid, or the user does not exist anymore. I added a better exception for that case to provide more clarity to the user.
- `T0: One or more errors ocurred` while sending. This seems to be related to the first item, but I haven't managed to repro so this one remains **unfixed**. Could have been caused by a faulty connection. We checked the server logs but nothing showed up. Tried invalidating my token to verify if this would replicate the error, but I got the expected warnings 👇🏼
- Renaming input. behaviour on the Send component should now work as expected.
- **Slow renaming** was caused (at least …
> GH: SOM reported bug fixes

- Objects/Converters/ConverterRevit/ConverterRevitShared/ConversionUtils.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertAdaptiveComponent.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertBeam.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertCableTray.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertCeiling.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertColumn.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertDuct.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertFaceWall.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertFamilyInstance.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertFloor.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertGeometry.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertPipe.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertProfileWall.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertRailing.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertRebar.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertRoof.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertWall.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertWire.cs
- the `GetElementType()` methods now returns a bool to allow for easier logic checks in primary conversions
- logging has been updated so that `ApplicationObjects` are always being returned on instances of failing `GetElementType` methods instead of a speckle exception being thrown
- fixes #1498
> fix(revit): updated GetElementType method to return bool with logging

- Objects/Objects/Primitive/Interval.cs
Fixes #1478
Pretty simple bug, doesn't require much explanation.
Interval length required some parenthesis to properly do the operations in order.
> fix(obj): Interval length parenthesis 🙃

- ConnectorGrasshopper/ConnectorGrasshopper/Extras/GenericAccessParam.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Extras/SpeckleStatefulParam.cs
- ConnectorGrasshopper/ConnectorGrasshopper/SchemaBuilder/CreateSchemaObject.cs
- ConnectorRhino/ConnectorRhino.sln
Reported here https://speckle.community/t/adaptive-component-error/3369/2
Issue seems to be two:
- Null reference errors being thrown while grabbing Lists using reflection
- Null reference errors being thrown on the menu popup, preventing it from showing up.
Bonus:
- Fixed wrong Param type on the Create Schema Node. It will now use the `StatefulSpeckleParam` for better control.
- Disabled name inherit behaviour if `MutableNickname` is false.
> GH: Fix Create Schema Object list input and rename options.

- Core/Core/Transports/SQLite.cs
Using the email hash as a unique id in Sentry created a race condition, removing the `Log.AddBreadcrumb` resolves it as no other Sentry call is made before it has finished initializing
> fix(core): do not call sentry before it has initialized

- Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.Geometry.cs
Autocad mesh faces can have negative vertex indices, which indicates a hidden vertex. This was resulting in distorted meshes with a vertex at the origin, reported by the community at: [https://speckle.community/t/autocad-commit-creating-lines-from-origin-point-in-speckle/2817](https://speckle.community/t/autocad-commit-creating-lines-from-origin-point-in-speckle/2817)
Fixes #1441
AutocadCivil `MeshToSpeckle` conversion
Before: 
After:
> fix(autocad): handles mesh face negative vertex index

- Core/Core/Models/Utilities.cs
- Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.Other.cs
- Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.cs
Proxy entities are sent as `Base` from AutoCAD / Civil3D to Speckle with properties attached and a bbox. Unable to retrieve display geometry for now.
*note* No displayable geometry is attached, so not viewable in the web viewer.
Requested by the community here: [https://speckle.community/t/acad-proxy-entity-not-being-sent-to-speckle/2818](https://speckle.community/t/acad-proxy-entity-not-being-sent-to-speckle/2818)
*note* in order to send the displayed meshes as requested by the community, they must be accessed via direct conversion. See #1527 
Fixes #1228
- `ProxyEntityToSpeckle()` conversion added to AutocadCivil connector
[https://speckle.xyz/streams/638d3b1f83/commits/558ab0be64](https://speckle.xyz/streams/638d3b1f83/commits/558ab0be64)
> feat(autocadcivil): add proxyentity conversion to speckle

- ConnectorGrasshopper/ConnectorGrasshopper/Ops/Operations.VariableInputSendComponent.cs
- Core/Core/Models/Extensions.cs
- Core/Core/Models/Extras.cs
- Core/Tests/ExceptionTests.cs
We usually get errors that are wrapped in other errors, where the meaningful message is somewhere deep inside the nested `Exception` structure.
I've added a new Exception extension in `Speckle.Core.Models.Extensions` (may not be the best place... TBD) called `ToFormattedString()`, which will fetch all messages from an Exception and print them.
So, instead of getting a useless `One or more errors occurred` message, you will now also get all the inner errors that actually occurred, right after the initial message (one line per exception).
This does not support indenting them, as I thought it would make it weird for our reports, but it could be a nice optional thing to have.
Because `exception.ToString()` will print all the exception messages along with their call stack. Even though having …
> CORE: Adds extension method to extract all messages from an Exception

- ConnectorRevit/ConnectorRevit/UI/ConnectorBindingsRevit2/ConnectorBindingsRevit2.Receive.cs
- Core/Core/Models/Extras.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertAdaptiveComponent.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertBeam.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertBlock.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertCableTray.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertCeiling.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertColumn.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertCurves.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertDirectShape.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertDuct.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertFaceWall.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertFamilyInstance.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertFloor.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertGeometry.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertGridLine.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertOpening.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertPipe.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertProfileWall.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertRailing.cs
Previously, curves and blocks were not being correctly logged on receive in the report. This is been fixed.
Also, updated report nots for the `ignore` setting to reflect that objects were skipped because an existing object was found
Includes new updating and ignoring fixes for block to native conversions.
Fixes #1522
Fixes #1508
> fix(revit): improved reporting for geometry and blocks

- ConnectorRevit/ConnectorRevit2022/ConnectorRevit2022.csproj
- ConnectorRevit/ConnectorRevit2023/ConnectorRevit2023.csproj
Removes hard references from Revit 2022 and 2023 connector `csproj` files.
Not sure how this happened, but it's been there for a while 😅
All other projects seemed fine.
> fix(rvt): Connector projects shouldn't directly reference the converters

- Core/Core/Models/DynamicBase.cs
- Core/Tests/BaseTests.cs
While creating some editor UI in Unity to inspect properties.
My current needs are to cache PropertyInfo of types inheriting `Base`, since using reflection every UI update is unacceptable.
We already cache PropertyInfo of speckle types inside `DynamicBase`.
But this data is only accessible through `GetInstanceMembers`
The problem is, I don't have an instance to call `GetInstanceMembers` on, just the `Type`
And I don't want to have to create a dummy instance of a `Type` (which I would then have to cache in the UI), just to call `GetInstanceMembers` (which just calls `GetType()` to access its internal static `propertyInfo` dictionary)
So I propose this small change. (first two lines are the important change)
https://github.com/specklesystems/speckle-sharp/blob/711238ecf7311a12e782302244f6bb0 …
> Added static accessor to `DynamicBase.GetInstanceMembers`

- ConnectorRevit/ConnectorRevit/Entry/App.cs
- Core/Core/Api/GraphQL/Client.GraphqlClientOperations.cs
- DesktopUI2/DesktopUI2/DesktopUI2.csproj
- DesktopUI2/DesktopUI2/ViewModels/BranchViewModel.cs
- DesktopUI2/DesktopUI2/ViewModels/StreamViewModel.cs
- DesktopUI2/DesktopUI2/Views/Pages/StreamEditControls/Receive.xaml
- DesktopUI2/DesktopUI2/Views/Pages/StreamEditControls/Send.xaml
- DesktopUI2/DesktopUI2/Views/Scheduler.xaml
- DesktopUI2/DesktopUI2/Views/Windows/Dialogs/DialogUserControl.cs
- DesktopUI2/DesktopUI2/Views/Windows/Dialogs/NewBranchDialog.xaml
- DesktopUI2/DesktopUI2/Views/Windows/Dialogs/NewBranchDialog.xaml.cs
Minor fiddles in DUI and Revit:
- fixes the URL opened when clicking on "View Online", if in Receive mode and `latest` is selected
- adds a safety guard when Revit starts up (some users reported issues when the plugin is registered/initialized)
- adds "add new branch" option when in send mode
> Revit & DUI fiddles

- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertAnalyticalStick.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertAnalyticalSurface.cs
- Objects/Objects/Structural/Material/Concrete.cs
- Objects/Objects/Structural/Material/Steel.cs
- Objects/Objects/Structural/Material/Timber.cs
All structural material types coming from Revit were set as concrete (0 in the MaterialType enum) because the materialType property was never being set. Now it is being set.
- set materialType value in empty constructor for Concrete, Steel, and Timber classes
- fixed some tab spacing to match the convention of the rest of our code
Manual tests of sending in Revit
> Fix: materialType not being set for structural objects sent from Revit

- ConnectorGrasshopper/ConnectorGrasshopper/Ops/Operations.VariableInputReceiveComponent.cs
The way the `Client` is implemented does not allow for the fetching of data without an Account for that server being present in the system. This makes sense to some degree, but not necessarily so when you're dealing with _public streams_ in _public servers_
I added a modification in the `Receiver` that will pass in a "fake account" with the basic info set so that the client will not throw an exception.
**Bonus**: removed local redundant client creation in favor of `ApiClient`
**Possible better workaround**
This solution could be pushed up to `Core`, so that the `StreamWrapper` would provide the correct "fake account" for any url, including ones that you don't have setup yet.
> feat(gh): Added ability for the receiver to fetch public streams with an old account

- ConnectorGrasshopper/ConnectorGrasshopper/Extras/Speckle.IGH_Goo.cs
Connecting a `Base` object in a panel yielded a result such as `Speckle Object`, `Speckle DirectShape`, `Speckle RevitWall` etc...
This change allows to also print the `name` property of a given object, if it is available and it is not null.
The name will be surrounded by `[]` and placed after the original text describing the type.
> feat(gh): When a `name` is available, include it in our GH_Goo.ToString() result

- ConnectorGrasshopper/ConnectorGrasshopperUtils/ConnectorGrasshopperUtils.csproj
- ConnectorRhino/ConnectorRhino.sln
- Objects/Converters/ConverterRhinoGh/ConverterGrasshopper6/ConverterGrasshopper6.csproj
- Objects/Converters/ConverterRhinoGh/ConverterGrasshopper7/ConverterGrasshopper7.csproj
- Objects/Converters/ConverterRhinoGh/ConverterRhino6/ConverterRhino6.csproj
- Objects/Converters/ConverterRhinoGh/ConverterRhino7/ConverterRhino7.csproj
Mac Installer for 2.8 is missing the Grasshopper converter, which causes it to fail when loading the default kit.
This was caused by the `Release Mac` config running some of the projects on `Debug` config, hence none of the converters would be found by our installer zip logic.
Additionally, added csproj flag to prevent VSCode from naming the converters as `gha`
> fix(gh): Mac installer missing GH converter due sln config misconfiguration

- ConnectorAutocadCivil/ConnectorAutocadCivil/UI/ConnectorBindingsAutocadCivil.cs
- Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/Converter.AutocadCivil.Utils.cs
- Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.Civil.cs
- Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.Geometry.cs
- Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.cs
Adds a reference point setting to allow the user to select from:
- internal origin (default, this is the world coordinate system)
- current user coordinate system (UCS)
- any named UCS that exists in the doc
Also updates all conversion methods, particularly `Point` and `Vector` methods, to use the selected coordinate system.
This will now help Civil3d -> Revit workflows where civil elements are located too far away from Revit's internal origin. See: 
- https://speckle.community/t/help-pipe-networks-from-c3d-to-revit/3485
- https://speckle.community/t/i-need-help-with-pipe-conversion-errors/3459
Closes #1021
AutocadCivil Connector 
AutocadCivil Converter
sending and receiving pipe networks with reference point settings
sending and receiving autocad test files
*known issues:*
any element …
> feat(autocadcivil): add reference point setting

- ConnectorGrasshopper/ConnectorGrasshopper/Ops/Operations.VariableInputReceiveComponent.cs
- Core/Core/Credentials/StreamWrapper.cs
Fixes an issue where `commitUrl` would not reset the ApiClient, leading to null exceptions or errors because the client was not refreshed.
Also uncovered a smaller issue with the `commitUrl` from the output of the `Send node` would be missing the `OriginalInput` string, leading to a null error if connected to a receive node.
> fix(gh): Get account fail when no OriginalInput was set in the StreamWrapper

- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertMeshUtils.cs
There are certain geomtry representation of elements like MassLevelData that is a solid with volume 0 but still valid as it has one face.
Fixes #891
- In the `GetSolids` method of the `ConverterRevit` class (file: ConvertMeshUtils), the condition for invalid solids had been changed from `if (gSolid.Faces.Size > 0 && Math.Abs(gSolid.Volume) > 0)` to `if (gSolid.Faces.Size > 0 && Math.Abs(gSolid.SurfaceArea) > 0)`. Changing the check from volume to surface area will account for solid that has only one face.
Manual tests for sending mass floors from Revit.
> Fix(Revit): support one-faced solid geometries (like mass floor)

- Objects/Objects/Geometry/Point.cs
- Objects/Tests/Geometry/PointTests.cs
Given a quick spin at this issue (hope you don't mind @AlanRynne)
closes #1516
`Point.operator==` now correctly returns true if both points are null.
I fear we may have been incorrectly relying on `basePoint == null` never being true.
https://github.com/specklesystems/speckle-sharp/blob/fa655fd5e883d5db26e7f3242352b8daa6c63965/Objects/Converters/ConverterRevit/ConverterRevitShared/Partial%20Classes/ConvertFamilyInstance.cs#L277-L280
> Objects: null point equality operator fix

- ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/Entry/ConnectorRhinoCommand.cs
- ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/Entry/Plugin.cs
Disable Rhino Connector on Mac only to prevent issue #1277.
> THIS IS NOT A FIX, JUST A PATCH.
TODO:
#1277 
Avalonia is not playing nice with Rhino at the moment, causing it to hijack the top-menu and making any items un-clickable.
This only happens as soon as we call the `Init` method inside our `Plugin` class, so I moved the initialisation to whenever we call `CreateOrShowSpeckle()`.
This allows me to directly show a warning on Mac before any Avalonia logic get's executed.
For now, the warning directs the user's to use Speckle Grasshopper, as it is installed alongside Rhino and does not suffer from these problems.
If necessary, the plugin can still be enabled manually from the settings page (this will cause the menu issue to occurr though... but the connector works fine otherwise.
> Patch(Rhino): Temporarily disable Rhino on Mac and delay `Init` call

- ConnectorArchicad/ConnectorArchicad/ConnectorBinding.cs
- ConnectorAutocadCivil/ConnectorAutocadCivil/UI/ConnectorBindingsAutocadCivil.cs
- ConnectorCSI/ConnectorCSIShared/UI/ConnectorBindingsCSI.Recieve.cs
- ConnectorCSI/ConnectorCSIShared/UI/ConnectorBindingsCSI.Send.cs
- ConnectorMicroStation/ConnectorMicroStationOpenShared/UI/Bindings2.cs
- ConnectorRevit/ConnectorRevit/UI/ConnectorBindingsRevit2/ConnectorBindingsRevit2.Receive.cs
- ConnectorRevit/ConnectorRevit/UI/ConnectorBindingsRevit2/ConnectorBindingsRevit2.Send.cs
- ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/UI/ConnectorBindingsRhino.cs
- ConnectorTeklaStructures/ConnectorTeklaStructuresShared/UI/ConnectorBindingsTeklaStructure.Send.cs
- ConnectorTeklaStructures/ConnectorTeklaStructuresShared/UI/ConnectorBindingsTeklaStructures.Receive.cs
- ConnectorTeklaStructures/ConnectorTeklaStructuresShared/UI/ConnectorBindingsTeklaStructures.Selection.cs
- DesktopUI2/DesktopUI2/ConnectorBindings.cs
- DesktopUI2/DesktopUI2/DummyBindings.cs
- DesktopUI2/DesktopUI2/ViewModels/StreamViewModel.cs
- Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.BuiltElements.cs
While testing, discovered that toggling preview send and receive on and off was creating report issues in rhino, and null converter was casuing crashes. Also, the preview button was enabled even if the method was not implemented. This fix includes:
DUI: 
- disabling the preview button on send/receive if the corresponding method has not been implemented. The most stable option for doing that was a bit messy: added 2 new abstract prop bindings
Rhino:
- named views and blocks were previously not being baked on receive if previewed first, this has been fixed
- converter throwing null exception in switching between preview send and receive, fixed
- report objects not being updated when toggling between send and receive or toggling the preview button on/off, fixed
- preview not automatically …
> fix(dui2/rhino): preview and report bugs

- ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/Entry/ConnectorRhinoCommand.cs
- ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/Entry/Plugin.cs
Fixes hard crash in Rhino Windows when loading the Speckle DUI for the first time.
This was a side-effect of having an `Init` method call wrapped in a `DEBUG` preprocessor directive, which made it work on local but not when released.
> fix(rhino): Init call in RunCommand was debug only

- ConnectorGrasshopper/ConnectorGrasshopper/BaseComponents/SelectKitTaskCapableComponentBase.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Conversion/DeserialiseTaskCapableComponent.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Conversion/SerialiseTaskCapableComponent.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Conversion/ToNativeTaskCapableComponent.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Conversion/ToSpeckleTaskCapableComponent.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Objects/CreateSpeckleObjectByKeyValueTaskComponent.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Objects/CreateSpeckleObjectTaskComponent.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Objects/DeconstructSpeckleObjectTaskComponent.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Objects/Deprecated/ExpandSpeckleObjectTaskComponent.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Objects/ExtendSpeckleObjectByKeyValueTaskComponent.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Objects/ExtendSpeckleObjectTaskComponent.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Objects/GetObjectValueByKeyTaskComponent.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Ops/Deprecated/Operations.ReceiveComponent.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Ops/Deprecated/Operations.SendComponent.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Ops/Deprecated/Operations.SendComponentSync.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Ops/Deprecated/Operations.VariableInputSendComponent.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Ops/Operations.ReceiveLocalComponent.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Ops/Operations.SendLocalComponent.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Ops/Operations.SyncSendComponent.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Ops/Operations.VariableInputReceiveComponent.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Ops/Operations.VariableInputSendComponent.cs
- ConnectorGrasshopper/ConnectorGrasshopper/SchemaBuilder/CreateSchemaObject.cs
- ConnectorGrasshopper/ConnectorGrasshopper/SchemaBuilder/CreateSchemaObjectBase.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Streams/StreamCreateComponent.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Streams/StreamDetailsComponent.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Streams/StreamGetComponent.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Streams/StreamListComponent.cs
- ConnectorGrasshopper/ConnectorGrasshopper/Streams/StreamUpdateComponent.cs
- Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.Geometry.cs
This PR fixes:
- Bug where a non existent `commit url` would not report an error to the user when plugged into the receive node (or attempting to receive).
- Adds `ToFormattedString` to all user facing instances where exception messages are shown (i.e. any AddRuntimeException() call. We were previously unwrapping the inner exception, but that doesn't print the entire error message in some cases.
> GH: Use `ToFormattedString` everywhere + fix non-existent commit error message in receiver

- ConnectorGrasshopper/ConnectorGrasshopper/Loader.cs
Closes #1601
Instead of just skipping the menu creation, I'm deleting it and creating it again to ensure all events are properly set.
> fix(gh): Unload top-menu if it exists before loading

- ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/UI/ConnectorBindingsRhino.cs
- ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/Utils.cs
When receiving commits with objects with duplicate ids, the `FlattenCommitObject()` method throws an exception (happened with Revit sample house)
Fixes this issue by adding a log item to any objects that have already been processed with the same id.
**note**: should investigate revit objects that have duplicate ids
Also, fixes a bug where render material settings were not being used for receiving objects without a display style
Received Sample House from RevitTestStream:
Log of a few revit items with duplicate ids:
Objects.BuiltElements.Revit.RevitWall 1fd359cab74929fa2a2476a3a27d47b5 Created
Found another Objects.BuiltElements.Revit.RevitWall in this commit with the same id. Skipped other object
Found another Objects.Geometry.Mesh in this commit with the same id. Skipped …
> hotfix(rhino): handles commits with objects with duplicate ids

- .circleci/scripts/config-template.yml
- Objects/Tests/GenericTests.cs
- Objects/Tests/Tests.csproj
Adds a step in `build-objects` to run the Objects unit tests (currently quite lacking).
Adds unit test to ensure **all objects in `ObjectsKit`** have an empty constructor implemented.
In order to not duplicate builds, `build-objects` will now only build:
- `Objects.csproj`
- `Tests.csproj`
All other projects correspond to `Converters` that are already being built on each of their respective `Connector` builds.
This also allowed to change the VM from windows to linux, which has less minute cost.
> Objects: Adds tests to CI job

- ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/Entry/Plugin.cs
Uses [HostUtils.GetCurrentProcessInfo](https://developer.rhino3d.com/api/RhinoCommon/html/M_Rhino_Runtime_HostUtils_GetCurrentProcessInfo.htm) to check if Rhino is running inside something and then it stops loading the Speckle plugin.
This is because it seems Rhino might get loaded before the Revit connector at times?
See: https://speckle.community/t/revit-command-failure-for-external-command/3489/27
> fix(rhino): disable Speckle when using Rhino.Inside.Revit, attempt #2

- Core/Core/Models/Base.cs
- Core/Core/Models/DynamicBase.cs
- Core/Core/Models/DynamicBaseMemberType.cs
- Core/Examples/ExampleApp.csproj
- Core/IntegrationTests/TestsIntegration.csproj
- Core/Tests/BaseTests.cs
- Core/Tests/TestsUnit.csproj
- Objects/Tests/Utils/ShallowCopyTests.cs
Fixes #
When`Base.ShallowCopy` was called, it will use `GetMembers`, which was not coded to exclude Obsolete properties, which would cause:
- `displayValue` to be set, but also
- `displayMesh` to be set, which will override the `displayValue` list
To fix this, we had to change the signature of `GetMembers` in a non-breaking way. It now accepts a set of `Flags` that allow you to control which members are included in the output. By default, it works as it used to.
Updated tests to check for these new cases inside `GetMembers`, and changed all hard coded property name strings to use `nameof()` instead so errors will pop up if properties are renamed. Previous tests were checking for _non-inclusion_ of a property that had been renamed, so they would always pass.
> GH: Fixes `ShallowCopy` issue with `displayValue` only containing 1 item

- ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/Entry/Plugin.cs
- ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/UI/Panel.xaml.cs
- DesktopUI2/DesktopUI2/ViewModels/StreamViewModel.cs
**Description:**
Fixes 2 (unlogged) issues in DUI that were affecting the Rhino connector:
1. When the Speckle panel was closed and reopened and the user would click on a Stream, an exception was thrown about a visual parent being reused in Avalonia. This would also crash Rhino.
2. When copy-pasting across different Rhino documents (AND under some other unclear circumstances), the stream edit navigation would break. Nothing was happening when clicking on streams.
**Solution:**
1. A new view model is now generated each time the panel is initiated, instead of reusing one stored in the `SpeckleRhinoConnectorPlugin` class
- note: now, if closing the panel and re-opening it, saved streams in DUI that have not been baked in the file will be lost, but this is probably a very rare use case
3. …
> fix(rhino): stream edit view selection issues in rhino

- ConnectorAutocadCivil/ConnectorAutocadCivil/UI/ConnectorBindingsAutocadCivil.cs
- ConnectorAutocadCivil/ConnectorAutocadCivil/Utils.cs
- ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/UI/ConnectorBindingsRhino.cs
- Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.Civil.cs
- Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.cs
- Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.Other.cs
Adds two main features to the autocad and civil3d connectors: 
- Interactive reports for send and receive, aligning the autocad civil conenctors with functionality in rhino and revit
- Update receive mode that uses application ids of incoming objects to replace existing document objects if they share the same app id
Related to: https://speckle.community/t/speckle-should-be-able-to-update-existing-objects-in-the-dwg-file/3424/2
Part of: #1530
- Autocad Civil3d connector: adds implementation for `SelectClientObjs` binding as a prerequisite for interactive reports 
manually tested sending/receiving in Autocad <> Autocad and Revit > Autocad
> feat(autocadcivil): interactive reports and update receive mode

- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertAnalyticalStick.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertBrace.cs
AnalyticalStick and Brace elements are currently creating duplicate elements on receive when the receive mode is set to update.
- assign applicationId to analytical stick elements in AnalyticalStickToNative
- manual tests sending and receiving structural object commits and braces.
- duplicates are no longer created for Element1D elements when the receive mode is set to update.
> Fix(Revit): Structural objects not updating (creating duplicates)

- ConnectorAutocadCivil/ConnectorAutocadCivil/UI/ConnectorBindingsAutocadCivil.cs
- ConnectorAutocadCivil/ConnectorAutocadCivil/Utils.cs
- ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/UI/ConnectorBindingsRhino.cs
- Core/Core/Models/Extras.cs
- Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/Converter.AutocadCivil.Utils.cs
- Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.Civil.cs
- Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.cs
- Objects/Objects/BuiltElements/Alignment.cs
This pr improves receiving alignments:
- Reference station point is now being set on receive
- In update mode, alignments are updated in place with a new reference station, and new segments or a new offset (for offset alignments). Layer will remain unchanged. This allows for featurlines referencing the alignment to remain intact on receive!
- Improves sending and receiving offset alignments: previously these were always being created as regular alignments. Now on receive, if the parent exists in the doc they will properly be linked to the parent as an offset
- also fixes a naming bug where the ToNative() method throws on creation if a duplicate name exists. 
Closes #1626
- Autocadcivil connector
- Autocadcivil converter
- small core change in updating Applicationobject to include …
> feat(civil3d): update alignments on receive

- Objects/Objects/BuiltElements/TeklaStructures/Bolts.cs
- Objects/Objects/BuiltElements/TeklaStructures/TeklaContourPlate.cs
- Objects/Objects/BuiltElements/TeklaStructures/Welds.cs
Removes `displayMesh` properties in non-IDisplayMesh elements:
- Bolts
- TeklaContourPlate
- Welds
> fix(objects): Removed non IDisplayMesh `displayMesh` properties

- ConnectorDynamo/ConnectorDynamo/ReceiveNode/Receive.cs
- ConnectorDynamo/ConnectorDynamo/SendNode/Send.cs
- ConnectorDynamo/ConnectorDynamoFunctions/BatchConverter.cs
- ConnectorDynamo/ConnectorDynamoFunctions/Developer/Conversion.cs
- ConnectorDynamo/ConnectorDynamoFunctions/Developer/Local.cs
- ConnectorDynamo/ConnectorDynamoFunctions/Functions.cs
- Core/Core/Credentials/StreamWrapper.cs
- Core/Core/Models/Base.cs
- Core/Core/Models/DynamicBase.cs
- Objects/Converters/ConverterDynamo/ConverterDynamoShared/ConverterDynamo.Geometry.cs
Closes #1387
- Conversion nodes
- Local transport nodes
- Send nodee
- Receive node
Bonus:
- Modified `MeshToNative` to use `TriangulateMesh` instead of `TriangulateFace` to remove duplication of code, since N-gons are not supported in Dynamo.
> feat(Dyn): Send/Receive tolerate conversion errors and reports them as node warnings

- .circleci/scripts/config-generator.py
- .circleci/scripts/config-template.yml
- .circleci/scripts/connector-jobs.yml
- ConnectorArchicad/ConnectorArchicad/ConnectorArchicad.csproj
- ConnectorArchicad/ConnectorArchicad/Properties/AssemblyInfo.cs
Fixes CI deploy jobs for mac, which were not uploading due to misconfiguration on the extension and expected file name.
**Mac deploys**:
- The output of our mac installer build would be called `rhino-mac.zip`, following the `slug`. The slug has now been changed to be universal (`i.e. `rhino` or `grasshopper`), and the deploy job uses the correct parameters for `os` and `arch`.
- Added `arch` parameter to the `deploy-connector-new` job
- Extension parameter was not being used in all necessary places.
- `deploy-connectors` job no longer uploads to the new manager. Instead, it's just used as a buffer step to wait for all `build` jobs to be completed before proceeding to deployment.
- Some changes were made on the `Speckle.Manager.Feed` CLI so that the job would fail if the upload is not …
> fix(ci): All mac connectors and Archicad for windows deployment

- ConnectorAutocadCivil/ConnectorAutocad2021/ConnectorAutocad2021.csproj
- ConnectorAutocadCivil/ConnectorAutocad2022/ConnectorAutocad2022.csproj
- ConnectorAutocadCivil/ConnectorAutocad2023/ConnectorAutocad2023.csproj
- ConnectorAutocadCivil/ConnectorCivil2021/ConnectorCivil2021.csproj
- ConnectorAutocadCivil/ConnectorCivil2022/ConnectorCivil2022.csproj
- ConnectorAutocadCivil/ConnectorCivil2023/ConnectorCivil2023.csproj
- ConnectorCSI/ConnectorCSIBridge/ConnectorCSIBridge.csproj
- ConnectorCSI/ConnectorSAFE/ConnectorSAFE.csproj
- ConnectorCSI/ConnectorSAP2000/ConnectorSAP2000.csproj
- ConnectorDynamo/ConnectorDynamo/ConnectorDynamo.csproj
- ConnectorGrasshopper/ConnectorGrasshopper/ConnectorGrasshopper.csproj
- ConnectorMicroStation/ConnectorMicroStation/ConnectorMicroStation.csproj
- ConnectorMicroStation/ConnectorOpenBuildings/ConnectorOpenBuildings.csproj
- ConnectorMicroStation/ConnectorOpenRail/ConnectorOpenRail.csproj
- ConnectorMicroStation/ConnectorOpenRoads/ConnectorOpenRoads.csproj
- ConnectorTeklaStructures/ConnectorTeklaStructures2020/ConnectorTeklaStructures2020.csproj
- ConnectorTeklaStructures/ConnectorTeklaStructures2021/ConnectorTeklaStructures2021.csproj
Adds <PlatformTarget> to all connector projets that were missing it.
Moved it to a global position in all connectors that only had it on `debug`
> Fix: Adds <PlatformTarget> property to all connector csproj files

- Objects/Converters/ConverterRevit/ConverterRevitShared/ConversionUtils.cs
error was being thrown when the "GetExistingElementsByApplicationId" function was returning null and then we were trying to call the .firstordefault() function on a null value.
GetExistingElementsByApplicationId now returns an empty list so the .firstordefault function won't throw an error
> Fix(Revit): null value error for GetExistingElementsByApplicationId

- ConnectorRevit/ConnectorRevit/ConnectorRevitUtils.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Categories.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertSpace.cs
MEP spaces are currenly not selectable as a category to send to speckle
Closes https://github.com/specklesystems/speckle-sharp/issues/1714
- adds spaces as a supported built in category
- enable sending space will a null outline
Community request https://speckle.community/t/send-spaces-from-revit/3801
> Fix(Revit): add "spaces" as sendable category

- Objects/Converters/ConverterRevit/ConverterRevitShared/ConverterRevit.cs
The converter has been checking for a specific setting when trying to receive, but if that value is null (we don't have the settings in Revit 19) then the conversion fails
- add default value when setting is null
This should fix the issue brought up here https://speckle.community/t/revit-2020-2019-empty-file-warning-value-cannot-be-null/3727/3
> Fix null value for receive mode setting

- ConnectorDynamo/ConnectorDynamo/ReceiveNode/Receive.cs
- ConnectorDynamo/ConnectorDynamoFunctions/Utils.cs
Dynamo was unable to find it's own Revit converter's due to a mismatch in the versions it was looking for.
Versions in connector and converter are now aligned.
Part of #1733
> Fix(dyn): Fixes the Converter loading issues with Dynamo

- Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/Converter.AutocadCivil.Utils.cs
- Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.Civil.cs
The `GetFromObjectIdCollection()` util method in the acadcivil converter wasn't previously checking whether or not an existing prop has a getter. This was breaking alignment to native conversions when trying to retrieve the alignment style.
Method has been updated to return a defualt value if null, and also to check for `CanRead` before accessing an object prop.
Fixes #1708 
AutocadCivil converter: Utils and AlignmentToNative conversion
Alignments received in new docs are now created without error.
> fix(autocadcivil): get from id collection should check for `CanRead` prop

- Objects/Converters/ConverterRevit/ConverterRevitShared/ConversionUtils.cs
- found an edge case where two objects can return the same hosted elements when the `host.FindInserts(true, false, false, false)` is called. To reproduce, receive [this commit](https://latest.speckle.dev/streams/f8991bf79d/commits/0281d670e1) into Revit and then try to send it back to speckle.
- When this happens, the first host tries to convert the objects and removes them from the contextObjects, but the conversion fails because the elements are hosted and the other host is still in the context objects. Therefore the conversion returns null assuming that the other host element will convert these objects. However, this doesn't happen because the objects have already been removed from the ContextObjects list (aka they are assumed to have already been converted) 
- Don't remove hosted …
> Fix(Revit): Don't remove context object unless it converts successfully

- Objects/Converters/ConverterRevit/ConverterRevitShared/ConversionUtils.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertBlock.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertGeometry.cs
[here](https://latest.speckle.dev/streams/85bc4f61c6/commits/52382fa1d8) is a stream that I sent from Rhino to Speckle. When receiving to Revit, every BREP and block instance was failing with a warning about invalid characters.
This is an example of one of the material names that it was trying to copy, "RhinoTestStream[ 1 standard/meters @ f093ffcc80 ] - default"
According to the [RevitApiDocs](https://www.revitapidocs.com/2023/5d8f8735-b814-5ac0-e8c5-114da8caa7bc.htm), there are several prohibited characters that cannot be used in a material name. This pr removes those prohibited characters.
now deleting all prohibited characters from the material name and the group name before trying to create those elements 
Receiving the commit linked above now works
> Fix(Revit): invalid characters causing object conversion failure

- ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/UI/ConnectorBindingsRhino.cs
Fixes behavior in the update receive mode to check for an object's `applicationId` user string for a match before checking for an object's guid.
This should align expected behavior when updating received objects in a new rhino file
Fixes #1727 
Recieved Rhino test file commit in new Rhino file, moved some recieved objects, received again in update mode (moved objects were moved back)
> fix(rhino): update receive mode checks for user string before guid match

- ConnectorDynamo/ConnectorDynamo/ReceiveNode/Receive.cs
- ConnectorDynamo/ConnectorDynamoFunctions/BatchConverter.cs
- ConnectorDynamo/ConnectorDynamoFunctions/ConnectorDynamoFunctions.csproj
- ConnectorDynamo/ConnectorDynamoFunctions/Functions.cs
- ConnectorDynamo/ConnectorDynamoFunctions/OnErrorEventArgs.cs
- Fixes #1733 
Receive node would swallow any deserialisation errors reported when expiring the node.
These changes just ensure that if a deserialisation error occurs, we report it to the user straight away and stop any further action.
Bonus:
- Fixes #1729 by just removing `EventArgs` as the parent of `OnErrorEventArgs`
> Dynamo: Handle deserialisation errors on Receive

- .circleci/scripts/config-template.yml
- ConnectorTeklaStructures/ConnectorTeklaStructures2021/ManifestGenerator.xml
Fixes #1630 
Tekla TSEP build step was removed last release because it was blocking our release while Rey was on vacation.
The issue with that step was that Tekla connector requries a `Manifest.xml` file that contains **all of the files the TSEP plugin should contain**.
This mainfest file is generated using a T4 template on the Tekla project, but it is not hooked up to be automatically updated on every build (to be fixed on issue #1749)
> fix(tekla): Regenerated Tekla's `ManifestGenerator.xml` and re-added C tsep build step

- .circleci/scripts/config-template.yml
An old part of our CI designed to work for the old deploy mechanism was creating the same `latest.yml` file in 2 different workspaces, causing CircleCI to freak out and fail all deploy jobs.
This is an urgent fix so it shall be merged directly.
> fix(CI): Remove old .yml file creation

- ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/UI/ConnectorBindingsRhino.cs
The Rhino update mode was not properly handling objects with null `applicationId` and therefore removing all previously baked objects with no `applicationId` user string.
Fixes #1775
Received https://speckle.xyz/streams/17b0b76d13/commits/c028853130?c=%5B283000.97965,5709543.66179,1602.16947,283676.88013,5709951.8115,543.55274,0,1%5D on update mode
> hotfix(rhino): handles null app ids on update receive mode

- .circleci/scripts/config-template.yml
- Objects/Converters/ConverterDxf/ConverterDxf.Tests/ConverterDxf.Tests.csproj
- Objects/Converters/ConverterDxf/ConverterDxf.Tests/ConverterFixture.cs
- Objects/Converters/ConverterDxf/ConverterDxf.Tests/ConverterSetup.cs
- Objects/Converters/ConverterDxf/ConverterDxf.Tests/Geometry/BrepTests.cs
- Objects/Converters/ConverterDxf/ConverterDxf.Tests/Geometry/CurveTests.cs
- Objects/Converters/ConverterDxf/ConverterDxf.Tests/Geometry/MeshTests.cs
- Objects/Converters/ConverterDxf/ConverterDxf.Tests/Geometry/VectorTests.cs
- Objects/Converters/ConverterDxf/ConverterDxf/ConverterDxf.csproj
- Objects/Converters/ConverterDxf/ConverterDxf/SpeckleDxfConverter.Document.cs
- Objects/Converters/ConverterDxf/ConverterDxf/SpeckleDxfConverter.Geometry.cs
- Objects/Converters/ConverterDxf/ConverterDxf/SpeckleDxfConverter.Units.cs
- Objects/Converters/ConverterDxf/ConverterDxf/SpeckleDxfConverter.cs
- Objects/Converters/ConverterRhinoGh/ConverterGrasshopper7/ConverterGrasshopper7.csproj
Fixes an issue introduced in #1621 inadvertently.
The PR modified the `Objects` job to run on bash instead of powershell. This seemed like the right choice at the time, since it simplified setup, reduced credit cost and actually ran faster.
I did not realise at the time that our `packandpublish` command was written in `powershell` so it would throw a syntax error on any jobs running on `bash`.
This PR fixes the issue by creating a specific job to pack and publish when using `bash` that follows the same logic.
Had to downgrade `ConverterDxf` language version usage to the default, as it was using version `9` and it was causing issues when building. Required some updates on the DXF tests to get them to work again too.
> fix(ci): Adds `packandpublish-bash` for any bash jobs that require nuget pushing

- ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/Entry/ConnectorRhinoCommand.cs
Adds Warning to not use Rhino for Mac (while we fix the issue with the top-menu (#1277).
It was accidentally removed when we fixed the SQLite build process for mac and windows.
> fix(rhino): Prevent Rhino from loading... again

- ConnectorArchicad/ConnectorArchicad/ConnectorArchicad.csproj
The `MSBuild.AssemblyInfo` was removed by @jozseflkiss because it was conflicting with his build process in Mac.
It is required for Innosetup to properly pick up the version when creating the installer.
Since Innosetup is windows only, i've also added a condition to prevent it from messing up with the mac build.
Tested on my computer and it works like a charm.
> fix(archicad): Added msbuild.assemblyinfo nuget for windows only (needed for Innosetup)

- Objects/Objects/BuiltElements/Conduit.cs
- Objects/Objects/BuiltElements/Fitting.cs
- Objects/Objects/BuiltElements/Network.cs
Adds the following classes to Objects:
- `Network`: organizational class representing graph connections for built elements objects like ducts, pipes, etc
- `NetworkElement`: element in a network (graph nodes)
- `NetworkLink`: links in a network (graph edges)
- revit subclasses for network element and link
- `Fitting`: new mep class
This is a prerequisite for handling sending and receiving revit mep elements that are connected to eachother.
Closes #1427
- Objects
**NOTE** some properties on the revit classes may potentially be deprecated with the Revit mep network PR if their supported function can be moved to the Revit connector or converter.
> feat(objects): adds network and mep classes

- ConnectorGrasshopper/ConnectorGrasshopperShared/Extras/SpeckleBaseParam.cs
This allows GH users to distinguish between a Speckle object and one that is not.
Fixes #1789
> feat(gh): Made GH_SpeckleBase public

- Objects/Objects/Geometry/Arc.cs
- Objects/Tests/Geometry/ArcTests.cs
Fixes #1419
While investigating the aforementioned issue, I discovered that the Arc constructor was missing the plane assignment, leading to it being `null`.
Also adds a test in the Objects test project to verify that #1419 is not an actual issue.
> fix(objects): Missing plane assignment in arc constructor

- ConnectorGrasshopper/ConnectorGrasshopperShared/Objects/ExtendSpeckleObjectTaskComponent.cs
Fixes #1829 
Aligns the `ESO` input verification with the `DSO` node, which already included a provision to test for `Base` as a value of any `IGH_Goo`.
This issue was not a problem within our own components, but a result of 3rd party nodes generating `GH_ObjectWrapper` classes containing base objects.
> Fix(gh):  Handle `GH_Goo<Base>` objects in `ESO`

- Core/Core/Models/DynamicBase.cs
- Core/Core/Models/DynamicBaseMemberType.cs
- Core/Tests/BaseTests.cs
Closes #1033 
This is the first step on removing the super misleading methods to retrieve the member names from a `DynamicBase` object. The affected methods in this PR all return a `List<string>` and already have an equivalent in the `GetMembers` method using the appropriate `DynamicBaseMemberType` flags
The following methods have been flagged as `Obsolete`, but **will not throw errors yet**:
`GetInstanceMembers` in both its static and non-static form remains as-is, as it has a different return type and it's used in different ways, I decided to leave it out of the scope of this
- Added some extra options in `DynamicBaseMemberType` to make it easier to find the equivalent of each obsolete method.
- `InstanceAll` will return all instance members including schema ignored and obsolete.
- …
> refactor(core): Flags DynamicBase misleadingly named methods as obsolete

- Core/Core/Kits/KitManager.cs
- Objects/Objects/ObjectsKit.cs
**🙌 this PR touches delicate parts of Speckle!**
The suggested changes were discussed with Dim and allow us to safely reference `Objects` in DUI for us to unlock some features in the Mapping tool ([see](https://www.notion.so/speckle/CAD-to-BIM-4bde12f16ab847c788b17bce9b55fa25#79ec640a6d27482dbcfa21cffb4d8bff)).
What this does:
- if Objects.dll is already loaded in the AppDomain, currently, the Kit only looks for converters in the same directory
- if Objects.dll is also referenced by DUI (or any other plugin used by the host app) there will not be any converters in the same folder (because it will be in the connector folder instead)
- these changes allow falling back to the default Kits/Objects folder in the above scenario
NOTE: while DUI will reference Objects for use in the Mapping tool, …
> feat(core): fallback to default Objects folder if no converter is found

- ConnectorGrasshopper/ConnectorGrasshopperShared/Extras/Utilities.cs
- ConnectorGrasshopper/ConnectorGrasshopperShared/Ops/Operations.VariableInputSendComponent.cs
- Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.Geometry.cs
Fixes #1324 
When encountering a mesh with no faces or vertices, we will now return `null` instead of sending a mesh that won't work anywhere.
This has been tested in Rhino and Grasshopper and does not interfere with the send operation.
> feat(gh): Prevents empty meshes from being sent

- ConnectorRevit/ConnectorRevit/UI/ConnectorBindingsRevit2/ConnectorBindingsRevit2.Events.cs
- ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/UI/ConnectorBindingsRhino.cs
I added new view to rhino named view `SpeckleCommentView` when user want to see it by clicking
`CanOpen3DView`and `Open3DView` binding methods are overriden in `ConnectorBindingsRhino` file.
According to upcoming coordinates camera position and target constructed as `Point3d` and `Vector3d` to assign them into `RhinoView`.
- Create a comment from speckle.xyz
- Receive it by Rhino
- Navigate to comments tab
- Click Open View 📷
> feat(rhino): open comments in 3D view

- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertNetwork.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertPipe.cs
- Objects/Objects.sln
- Objects/Objects/BuiltElements/Network.cs
Fixes some issues receiving mep networks in Revit, including:
- removing `JsonIgnore` flags on revit network link tags as these are actually set on send and not on receive
- `Conduit` bug handling
- omitting some extra `Pipe` props on send to prevent incorrect elevations on receive
- Objects
> fix(revit): bug fixes for receiving mep networks

- DesktopUI2/DesktopUI2/Views/Windows/Dialogs/DialogUserControl.cs
In some cases, such as exception dialog, they would not show up. 
The second dialog will show and close because the first dialog set `MainViewModel.Instance.DialogBody` to `null`. 
Like the example below I will not see a dialog indicating the reason for the failure.
https://github.com/specklesystems/speckle-sharp/blob/2cf08671f6ef70ce400a123bbf7237f9b8c46664/DesktopUI2/DesktopUI2/ViewModels/HomeViewModel.cs#L586-L618
Set `MainViewModel.Instance.DialogBody` to `null` before invoke `Closed` event.
> fix(dui): dialog conflict

- Core/Core/Api/Helpers.cs
Reverts to using `Environment.SpecialFolder.ApplicationData` to get the user app data folder, and introduces a `SPECKLE_USERDATA_PATH`  env variable to override it.
More info: https://www.notion.so/speckle/Default-Speckle-folder-in-Core-7a173b67869d468882074b300d4ba781
> feat(core): changes how the user app data folder is retrieved

- ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/UI/ConnectorBindingsRhino.cs
Fixes issue 2.10 issue with sends getting stuck with "everything" filter
A small null check was all that's needed.
> fix(rhino): fixed issue with everything filter

- ConnectorCSI/ConnectorCSIShared/UI/ConnectorBindingsCSI.Selection.cs
When receiving a commit into Speckle and then trying to send it to Speckle again, my speckle commits were not showing any displayable objects in them. Upon further investigation I found that the master list of object IDs that the send operation then narrows down to your specified filter (Everything, Selection, Group, etc.) is only refreshed in the GetSelectionFilters() method which is only called when a user opens a stream view. Therefore between the actions of receiving and sending, the master list of elements is never refreshed (unless the user goes back to the main list of streams and re-opens the stream view) which makes the send operation show 0 visible elements.
It sounds reasonable to assume that we could maybe only call this method once when the user opens the stream view, as most …
> Fix(CSI): refresh objects list every time we send to Speckle

- ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/UI/ConnectorBindingsRhino.cs
Previously, blocks were being deleted prematurely in the connector receive logic because they were created during convert instead of on bake (this hypothetically applies to views too? need to check view update behavior)
Now, blocks and views are skipped during conversion and created on bake, since the converter methods for these two types add the objects to modelspace during conversion.
Fixes #1909
> fix(rhino): successfully converts blocks on receive

- Objects/Converters/ConverterRevit/ConverterRevitShared/Revit/ConnectionPair.cs
Fixes error that was stopping Revit elements from being sent to Speckle
- add initial value of 0 to connection pair dimensions
- don't try to set dimensions if the connectorProfileType is invalid
- was getting an error that said "The shape of the connector is neither rectangular nor oval." but now we are not getting that error
this partially fixes this issue https://github.com/specklesystems/speckle-sharp/issues/1915
> Fix(revit): MEP elements handle invalid shape

- ConnectorAutocadCivil/ConnectorAutocadCivil/UI/ConnectorBindingsAutocadCivil.cs
- ConnectorAutocadCivil/ConnectorAutocadCivil/Utils.cs
- adds check for erased ids to not be included as objects to remove
- assigns the correct application id from xdata on send, if present
Fixes #1889
*NOTE* this does not fix the incorrect update behavior when receiving elements from autocad in a new autocad file - this is due to a limitation in how Autocad generates its persistent ids (`handle`s), which are very short and always generated from the same seed. Ref [this forum post](https://forums.autodesk.com/t5/net/is-the-quot-objectid-quot-unique-in-a-drawing-file/m-p/6527799#M49953) explaining the difference and why handle duplication is unavoidable
- connector bindings
- connector utils
> fix(acadcivil): application id handling fixed on send

- Objects/Converters/ConverterRevit/ConverterRevitShared/ConversionUtils.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertMeshUtils.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertView.cs
Sometimes when receiving into revit, no error gets thrown yet the entire transaction will get rolled back during the transation. I found one specific case where this was being caused by trying to import a perspective 3D view and setting the "VIEW_NAME" property. The erroreater was throwing an error talking about a name already existing in the project.
It seems like the view name property for this view was temporarily changed to the same name as an existing view before being changed to a unique name. We've seen instances before where objects become invalid for a split second but then become valid again and the receive process continues without throwing an error until the commit operation causes the whole transaction to be rolled back (ref [this …
> Fix(Revit): don't set view name parameter and fix null value error

- Core/Core/Kits/KitManager.cs
Seems like the new logic added in [#1924](https://github.com/specklesystems/speckle-sharp/pull/1924) was not working well in Revit, as some of the loaded assemblies were null.
This nul check seems to do the job.
> fix(core): null check for GetReferencedAssemblies

- .circleci/scripts/config-template.yml
Adds the `Version` parameter to the msbuild job on mac.
This was already applied in the `unless` clause of the `build-with-mono` param, but was not reflected in the initial conditional steps.
Fixes #1910
> fix(ci): Re-add version param to build with mono step

- ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/UI/ConnectorBindingsRhino.cs
Fixes a bug introduced with the rhino block bug pr where `ConvertObject` in the connector was expecting a convertible `Base`, not a `ApplicationObject`
- Rhino Connector
> fix(rhino): incorrect arg type for ConvertObject method

- ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/UI/ConnectorBindingsRhino.cs
When receiving on update mode, received objects will now be placed on the same layer as the object they are replacing if they exist.
Also fixes a bug where previously updated objects were being shown as created instead of updated in the report.
Fixes #1836
> fix(rhino): uses existing object layer when receiving on update mode

- ConnectorRevit/ConnectorRevit/UI/ConnectorBindingsRevit.Send.cs
Currently when sending large amounts of objects to Speckle (more than a few hundred) the screen will freeze up until the operation is successful. Which could take a very long time. Unfortunately this also freezes up the progress bar so you don't know how much longer the operation will.
Pause execution of the UI thread for 1 ms after each object is converted in order to execute the user's interactions. 
The code is identical to the code that we use during the receive operation except the token cancels after 1 ms instead of 5. I didn't do any benchmarking but I found that both produced similar results so I just used the lower value.
Before:
After:
Screen now not frozen during large send operations.
> Fix(Revit): Keep UI refreshed during send operation

- Objects/Objects/Other/Transform.cs
Fixes the iteration logic of `ApplyToVector` in our `Transform` class. This was causing `GetInsertionPlane` to return incorrect planes, resulting in failed receives in Dynamo.
Fixes #1949
Fixes #1683 
Objects
> hotfix(objects): incorrect application of `Transform` to vector

- DesktopUI2/DesktopUI2/ConnectorBindings.cs
- DesktopUI2/DesktopUI2/ViewModels/StreamViewModel.cs
- DesktopUI2/DesktopUI2/Views/Controls/StreamEditControls/Receive.xaml
- DesktopUI2/DesktopUI2/Views/Controls/StreamEditControls/Send.xaml
- DesktopUI2/DesktopUI2/Views/Pages/StreamEditView.xaml
Some connectors cannot receive, eg Navisworks, this PR adds a virtual binding prop to specify if Receive should be enabled or not.
This PR also fixes the "advanced settings" button not being hidden when no settings were available for the connector.
> feat(dui): adds support for hiding the receive tab

- ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/UI/ConnectorBindingsRhino.cs
Previously, receiving in Rhino always creates a top layer with the stream, branch, and commit info, except in update mode where the received object is placed in the same layer as the object it is replacing.
Now, the top commit layer will only be created in `Create` receive mode.
In `Update` mode, objects will be placed in the layer structure as determined by the commit traversal. This means any object that is replacing an existing object in the rhino file will no longer be placed in the existing object's layer.
Fixes #1836 
Before:
After (update mode):
After (create mode):
> fix(rhino): no longer using commit top layer in update receive mode

- Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.Geometry.cs
Fixes #1967
Removed the welding step on our displayMesh creation logic for all `Breps`
This will result in some duplicated vertices (i.e. minor increase in size) but has the benefit of rendering correctly on the viewer.
> fix(rhino/gh): Do not weld Brep displayMeshes anymore

- ConnectorAutocadCivil/ConnectorAutocadCivil/UI/ConnectorBindingsAutocadCivil.cs
- ConnectorRevit/ConnectorRevit/UI/ConnectorBindingsRevit.Events.cs
- ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/UI/ConnectorBindingsRhino.cs
- DesktopUI2/DesktopUI2/ViewModels/StreamViewModel.cs
- Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.Other.cs
- Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.BuiltElements.cs
- Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.Geometry.cs
- Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.Other.cs
- Objects/Objects/Other/Transform.cs
Reverts specklesystems/speckle-sharp#1980
Updates between `release` and `main` branches should **always be done with merge commits**.
Reverting this PR bc it was **squashed merged** instead, which means we loose track of the history and can end up with super complex conflicts in the process
> Revert "Update `release/2.11` with changes in `main`"

- Core/Core/Transports/SQLite.cs
The new `Microsoft.Data.Sqlite` handles network paths differently from the library we had before and this change is to address that.
> fix(core): fixes issues using the new sqlite on network drives

- Core/Core/Transports/SQLite.cs
Brings this hotfix into `release/2.11`
* fix(core): fixes issues using the new sqlite on network drives
* chore: removes duplicated using
> fix(core): fixes issues using the new sqlite on network drives (#1989)

- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertSpace.cs
Issue described here: https://github.com/specklesystems/speckle-sharp/issues/1956
In short, conversion of Revit Spaces without a zone to Speckle raised an error, as an attempt is made to get the `Zone.Name`, without a null check. This check is now implemented.
Only a null check added, literally one character.
Can now send a model including Spaces without Zones to Speckle. Receiving worked fine, and still does.
> Fix(Revit): Allow conversion of Revit Spaces without a zone to Speckle

- Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.Utils.cs
- Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.cs
Rhino hangs when sending objects with invalid user strings, since the connector is attaching user strings as `Base` where each user string key is a prop name and therefore can't contain `./`. 
This fix no longer attaches the user string with invalid chars, and instead reports the missing user string when sending the object.
Fixes #1993 
> fix(Rhino): handle invalid userstrings

- ConnectorCSI/ConnectorCSIBridge/ConnectorCSIBridge.csproj
- ConnectorCSI/ConnectorETABS/ConnectorETABS.csproj
- ConnectorCSI/ConnectorSAFE/ConnectorSAFE.csproj
- ConnectorCSI/ConnectorSAP2000/ConnectorSAP2000.csproj
- ConnectorCSI/DriverCSharp/DriverCSharp.csproj
- ConnectorGrasshopper/ConnectorGrasshopper6/ConnectorGrasshopper6.csproj
- ConnectorRhino/ConnectorRhino7/ConnectorRhino7.csproj
- ConnectorTeklaStructures/ConnectorTeklaStructures2020/ConnectorTeklaStructures2020.csproj
- ConnectorTeklaStructures/ConnectorTeklaStructures2021/ConnectorTeklaStructures2021.csproj
- removes direct depencencies of speckle newtonsoft and sentry from structural connectors
- adds system.forms and windowbase to gh6
- updates hardcoded version of sqlitepclraw.lib.e_sqlite3 in rhino7
> Fix dependency conflicts after update

- Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.Geometry.cs
- Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.Other.cs
- Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.cs
When receiving, `Polycurve`s which need to be converted as individual segments are now reported correctly in DUI.
Reporting for receiving `Hatch`es has also been improved with error logging when individual hatch loops fail.
Part of #1906 
Hatch and Polycurve conversion to native in Autocad
This requires modifying the return type of these methods to `ApplicationObject`
> fix(autocadcivil): polycurve handling and reporting

- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertGeometry.cs
Previously, pointclouds in Revit were being generated with the transform origin, which was cutting off any part of the point cloud file that was below the origin xy plane. This has been fixed to use the pointcloud bounding box minimum plane, so the entire pointcloud should now be correctly captured on send.
Fixes #1816
Revit converter `PointcloudToSpeckle()`
Before:
After:
> fix(revit): uses bbox minimum plane for generating pointclouds

- ConnectorAutocadCivil/ConnectorAutocadCivil/UI/ConnectorBindingsAutocadCivil.cs
- ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/UI/ConnectorBindingsRhino.cs
Adds preview send feature to the autocad / civil3d connector. This feature selects objects that will be sent, and generates a report on the expected status of each object
This includes implementing the `ResetDocument()` and `PreviewSend()` bindings. 
Also includes a minor refactor of the rhino preview send feature, so that the converter isn't being set per object selected, and fixes a bug where objects weren't being logged to the report
Autocadcivil Connector
> feat(acadcivil): preview send

- ConnectorCSI/ConnectorCSIShared/StreamStateManager/StreamStateManager.cs
- ConnectorCSI/ConnectorCSIShared/UI/ConnectorBindingsCSI.ClientOperations.cs
- ConnectorCSI/ConnectorCSIShared/UI/ConnectorBindingsCSI.Recieve.cs
- ConnectorCSI/ConnectorCSIShared/UI/ConnectorBindingsCSI.cs
- ConnectorCSI/ConnectorCSIShared/Util/ConnectorCSIUtils.cs
- ConnectorCSI/ConnectorETABS/ConnectorETABS.csproj
- Objects/Converters/ConverterCSI/ConverterCSIShared/ConverterCSIUtils.cs
- Objects/Converters/ConverterCSI/ConverterCSIShared/Partial Classes/Geometry/ConvertArea.cs
- Objects/Converters/ConverterCSI/ConverterCSIShared/Partial Classes/Geometry/ConvertFrame.cs
- refresh the "Beam Object Connectivity" table as a workaround for a bug on CSI's end where frame elements that are moved via api calls will be moved in the database yet still appear in the previous location in the modelling space
- delete frame elements that were deleted from the stream to mimic the behavior of other connectors (namely Revit)
- cleanup the streamState saving process. Don't call it via the connector because it will be called later from DUI
- because the changes to the user's model cannot be undone (thanks CSI) save a backup in the Speckle folder before making any changes
Sending and receiving the same elements in different locations several times. Now experiencing a fairly smooth user experience)
> fix(csi): frames appear in wrong location & deleted frames not tracked

- .circleci/scripts/config-generator.py
- .circleci/scripts/config-template.yml
- .circleci/scripts/connector-jobs.yml
Due to the recent CircleCI debacle, we've been forced to rotate all credentials. Since we were at it, we converted all repeated env vars into contexts and applied those on the ci jobs.
This is a better strategy than the one we were following previously.
We're also now fetching the `speckle-sharp-ci-tools` repo via `ssh` instead of via a github_token.
> CI: Adds use of contexts and pulling through ssh

- ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/UI/ConnectorBindingsRhino.cs
- Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.BuiltElements.cs
- Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.Other.cs
- Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.cs
Blocks and Views should now be correctly received in update mode, with correct reporting as well.
This also includes an improvement to the block to native methods to handle dynamically detached block properties (eg blocks sent from sketchup)
This fix may be relevant for #1905
Rhino connector and converter
> fix(rhino): updating blocks and views

- .circleci/scripts/config-generator.py
- README.md
Quick fix on the config generator script that was assuming `get-ci-tools` item was a string, but since last Friday it is now an object (as it now needs to have a `context` attached to it to work)
> fix(ci): Prevents duplicate `get-ci-tools` job on deploy

- .circleci/scripts/config-template.yml
To be merged in **main and 2.12**:
- adds verbose output when pushing nugets, so ,see we can understand what's triggering that ghost error in the CI
> ci: verbose output when pushing nugets

- Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.Geometry.cs
Fixes #2064  issue with Box size intervals not being scaled to other dimensions.
The box position would be corrected, but it's intervals would not.
Added an optional input to `IntervalToNative` to pass in the parent object units, since Intervals are unit-less.
> fix(rh/gh): scale intervals in BoxToNative conversion

- ConnectorCSI/ConnectorCSIShared/UI/ConnectorBindingsCSI.Send.cs
- Objects/Converters/ConverterCSI/ConverterCSIShared/ConverterCSI.cs
- Objects/Converters/ConverterCSI/ConverterCSIShared/ConverterCSIUtils.cs
check context objects for an object with a created id equal to an element's GUID. This enables roundtrip workflows (but admittedly it is a bit fragile).
- Set previous objects on send
- Check previous objects for an element that created the object being sent and change the appId if one is found
revit -> csi -> revit now works and updates all member sizes without creating duplicates
> feat(csi): enable roundtripping

- Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.Civil.cs
Try catches retriving corridor surfaces when sending corridors, since accessing corridor surfaces that are null returns an exception.
Fixes #2065
auotcadcivil converter
> fix(autocadcivil): handles null corridor surfaces on send

- DesktopUI2/DesktopUI2/Models/Filters/TreeSelectionFilter.cs
- DesktopUI2/DesktopUI2/Views/Filters/TreeFilterView.xaml
- DesktopUI2/DesktopUI2/Views/Filters/TreeFilterView.xaml.cs
The new Binding defaults to "Multiple + Toggle" modes. Overriding this with "Toggle" allows for restricting to the single selected item.
NB. An opinionated view that Multi-select should be the default.
Additional null checking prior to outputting to the Summary field.
> feature (DUI): TreeViewFilter to allow SelectionMode Binding

- ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/UI/ConnectorBindingsRhino.cs
- ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/Utils.cs
Allow Rhino standard views (viewport) to be included in the send operation.
This wasn’t possible before and a request was made on the community forum about it: https://speckle.community/t/send-the-views-from-reno-grasshopper-to-the-web-version/2109/6
The associated issue : https://github.com/specklesystems/speckle-sharp/issues/919
Ensure the team is ok with this logic:
Standard appearing in the view tab and in their own "Standard views" container:
Test have been manually done in Rhino 7 and Rhino 6. This public stream contains standard views for exemple :
https://speckle.xyz/streams/5827632392/commits/eb333113b8
> Feat(Rhino): include standard views viewport in Project Info when sending

- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertDirectShape.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertFreeformElement.cs
Fixes #2137 
Modifies both leftover references of `GenericModels` category in `FreeformElement` and `DirectShape` conversion.
> fix(rvt): Updates leftover `GenericModels` category references in Revit conversions.

- ConnectorArchicad/AddOn/Sources/AddOn/LibpartImportManager.cpp
- ConnectorArchicad/ConnectorArchicad/Converters/Converters/ObjectConverter.cs
Simple mesh elements are not imported as Objects.
https://speckle.community/t/cant-receive-in-archicad/4906
> fix(archicad): Mesh import

- Objects/Converters/ConverterRevit/ConverterRevitShared/ConversionUtils.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/ConverterRevit.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertAnalyticalStick.cs
- Objects/Objects/Structural/Enums/PropertyType.cs
- Objects/Objects/Structural/Property/SectionProfile.cs
- simple change in conversionUtils because .toString was being called on null members and throwing errors
-  create cache for SectionProfiles so sections don't have to be created every time
- when updating, make sure not to flip the baseLine of elements (this partially fixes https://github.com/specklesystems/speckle-sharp/issues/2164 but not fully)
- don't hard cast curves to a baseLine because that will throw errors sometimes
- use reflection to get all the props of the structuralSection from Revit. There are so many structural section classes in Revit that this seemed like the cleanest solution to me
- change the ShapeType prop of Speckle StructualSections to a virual prop and then give each child prop a default value. It doesn't make sense to always have to tell an angle section that …
> fix(revit): various fixes to analytical elements in Revit

- ConnectorNavisworks/ConnectorNavisworks/Entry/SpeckleNavisworksCommand.cs
Reverts specklesystems/speckle-sharp#2191
Reverting this as it was merged in the wrong branch 🙇🏼‍♂️
> Revert "fix:(navisworks): No longer require wgl."

- ConnectorGrasshopper/ConnectorGrasshopperShared/Conversion/ToSpeckleTaskCapableComponent.cs
- ConnectorGrasshopper/ConnectorGrasshopperShared/SchemaBuilder/CreateSchemaObject.cs
- ConnectorGrasshopper/ConnectorGrasshopperShared/SchemaBuilder/CreateSchemaObjectBase.cs
- ConnectorGrasshopper/ConnectorGrasshopperUtils/ConnectorGrasshopperUtils.csproj
- ConnectorTeklaStructures/ConnectorTeklaStructuresShared/UI/ConnectorBindingsTeklaStructures.cs
- Objects/Converters/ConverterRevit/ConverterRevit2023/ConverterRevit2023.csproj
- Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/BrepEncoder.cs
- Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.Geometry.cs
- Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.cs
- Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGhShared.projitems
- Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/KnotListEncoder.cs
Fixes #2145
Improves compatibility between Rhino and _lesser_ applications with crappy geometry kernels ( 👀 Revit ).
This introduces several changes in the way we convert BREPs that are inspired by the lovely peeps at McNeel, specifically their `BrepEncoder` class inside `Rhino.Inside Revit` (see https://github.com/mcneel/rhino.inside-revit/blob/1.x/src/RhinoInside.Revit/Convert/Geometry/BrepEncoder.cs)
**Preprocess Geometry**:
By pre-processing geometry, what we mean is actually just simplifying the BREP so that it does not include some non-supported features in other software. Namely:
- Knots with lower multiplicity than degree + 1 on edges
- Surfaces that are closed in U or V direction (or both)
- Tiny edges/faces that are too small to be drawn
- Surfaces with kinky seams (i.e. surface …
> feat(Rhino/GH): Adds BREP pre-processing logic to Rhino converter

- ConnectorAutocadCivil/ConnectorAutocadCivil/Utils.cs
- Core/Core/Kits/Units.cs
- Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.Geometry.cs
Adds `USFeet` to units class, and all related unit conversions.
Also added `Yard` conversions because I noticed they were missing.
Closes #2207
Core
Sent geo from Civil3d in us survey feet
> feat(core): adds us survey feet support to units

- .circleci/config.yml
- .circleci/scripts/config-generator.py
- .circleci/scripts/config-template.yml
This changes allow for 3rd party developers PRs to be built without leaking any secrets on our end.
Secrets were already securely stored, and not shared to external repo builds, but our pipeline was still relying on some steps that would fail if secrets were missing (`get-ci-tools` mainly, and any step using the `speckle-sharp-ci-tools/` path)
#2214 was the test PR I made and it seemed to work like a charm.
> feat(ci): Allow external PRs to build

- ConnectorGrasshopper/ConnectorGrasshopperShared/Ops/Operations.VariableInputReceiveComponent.cs
Fixes #2218
On initial start, the receiver may not have started the client request, so waiting for it would result in a null reference exception.
We now ensure the client has been requested and wait for it to be set before proceeding to receive anything.
> fix(gh): Receive node now ensure client has been requested and is ready

- Core/Tests/SerializerNonBreakingChanges.cs
I've implemented a set of Tests that describe the behaviour of our serializer's when we make a changes to Object models.
I've documented which changes to a property's type breaks or maintains backwards compatibility with deserializing older commits. 
And answers the question of 
> If I change a prop from type `X` to type `T`, is that a breaking change?
These document the Current behaviour of our deserialize, not necessarily the behaviour we have designed/taken conscious decisions to maintain support for. And is focused SpeckleSharp and doesn't guarantee that things work the same in SpecklePy, Unreal, or Sketchup.
I've done some tricks to allow unit testing to emulate making changes to object models. This is achieved by re-writing the `SpeckleType` of an object such that it will …
> test(core): Serializer breaking changes tests

- DesktopUI2/DesktopUI2/Models/Filters/TreeSelectionFilter.cs
Implements a Flatten method to make addressing members of the TreeFilter Elements more straightforwardly from a flat List. The hierarchy implicit in the TreeNode structure is not relevant to matching individual selections.
This PR removes the need for Connectors to implement the equivalent method multiple ways.
Change is limited to TreeSelectionFilter
> enhancement(DUI): Adds a Flatten method to the TreeNode class. Closes #2233

- ConnectorNavisworks/ConnectorNavisworks/Bindings/ConnectorNavisworksBindings.Selections.cs
Previous logic was presuming that elements are hidden when all their ancestors in the tree are hidden. This was incorrect as Navisworks sets the hidden logic on the node closest to root that encompasses all children due to be hidden rather than propagating hidden status to all children.
Unhiding an element will clear the hidden status of ancestors and then the tree will reprocess to hide sibling nodes but leave children unaffected.
The change was a shift from `.All` to `.Any` in the `element.AncestorsAndSelf.Any(x => x.IsHidden != true);` check.
> fix(Navisworks): Changes hidden self and ancestor logic. Fixes #2051

- Core/Core/Models/Base.cs
Removes abstract types from speckle type serialization in `Base`.
Closes #2249
Core/Models/Base
Before:
After:
Sent and received block instances
> fix(core): ignore abstract types in `Base.speckle_type` serialization

- ConnectorGrasshopper/ConnectorGrasshopperShared/Streams/StreamCreateComponentV2.cs
Fixes #2252 
Stream Create task needed to be wrapped in a `Task.Run` call with the CancelToken
> fix(gh): Stream create no longer locks the main thread

- ConnectorGrasshopper/ConnectorGrasshopperShared/Loader.cs
- ConnectorGrasshopper/ConnectorGrasshopperShared/SchemaBuilder/SchemaBuilderGen.cs
- ConnectorGrasshopper/ConnectorGrasshopperShared/SchemaBuilder/SchemaBuilderGen.tt
Fixes #2253 
Adds a minor fix to obsolete schema nodes being shown in the toolbar instead of hidden
> feat(gh): Adds AdvanceSteel schema nodes

- ConnectorRevit/ConnectorRevit/ConnectorRevitUtils.cs
- ConnectorRevit/ConnectorRevit/UI/ConnectorBindingsRevit.Send.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/ConversionUtils.cs
This PR aims to solve some of the issues reported in [this thread](https://speckle.community/t/mapping-tool-for-cad-bim-workflows/4086/24) in regard to the localization of categories used for grouping objects.
The idea is to derive an English name from the OST_BuiltInCategoryName name, note that there is not always an exact match here. For example, `Levels` in the UI corresponds to `OST_Levels`, but `Air Terminal Tags` to `OST_DuctTerminalTags`.
**NOTE: this PR will be breaking change for any code/app relying on a specific language for the category names.**
The category property on each element is kept as it is. 
Sample output, where `Soffitti` has been renamed to `Ceilings`:
> feat: forces the use of english names when grouping objects on send

- ConnectorGrasshopper/ConnectorGrasshopperShared/Extras/SpeckleStatefulParam.cs
Fixes an issue reported by SOM where our `ExtractParameter` logic would place the resulting node in the wrong location.
This seemed to be an issue with HighDPI screens and how Grasshopper computes the canvas coordinates based on that.
Using `Global_Proc.AdjustUI` now to fix that.
> fix(gh): Extract parameter position is now consistent

- ConnectorGrasshopper/ConnectorGrasshopperShared/BaseComponents/GH_SpeckleAsyncComponent.cs
- ConnectorGrasshopper/ConnectorGrasshopperShared/BaseComponents/SelectKitAsyncComponentBase.cs
- ConnectorGrasshopper/ConnectorGrasshopperShared/Ops/Deprecated/Operations.ReceiveComponent.cs
- ConnectorGrasshopper/ConnectorGrasshopperShared/Ops/Deprecated/Operations.SendComponent.cs
- ConnectorGrasshopper/ConnectorGrasshopperShared/Ops/Deprecated/Operations.VariableInputSendComponent.cs
- ConnectorGrasshopper/ConnectorGrasshopperShared/Ops/Operations.ReceiveLocalComponent.cs
- ConnectorGrasshopper/ConnectorGrasshopperShared/Ops/Operations.SendLocalComponent.cs
- ConnectorGrasshopper/ConnectorGrasshopperShared/Ops/Operations.VariableInputReceiveComponent.cs
- ConnectorGrasshopper/ConnectorGrasshopperShared/Ops/Operations.VariableInputSendComponent.cs
- ConnectorGrasshopper/ConnectorGrasshopperShared/Streams/StreamListComponentV2.cs
Our latest fix for logging in #2274 broke our GH_AsyncComponent logic (on the components that inherited from it)
We did not take into account the convoluted solving logic of the Async component, and this lead to an infinite recursive call of `SolveInstance -> SolveInstanceWithLogContext -> SolveInstance`....
> fix(gh): Logging in Async component could lead to stack overflow by recursively calling the parent SolveInstance.

- ConnectorDynamo/ConnectorDynamo/ConnectorDynamo.csproj
- ConnectorDynamo/ConnectorDynamoFunctions/BatchConverter.cs
- ConnectorDynamo/ConnectorDynamoFunctions/ConnectorDynamoFunctions.csproj
- ConnectorGrasshopper/ConnectorGrasshopperShared/Objects/DeconstructSpeckleObjectTaskComponent.cs
- Core/Core/Kits/Attributes.cs
- Core/Core/Models/DynamicBase.cs
- Core/Core/Models/DynamicBaseMemberType.cs
- Objects/Converters/ConverterDynamo/ConverterDynamoShared/ConverterDynamo.Geometry.cs
- Objects/Objects/Other/Instance.cs
- Objects/Tests/GenericTests.cs
This PR adds a new mechanism for `GetMembers` to fetch properties of an object, but also any computed values we may want to have included.
Any method that should be displayed in the output of `GetMembers` should be flagged with the `SchemaComputed` attribute, which requires a name.
GetMembers will use that name as the property name for  the output dictionary.
This PR also updates both Grasshopper and Dynamo nodes to reflect this change.
> refactor(objects): New SchemaComputed attribute and GetMembers implementation

- Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.Other.cs
- Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.Utils.cs
Fixes receiving revit instances with render materials in Rhino. 
Also improves revit instance definition naming, using the category/family/type information for Rhino block definition names.
Rhino converter
Before:
After:
Tested receiving a few different revit family instances
> fix(rhino): assigns materials when receiving revit instances

- ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/UI/ConnectorBindingsRhino.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertFamilyInstance.cs
Fixes logic in rhino connector that was baking revit instances prematurely & therefore deleting them after creation.
Also fixes transforms on nested revit instances, as seen on this stream: [https://latest.speckle.dev/streams/5b9e23aa6c/commits/0f341dc6fd](https://latest.speckle.dev/streams/5b9e23aa6c/commits/0f341dc6fd)
- rhino connector
- revit converter
Before:
After:
> fix(rhino/revit): fixed nested revit instance transform calculation

- Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.Other.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertFamilyInstance.cs
- Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.Other.cs
When `RevitInstance` is sent, the corresponding `RevitSymbolElementType` definition is reconverted every time, since there is no quick way to determine whether the `displayValue` on the familysymbol has changed based on instance parameters.
Also includes updates to Rhino and Autocad on receiving revit instances, which now appends the revit definition id to the created block definition name (which differentiates between same familysymbols with different display values).
Fixes #2302 and also some other bugs discovered when sending revit instances.
Revit, rhino, and autocad converter
Before: see issue
After:
also tested receiving in rhino: block defs are being created as expected
> fix(revit): recomputes familysymbol definitions when sending revit instances

- Objects/Converters/ConverterRevit/ConverterRevitShared/ConversionUtils.cs
Edge case reported on forum where object was being sent to Speckle but was unable to be received back. The issue was that the object had a parameter which would not accept a 0 value.
Trying to set the value to 0 on the frontend would results in the following error
The issue occurs when there is no value assigned to the parameter, the "AsInteger" property evaluates to 0 because that is the default value of integers.
Therefore we want to check if there is actually a value assigned to a parameter before we send the parameter to Speckle
- add check for param.HasValue
this object can now be sent and received successfully
https://speckle.community/t/revit-connector-issue-receiving-lighting-fixtures/5129/2
> fix(Revit): don't send unassigned parameters

- Core/Core/Api/GraphQL/Client.cs
- Core/Core/Api/Operations/Operations.Receive.cs
- Core/Core/Api/Operations/Operations.Send.cs
- Core/Core/Credentials/AccountManager.cs
- Core/Core/Helpers/Http.cs
- Core/Core/Kits/KitManager.cs
- Core/Core/Logging/Analytics.cs
- Core/Core/Logging/SpeckleException.cs
- Core/Core/Logging/SpeckleLog.cs
- Core/Core/Models/DynamicBase.cs
- Core/Core/Serialisation/BaseObjectDeserializerV2.cs
- Core/Core/Transports/Memory.cs
- Core/Core/Transports/Server.cs
- Core/Core/Transports/ServerV2.cs
- Core/Examples/Program.cs
- Core/IntegrationTests/Fixtures.cs
- Core/Tests/Fixtures.cs
- Core/Transports/MongoDBTransport/MongoDB.cs
This is a non breaking change, but enables the fixing of #2258 
Also changes the seq api key to a new one.
> fix(core logging): make sure core logger uses our own SpeckleLog logger, not the global serilog instance

- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertAnalyticalSurface.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertFloor.cs
in order to make a floor, Revit needs to be passed a flat floor outline, even if the floor is actually sloped. Previous we were editing the floor outline to be flat, but this ended up messing up the import of analytical panels which do not need to be passed in as a flat outline.
- return a copy of of the floor outline with flattened points instead of changing the values of the object
Receiving [this commit](https://latest.speckle.dev/streams/85bc4f61c6/commits/ef41f8402c) results in many object baking failures including one that causes the entire transaction to be rolled back
After this PR, the commit bakes with no failures
Forum post that brough this issue to my attention
https://speckle.community/t/errors-in-receiving-slabs-and-walls-from-etabs-to-revit/5183/4
> fix(Revit): don't modify points when flattening floor outline

- Objects/Converters/ConverterRevit/ConverterRevitShared/ConversionUtils.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/ConverterRevit.MeshBuildHelper.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/ConverterRevitShared.projitems
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertColumn.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertCombinableElement.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertDirectShape.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertFamilyInstance.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertGeometry.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertMeshUtils.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertWall.cs
- Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.Other.cs
- Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.cs
- Objects/Objects/Other/Instance.cs
The reported bug in #2311 was originally caused by an unhandled null exception when retrieving the display value meshes from revit elements, resulting in some definitions not having meshes in their display value which looked like missing instances.
This fix introduces a new `GetElementDisplayValue()` method for retrieving the display meshes for any revit element, which is refactor to replace many redundant methods in MeshUtils. It is currently implemented for `RevitInstance` and `Wall` conversions but should be rolled out to as many other conversions as possible (see #2314 )
This also _**improves how we were previously handling hosted and mirrored family instances**_, with better support for receiving hosted and mirrored instances (still some edge cases to be debugged here)
Also includes …
> fix(revit/rhino): handles exception when converting null meshes in revit

- ConnectorGrasshopper/ConnectorGrasshopperShared/Loader.cs
- ConnectorNavisworks/ConnectorNavisworks/Bindings/ConnectorNavisworksBindings.cs
- ConnectorNavisworks/ConnectorNavisworks/Entry/SpeckleNavisworksCommand.cs
- ConnectorRevit/ConnectorRevit/Entry/App.cs
- ConnectorRevit/ConnectorRevit/UI/ConnectorBindingsRevit.cs
- ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/Entry/Plugin.cs
- Core/Core/Logging/SpeckleLog.cs
Fixes logger initialisation issues in:
- Rhino for mac
- Grasshopper
- Revit
- Navisworks
> fix(core/rhino/gh/revit/navis): Adds enhancedLogContext config option and disables it on mac

- ConnectorGrasshopper/ConnectorGrasshopperShared/Extras/TreeBuilder.cs
Fixes issue where tree builder would output a `List` object, instead of a tree with a single branch in it.
This was caused because we expected a `List<object>` but that doesn't cover all cases. Instead we should be checking for `IList`
The DSO node already did this so this was an oversight on my behalf
> fix(gh): TreeBuilder was checking for List<object> when it should be IList instead

- Objects/Converters/ConverterNavisworks/ConverterNavisworks/ConverterNavisworks.Properties.cs
> fix(Navisworks): avoid the `Item` reserved property name for Indexed data structures

- Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.Geometry.cs
- Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.cs
Fixes issue reported by Pavol where a specific brep was not converting properlly.
Turned out it was a clash of a legacy edge case condition in the nurbs curve conversion + a bug in the actual conversion of ellipses inside `ConvertToSpeckle`
> fix: Legacy Ellipse curve checks + missing return on ellipse clause in CurveToSpeckle

- ConnectorAutocadCivil/ConnectorAutocadCivil/UI/ConnectorBindingsAutocadCivil.cs
- ConnectorAutocadCivil/ConnectorAutocadCivil/Utils.cs
- Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/ConversionUtils.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertFamilyInstance.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertGeometry.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertMeshUtils.cs
Fixes how display value meshes were being retrieved on instance definitions, as well as taking into consideration linked models and reference point settings when computing transforms.
Now revit instance display values are always retreived relative to the internal origin, and the linked model and reference point setting transforms are baked into the instance transform.
Also includes a small fix for autocad, which now correctly traverses revit instances on receive.
- Autocad connector and converter
> fix(revit): correct transforms when sending linked models and with a reference point setting

- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertFamilyInstance.cs
- Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.Other.cs
Uses the old point based family instance conversion method for structrual foundations, because i couldn't figure out why the transforms on the instances were out of place.
!! also fixes an issue with recieving rhino blocks on the correct layers
- revit converter
Before:
After:
> fix(revit): uses old family instance method for converting structural foundations

- ConnectorAutocadCivil/ConnectorAutocadCivil/Utils.cs
- Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.Other.cs
Fixed issue with some instances receiving invisible
There was a bug where we were converting the dispalyStyle as null, and falling back to the RenderMaterial color, but the render material color.alpha does NOT encode transparency the way autocad expects. 
I've fixed this by using the alpha for dispalyStyles only, and `renderMaterial.transparency` for `RenderMaterial`s being converted as fallbacks to `DisplayStyle`s
Also fixed a regression where the  opacity on Render materials weren't being used.
Now translucent/transparent meshes will appear correctly.
There's potential for some further cleanup, I notice we are converting displayStyles and render materials both in the connector, and converter, but for now This works!
---
Before: (unselected)
Before: (selected)
After:
Before (PBR):
After:
> fix(acad): style transparency fix

- ConnectorGrasshopper/ConnectorGrasshopperShared/Accounts/Accounts.ListAccounts.cs
Requested by Arup folks.
This was causing their scripts to fail on Rhino compute and return a 500 error.
A warning is all that is necessary for a user that has no accounts to be aware of what to do about it, and will allow any Compute run that uses this node to succeed.
> fix(gh): Lower AccountList "no accounts" message to be warning

- Core/IntegrationTests/Fixtures.cs
Or throw an exception with clear meaning.
Kudos to @iainsproat and @fabis94 for the help finding this!
> fix(core): Parse the redirect URL correctly to retrieve the access code

- ConnectorNavisworks/ConnectorNavisworks2020/ConnectorNavisworks2020.csproj
- ConnectorNavisworks/ConnectorNavisworks2021/ConnectorNavisworks2021.csproj
- ConnectorNavisworks/ConnectorNavisworks2022/ConnectorNavisworks2022.csproj
- ConnectorNavisworks/ConnectorNavisworks2023/ConnectorNavisworks2023.csproj
> fix(Navisworks): Adds <UseWpf> to projects to enable CICD builds on linux/mac

- ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/UI/MappingBindingsRhino.cs
Fixes #2386
Should fix extrusion mapping missing in some cases, and brep to floor cases too.
The value of a `double` cannot be checked in Rhino for equality, as the comparison is done in an exact manner.
Tolerance based comparison is the recommended approach, so I used the `AbsoluteModelTolerance` to check instead.
> fix(rhino/mapping): Added tolerance based comparison between dobules

- Objects/Converters/ConverterRevit/ConverterRevitShared/ConverterRevit.cs
Fixes #2378 
The old logic (from 2021!!! 😱) of our `@speckleSchema` swapping mechanism in the Revit converter was totally broken for `DirectShapes`
A full fix is necessary which may require the addition of an extra attribute on the main geometry property we need to swap.
To go from `geometry->SpeckleSchema` to `SpeckleSchema->geometry` in a consistent way that does not require guesswork.
This fixes the issue at hand for now, but we should re-engineer a better solution once we get to re-engineering mappings
> fix(revit): SpeckleSchema logic for DirectShapes

- Objects/Converters/ConverterRevit/ConverterRevitShared/ConverterRevit.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertBlock.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertDirectShape.cs
Fixes #1674 
I refactored the entire direct shape logic so that:
- DirectShapeToNative can only take a `DirectShape` object, and has no fallback DXF handling
- TryDirectShapeToNative calls `DirectShapeToNative` and handles DXF fallback
- Other `TryDirectShapeToNative` calls accept the existing options (Mesh, Brep, List<Mesh>) but now consistently handle DXF fallback mode too.
- Removed the previous `DirectShapeToNative` overloads
- Updated any use of the removed functions throughout the converter
DirectShape now checks if the object exists in the doc and, if so, will no longer delete it. Instead it will grab that existing DirectShape and call `SetShape` on it.
The previous logic would remove the existing direct shape and create a new one. This will still happen in create mode, only update …
> feat(revit): DirectShape conversion is now capable of updating existing DS

- ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/UI/MappingBindingsRhino.cs
Adds the DirectShape option to all extrusions in Rhino.
This change also respects any other mappings that may be added too, but the DS option should always be available for any extrusion.
> feat(rhino): Allow mapping of extrusions to DirectShapes

- ConnectorCSI/ConnectorCSIBridge/ConnectorCSIBridge.csproj
This has been fixed in the latest `dev` branch while doing the monorepo cleanup and the change now conflicts with the `dev` branch.
If this is the way CSIBridge has always been shipped, I saw we just wait 1 release cycle and it will fix itself with no conflicts 🙌🏼
That is, unless it was removed for a specific reason on `2.13.0-rc3`
> Revert "Fix(CSiBridge): remove objs ref"

- ConnectorDynamo/ConnectorDynamoFunctions/Functions.cs
- ConnectorGrasshopper/ConnectorGrasshopperShared/Ops/Deprecated/Operations.ReceiveComponentSync.cs
- ConnectorGrasshopper/ConnectorGrasshopperShared/Ops/Operations.SyncReceiveComponent.cs
- ConnectorGrasshopper/ConnectorGrasshopperShared/Ops/Operations.VariableInputReceiveComponent.cs
Partially fixes specklesystems/admin#389
Adds `isMultiplayer` property to the dictionary of every Receive event sent from Dynamo or Grasshopper
> feat(gh/dyn): Adds `isMultiplayer` property to receive events

- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertFloor.cs
Fixes possibly two forum reported bugs:
- https://speckle.community/t/revit-errors-importing-a-floor/5420
- maybe this one too (not tested): https://speckle.community/t/revit-to-etabs-groups/5419
Test files (revit 2023):
[floor bug.zip](https://github.com/specklesystems/speckle-sharp/files/11213994/floor.bug.zip)
> fix(revit): floor outline flattening fix

- Core/Core/Core.csproj
- Directory.Build.props
Fixes the new target that runs in Core for every restore. Condition for IsDesktopBuild was wrong.
> fix(husky): Fixed install on restore in Core target

- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertFamilyInstance.cs
Following [this user-reported bug](https://speckle.community/t/speckle-2-12-2-generic-model-with-void-or-solid-face-based-family-as-cutout/5071) it seems that face-hosted family instances are not converting well when sending from Revit.
This PR excludes then and also improves the exclusion for "Structural Framing" making it language agnostic.
If we want to look at it again it might be tackled together with: https://github.com/specklesystems/speckle-sharp/issues/586
Source:
Before:
After:
Sample file:
`G:\Shared drives\All Company\07 Sample Models\Revit\Generic Model with cutout`
> fix: exclude face hosted families from new instancing logic

- .circleci/scripts/config-template.yml
Upgrades deploy jobs to use dotnet 7.0 (same one we have on our computers)
> fix(ci): Run deploy on dotnet7.0

- ConnectorCSI/ConnectorCSIBridge/ConnectorCSIBridge.csproj
- ConnectorCSI/ConnectorSAP2000/ConnectorSAP2000.csproj
- ConnectorRevit/ConnectorRevit2020/ConnectorRevit2020.csproj
- ConnectorRevit/ConnectorRevit2021/ConnectorRevit2021.csproj
- ConnectorRevit/ConnectorRevit2022/ConnectorRevit2022.csproj
- ConnectorRevit/ConnectorRevit2023/ConnectorRevit2023.csproj
Some projects (revit) needed to have this added:
```    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
```
We also pushed some dummy changes for CSI and SAP that should have never been pushed when we were figuring out what was the CSI and sap release strategy.
> fix(ci): Move to dotnet changed output paths for some projects

- ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/UI/MappingBindingsRhino.cs
Fixes #2379 
Default beam view model was left out of the planar beam options, but there was no reason to do so, as the default beam holds an `ICurve`.
> fix(mapping): Added default beam mapping to planar curves

- ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/UI/ConnectorBindingsRhino.cs
- Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.Other.cs
Fixes a regression where user attributes were no longer being added to block instances on receive
Fixes #2445 
- Rhino connector
user strings and other user atts now received:
> fix(rhino): adds missing user attributes to block instances on receive

- Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.Geometry.cs
Falls back to using nurbs conversions in the `CurveToSpeckle` method when attempts to convert a curve to circles, ellipses, and polylines fail.
This was causing an error in some models that have curves which return true for being a subclass of Curve but fail when trying to convert the curve into its subclass curve.
Fixes [https://github.com/specklesystems/admin/issues/395](https://github.com/specklesystems/admin/issues/395)
Rhino converter
> fix(rhino): handle invalid curve conversions to speckle

- Core/Core/Logging/SpeckleLog.cs
initialize logger by default as Core logger instead of throwing
> add default initialization to logger with Core as the app name

- All.sln
- ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/Utils.cs
- Core/Core/Api/GraphQL/Models.cs
- Core/Core/Api/Helpers.cs
- Core/Tests/Helpers.cs
- DesktopUI2/DesktopUI2/DummyBindings.cs
- DesktopUI2/DesktopUI2/Models/StreamState.cs
- DesktopUI2/DesktopUI2/Utils.cs
- DesktopUI2/DesktopUI2/ViewModels/HomeViewModel.cs
- DesktopUI2/DesktopUI2/ViewModels/OneClickViewModel.cs
- DesktopUI2/DesktopUI2/ViewModels/StreamSelectorViewModel.cs
- DesktopUI2/DesktopUI2/ViewModels/StreamViewModel.cs
Previously, we were using `DateTime.Parse` and `DateTime.ToString` in several places across DUI2 and Core.
`DateTime.Parse` is dependent on system culture and TimeZone.
While debugging, I noticed some US formatted dates were failing to parse as UK dates.
I have replaced occurrences of raw string dates with `DateTime` comparisons, which resolves the problem.
I have also consolidated `DesktopUI2\Utils.TimeAgo` and `Speckle.Core.API.Formatting.TimeAgo` to use the same implementation.
Additionally, There was a third variant of this "TimeAgo" function in `ConnectorRhinoShared\Utils.cs`
This is unused, and I haven't touched it, since its implementation was slightly different to that of Core & DUI
> fix(dui2): Fixed issues with date time formatting

- ConnectorRevit/ConnectorRevit/UI/ConnectorBindingsRevit.Previews.cs
- ConnectorRevit/ConnectorRevit/UI/ConnectorBindingsRevit.Selection.cs
- DesktopUI2/DesktopUI2/ViewModels/StreamViewModel.cs
Fix for this user-reported issue: https://speckle.community/t/curtain-wall-panel-with-nested-shared-famillies/5508/4
Using the Preview Send button in Revit 22 or lower would lead to a fatal crash ([unmanaged exception](https://www.autodesk.com/support/technical/article/caas/sfdcarticles/sfdcarticles/Revit-crashes-with-CER-when-selecting-specific-elements-in-a-model.html)), and it throws a managed exception and does not work in Revit 23.
This was caused by the `Bindings.PreviewSend(StreamState, Progress);` being wrapped inside a `Task` and probably some multi-threading issues.
The PR also cleans up the selection logic a bit and wraps the bindings in try catches with logging. 
Tested in Revit 22, 23 and Rhino 7, and all seem to work fine.
> fix(revit): preview send crashing Revit

- .editorconfig
- Core/Core/Api/GraphQL/Serializer/MapConverter.cs
- DesktopUI2/DesktopUI2/Views/Windows/Dialogs/DialogUserControl.cs
- DesktopUI2/DesktopUI2/Views/Windows/Dialogs/ImportFamiliesDialog.xaml.cs
- DesktopUI2/DesktopUI2/Views/Windows/Dialogs/MappingViewDialog.xaml.cs
- Directory.Build.props
- Objects/Objects/Objects.csproj
Some of our NetAnalyzers were quite noisy, and were warning about things that were not our priority right now (globalization, moving functions to be static...)
Some were still useful so they'll still appear as suggestions, but not as compile time warnings.
> Fix: Removes or demotes warnings in monorepo

- ConnectorAutocadCivil/ConnectorAdvanceSteel2023/ConnectorAdvanceSteel2023.csproj
- ConnectorAutocadCivil/ConnectorAutocad2021/ConnectorAutocad2021.csproj
- ConnectorAutocadCivil/ConnectorAutocad2022/ConnectorAutocad2022.csproj
- ConnectorAutocadCivil/ConnectorAutocad2023/ConnectorAutocad2023.csproj
- ConnectorAutocadCivil/ConnectorCivil2021/ConnectorCivil2021.csproj
- ConnectorAutocadCivil/ConnectorCivil2022/ConnectorCivil2022.csproj
- ConnectorAutocadCivil/ConnectorCivil2023/ConnectorCivil2023.csproj
- ConnectorNavisworks/ConnectorNavisworks2020/ConnectorNavisworks2020.csproj
- ConnectorNavisworks/ConnectorNavisworks2022/ConnectorNavisworks2022.csproj
- ConnectorNavisworks/ConnectorNavisworks2023/ConnectorNavisworks2023.csproj
- ConnectorNavisworks/ConnectorNavisworks2024/ConnectorNavisworks2024.csproj
- ConnectorRevit/ConnectorRevit2020/ConnectorRevit2020.csproj
- ConnectorRevit/ConnectorRevit2021/ConnectorRevit2021.csproj
- ConnectorRevit/ConnectorRevit2022/ConnectorRevit2022.csproj
- ConnectorRevit/ConnectorRevit2023/ConnectorRevit2023.csproj
Exclude adsk nugets from output dir
> fix(acad): exclude adsk nugets from being copied to the output dir

- ConnectorRevit/ConnectorRevit/UI/ConnectorBindingsRevit.Mappings.cs
- various code cleanup
- change expected format of incoming etabs commits
The dialoug shows up again 
https://speckle.community/t/revit-etabs-type-mapping-issue/5466
> Fix(Revit): mapping on receive 

- Core/Core/Api/Helpers.cs
- Core/Core/Api/Operations/Operations.Send.cs
- Core/Core/Credentials/AccountManager.cs
- Core/Core/Credentials/StreamWrapper.cs
- Core/Core/Helpers/Http.cs
- Core/Core/Models/Utilities.cs
- Core/Core/Transports/Server.cs
- Core/Core/Transports/ServerUtils/GzipContent.cs
- Core/Core/Transports/ServerUtils/ServerAPI.cs
- DesktopUI2/DesktopUI2/ConnectorHelpers.cs
- DesktopUI2/DesktopUI2/ViewModels/DesignViewModels/DesignHomeViewModel.cs
- DesktopUI2/DesktopUI2/ViewModels/HomeViewModel.cs
- DesktopUI2/DesktopUI2/ViewModels/MappingTool/MappingsViewModel.cs
- DesktopUI2/DesktopUI2/ViewModels/OneClickViewModel.cs
- DesktopUI2/DesktopUI2/ViewModels/StreamSelectorViewModel.cs
- DesktopUI2/DesktopUI2/ViewModels/StreamViewModel.cs
Many of our classes being used in core and DUI are disposable, meaning we need to manually dispose of them or things may linger and break unexpectedly.
This is usually related to our `Client` and `Transports`, but other classes such as `DUI ViewModels` may need reviewing.
> Core/DUI: Wraps disposable objects in using statements

- .editorconfig
https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1062
CA1062 does not play nicely with nullability syntax, I suggest we revert to it being disabled.
> ca1062 supress

- ConnectorRevit/ConnectorRevit/UI/ConnectorBindingsRevit.Send.cs
- Core/Core/Models/Extensions.cs
- Core/Tests/BaseExtensionsTests.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/ConversionUtils.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertRoof.cs
#2456 introduced an issue where objects were being sent with both an "elements" instance prop (null) and an "@elements" dynamic prop (populated)
This PR provides a hacky work around, by checking for the presence of an instance prop before trying to set "@elements" dynamically.
I have put a few helper extension methods in core for this (with unit tests), unsure if this is the best place for them seeing as we likely want to push a more robust fix for this issue (potentially one that changes the way dynamic detaching works)
> fix(revit): fixed issue with elements prop dynamic detaching issue

- ConnectorNavisworks/ConnectorNavisworks/Bindings/ConnectorNavisworksBindings.Send.cs
Passes the full Navis name and version to the `CommitCreateInput` so that on receive the right `sourceHostAppVersion` can be set.
For reference: https://github.com/specklesystems/speckle-sharp/blob/main/ConnectorRevit/ConnectorRevit/UI/ConnectorBindingsRevit.Send.cs#L243
> fix(navis): set hostapp with version

- ConnectorRevit/ConnectorRevit/ConnectorRevitUtils.cs
- ConnectorRevit/ConnectorRevit/UI/ConnectorBindingsRevit.Selection.cs
- Allow user easy send element by rule-base filters has setting inside Revit.
- Add new option allow select by filters created in Revit
- Selection Filters : 
- Dropdown : 
- After Send Select Window Level 2  - 7 Windows Elements sent
- After Send Select Window Level 1  - No Element
- After Send Select Window Total  - 17 Windows Elements sent
- After Send Select Window Total + Window Level 2 + Window Level 1 + Door : 33 Elements sent (filtered duplicate element)
> Revit Connector : Add Feature || Allow selection by filters

- .circleci/scripts/config-template.yml
Some CI jobs started failing on restore steps. Not sure exactly what the cause is, but could be related to how we're caching the checkout.
I'm removing it as it didn't give us the speed improvement we hoped for in the first place.
> Disabling cached checkout due to failing CI's on restore

- ConnectorRevit/ConnectorRevit/ConnectorRevitUtils.cs
- ConnectorRevit/ConnectorRevit/UI/ConnectorBindingsRevit.Selection.cs
Removes the parameter filter in Revit in favor of the Filter one as it does the same and is more powerful. See https://github.com/specklesystems/speckle-sharp/pull/2517
This will also make opening streams inside large models faster.
> Remove parameter filter

- ConnectorGrasshopper/ConnectorGrasshopperShared/Objects/GetObjectValueByKeyTaskComponent.cs
We originally added the `schemaComputed` properties (and it's corresponding flag in `Base.GetMembers()`) and it was added to the expandSpeckleObject functionality, but apparently we never did so for the Key Value by Object component.
This PR fixes this issue, and removes a double warning that was being reported when the key was not found.
> fix(gh): Adds the ability for `key value by object` to fetch schemaComputed properties

- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertAnalyticalSurface.cs
- Objects/Objects/Structural/Geometry/Element2D.cs
- previously we were not adding openings to Speckle analyical 2D elements.
- add 'openings' prop for 2D analytical elements
- get analytical openings and convert to speckle
There is now an openings prop that wasn't there before
https://latest.speckle.dev/streams/85bc4f61c6/commits/8d6c547560?filter=%7B%7D&c=%5B19.32601,-11.31229,4.78412,-4.24437,4.38822,-4,0,1%5D
https://speckle.community/t/etabs-20-3-and-revit-2022-interoperability-issue/5065/8
> Feat(Revit): add support for openings in analytical surfaces in 2023+

- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertFamilyInstance.cs
- Objects/Converters/ConverterRevit/ConverterRevitTests/ConverterRevitTestsShared/FamilyInstanceTests.cs
- Objects/Converters/ConverterRevit/ConverterRevitTests/ConverterRevitTestsShared/SpeckleConversionTest.cs
A few instance based elements in the "familyInstance" tests were not having their rotation properly set
- change the "axis" line that the elements are rotating around. The [createUnbound](https://www.revitapidocs.com/2023/133d2d1b-e954-5eba-1175-15e8d9e62d16.htm) method in the Revit API takes a point and a direction as inputs. The existing code seems to think that this method takes two points instead.
- flip the subtraction between the computed rotation and the existing rotation. 
- various fixes to the "selectionToNative" method in the integration tests
- The family instance integration tests have these table objects that were receiving in the correct location, but with the wrong rotation. Those elements now have the correct rotation.
> Fix(Revit): setting instance rotation on receive

- Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.Other.cs
- Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.cs
Updates Rhino `InstanceDefinition` on update receive mode. This was requested by a few users because previously only instance transforms were updated, not instance definition geometry.
Part of #2487 , the rest to be completed after we finish scoping collection and base commit sctructure.
- rhino converter
Before block def update:
After updating block def of same name and moved instances:
Test procedure: 
- send some blocks from rhino
- replace existing definition with new definition geometry of the same name
- receive previously sent blocks
> feat(rhino): updates block definitions on update receive mode

- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertAdaptiveComponent.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertAnalyticalStick.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertAnalyticalSurface.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertArea.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertBeam.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertBuildingPad.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertCableTray.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertCeiling.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertColumn.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertConduit.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertDuct.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertFamilyInstance.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertFloor.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertMeshUtils.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertPipe.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertRailing.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertRevitElement.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertRoof.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertRoom.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertSpace.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertStair.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertStructuralConnectionHandlers.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertTopRail.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertTopography.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertWall.cs
Removes all references to the old mesh display value methods in Revit conversions. This needs to be thoroughly tested to ensure no regressions in how element display meshes were previously being retrieved in revit conversions.
Closes #2314
**note: this pr is replacing #2426 due to the other pr becoming unwieldy from cumulative reformatting hook changes**
Revit converter
> refactor(revit): deprecates old revit mesh display value methods

- ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/UI/MappingBindingsRhino.cs
- DesktopUI2/DesktopUI2/ViewModels/MappingTool/MappingsViewModel.cs
- DesktopUI2/DesktopUI2/ViewModels/MappingTool/Schemas.cs
- DesktopUI2/DesktopUI2/Views/MappingsControl.xaml
- Removes `Default Wall` option from all extrusions, and only adds that option when the extrusion is a vertical single surface
- Adds `Default Floor` option for all horizontal single surface breps and extrusions.
Fixes #2558 
Fixes #2557 
Rhino mapping tool and dui mapping tool
removing default wall from solid extrusion:
adding default floor:
> bug(rhino): mapper tool bugs with walls and floors

- .circleci/scripts/config-template.yml
- ConnectorRhino/ConnectorRhino7/ConnectorRhino7.csproj
Jonathon reported that our mac installers did not work.
After a bit of digging I realised we were using the wrong configuration when building (it was hard-coded to `release` instead of the input parameter.
Additionally, our condition to copy to the output folder the necessary mac files was not being executed anymore since we were checking for the os to be `OSX` specifically, but this is no longer the case as we're building Rhino mac on linux already.
These 2 changes should fix the installer, but a new release needs to be made to test this
> fix(rhino): Use correct configuration in CI + copy to output condition

- Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.cs
Fixes preprocess geometry feature not being respected in Rhino.
Also preserves the default setting of the converter after modifying modifying it to ensure successive conversions are not polluted.
- PreprocessGeometry is forced to `true` in any BuildingElement, Structural or Mapping conversion.
- Setting is rolled back to it's original value when it finishes
- If the geometry conversion has a schema, we enforce PreprocessGeometry on both `MappingToSpeckle` and the main geometry switch statement.
> fix(rhino): Enforce preprocess geometry at both child and parent level

- ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/UI/ConnectorBindingsRhino.cs
- DesktopUI2/DesktopUI2/ViewModels/HomeViewModel.cs
Disables the doc layer change event handler on layer creation during receive operations, as this was causing a huge performance issue when receiving commits that result in many layers being created.
Not the ideal solution, but should fix #2570
- rhino connector
> bug(rhino): temporarily disables doc layer change event handler for performance

- .circleci/scripts/config-template.yml
File version was not properly set on our releases since our mono-repo cleanup.
This PR fixes this for every job available.
Verified in WIN and MAC builds from the CI logs.
> CI: Fixes incorrect FileVersion on releases

- ConnectorRevit/ConnectorRevit/RevitCommitObjectBuilder.cs
- Core/Core/Models/CommitObjectBuilder.cs
- DesktopUI2/DesktopUI2/ViewModels/MappingTool/MappingsViewModel.cs
Accidently, we were sending `@Types` as a list (of a single item, the types object)
Now we are just sending `@Types` = the types object.
Like so: https://latest.speckle.dev/streams/c1faab5c62/commits/96057e27d7?filter=%7B%7D
> revit(fix): Fixed issue with Types base being nested under a list

- ConnectorArchicad/AddOn/Sources/AddOn/Commands/CreateBeam.cpp
- ConnectorArchicad/AddOn/Sources/AddOn/Commands/CreateColumn.cpp
- ConnectorArchicad/AddOn/Sources/AddOn/Commands/CreateCommand.cpp
- ConnectorArchicad/AddOn/Sources/AddOn/Commands/CreateObject.cpp
- ConnectorArchicad/AddOn/Sources/AddOn/Commands/CreateObject.hpp
- ConnectorArchicad/AddOn/Sources/AddOn/Commands/CreateRoof.cpp
- ConnectorArchicad/AddOn/Sources/AddOn/Commands/CreateShell.cpp
- ConnectorArchicad/AddOn/Sources/AddOn/Commands/CreateSlab.cpp
- ConnectorArchicad/AddOn/Sources/AddOn/Commands/CreateWall.cpp
- ConnectorArchicad/AddOn/Sources/AddOn/Commands/CreateZone.cpp
- ConnectorArchicad/AddOn/Sources/AddOn/FieldNames.hpp
- ConnectorArchicad/AddOn/Sources/AddOn/LibpartImportManager.cpp
- ConnectorArchicad/AddOn/Sources/AddOn/LibpartImportManager.hpp
- ConnectorArchicad/ConnectorArchicad/Communication/Commands/Command_CreateObject.cs
- ConnectorArchicad/ConnectorArchicad/Converters/Converters/ObjectConverter.cs
- ConnectorArchicad/ConnectorArchicad/Converters/Converters/RoofConverter.cs
- ConnectorArchicad/ConnectorArchicad/Converters/Converters/RoomConverter.cs
- ConnectorArchicad/ConnectorArchicad/Converters/Converters/Utils.cs
- ConnectorArchicad/ConnectorArchicad/Converters/ElementConverterManagerReceive.cs
- ConnectorArchicad/ConnectorArchicad/Converters/ModelConverter.cs
- ConnectorArchicad/ConnectorArchicad/Elements/Object.cs
- ConnectorArchicad/ConnectorArchicad/Model/MeshModel.cs
- Core/Core/Helpers/Constants.cs
- Objects/Objects/Geometry/Mesh.cs
* Receiving instances in Archicad (https://github.com/specklesystems/speckle-sharp/issues/2340)
* two-level instancing is used in Archicad: `instance` = `Archicad Object` + `1 definition` = `GDL library part`
* currently custom definition traversal (`TraverseDefinitions`) is used, however usage of Core's traversal mechanism should be considered
* Revit to Archicad workflow checked deeply, other workflows might need improvement
* New oriented polygon normal calculation for edge classification introduced for concave polygons
* Per element type try-catch blocks used in element conversion
* Performance decreased a bit: started to use System.Numerics.Vector3 instead of our Vector classes, however not finished, need further validation
> feat(Archicad): instancing + other improvements

- ConnectorArchicad/ConnectorArchicad/Program.cs
- Core/Core/Logging/Setup.cs
- Core/Core/Logging/SpeckleLog.cs
- Core/Core/Models/CommitObjectBuilder.cs
I noticed while testing that the archicad connector was logging to console/file/seq under "Coreunknown"
After some investigation, it seems that the kit loading done by `App` uses the logger before its initialised by DUI2.
This fix adds an extra log in the entry point of the Archicad connector to ensure Setup is initialised before DUI2.
This is similar to how we do things in Rhino and Revit connectors.
@AlanRynne please could you review the changes made in Core
@jozseflkiss , I didn't figure out how to run the archicad connector locally, if you are available tommorow to give this a quick test for me. 
Simply running the connector from this branch. I expect the first console line to read "Archicad26" and not "Coreunknown"
> fix(archicad): Fixed issue where logger was used before initialising

- .circleci/scripts/config-template.yml
Fixes incorrect parsing of TAG -> SEMVER in the nuget deploy steps:
- build-sdk
- postbuidstep for nugets
> fix(ci): Fixes regex version parsing for nuget packages

- ConnectorGrasshopper/ConnectorGrasshopperShared/Objects/ExtendSpeckleObjectByKeyValueV2TaskComponent.cs
Fixes #2609
Adds verification to ensure any IGH_Goo that has a `Base` as it's value is compatible with our nodes.
> fix(gh): Adds "is Base" check to ESO-K/V input

- ConnectorDynamo/ConnectorDynamo/ConnectorDynamo.csproj
- ConnectorDynamo/ConnectorDynamoFunctions/ConnectorDynamoFunctions.csproj
Fixes: https://github.com/specklesystems/speckle-sharp/issues/2612
Not sure why these after-build steps were modified during the SDK project migration, but that broke the Connector.
This PR restores the after-build step to what it was before.
> fix(dynamo): broken project after build step

- .vscode/launch.json
- Core/.vscode/launch.json
- Core/.vscode/settings.json
- Core/.vscode/tasks.json
- Core/Core/Credentials/Account.cs
- Core/Core/Credentials/AccountManager.cs
- Core/IntegrationTests/.vscode/launch.json
- Core/IntegrationTests/.vscode/tasks.json
The fixed 2 gql queries were still using the old deprecated user query.
I'd like to push this out as a hotfix since its blocking the proper deprecation of the endpoint in the server.
> fix(core): remove deprecated user queries in account management

- Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.Other.cs
Adds applicationId to all instance conversions, where previously this wasn't being set for nested instances. This was creating issues when updating nested blocks in sketchup.
> hotfix(rhino): adds applicationId to nested instances

- ConnectorGrasshopper/ConnectorGrasshopper6/ConnectorGrasshopper6.csproj
Fixes #2628 
Adds `RootNamespace` to Grasshopper6 connector project, mirroring Grasshopper7
This seems to resolve the resources missing warning locally.
> fix(gh): Adding root namespace to GH6 project fixes missing resource error.

- Core/Core/Serialisation/BaseObjectSerialzerUtilities.cs
- Core/Tests/ObjectModelDeprecationTests.cs
- Objects/Objects/Organization/Deprecated/Collection.cs
To allow us to have backwards compatibility saving object models, as targets for deserialization, I have changed the way the deserialiser looks for types to also check for a ".Deprecated" namespace that otherwise matches an incoming speckle type.
This provides us a convenient way to change/move the namespace/type name of our object models, without having to change converters in anyway.
This was motivated by a change made by #2382 that breaks older commits from 2.13
> hotfix(collections): Deprecated object models for backwards compatibility.

- ConnectorRevit/ConnectorRevit/UI/ConnectorBindingsRevit.Previews.cs
- ConnectorRevit/ConnectorRevit/UI/ConnectorBindingsRevit.Selection.cs
- ConnectorRevit/ConnectorRevit/UI/ConnectorBindingsRevit.Send.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/ConverterRevit.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertMeshUtils.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertWall.cs
- if the user sends 1 selected view, then pass that view into the converter. The converter will then save that view in a ViewSpecificOptions property
- if the ViewSpecificOptions property is not null then it trumps any option value that may have been passed into the GetElementDisplayValue method. This ensures the view specific geometry will be sent
- Changes to CurtainWall mesh retrieval
- Because a wall retrieves it's own curtain wall panels and mullions, there is no guarentee that those panels are actually present in the view. This will cause them to be sent as normal when they shouldn't be present at all. Here is an example of this behavior
- Therefore we need to actually check if each panel is present in the view (if the ViewSpecificOptions isn't null)
From Revit
Sending 3D view …
> Feat(Revit): send cropped meshes from view filter

- Core/Core/Models/GraphTraversal/DefaultTraversal.cs
- Core/Core/Models/GraphTraversal/ITraversalRule.cs
- Core/Core/Models/GraphTraversal/RuleBuilder.cs
While creating the traversal documentation, I noticed that there is one source of inconsistencies between some of our traversal functions.
And it raises a great question that potentially could simplify one of the rules.
Can anyone think, are there any Object models that
1. `CanConvertToNative` returns `true` for,
2. AND we expect dynamic properties to be traversed,
IF NOT, then we can 
1. increse travesral performance by avoiding unnessesry traversal!
2. Align better the rhino/revit traversal rules with Archicad/Blender rules which already have this behaviour (with no reported problems)
> feat(core): Traversal optimisation by avoiding unnecessary traversal of dynamic properties

- Objects/Converters/ConverterCSI/ConverterCSIBridge/ConverterCSIBridge.csproj
- Objects/Converters/ConverterCSI/ConverterETABS/ConverterETABS.csproj
- Objects/Converters/ConverterCSI/ConverterSAFE/ConverterSAFE.csproj
- Objects/Converters/ConverterCSI/ConverterSAP2000/ConverterSAP2000.csproj
We fixed an issue with `PolygonMesher` not being included in the Kit on our ci-tools repo.
This is the equivalent fix for Debug mode. All CSI converters will now copy the PolygonMesher dependency to the Objects kit folder.
> fix(csi): Add polygonmesher to copy to kit task

- ConnectorNavisworks/ConnectorNavisworks/Bindings/ConnectorNavisworksBindings.Send.cs
- Objects/Converters/ConverterNavisworks/ConverterNavisworks/ConverterNavisworks.cs
The previous code set Converter on Init and Document change did not reflect the settings change for Basepoint options.
Change to call SetConverterContext on each send.
> fix(Navisworks): Reset ConverterContext on each send. Fixes #2430

- ConnectorNavisworks/ConnectorNavisworks/Bindings/ConnectorNavisworksBindings.Send.cs
- ConnectorNavisworks/ConnectorNavisworks/Other/SelectionBuilder.cs
Fixes #2665.
The code changes prevent division by zero errors in three different files. The changes ensure that the progress bar is updated correctly even when there are no items to process or fewer than the anticipated interval, resulting in a more accurate representation of progress.
Code changes wrap the interval assignment to a default value where the total is less than the default interval chunk. For increment values, the divisor is zero-checked.
This is an alternative to checking on the Progress update loop. However, that would be more DRY.
> fix(Navisworks): Division by zero errors on small models. Fixes #2665

- Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/Converter.AutocadCivil.Utils.cs
- Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.Other.cs
- Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.cs
As requested by a community member, this PR adds object extension dictionaries as `Base` on send. This currently only applies to `ResultBuffer` dictionary entries, but may be improved to include `RXClass` entries as well.
Tested on a file provided, resulting in this commit: [https://speckle.xyz/streams/b53a53697a/commits/9ee73de121](https://speckle.xyz/streams/b53a53697a/commits/9ee73de121
)
Closes #2673 
- Autocad converter
> feat(autocadcivil): adds extension dictionaries to speckle conversions

- Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.Mappings.cs
Fixes an issue where FamilyInstance mappings would have `NaN` rotation.
this was caused by the use of `Math.Acos` with an input out of range (must be between -1 and 1).
To circumvent this, I'm recalculating the angle using RhinoCommon's own methods, which are way more reliable long term in these type of cases.
> fix(rhino): Fixes family rotation by computing the angle between the insertion plane and world X

- ConnectorGrasshopper/ConnectorGrasshopperShared/Accounts/Accounts.ServerAccount.cs
- Core/Core/Credentials/Account.cs
- Core/Core/Credentials/AccountManager.cs
- Core/Core/Credentials/Responses.cs
Fixes issue reported in the forum, where Account.ToString would throw because it would be missing the `User` information after validation.
This was caused by the fact that, even though the queries were updated to use `activeUser` a while back, **the responses were not**
> fix(core): AccountManager.GetUserInfo was still using old user query

- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertArea.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertMeshUtils.cs
- areas don't seem to have a valid mesh and were returning null
- areas without a boundary had no profile, and this was throwing an error and preventing conversion
> fix(revit): areas mesh and profile

- ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/UI/ConnectorBindingsRhino.cs
- ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/Utils.cs
Fixes an issue where created layers with modified paths due to invalid chars were not being cached correctly, so objects on those layers were being placed on the default layer
> fix(rhino): places objects from layers with invalid chars on correct layers

- ConnectorRevit/ConnectorRevit/TypeMapping/ElementTypeMapper.cs
During testing, it was discovered that existing types would flag the "missing incoming types" dialog. This was the result of a mistake on my part in changing some code and then not realizing the consequences of the changes. This should fix it.
> Fix(Revit) : new incoming types false positive

- ConnectorRevit/ConnectorRevit/UI/ConnectorBindingsRevit.Selection.cs
- use collector for elements and add that to the selection. Don't use the collector for views
> Fix(Revit) : using wrong collector for views

- ConnectorNavisworks/ConnectorNavisworks/Bindings/ConnectorNavisworksBindings.Send.cs
- ConnectorNavisworks/ConnectorNavisworks/Bindings/ConnectorNavisworksBindings.Settings.cs
- ConnectorNavisworks/ConnectorNavisworks/Other/Constants.cs
- ConnectorNavisworks/ConnectorNavisworks/Other/Elements.cs
- ConnectorNavisworks/ConnectorNavisworks/Other/SelectionBuilder.cs
- Objects/Converters/ConverterNavisworks/ConverterNavisworks/ConverterNavisworks.ToSpeckle.cs
Implements #2657 
This feature will populate a Geometry Node with all the data from itself up to the "First Object". The "First Object" is a special state related to what Navisworks understands as a significant Node for selection. Many First Objects can exist in an ancestral tree; logically, the reverse ancestral lookup makes the most sense.
Selecting this option will also include the reference nodes in the commit tree. In this way, it will be more referential than a simple node selection - it will provide context for where the data has been gleaned.
The performance in the viewer with this change is that Data that may be instantiated in a First Object will now propagate to the selected geometry object in the Speckle frontend. This also brings much greater Data Filtering capabilities.
- …
> feat(Navisworks): Option to coalesce all data from First Object to the Geometry Node

- ConnectorRevit/ConnectorRevit/ConnectorRevitUtils.cs
- ConnectorRevit/ConnectorRevit/UI/ConnectorBindingsRevit.Selection.cs
Fixes ambiguous view names in filter view.
Reported in 2.15 testing in the Notion table.
> fix(rvt): View selection filter now uses `Title` instead of `Name`

- ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/UI/ConnectorBindingsRhino.Events.cs
Previously, the `Preview` list was not being cleared in a document open event, which resulted in unexpected behaviors when receiving the same commit in a new document after receiving it already.
This clears the cache anytime the document open event is triggered.
Before
After
> bug(rhino): clear cache on document open event

- ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/UI/ConnectorBindingsRhino.Events.cs
- Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.Other.cs
- Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.cs
Fixes a bug where layer materials were not being correctly sent. Adds a new method to handle `Rhino.Render.RenderMaterial` conversion to Speckle.
Before: 
After:
> bug(rhino): layer material not correctly sent

- Objects/Converters/ConverterRevit/ConverterRevitShared/ConversionUtils.cs
I am unsure why we originally had this code here. What was going on is that we would check if a category had already been assigned to a Speckle object, and if so then we would overwrite that value with some logic A. If the category didn't exist, then we would assign the prop with logic B.
The call Categories.GetSchemaBuilderCategoryFromBuiltIn(category.Name) was throwing because the expected input is a builtincategory, which is different than a Category.Name (which is what it was being provided).
I've removed the Categories.GetSchemaBuilderCategoryFromBuiltIn(category.Name) call completely and am assigning the category to category.Name unless the specific object conversion already assigned a category value
All integration tests pass.
Here is a commit that I made with this sending logic.
- …
> Fix(Revit) : assign category fix

- ConnectorTeklaStructures/ConnectorTeklaStructures2023/Properties/launchSettings.json
- ConnectorTeklaStructures/ConnectorTeklaStructuresShared/MainForm.cs
This PR fixes 2 issues:
- it was not possible to re-open DUI after the window was closed (and there were some unnecessary extra calls to get streams etc) - the main Tekla window is now set as owner of DUI so that DUI doesn't hide back when unfocused
-
> fix(tekla): properly load DUI after it's been closed, sets the window owner

- ConnectorArchicad/AddOn/Sources/AddOn/Commands/CreateBeam.cpp
- ConnectorArchicad/ConnectorArchicad/UI/ConnectorBinding.Settings.cs
- Objects/Objects/BuiltElements/Archicad/Fenestration.cs
- Objects/Objects/BuiltElements/Beam.cs
- Objects/Objects/BuiltElements/Column.cs
- Objects/Objects/BuiltElements/Floor.cs
- Objects/Objects/BuiltElements/Roof.cs
- Objects/Objects/BuiltElements/Room.cs
- Objects/Objects/BuiltElements/Wall.cs
Fixes:
* 😡 Revit → Archicad - Fatal crash receiving whole Revit models
* 😢 Revit → Archicad zero thickness walls and no openings 
The cause of both issues above is with optional props in the common schema (see [#2342]).
Optional flags are introduced for properties in the common schema with the tag /*APINullable*/, which means the field can be null in the Archicad API calls, but not in the Speckle common schema. This might not be the ideal solution for #2342.
> fix(Archicad): Parametric receive fixes

- Objects/Converters/ConverterRevit/ConverterRevitShared/ConverterRevit.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertModel.cs
- Objects/Objects/Organization/Model.cs
With the `Collection` implementation in Revit, the base commit object was changed from a `Organization.Model` class object (which uses the generic traversal) to a `Core.Model.Collection::Organization.Model` class object (which uses the `Collection` traversal). This meant that older commits prior to 2.12 where not traversed correctly on receive in any connector using the sharp traversal.
This is fixed by:
1. removing the `Model` class
2. Having Revit send with the base commit as a `Collection`, with the additional `ModelInfo` prop dynamically attached
Also deprecates the unsued `Setting` class
- Revit Converter
- Objects
> fix(revit): fixes regression where 2.12 and older commits were nto being received by any sharp connector

- ConnectorArchicad/ConnectorArchicad/Converters/Converters/ObjectConverter.cs
To be able to receive all kind of instances.
Found an issue during v.2.15 testing: Receiving nested hosted Revit instances results in duplicates in Archicad.
* hosted elements traversals: we don't traverse the "elements" field of the root BlockInstance (they will be traversed by the main element traversal) 
* transform appleid only elements via the "definition" property (not via "elements" property)
* `ArchicadDefinitionTraversal` renamed to `ArchicadGeometryCollector`
> fix(Archicad): Receive all kind of instances 

- ConnectorArchicad/README.md
Users potentially could create `ConnectorArchicad` folder under `C:\Program Files\GRAPHISOFT\ARCHICAD 26\Add-Ons`  based on this readme especially in case of previous installer problems. Instead of copying build files, they should load the add-ons via Add-On Manager. Installer will remove this folder in https://github.com/specklesystems/speckle-sharp-ci-tools/issues/97. Readme updated accordingly.
> fix(Archicad): build readme update

- ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/UI/MappingBindingsRhino.cs
- DesktopUI2/DesktopUI2/ViewModels/MappingTool/MappingsViewModel.cs
Removes beam assignment from polylines, and constrains facewall assignment to basic wall types only.
> fix(rhino): mapping constraints on polylines and facewalls

- ConnectorRevit/ConnectorRevit/Revit/ErrorEater.cs
- ConnectorRevit/ConnectorRevit/UI/ConnectorBindingsRevit.Receive.cs
- Core/Core/Logging/SpeckleException.cs
- Core/Core/Logging/SpeckleLog.cs
- Core/Core/Logging/SpeckleNonUserFacingException.cs
- DesktopUI2/DesktopUI2/ViewModels/StreamViewModel.cs
This PR is the first step toward fixing https://github.com/specklesystems/speckle-sharp/issues/2717. This will log any errors that cause the transaction to be rolled back and it will prompt the user to check the logs.
This PR does not update the report objects, which should be done in the future.
- Log critical issues from the error eater
- Keep track of resolved issues and only try to commit the transaction if some errors have been resolved. This helps avoid infinite loops
- If several issues cause the transaction to be rolledback, then give the user a link to the logs to take a look at.
https://github.com/specklesystems/speckle-sharp/issues/2717
> Fix(Revit): Better reporting of critical errors in Revit

- ConnectorRevit/ConnectorRevit/Entry/App.cs
- Objects/Objects/ObjectsKit.cs
If a user has installed connectors of different versions (eg Revit 2.14 and Navis 2.15) there is a risk of conflicts between their respective different versions of Objects.dll and converters dlls.
This PR forces the Objects Kit to only load converters that have a matching Major and Minor version numbers, and in Revit shows the following popup box:
Currently this was handled as a UI warning in Manager but it is not enough and has led to [user frustration](https://speckle.community/t/system-typeload-exception-revit-export/6328):
Another fix to be eventually carried out is to have Core only load DLLsin the kits folder in reflection mode when checking for kits.
> feat(objects): only load converters matching the version of the Objects dll

- ConnectorArchicad/ConnectorArchicad/Converters/Converters/BeamConverter.cs
- ConnectorArchicad/ConnectorArchicad/Converters/Converters/ColumnConverter.cs
- ConnectorArchicad/ConnectorArchicad/Converters/Converters/DirectShapeConverter.cs
- ConnectorArchicad/ConnectorArchicad/Converters/Converters/DoorConverter.cs
- ConnectorArchicad/ConnectorArchicad/Converters/Converters/FloorConverter.cs
- ConnectorArchicad/ConnectorArchicad/Converters/Converters/ObjectConverter.cs
- ConnectorArchicad/ConnectorArchicad/Converters/Converters/RoofConverter.cs
- ConnectorArchicad/ConnectorArchicad/Converters/Converters/RoomConverter.cs
- ConnectorArchicad/ConnectorArchicad/Converters/Converters/SkylightConverter.cs
- ConnectorArchicad/ConnectorArchicad/Converters/Converters/WallConverter.cs
- ConnectorArchicad/ConnectorArchicad/Converters/Converters/WindowConverter.cs
- ConnectorArchicad/ConnectorArchicad/Converters/ElementConverterManagerReceive.cs
Receive cancellation behaviour in Archicad connector differs from other connectors. 
With this fix `token.ThrowIfCancelationRequested()` is used when iteration through the elements to be converted.
Limitations:
* Currently in Archicad side multiple transactions are used, the already finished ones won't be aborted or roll-backed
* Because of this partial model could be received when cancelling the operation
> fix(Archicad): Receive cancellation behaviour

- ConnectorRevit/ConnectorRevit/TypeMapping/ElementTypeMapper.cs
- ConnectorRevit/ConnectorRevit/TypeMapping/TypeMap.cs
Currently if you were to receive a commit and created mappings, and then receive a commit with different objects, there is a good chance that creating mappings for the new incoming objects will fail. If it doesn't fail, then it will show you every single incoming type that you have mapped before instead of only the incoming types that you are currently receiving.
- use two different TypeMaps in each receive operation. One map is a master map of every type that a user has ever created a mapping for. The second TypeMap is only for the incoming types that the user is receiving in the current operation.
- create method to add the mapped values from the current operation TypeMap to the master type map
> Fix(Revit) : Don't show every mapped value for each receive operation

- ConnectorNavisworks/ConnectorNavisworks/Bindings/ConnectorNavisworksBindings.File.cs
- ConnectorNavisworks/ConnectorNavisworks/Bindings/ConnectorNavisworksBindings.Selections.cs
- ConnectorNavisworks/ConnectorNavisworks/Bindings/ConnectorNavisworksBindings.Send.cs
- ConnectorNavisworks/ConnectorNavisworks/Bindings/ConnectorNavisworksBindings.cs
As reported on the forum:
https://speckle.community/t/navisworks-speckle-greys-out-after-use-and-naviswork-need-to-be-restarted/6311?u=jonathon
And it is replicable.
Two situations occur: 
1. One Click Send is enabled in the DUI even with a completely empty document with no prospect of sending anything.
- Code now guards by throwing a `FileNotFoundException` 
2. With the file present, I am still in the defensive mode about allowing Everything mode. 
- The code now validates ahead of the progress bar being initiated.
TODO: Consider changes to DUI2 logic on Send so that it is possible to legitimate communicate that a new Stream should not be created under the circumstances that the Connector is in control of - like a `get` only property Binding. Might hold for DUI3 (@teocomi ?)
> fix(Navisworks): Handles lack of One-click-send implementation causing host app to be unresponsive

- Core/Core/Logging/Analytics.cs
A quick change to use the dll product version instead of the file version for better analytics.
Cc @paloknapo
> chore(core): use product version

- ConnectorArchicad/AddOn/Sources/AddOn/LibpartImportManager.cpp
There are unnecessary hotspots for object in 3D at the project zero level.
The parameter AC_show2DHotspotIn3D has been set to false.
Before:
After:
> fix(Archicad): Remove unnecessary hotspots from 3D objects

- ConnectorArchicad/AddOn/Sources/AddOn/AddOnMain.cpp
- ConnectorArchicad/ConnectorArchicad/ConnectorBinding.cs
- ConnectorArchicad/ConnectorArchicad/Converters/ElementConverterManagerReceive.cs
Receive process cancellation fix:
* warning bubble shows correct text
* no error entries created in the log
1. All exceptions are rethrown the base ReceiveStream function
2. `progress.Report.LogOperationError` of cancelation removed from `ConvertToNative`, because it is not shows on the DUI Report page in case of any kind of exceptions
3. `SpeckleLog.Logger.Error` not created if cancelled (despite of Revit, which should be fixed also)
> fix(Archicad): Receive cancellation handling improvement

- ConnectorRevit/ConnectorRevit/UI/ConnectorBindingsRevit.Previews.cs
- ConnectorRevit/ConnectorRevit/UI/ConnectorBindingsRevit.Selection.cs
- ConnectorRevit/ConnectorRevit/UI/ConnectorBindingsRevit.Send.cs
The method that we are using to get the selected elements from views will already include the visible design options because we're retreiving the elements via view-specific element filters. Therefore if only one view is selected, then we don't want to apply any design option exclusions.
Steps taken:
- Send view with no specific design option selection ✅
- Send view with non-primary design option selection ✅
- Change view-specific design option settings from the default to a non-primary option
- Send view with no specific design option selection ❌
- Send view with no specific design option selection ✅
- Send view with non-primary design option selection ✅
- Change view-specific design option settings from the default to a non-primary option
- Send view with no specific design option …
> Fix(Revit) : view specific design option fix

- Objects/Converters/ConverterRevit/ConverterRevitTests/TestGenerator/TestGenerator.csproj
Any project added to `Objects` is automatically `packable` unless otherwise stated.
`TestGenerator` was left without the `IsPackable` flag set to false.
> fix: Do not pack Revit TestGenerator

- ConnectorRevit/ConnectorRevit/Entry/App.cs
- ConnectorRevit/ConnectorRevit/TypeMapping/FamilyImporter.cs
- ConnectorRevit/ConnectorRevit/UI/ConnectorBindingsRevit.Events.cs
- ConnectorRevit/ConnectorRevit/UI/ConnectorBindingsRevit.Previews.cs
- ConnectorRevit/ConnectorRevit/UI/ConnectorBindingsRevit.Receive.cs
- ConnectorRevit/ConnectorRevit/UI/ConnectorBindingsRevit.Send.cs
- ConnectorRevit/ConnectorRevit2020/ConnectorRevit2020.csproj
- ConnectorRevit/ConnectorRevit2021/ConnectorRevit2021.csproj
- ConnectorRevit/ConnectorRevit2022/ConnectorRevit2022.csproj
- ConnectorRevit/ConnectorRevit2023/ConnectorRevit2023.csproj
- ConnectorRevit/ConnectorRevit2024/ConnectorRevit2024.csproj
- ConnectorRevit/RevitSharedResources/Models/APIContext.cs
- ConnectorRevit/RevitSharedResources/RevitSharedResources.projitems
- Objects/Converters/ConverterRevit/ConverterRevitShared/ConversionUtils.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/Units.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/RevitCommitObjectBuilder.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/RevitVersionHelper.cs
- Objects/Converters/ConverterRevit/ConverterRevitTests/ConverterRevitTests2021/ConverterRevitTests2021.csproj
- Objects/Converters/ConverterRevit/ConverterRevitTests/ConverterRevitTests2022/ConverterRevitTests2022.csproj
- Objects/Converters/ConverterRevit/ConverterRevitTests/ConverterRevitTests2023/ConverterRevitTests2023.csproj
- Objects/Converters/ConverterRevit/ConverterRevitTests/ConverterRevitTestsShared/AssertUtils.cs
- Objects/Converters/ConverterRevit/ConverterRevitTests/ConverterRevitTestsShared/SpeckleConversionTest.cs
- Objects/Converters/ConverterRevit/ConverterRevitTests/ConverterRevitTestsShared/SpeckleUtils.cs
- replaced RevitAsync nuget package with custom APIContext class
- This new version does almost the same thing as the nuget package except it does not subscribe to the revit [IdlingEvent](https://www.revitapidocs.com/2023/e233027b-ba8c-0bd1-37b7-93a066efa5a3.htm)
- This only speeds up the conversion from .5-1s. However, the idling event documentation says that subscribing to the event in a certain way (that RevitAsync is using) "can result in performance degradation for the system on which Revit is running because the CPU remains fully engaged in serving Idling events during the Revit application's downtime." So it is recommended to avoid using this event
- Throttle Send operation
- only refresh the UI every .15 seconds. This makes a small impact on the ui refreshing and a huge impact on …
> Feat(Revit) : send performance enhancement

- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertRoof.cs
Simple fix for importing extrusions roofs so that they come in correctly instead of like this 
AFAIK, when sending the roof to speckle, there is no way to retreive the orientation of the reference plane. Therefore the is a 50% chance that when receiving an extrusion roof, the side offsets will be flipped. Therefore we need to check if the startOffset is actually equal to the end offset and if so we need to delete the roof, flip the reference plane, and recreate it.
Receiving sample house roof as well as roofs in the Revit integrations tests create the roofs in the correct location
> Fix(Revit) : Remove cool retractable roof feature

- .circleci/scripts/config-template.yml
- .circleci/scripts/connector-jobs.yml
Fixes broken CI caused by 2023.08.01 update on the win/server-2019 executor. This is coming from CircleCI and there is no documentation or notification of when these types of things will happen.
For now, we've fixed the version to the one from March which seemed to include all the necessary tools. In particular:
- MSVC v142 C++ Build Tools is missing and is required by our windows build step prior to building the Archicad connector.
> fix(ci): Now using fixed win/server-2019 version as august release broke our pipeline

- ConnectorArchicad/ConnectorArchicad/Converters/ConverterArchicad.cs
- Core/Core/Kits/ISpeckleConverter.cs
- Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.cs
- Objects/Converters/ConverterBentley/ConverterBentleyShared/ConverterBentley.cs
- Objects/Converters/ConverterCSI/ConverterCSIShared/ConverterCSI.cs
- Objects/Converters/ConverterDynamo/ConverterDynamoShared/ConverterDynamo.cs
- Objects/Converters/ConverterNavisworks/ConverterNavisworks/ConverterNavisworks.ToNative.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/ConverterRevit.cs
- Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.cs
- Objects/Converters/ConverterTeklaStructures/ConverterTeklaStructuresShared/ConverterTeklaStructures.cs
> **THIS IS A BREAKING CHANGE**
Adds new `ConvertToNativeDisplayable()` and `CanConvertToNativeDisplayable()` bindings to our `ISpeckleConverter` interface.
These bindings are a prerequisite to pr #2841 and part of #2777 
Converters
> break(objects): adds new convert to native displayable bindings

- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertRevitElement.cs
Fixes https://github.com/specklesystems/admin/issues/429
Removes the limitation for sending only objects from Revit that can be displayed.
There are cases where valid objects were not being sent:
- MEP Systems, which act as containers for all the other elements
- Unplaced rooms
- Some edge-cases for MEP families such as PipeFittings.
This does not affect any existing conversion on `ToSpeckle`, and tests on receiving it back seem to not conflict with existing conversion logic, as all of these items are being sent through as generic `RevitElement` types.
> fix(rvt): Send objects that have no 3d representation to Speckle

- ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/UI/ConnectorBindingsRhino.Receive.cs
- Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.Other.cs
- Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.cs
Includes the following improvements:
- When receiving commits with nested elements, the rhino connector now places those nested elements in a top-level layer named by their `category` property when previously they were placed under their host element's layer.
- Removes locked and/or hidden objects when receiving on update mode, which was previously resulting in duplicates
- Adds parameters to instances and nested instances, and uses the Parameter `name` property as part of the user string key for legibility
This is part of #2872 
- Rhino connector and converter
> feat(rhino): nested elements layers and parameters improvements when receiving revit commits

- ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/UI/ConnectorBindingsRhino.Previews.cs
- ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/UI/ConnectorBindingsRhino.Receive.cs
- Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.BuiltElements.cs
- Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.cs
Adds `LevelToNative()` conversion to rhino as `Named Construction Plane` objects. 
Part of #2872 
- Rhino connector and converter
Receiving Revit Sample House with two levels:
> feat(rhino): adds level to native conversion

- Objects/Converters/ConverterRevit/ConverterRevitShared/ConversionUtils.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Extensions/ForgeTypeIdExtensions.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/Units.cs
See description here https://github.com/specklesystems/speckle-sharp/pull/2879 for problem.
Benchmarking the above solution led to finding a very slight slow down. On small models it is unnoticable. Here are some average results that I found from benchmarking the solution in the above PR (this cached value solution) and this solution (the type check solution)
Cached value solution : ~ 57.7s
Type check solution : ~ 55.3s
It is interesting to me that the recorded time difference between these two functions is ~ 100 ms (or maybe ticks?), but the time difference of the send operations was consistantly ~2s. This may be because of the extra heap allocations and garbage collections, but that is just my guess. The difference is small enough that I wondered if this PR is really necessay, but it's …
> Fix(Revit) : fix units that don't scale linearly

- ConnectorArchicad/AddOn/Sources/AddOn/AddOnMain.cpp
- ConnectorArchicad/AddOn/Sources/AddOn/Commands/CreateZone.cpp
- ConnectorArchicad/AddOn/Sources/AddOn/Commands/GetZoneData.cpp
- ConnectorArchicad/AddOn/Sources/AddOn/Commands/GetZoneData.hpp
- ConnectorArchicad/AddOn/Sources/AddOn/Utility.cpp
- ConnectorArchicad/AddOn/Sources/AddOn/Utility.hpp
- ConnectorArchicad/ConnectorArchicad/Communication/Commands/Command_CreateRoom.cs
- ConnectorArchicad/ConnectorArchicad/Communication/Commands/Command_GetRoomData.cs
- ConnectorArchicad/ConnectorArchicad/Converters/Converters/RoomConverter.cs
- ConnectorArchicad/ConnectorArchicad/Converters/ElementConverterManager.cs
- ConnectorArchicad/ConnectorArchicad/Converters/ElementTypeProvider.cs
- ConnectorArchicad/ConnectorArchicad/Elements/Room.cs
- Objects/Objects/BuiltElements/Room.cs
Archicad side of https://github.com/specklesystems/speckle-sharp/issues/2820
Objects:
* `ArchicadLevel archicadLevel` virtual property added to ArchicadRoom, overriding the `level` property of the base
* `Objects.BuiltElements.Archicad.Room` is not used for the communication between the Connector and Archicad anymore (nullability has been removed from properties)
C# connector:
* a new `Archicad.Room` class has been introduced for this communication
* `RoomConverter` and HTTP commands changed accordingly
C++ add-on:
* `GetRoomData` class renamed to `GetZoneData` (AC API terminology used)
* BasePoint calculation: we cut the polygon into half with a line parallel to one of axes, get the section lines, take one from the middle, and take the midpoint of it
* …
> feat(Archicad): Revit add support for Zones - Archicad side

- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertSpace.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertZone.cs
Minor clash between #2868 and #2884
Revit Converter.Doc was made static by accident, switched back by me but meanwhile Jonathon added some static functions that used the doc.
All static functions using Doc have now been reverted to non-static.
> fix(rvt): Fix static usages of Doc inside converter

- ConnectorGrasshopper/ConnectorGrasshopperShared/Objects/DeconstructSpeckleObjectTaskComponent.cs
Fixes #2896 
DSO was seemingly preventing any modifiers (such as graft, simplify or flatten) from being applied to the output parameters of the component.
In reality, what was happening is that our `OutputChanged` function had a small bug that was returning `true` for every case, leading to a complete reconstruction of the outputs on any minor change of the component.
This has now been fixed and component outputs work as expected.
Outputs are also sorted on every change, including rename of a single input, which if not done would cause a full recreation of the outputs, leading to the same result.
> fix(gh): fixes OutputChange bug in DSO that was forcing a param rebuild everytime

- ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/UI/ConnectorBindingsRhino.Receive.cs
- Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.BuiltElements.cs
- Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.Other.cs
- Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.cs
Fixes the following issues during receiving:
- Revit parameters with null values are now being handled correctly: previously this was throwing a null exception and preventing receives
- Receiving on a different mesh setting now updates all objects properly: previously, when re-receiving the same commit with a different mesh setting, the previously converted mesh objects were not being re-converted
- Now traverses and receives `Views` and `Levels` on revit commits without any geometry, by treating all `model` type collections as not convertible
rhino connector
> fix(rhino): various bugs when receiving

- DesktopUI2/DesktopUI2/Views/Windows/Dialogs/NewStreamDialog.xaml
Closes #2900
Improved semantics to aid the acceptance of Speckle in privacy/security interested organisations and individuals.
- Change the text for ToggleSwitch when IsChecked is true to "Link Shareable"
- Change the text for ToggleSwitch when IsChecked is false to "Private"
- increased padding between control and label text
> fix(DUI): Wording alignment between web and dui. Improved semantics.

- DesktopUI2/DesktopUI2/ViewModels/MappingTool/Schemas.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Categories.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertBlock.cs
- Objects/Objects/BuiltElements/Revit/Enums.cs
Fixes #2905  
It turns out the list of catagories that can be used for new family creation is a subset of the BuiltIn ones.
See dialog below. I created a list that matches the one in the Revit UI (manually, as I could not find anything on this in the API) and used that for the Block > New Family Mapper objects:
> fix(revit): Category not assigned to Blocks>NewFamily

- Objects/Converters/ConverterNavisworks/ConverterNavisworks/ConverterNavisworks.Geometry.cs
Changes across speckle-sharp by https://github.com/specklesystems/speckle-sharp/pull/2815 broke the internal NavisToSpeckle conversion.
Casting the internal interop object directly to `double` was an invalid cast.
This PR reverts to the previous state.
Closes #2908
> fix(navis): no geometry sent

- Core/Core/Models/GraphTraversal/DefaultTraversal.cs
Revit Traversal is still traversing all elements inside a `displayValue` list, even when we're already considering the parent object to be "displayable", and hence, convertible too.
This leads to duplicated objects when receiving "purely displayable objects" (ones that we can't directly convert), as the traversal will return the parent and all it's children.
Changes in this PR modify the Revit traversal so that it also stops traversing when an object is displayable (Navis objects are always purely displayable)
This could be related to some of the other instance duplication issues we've been encountering.
Kudos to @JR-Morgan for the quick session on traversal details.
> fix(rvt): Modified revit traversal to prevent traversing displayable objects

- Objects/Converters/ConverterNavisworks/ConverterNavisworks/ConverterNavisworks.ToSpeckle.cs
Fixes: #2893 
Non-anglicised installations of Navisworks could not send geometry.
- Prior Base object type conversion was tied to a localised string "Geometry" // me == dumbass
- Changed logic to a switch on HasGeometry as a method
- Extracted CategoryToSpeckle method into a new ConvertModelItemToSpeckle method
- Added helper methods: FindCategoryProperty, GetCategoryDisplayName, CreateSpeckleObject
- Updated comments for clarity and documentation<!---
I have run the application in various Latin and non-Latin language modes - all produced success.
> fix(Navis): Localised versions of Navis will now correctly build the commit object

- Objects/Converters/ConverterRevit/ConverterRevitShared/Categories.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/ConversionUtils.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/ConverterRevit.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertBlock.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertDirectShape.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertFreeformElement.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertRailing.cs
Fixes issues of failed railing creation due to improper sending and retrieval of built in categories for revit 2023 and 2024.
This pr mirror ths logic used by schema builder to remove "OST_" from bic internal names to find the equivalent RevitCategory, when before we were just using the category name. This was causing issues in differentiating between "OST_Railings" and "OST_StairsRailing" bics because they both had the category name of "Railing". Also seems to have fixed some issues in native railing conversion by retrieving the correct type.
Railings now received on fallback conversion:
> fix(revit): better handling of built-in-categories 

- ConnectorRevit/ConnectorRevit/TypeMapping/ElementTypeMapper.cs
- ConnectorRevit/ConnectorRevit/UI/ConnectorBindingsRevit.Receive.cs
- ConnectorRevit/ConnectorRevit/UI/ConnectorBindingsRevit.Settings.cs
> fix(revit): do not show the missing types dialog if the DS fallback option is set to Always

- Objects/Converters/ConverterRevit/ConverterRevitShared/ConverterRevit.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertDirectShape.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertDisplayableObject.cs
Fixes issue where we were getting duplicate objects when using the fallback to directshape setting when receiving.
This now searches for existing elements within the DS conversion not limited to DS objects, and adds a missing applicationID to created DS objects in the ConvertAsDisplayable method.
> fix(revit): displayable conversion now replaces existing objects on update receive

- Objects/Converters/ConverterRevit/ConverterRevitShared/ConverterRevit.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/ConverterRevitShared.projitems
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertFamilyInstance.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertPanel.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertRevitElement.cs
- Objects/Objects/BuiltElements/Revit/RevitCurtainWallPanel.cs
> ⚠️ **WARNING**
> This PR and #2912 fix the same issue in different ways. Only one of them should be merged
In the case of receiving curtain walls, where the parent wall (1) is convertible and (2) has panel and mullion objects inside the elements property that should not be created, we needed a way to skip the conversion of these elements in the connector.
This implementation includes:
- a new RevitCurtainWallPanel object that is just a RevitElement
- implements PanelToNative which just skips converting to native
> Fix(Revit) : add curtain panel class with ToNative implementation to avoid converting as displayable object

- Objects/Converters/ConverterRevit/ConverterRevitShared/ConversionUtils.cs
Revit tests for `DirectShapes` were failing as reported by @connorivy : 
Turns out this was due `DirectShape` having a `category` prop of type `RevitCategory` and not `string` (which is the case for all other revit built elements). This case check was removed in [https://github.com/specklesystems/speckle-sharp/commit/5dc407faaa0cc2a8be30afb65ab59f92e51de307](https://github.com/specklesystems/speckle-sharp/commit/5dc407faaa0cc2a8be30afb65ab59f92e51de307) with the intent of skipping category assignment if a category value already exists, assuming all missing categories would be of type `string`. Pr #2910 subsequently missed the null check and caused DS tests to fail.
Pr adds a type case check back in to make explicit the different types of `category` prop we can expect in our object model, …
> fix(revit): skips category assignment when category already exists on send

- ConnectorRevit/ConnectorRevit/TypeMapping/ElementTypeMapper.cs
- ConnectorRevit/ConnectorRevit/TypeMapping/FamilyImporter.cs
As reported here: https://www.notion.so/speckle/ImportTypes-Failed-ba359f3d6c8a43ccb0027f5ecce5591e?pvs=4
The `revitDocumentAggregateCache` was never initialized or passed to the `FamilyImporter` class, this caused a null reference exception. Not sure how this was working before or how it broke?
> fix(revit): type mapping null reference

- Objects/Objects/BuiltElements/Room.cs
v2.15.1 stream cannot be deserialised in case they contain Archicad Rooms.
Till that version the level property could be null, however a null check was introduced in the meantime.
The check has been removed.
> fix(Archicad): Room deserialisation fix

- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertWall.cs
Curtain walls were sending with a `null` displayValue property, resulting in their baseline being traversed in the viewer and other connectors. This sets the displayValue to empty to render the wall `displayable` during traversal.
> hotfix(revit): sets displayValue to empty for curtain walls

- ConnectorDynamo/ConnectorDynamoFunctions/Functions.cs
- ConnectorGrasshopper/ConnectorGrasshopperShared/Ops/Deprecated/Operations.ReceiveComponent.cs
- ConnectorGrasshopper/ConnectorGrasshopperShared/Ops/Deprecated/Operations.ReceiveComponentSync.cs
- ConnectorGrasshopper/ConnectorGrasshopperShared/Ops/Deprecated/Operations.SendComponent.cs
- ConnectorGrasshopper/ConnectorGrasshopperShared/Ops/Deprecated/Operations.SendComponentSync.cs
- ConnectorGrasshopper/ConnectorGrasshopperShared/Ops/Deprecated/Operations.VariableInputSendComponent.cs
- ConnectorGrasshopper/ConnectorGrasshopperShared/Ops/Operations.SyncReceiveComponent.cs
- ConnectorGrasshopper/ConnectorGrasshopperShared/Ops/Operations.SyncSendComponent.cs
- ConnectorGrasshopper/ConnectorGrasshopperShared/Ops/Operations.VariableInputReceiveComponent.cs
- ConnectorGrasshopper/ConnectorGrasshopperShared/Ops/Operations.VariableInputSendComponent.cs
- ConnectorGrasshopper/ConnectorGrasshopperShared/Streams/StreamCreateComponentV2.cs
- ConnectorGrasshopper/ConnectorGrasshopperShared/Streams/StreamListComponentV2.cs
- Core/Core/Api/GraphQL/Client.GraphqlCleintOperations/Client.ActivityOperations.cs
- Core/Core/Api/GraphQL/Client.GraphqlCleintOperations/Client.BranchOperations.cs
- Core/Core/Api/GraphQL/Client.GraphqlCleintOperations/Client.CommentOperations.cs
- Core/Core/Api/GraphQL/Client.GraphqlCleintOperations/Client.CommitOperations.cs
- Core/Core/Api/GraphQL/Client.GraphqlCleintOperations/Client.ObjectOperations.cs
- Core/Core/Api/GraphQL/Client.GraphqlCleintOperations/Client.ObsoleteOperations.cs
- Core/Core/Api/GraphQL/Client.GraphqlCleintOperations/Client.ServerOperations.cs
- Core/Core/Api/GraphQL/Client.GraphqlCleintOperations/Client.StreamOperations.cs
- Core/Core/Api/GraphQL/Client.GraphqlCleintOperations/Client.UserOperations.cs
- Core/Core/Api/GraphQL/Client.cs
- Core/Core/Api/GraphQL/Models.cs
- DesktopUI2/DesktopUI2/ConnectorHelpers.cs
- DesktopUI2/DesktopUI2/ViewModels/HomeViewModel.cs
- DesktopUI2/DesktopUI2/ViewModels/StreamSelectorViewModel.cs
This PR updates the `Client` functions to accept an optional `CancellationToken` parameter in the last position in the method signature.
This follows the C# convention defined by [CA1068: CancellationToken parameters must come last](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1068)
Following this convention improves the DX by 
- reducing the complexity of `Client` (by reducing overloads)
- using a cancellation structure developers are more familiar with
- using a cancellation structure consistent with other functions in Core
- Enables proper use of [`CA2016: Forward the CancellationToken parameter to methods that take one`](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2016)
- And for us, we have fewer warnings …
> chore(core): Make client functions consistent with cancellation token position

- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertCeiling.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertFloor.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertToposolid.cs
New curve extraction method for ceilings and floors based on extracting the drawn curve loops from the sketch. Each curve loop will become a polycurve.
This is the same behaviour that Toposolid uses.
Moved `GetSketchCurves` onto the floor file since TopoSolid file is only applied in 2024 and above.
Support for this new extraction logic only applies to >2022, so 2020 and 2021 continue to have the same issue.
> fix(rvt): Fixes curve extraction method for Ceilings and Floors

- Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.Other.cs
Uses the speckle id of a `renderMaterial` when no name exists. This was causing many duplicate render materials on receive in rhino.
Note: this needs https://github.com/specklesystems/speckle-server/issues/1806 to be fixed for render materials in ifc uploaded commits to receive well in rhino and other connectors.
- Rhino converter
> fix(rhino): default to using speckle id when creating render materials with no name

- ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/UI/ConnectorBindingsRhino.Previews.cs
- ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/UI/ConnectorBindingsRhino.Receive.cs
- Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.cs
- Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.BuiltElements.cs
- Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.cs
Adds conversions for `Gridline`s as `Curve`s. 
In Rhino, the gridline `label` property is added as the curve `name` as well as two `TextDot`s at the curve start and end. The curve uses a default dashed linetype if no `DisplayStyle` is found.
In AutoCAD, the curve is added with a default dashed linetype if no `DisplayStyle`. The label isn't created in Autocad.
Note: in order for display styles to be accurately represented, gridlines should be sent with a `DisplayStyle` property from Revit and other applications.
- Autocad connector and converter
- Rhino connector and converter
Rhino
Autocad
> feat(autocad/rhino): adds gridline to native conversion

- Objects/Converters/ConverterRevit/ConverterRevitShared/AllRevitCategories.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Categories.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/ConversionUtils.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertBlock.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertDirectShape.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertDisplayableObject.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertFreeformElement.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertRailing.cs
- Objects/Objects/BuiltElements/Revit/DirectShape.cs
Reverts: https://github.com/specklesystems/speckle-sharp/pull/2910
Changes the logic to use the BuiltInCategory instead of the `RevitCategory` enum, because more reliable:
- adds a `builtInCategory` prop to every element coming out of Revit
- when falling back to DirectShape first checks if there is a `builtInCategory` prop and uses that, and if not uses the old `RevitCategory` enum
Internal notes: https://www.notion.so/speckle/2-16-Category-Mis-Alignment-8d5a51e672fc4314883eab3af2f02b2d#8ca51ecef5c148ae8cdb48f1b58e4c53
- send from the sample revit model
- receive in a new doc with direct shape fallback logic set to Always
- railings are received correctly
in the future we should:
- get rid of the `RevitCategory` enum entirely
- better align the collections names and element category …
> feat(revit): send builtInCategories

- Core/Core/Api/GraphQL/Models.cs
- Core/Core/Credentials/AccountManager.cs
Adds info needed to deliver a better UX when using DU2 & FE2:
- adds a (temporary?) `frontend2` prop to the `serverInfo` class
- checks against the response headers to see if a server/account is using frontend 2
> feat: check if server is using fe2

- Core/Core/Api/GraphQL/Models.cs
- Core/Core/Credentials/AccountManager.cs
- DesktopUI2/DesktopUI2/ViewModels/CommentViewModel.cs
- DesktopUI2/DesktopUI2/ViewModels/DialogViewModel.cs
- DesktopUI2/DesktopUI2/ViewModels/HomeViewModel.cs
- DesktopUI2/DesktopUI2/ViewModels/StreamViewModel.cs
- DesktopUI2/DesktopUI2/Views/Controls/StreamEditControls/Comments.xaml
- DesktopUI2/DesktopUI2/Views/Pages/HomeView.xaml
- DesktopUI2/DesktopUI2/Views/Windows/Dialogs/AddAccountDialog.xaml.cs
- DesktopUI2/DesktopUI2/Views/Windows/Dialogs/AddFromUrlDialog.xaml
- DesktopUI2/DesktopUI2/Views/Windows/Dialogs/AddFromUrlDialog.xaml.cs
- DesktopUI2/DesktopUI2/Views/Windows/Dialogs/NewStreamDialog.xaml
- DesktopUI2/DesktopUI2/Views/Windows/Dialogs/NewStreamDialog.xaml.cs
Depends on: #2989 
This PR improves how DUI2 integrates with FE2:
- moves the FE2 toggle to the main toolbar
- any stream related action (eg view online) now automatically detects if a stream is on fe2 and uses the new routes
- added more string replacements here and there
NOTE: this PR depends on some changes to Manager which are already being rolled out (current beta)
> feat(dui): better fe2 compatibility

- Core/Core/Api/GraphQL/Client.GraphqlCleintOperations/Client.StreamOperations.cs
In https://github.com/specklesystems/speckle-sharp/pull/2925, I accidently introduced a regression by renaming  `id` -> `streamId` in StreamGetPendingCollaborators
(side note, this demonstrates we are missing an integration test for this query)
> fix(core): Fixed regression with stream collaborators query parameters

- Core/Core/Helpers/Http.cs
We have a reported issue of crashing in Revit 2024 which appears to relate to cert validation.
As a test we setting this to false to not check for valid certification...
https://speckle.community/t/revit-2024-1-1-speckle-not-functional/7598
This involved explicitly setting the property on the handler.
> Suppress CRL checking

- Core/docker-compose.yml
Core tests for #3016 were failing due to the `minio/minio` container failing health check.
The current compose file used for the core integration tests uses `minio/minio` latest which is currently an alias for `RELEASE.2023-11-01T01-57-10Z`
This PR pinns the version to the release before last `minio/minio:RELEASE.2023-10-25T06-33-25Z`
https://app.circleci.com/pipelines/github/specklesystems/speckle-sharp/12266/workflows/dc31cf3a-3dbc-40c1-953d-209c2ccadaf9/jobs/93448
We'll look into why the health check is failing on the newer version some other time.
> fix(ci): Pinned MinIO version in core docker compose

- Core/Core/Helpers/Http.cs
Prepping for hotfix to remove Cert Revocation List checking.
> Remove enforcement of Cert Revocation List Check

- DesktopUI2/DesktopUI2/ViewModels/StreamViewModel.cs
Increases the limit of branches pulled from DUI from 100 to 500.
https://speckle.community/t/is-there-a-limit-in-the-number-of-branches-you-can-have-in-a-stream/7692/5?u=teocomi
> fix(dui): bump branch limit to 500

- Core/Core/Helpers/Http.cs
- Directory.Build.props
See #3018 
Removes the additional line to check certificate revocation list
Suppresses CA5399 violation on method
Makes CA5399 a nowarn
> chore(dev): Remove CRL check from proxy client

- Objects/Converters/ConverterRevit/ConverterRevitShared/ConversionUtils.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/ConverterRevit.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/UpdateParameter.cs
> ⚠️ Reported by Pavol, pending linking with Notion backlog issue
> ❗️Targeting `main` as I'm assuming we'd want this as a hotfix, but we can target `dev` if this is not the case.
Fixes issue with ParameterUpdater objects from Grasshopper not succeeding conversion when received in Revit.
Nothing was wrong with the conversion itself, but the addition of `DisplayableObject` conversions introduced the assumption that if the conversion returned `null` it had failed.
This assumption did not hold for `ParameterUpdater` conversions, where **it was always returning null** as the function had a `void` return.
This PR changes the signature of the UpdateParameter method so that it returns an app object, in line with every other conversion. This results in the connector assuming conversion has …
> fix(rvt): Modify signature of `RevitConverter.UpdateParameter` to return AppObj

- ConnectorGrasshopper/ConnectorGrasshopperShared/SchemaBuilder/CreateSchemaObject.cs
- ConnectorGrasshopper/ConnectorGrasshopperShared/SchemaBuilder/CreateSchemaObjectBase.cs
- ConnectorGrasshopper/ConnectorGrasshopperUtils/UserInterfaceUtils.cs
Fixes issue originally introduced in https://github.com/specklesystems/speckle-sharp/pull/2694: Sorting was performed on the original values, which changed the indexes of the enum, hence modifying it's return value to an unrelated one.
Unifies the implementation of the dropdown enum creation into the GrasshopperUtils project (already existing), so that miss-alignment around this cannot occur anymore.
Introduces new `UserInterfaceUtils` class to hold this logic (and any other in the future related to Grasshopper UI things)
- `CreateEnumDropdown` -> Is the replacement of the original `CreateDropdown`, but now works more robustly and should preserve all integer values of an enum regardless of sorting.
- `CreateCanvasDropdownForAllEnumInputs` (name pending revision 😅): Will create all the …
> fix(gh): Fixes sorting on dropdown for input enum values

- ConnectorCSI/ConnectorCSIShared/UI/ConnectorBindingsCSI.Recieve.cs
- ConnectorCSI/ConnectorCSIShared/UI/ConnectorBindingsCSI.Send.cs
- ConnectorCSI/ConnectorCSIShared/Util/ConnectorCSIUtils.cs
- ConnectorCSI/ConnectorCSIShared/cPlugin.cs
- ConnectorRevit/ConnectorRevit/UI/ConnectorBindingsRevit.Receive.cs
- ConnectorRevit/ConnectorRevit/UI/ConnectorBindingsRevit.Send.cs
- ConnectorTeklaStructures/ConnectorTeklaStructuresShared/UI/ConnectorBindingsTeklaStructure.Send.cs
- ConnectorTeklaStructures/ConnectorTeklaStructuresShared/UI/ConnectorBindingsTeklaStructures.Receive.cs
- DesktopUI2/DesktopUI2/ConnectorHelpers.cs
Unified connector logging between CSI, Tekla, and Revit
- Fixed issue with CSI connectors reporting as CoreUnknown
- Added `Setup.Init` call just after we create bindings (same way Revit & Autocad)
- Added new connector helper functions for logging converter errors
- I was finding that I was duplicating the big catch cases between connectors. So I extracted them out to two functions. One for logging to seq, the other for grabbing the correct AppObject status to report.
- Added converter settings to logging
- Previously, we were just reporting the converter name + author + direction. I added the converter settings dictionary to the mix so we can create some dashboards on which settings users are using. This might help us inform defaults + where to focus our effort in future.
> log(structral): Unified logging between structural connectors

- ConnectorArchicad/AddOn/Sources/AddOn/Commands/CreateBeam.cpp
- ConnectorArchicad/AddOn/Sources/AddOn/Commands/CreateColumn.cpp
- ConnectorArchicad/AddOn/Sources/AddOn/Commands/CreateCommand.cpp
- ConnectorArchicad/AddOn/Sources/AddOn/Commands/CreateCommand.hpp
- ConnectorArchicad/AddOn/Sources/AddOn/Commands/CreateDoor.cpp
- ConnectorArchicad/AddOn/Sources/AddOn/Commands/CreateObject.cpp
- ConnectorArchicad/AddOn/Sources/AddOn/Commands/CreateRoof.cpp
- ConnectorArchicad/AddOn/Sources/AddOn/Commands/CreateShell.cpp
- ConnectorArchicad/AddOn/Sources/AddOn/Commands/CreateSkylight.cpp
- ConnectorArchicad/AddOn/Sources/AddOn/Commands/CreateSlab.cpp
- ConnectorArchicad/AddOn/Sources/AddOn/Commands/CreateWall.cpp
- ConnectorArchicad/AddOn/Sources/AddOn/Commands/CreateWindow.cpp
- ConnectorArchicad/AddOn/Sources/AddOn/Commands/CreateZone.cpp
- ConnectorArchicad/AddOn/Sources/AddOn/Commands/GetDataCommand.cpp
- ConnectorArchicad/AddOn/Sources/AddOn/FieldNames.hpp
- ConnectorArchicad/ConnectorArchicad/Elements/Object.cs
- ConnectorArchicad/ConnectorArchicad/Elements/Room.cs
- Objects/Objects/BuiltElements/Beam.cs
- Objects/Objects/BuiltElements/Column.cs
- Objects/Objects/BuiltElements/Floor.cs
- Objects/Objects/BuiltElements/Roof.cs
- Objects/Objects/BuiltElements/Room.cs
- Objects/Objects/BuiltElements/Wall.cs
To send and receive `layer` information from Archicad.
Objects:
* new `Layer` string type property is introduced
Archicad Connector:
* send and receive codes changed accordingly 
* when receiving, an Archicad layer with that specific name should be present (like other Archicad attributes, no attributes are created)
> feat(Archicad): Send and receive layer information

- Objects/Converters/ConverterCSI/ConverterCSIShared/PartialClasses/Geometry/ConvertArea.cs
- Objects/Converters/ConverterCSI/ConverterCSIShared/PartialClasses/Geometry/ConvertFrame.cs
Extracted one important change from #3008 to ensure that we never set objects to AppObject.Status.Failed and instead throw an exception.
This guarantees that failed objects will always have an error message in the report.
> chore(CSI): added exception for failing areas and frames

- Objects/Objects/BuiltElements/Beam.cs
- Objects/Objects/BuiltElements/Column.cs
- Objects/Objects/BuiltElements/Floor.cs
- Objects/Objects/BuiltElements/Roof.cs
- Objects/Objects/BuiltElements/Wall.cs
In case of null objects, `public override Level? level` can accept nulls, however an exception is thrown.
Enable nulls to be set as `level` properties.
> fix(archicad): Archicad nullable levels fix

- ConnectorArchicad/AddOn/Sources/AddOn/Commands/GetElementTypes.cpp
- ConnectorArchicad/AddOn/Sources/AddOn/Commands/GetSubElementInfo.cpp
- ConnectorArchicad/AddOn/Sources/AddOn/TypeNameTables.cpp
- ConnectorArchicad/AddOn/Sources/AddOn/TypeNameTables.hpp
According to the introduction of Grid send and receive, Archicad element types are identified by `typeId` and `variationId` pairs (earlier only by `typeId`), because the GridElement in Archicad is an Object with subtype `APIVarId_GridElement`.
There could be other element types with `variationId` (e.g. corner window) in the model, which were not handled in a hashtable.
Checking the hash table before referencing an element in it.
> fix(Archicad): Crash when sending a Corner Window

- Core/Core/Api/ServerLimits.cs
- Core/IntegrationTests/Api.cs
- Core/IntegrationTests/TestsIntegration.csproj
- Core/docker-compose.yml
- DesktopUI2/DesktopUI2/ViewModels/StreamSelectorViewModel.cs
- DesktopUI2/DesktopUI2/ViewModels/StreamViewModel.cs
Fully aligns codebase with changes from #3021.
- Created a new `ServerLimits` static class to hold this magic number (and others that will come)
- Applied the change to all calls of `StreamGetBranches`
- Added tests to verify branch limits are respected in SDK and resulting data aligns with expectations.
- Added ENV var in docker-compose.yml to upgrade test server limit to 500.
Tests are quite simple, but I didn't want to start re-engineering our integration test logic to fit this particular edge-case (tests depend on each other, can get messy). Ideally, API.cs in the integration tests should be split into pieces.
> fix(core): Fixes Branch get Limit up to 500

- Core/Core/Api/GraphQL/Client.GraphqlCleintOperations/Client.BranchOperations.cs
- Core/Core/Api/GraphQL/Client.cs
- DesktopUI2/DesktopUI2/ViewModels/StreamSelectorViewModel.cs
- DesktopUI2/DesktopUI2/ViewModels/StreamViewModel.cs
Currently if the server's GQL backend supports only 100 elements and we request 500, then the call to get the branches fails a bit opaquely. With this change, if the call fails asking for 500, we drop to asking for 100.
Just a DUI change to proxy the call through another method and retry on failed 500 request with 100 limt.
Validation would need performing on a speckle.xyz exhibting the problem.
> Hotfix to tolerate server branch limits of 100 and 500

- ConnectorArchicad/ConnectorArchicad/Communication/HttpCommandExecutor.cs
Dump of HTTP request and response messages between Archicad add-on and the Connector has been removed.
It is a debug code should not be there in production.
> fix(Archicad): Timeout after 100s when sending large models

- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertDuct.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertFreeformElement.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertPipe.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertRoof.cs
Fixes bugs when receiving generic mep elements, which was a regression due to the recent revit `Network` refactor. This was causing failed conversions when receiving built elements from Grasshopper.
Includes some minor changes to `RoofToNative` and `FreeformElementToNative` conversions, but does not successfully fix receiving for those elements sent from Grasshopper BuiltElements test file.
Before:
After:
> fix(revit): receiving generic mep elements

- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/Units.cs
Fixes issue encountered when testing QGIS->Revit
Units from qgis were on a valid value but not on the standard format.
Revit's UnitToNative implementation differed from others in that it was not ensuring the units string that was passed had the correct value (i.e. "m" instead of "meters").
This is achieved by calling `Units.GetUnitsFromString`, which parses the string value into the standard unit string.
> fix(rvt): Revit's UnitToNative did not ensure units were parsed

- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertFreeformElement.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertGeometry.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertRoof.cs
Extrusion roofs were not being properly converted to native due to incorrect use of `roof.outline` in place of `extrusionRoof.referenceLine`.
Freeform elements received in revit from GH with no subcategory assigned are now successfully created. Previously, setting null or generic model default subcategory was throwing errors on solid creation.
> fix(revit): extrusion roof and freeform elements conversion

- Objects/Converters/ConverterRevit/ConverterRevitShared/Partial Classes/ConvertSpace.cs
For Revit to native, we are still updating the app object directly.
Not nice, but safer imo than throwing right now until we properly refactor this aspect of the connector (like we've already done for ToSpeckle)
> Clearer error message for failed spaces

- Objects/Converters/ConverterCSI/ConverterCSIShared/ConverterCSIShared.projitems
Fixes incorrect casing on one of the paths for the ConverterCSIShared project.
This was breaking Nuget builds, which are done in Linux and have a stricter case-sensitivity than Windows (where our connectors and installers are built)
> fix(CSI): wrong case in shared CSI file path

- ConnectorArchicad/ConnectorArchicad/Communication/ConnectionManager.cs
Additional timeout increase for https://github.com/specklesystems/speckle-sharp/pull/3038.
Timeout of HTTP request calls to Archicad API has been increased to 300s.
(Investigation of possible performance slow down is to come later.)
> fix(Archicad): Timeout after 100s when sending large models #2

- Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.cs
TextEntity cannot be fetched from Rhino, but can be created through a Python/C# script, and obviously received through Speckle.
It also cannot be baked from Grasshopper, so users are left the responsibility of knowing what to do with these.
Since they're convertible, you can always plug them into a "Deconstruct Speckle Object" to get their inner info.
> feat(gh): Add support for TextEntity conversion both ways.

- ConnectorCSI/ConnectorCSIShared/Util/ConnectorCSIUtils.cs
- Objects/Converters/ConverterCSI/ConverterCSIShared/PartialClasses/Analysis/ConvertModel.cs
Removes all CA1806 warnings from CSI projects:
This fixes a bug in `GetAllNamesOfObjectType` where the `Model` name was not being included in the list.
Also removes some unnecessary `ToList` calls whose output was not being used.
> fix(csi): CNX-8342 Fix CA1806 for CSI projects

- DesktopUI2/DesktopUI2/ViewModels/OneClickViewModel.cs
We forgot to add the switch in the One Click Mode.
Here's a quick fix for it that should be probably released as hotfix sometime soon.
Community report: https://speckle.community/t/rhino-speckle-connector-server-link-issue/8170/2
> fix(dui): broken fe2 url when in oneclick mode

- ConnectorCSI/ConnectorCSIShared/Util/ConnectorCSIUtils.cs
- ConnectorDynamo/ConnectorDynamoFunctions/BatchConverter.cs
- Directory.Build.props
- Objects/Converters/ConverterCSI/ConverterCSIShared/PartialClasses/Analysis/ConvertModel.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/PartialClasses/ConvertFaceWall.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/PartialClasses/ConvertGeometry.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/PartialClasses/ConvertRebar.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/RevitVersionHelper.cs
- Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.Other.cs
- Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.cs
- Objects/Objects/BuiltElements/Wall.cs
This is the main PR to collect all CA1806 fixes and verify all projects are correct before merging.
This branch already contains the enforcement on CI for CA1806, all builds containing this warning will fail.
> fix(all): CNX-7446 - ⚠️ CA1806 Fix

- Automate/Speckle.Automate.Sdk/AutomationContext.cs
- Automate/Tests/Speckle.Automate.Sdk.Tests.Integration/SpeckleAutomate.cs
- ConnectorDynamo/ConnectorDynamoFunctions/Developer/Local.cs
- ConnectorDynamo/ConnectorDynamoFunctions/Functions.cs
- ConnectorGrasshopper/ConnectorGrasshopperShared/Ops/Operations.SendLocalComponent.cs
- Core/Core/Api/Helpers.cs
- Core/Core/Api/Operations/Operations.Send.cs
- Core/Core/Api/Operations/Operations.Serialize.cs
- Core/Core/Api/Operations/Operations.cs
- Core/Core/Kits/Applications.cs
- Core/Core/Models/Base.cs
- Core/Core/Serialisation/BaseObjectSerializerV2.cs
- Core/Core/Transports/Exceptions.cs
- Core/Core/Transports/ITransport.cs
- Core/Core/Transports/Memory.cs
- Core/Core/Transports/SQLite.cs
- Core/IntegrationTests/Api.cs
- Core/IntegrationTests/ServerTransportTests.cs
- Core/IntegrationTests/Subscriptions/Commits.cs
- Core/Tests/ClosureTests.cs
- Core/Tests/SendReceiveLocal.cs
- Core/Transports/DiskTransport/DiskTransport.cs
- DesktopUI2/DesktopUI2/ConnectorHelpers.cs
- Directory.Build.props
As part of our effort to reduce analyser warnings across our code base. It's important that our Core functions are clear about what exceptions types they throw.
This motivation for this PR was to focus on `Operations.Send` and attempt to enforce and provide clear guidance on the exception types that can be thrown.
Our original `Operations.Send` overloads were doing some smelly things:
In the signature of the function alone:
1. We were allowing users to pass in a `SerializerVerion` enum to switch to using the old v1 serializer. This serializer hasn't been used (or tested) in almost two years, its past time we drop exposing it as an option for `Operations.Send`
2. A long time ago, we were using `OnErrorAction` to signal errors in transports and sending. We have since deprecated this in …
> feat(Core): CNX-8352 operations.send

- All.sln
I noticed several connector projects in our All.sln were missing the indirect build dependency on their converter. 
This is needed so when you make changes to the converter, and then build/run the connector, the converter should also be rebuilt.
> fix(sln): Added postProject build dependencies for missing connector

- Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.Organization.cs
- Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.Utils.cs
Handles ca1031 warnings in the rhino converter. Mostly concerns layer handling, and `CollectionToNative` conversions, including a minor fix for missing invalid chars and minor refactoring to remove duplicated local methods.
- Rhino converter
> fix(rhino): CNX-8572 Handles ca1031 in Rhino converter files

- Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.Civil.cs
Adjusts the previous pr's implementation of design speeds to include design speeds that may not be on an alignment's existing stations. 
This implementation stores each design speed as a `Base` with 4 properties: the speed `number`, `station`, `value`, and `comment` (if exists). The list of speeds is stored as a detached `List<Base>` on the alignment.
[https://speckle.xyz/streams/b53a53697a/commits/89b9c3e6f5](https://speckle.xyz/streams/b53a53697a/commits/89b9c3e6f5)
- Civil3D converter
> feat(civil3d): CNX-8013 add alignment properties design speed

- Objects/Converters/ConverterRevit/ConverterRevitShared/RevitCommitObjectBuilder.cs
This commit refactors the `RevitCommitObjectBuilder` class to handle the retrieval of a FabricationPart's associated host element. It introduces a new private method, `HandleFabricationPart`, which processes a `FabricationPart` and returns its host element. The method checks if the `FabricationPart` has a host and retrieves it using the `GetHostedInfo()` method.
The prior code would pass `null` from `GetHostedInfo()` into `GetElement()` which threw from deep withing the Revit API
Before: 
After:
Manual testing with provided test file.
> fix(Revit): CNX-8655 - handle FabricationPart host retrieval

- ConnectorArchicad/ConnectorArchicad/Communication/AsyncCommandProcessor.cs
- ConnectorArchicad/ConnectorArchicad/ConnectorBinding.cs
- ConnectorArchicad/ConnectorArchicad/Converters/ElementConverterManagerReceive.cs
Handle CA1031 warnings in ArchiCAD projects
https://spockle.atlassian.net/browse/CNX-8392
Specific exceptions used.
> fix(Archicad): CNX-8392 Handle CA1031 warnings in ArchiCAD projects

- Automate/Speckle.Automate.Sdk/AutomationContext.cs
- Automate/Speckle.Automate.Sdk/Runner.cs
- Automate/Speckle.Automate.Sdk/Schema/AutomationRunData.cs
- Automate/Speckle.Automate.Sdk/Schema/AutomationStatusMapping.cs
- Automate/Speckle.Automate.Sdk/Schema/ObjectResultLevelMapping.cs
- Automate/Speckle.Automate.Sdk/Schema/ObjectResultValues.cs
- Automate/Speckle.Automate.Sdk/Schema/ObjectResults.cs
- Automate/Speckle.Automate.Sdk/Speckle.Automate.Sdk.csproj
- Automate/Tests/Speckle.Automate.Sdk.Tests.Integration/GetAutomationStatus.cs
- Automate/Tests/Speckle.Automate.Sdk.Tests.Integration/README.md
- Automate/Tests/Speckle.Automate.Sdk.Tests.Integration/Speckle.Automate.Sdk.Tests.Integration.csproj
- Automate/Tests/Speckle.Automate.Sdk.Tests.Integration/SpeckleAutomate.cs
- Automate/Tests/Speckle.Automate.Sdk.Tests.Integration/TestAutomateFunction.cs
- Automate/Tests/Speckle.Automate.Sdk.Tests.Integration/TestAutomateUtils.cs
Fixing all warnings on Automate.SDK and it's test project. And added README for test project.
> Fix(Automate): CNX-8610 automate sdk warnings

- .editorconfig
- Core/Tests/Speckle.Core.Tests.Integration/Api.cs
- Core/Tests/Speckle.Core.Tests.Integration/Fixtures.cs
- Core/Tests/Speckle.Core.Tests.Integration/GraphQLCLient.cs
- Core/Tests/Speckle.Core.Tests.Integration/ServerTransportTests.cs
- Core/Tests/Speckle.Core.Tests.Integration/Speckle.Core.Tests.Integration.csproj
- Core/Tests/Speckle.Core.Tests.Integration/Subscriptions/Branches.cs
- Core/Tests/Speckle.Core.Tests.Integration/Subscriptions/Commits.cs
- Core/Tests/Speckle.Core.Tests.Integration/Subscriptions/Streams.cs
- Core/Tests/Speckle.Core.Tests.Unit/Api/GraphQLClient.cs
- Core/Tests/Speckle.Core.Tests.Unit/Api/Operations/OperationsReceiveTests.Exceptional.cs
- Core/Tests/Speckle.Core.Tests.Unit/Api/Operations/OperationsReceiveTests.cs
- Core/Tests/Speckle.Core.Tests.Unit/Api/Operations/SendReceiveLocal.cs
- Core/Tests/Speckle.Core.Tests.Unit/Api/Operations/SerializationTests.cs
- Core/Tests/Speckle.Core.Tests.Unit/Credentials/Accounts.cs
- Core/Tests/Speckle.Core.Tests.Unit/Credentials/FE2WrapperTests.cs
- Core/Tests/Speckle.Core.Tests.Unit/Helpers/Path.cs
- Core/Tests/Speckle.Core.Tests.Unit/Kits/KitManagerTests.cs
- Core/Tests/Speckle.Core.Tests.Unit/Models/BaseTests.cs
- Core/Tests/Speckle.Core.Tests.Unit/Models/Extensions/ExceptionTests.cs
- Core/Tests/Speckle.Core.Tests.Unit/Models/Hashing.cs
- Core/Tests/Speckle.Core.Tests.Unit/Models/TraversalTests.cs
- Core/Tests/Speckle.Core.Tests.Unit/Serialisation/SerializerNonBreakingChanges.cs
- Core/Tests/Speckle.Core.Tests.Unit/Transports/SQLiteTransportTests.cs
- Core/Tests/Speckle.Core.Tests.Unit/Transports/TransportTests.cs
- Directory.Build.targets
- Resolved naming violations in Integration test projects
- Updated editor config to warn when using the old nunit functions
- Updated both Unit and integration tests to use the new unit functions
- Removed ConfigureAwaits from test project:
- My reasoning is. They aren't needed, don't provide value, just adds visual clutter.
- Happy to discuss and revert if prefered.
> Chore(Tests): CNX-8640 core integration test project

- ConnectorGrasshopper/ConnectorGrasshopperShared/Accounts/Accounts.ListAccounts.cs
- ConnectorGrasshopper/ConnectorGrasshopperShared/Extras/GH_SpeckleAccount.cs
- Core/Core/Credentials/Account.cs
- Core/Core/Credentials/AccountManager.cs
- Core/Tests/Speckle.Core.Tests.Unit/Credentials/Accounts.cs
Fixes ambiguity between accounts by no longer trying to find an account exclusively by it's user ID.
The accounts are now distinguished by their "Local Identifier", which is basically just the server URL with an `id` query parameter holding the user ID.
`https://speckle.xyz/?id=USER_ID`
This guarantees uniqueness of each user+server pair.
Changes in this PR include:
- `Account` class: Addition of internal `GetLocalIdentifier`
- `AccountManager` class:Addition of `GetLocalIdentifierForAccount` and `GetAccountForLocalIdentifier`
- `Accounts.ListAccounts` GH component: Now uses the above AccountManager methods everywhere it's needed. It also now outputs actual `Account` instances instead of the previous user ID, so the solution is now more robust.
- `GH_SpeckleAccount` class: No longer …
> fix(grasshopper): CNX-8642 resolving account by id from the accounts list will return the first account found in a server running fe1 fe2

- ConnectorDynamo/ConnectorDynamo.slnf
- ConnectorDynamo/ConnectorDynamo/CreateStreamNode/CreateStream.cs
- ConnectorDynamo/ConnectorDynamo/ReceiveNode/Receive.cs
- ConnectorDynamo/ConnectorDynamo/SendNode/Send.cs
- ConnectorDynamo/ConnectorDynamoExtension/SpeckleExtension.cs
- ConnectorDynamo/ConnectorDynamoExtension/SpeckleWatchHandler.cs
- ConnectorDynamo/ConnectorDynamoFunctions/Auto.cs
- ConnectorDynamo/ConnectorDynamoFunctions/BatchConverter.cs
- ConnectorDynamo/ConnectorDynamoFunctions/Functions.cs
- ConnectorDynamo/ConnectorDynamoFunctions/Stream.cs
- ConnectorDynamo/ConnectorDynamoFunctions/Utils.cs
- Directory.Build.props
- Objects/Converters/ConverterDynamo/ConverterDynamoShared/ConverterDynamo.Geometry.cs
- Objects/Converters/ConverterDynamo/ConverterDynamoShared/Utils.cs
https://spockle.atlassian.net/browse/CNX-8394
Here goes nothing! I have to confess I've had to held back on refactoring half the codebase here... so I've made heavy use of `IsFatal` as there were places where it was unclear what could be thrown.
PR removes all CA1031 warnings from the Dynamo project, and a minor refactor of 1 horrible method with an very old angry comment above it 😅
> fix(dynamo): CNX-8394 Handle CA1031 warnings in Dynamo projects

- ConnectorAutocadCivil/ConnectorAutocadCivil/Entry/App.cs
- ConnectorAutocadCivil/ConnectorAutocadCivil/Entry/SpeckleAutocadCommand.cs
- ConnectorAutocadCivil/ConnectorAutocadCivil/UI/ConnectorBindingsAutocadCivil.Send.cs
- ConnectorGrasshopper/ConnectorGrasshopperShared/Ops/Operations.VariableInputReceiveComponent.cs
- Core/Core/Api/GraphQL/Serializer/MapConverter.cs
- Core/Core/Core.csproj
- Core/Core/Credentials/Account.cs
- Core/Core/Helpers/Path.cs
- Core/Transports/MongoDBTransport/MongoDBTransport.csproj
- Directory.Build.props
- Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.Civil.cs
- Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.Geometry.cs
- Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.Mappings.cs
- Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.Utils.cs
- Objects/Objects/BuiltElements/AdvanceSteel/AsteelBolt.cs
- Objects/Objects/BuiltElements/Revit/Parameter.cs
- Objects/Objects/Geometry/Extrusion.cs
- Objects/Objects/Objects.csproj
- Objects/Objects/Utils/MeshTriangulationHelper.cs
- For CI builds only:
- Added `TreatWarningsAsErrors` on all SDK projects
- Added existing warning codes as `WarningsNotAsErrors`
This means that no new types of warnings can be introduced without CI erroring.
It won't stop new violations of any of the existing types.
Remaining Warnings in Objects
```
69 | IDE1006 
33 | CA1819 
26 | CA1034 
11 | IDE0060 
9 | CA1708 
7 | CA2225 
6 | CA2201 
5 | CA1711 
4 | CA1008 
4 | CA1724 
4 | CS0728 
3 | CA1716 
2 | CA1024 
1 | CA1051 
1 | CA1065 
1 | CA1725 
1 | CS0659 
1 | CS0661 
1 | IDE0041 
```
Remaining Warnings in Core
```
59 | IDE1006 
10 | CA1003 
8 | CA1051 
8 | CA1724 
7 | CA1710 
5 | CS8600 
5 | CS8602 
4 | CA1000 
3 | CA1063 
3 | CA1502 
3 | CA1720 
3 | CA1851 
3 | CS0618 
3 | CS8604 
2 | CA1708 
2 | CA1711 
2 | CA2201 
2 | CS8603 
2 | …
```
> Chore(build): CNX-8713 CNX-8572 CNX-8389: Enforce no more warning  (Unique Analyser codes) for SDK projects

- Directory.Build.props
#3150 made all Level 1 warnings errors that didn't have existing violations.
However, it accidently included a couple that have violations.
Weirdly, it appears some of these analysers don't get run as errors on build anyway, so this was how it slipped past me.
Further investigation required, but for now, this PR means Rider doesn't show squiggly red files despite MSBuild compiling successfully
> Chore(build) Lowered several XML warnings from errors

- ConnectorArchicad/AddOn/Sources/AddOn/TypeNameTables.cpp
https://spockle.atlassian.net/browse/CNX-8849
There is new zone relation type (APIZRel_SubtractFromZone) introduced in AC27 which was not handled in a hashset.
Crashed here:
`	os.Add (Column::ColumnRelationToZoneName, relationToZoneNames.Get (elem.column.zoneRel));`
Hashset entry added to `relationToZoneNames` according to the AC27 API.
> fix(Archicad): Crash when sending columns with "subtract from zone" relation

- ConnectorCore/BatchUploader.Sdk/BatchUploader.Sdk.csproj
Using the 7.0.3 version of System.Text.Json in Batchuploader SDK is causing conflicts with core/revit
> CNX-8753-Downgrade-Text.Json

- ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/UI/ConnectorBindingsRhino.Receive.cs
- Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.Other.cs
- Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.Utils.cs
Adds missing user strings to nested blocks when converting to native.  Refer to this community post for more info: [https://speckle.community/t/questions-about-nested-blocks-from-rhino/8955/3](https://speckle.community/t/questions-about-nested-blocks-from-rhino/8955/3)
Receive this commit: [https://latest.speckle.dev/streams/3f895e614f/commits/ff0ab3fe69](https://latest.speckle.dev/streams/3f895e614f/commits/ff0ab3fe69)
> bug(rhino): fixes missing user strings on nested instances when receiving

- ConnectorGrasshopper/ConnectorGrasshopperShared/Ops/Operations.VariableInputSendComponent.cs
- ConnectorGrasshopper/ConnectorGrasshopperShared/Streams/StreamListComponentV2.cs
https://spockle.atlassian.net/browse/CNX-8866
Fixes how Grasshopper duplicates StreamWrapper's by also propagating the original account.
This ensures that the logic to expose FE2 or FE1 logic gets also preserved after the streamwrapper was validated.
> CNX-8866 Grasshopper nodes format result URL in Stream/Branch format regardless of the input format

- ConnectorGrasshopper/ConnectorGrasshopperShared/Accounts/Accounts.GetAccountToken.cs
Account token component was broken by this PR https://github.com/specklesystems/speckle-sharp/pull/3141 which changed the behavior of accounts
This PR applies the same fix that was used for the other components that depended on the account component.
> Fix(GH) : account token component not finding correct account

- Automate/Speckle.Automate.Sdk/AutomationContext.cs
> fix: enforce the minimum 1 objectId is in the automate result case

- ConnectorArchicad/ConnectorArchicad/Converters/Converters/BeamConverter.cs
- ConnectorArchicad/ConnectorArchicad/Converters/Converters/ColumnConverter.cs
- ConnectorArchicad/ConnectorArchicad/Converters/Converters/DoorConverter.cs
- ConnectorArchicad/ConnectorArchicad/Converters/Converters/FloorConverter.cs
- ConnectorArchicad/ConnectorArchicad/Converters/Converters/RoofConverter.cs
- ConnectorArchicad/ConnectorArchicad/Converters/Converters/SkylightConverter.cs
- ConnectorArchicad/ConnectorArchicad/Converters/Converters/Utils.cs
- ConnectorArchicad/ConnectorArchicad/Converters/Converters/WallConverter.cs
- ConnectorArchicad/ConnectorArchicad/Converters/Converters/WindowConverter.cs
Fixes: https://spockle.atlassian.net/browse/CNX-8875
Cause of the problem: during sending Archicad properties, for better readability on the server, property names and property values are exported as JSON key-value paris (see `PropertyGroup.ToBase` and other `.ToBase` functions). In case of localized version of Archicad these JSON keys can contain special characters. From the JSON standard point of view it is a valid format, however Archicad's JSON interpretation drops this data.
Since currently properties are not imported back to Archicad, we clear the `elementProperties` and `componentProperties` during receive process. (`elements` property can contain door/window subelements in the same JSON format, however since they are converted in a separate step, `elements` property also cleared.)
> fix(Archicad): Could not receive parametric elements with localized version of Archicad

- All.sln
- ConnectorGrasshopper/ConnectorGrasshopperShared/Ops/Operations.VariableInputSendComponent.cs
- Core/Core/Credentials/StreamWrapper.cs
> CNX-8963: Grasshopper - Send node output URLs are incorrectly formatted incorrectly

- ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/Utils.cs
- Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.Organization.cs
- Restores the previous collection to native method (prior to [exception handling pr](https://github.com/specklesystems/speckle-sharp/pull/3111/files)) 
- no longer disposes created layers in connector utils 
Results when receiving Revit objects testing commit:
> Fix(rhino): restores previous collection to native method and no longer disposes created layer in connector

- Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.Civil.cs
Fixes an unhandled exception in the ProfileToSpeckle conversion which was missed during exception handling cleanup.
- civil3d converter
> CNX-8978: Civil3d missing elements due to unhandled exception

- ConnectorArchicad/ConnectorArchicad/Converters/ElementConverterManager.cs
Fix of https://spockle.atlassian.net/browse/CNX-8984
In case of opening elements' parents (roofs/shells of skylights or walls/slabs of doors/windows) are filtered out from send operation, a separate collection is created for the openings.
> fix(Archicad): Sending "Skylights" element type throws null reference

- ConnectorAutocadCivil/ConnectorAutocadCivil/UI/ConnectorBindingsAutocadCivil.Events.cs
Fixes regression in DUI saved stream updating with document event handling, caused by [this pr](https://github.com/specklesystems/speckle-sharp/pull/3119/files#diff-b6cd7f4d722cb29e541152b4256cbc85d8dc354014ff06e85337f13b7e580124L69)
Regression: creating new files (with no saved streams) did not update DUI saved streams when switching from a file with saved streams.
- autocad connector event handling
> fix(autocadcivil): Cnx 9042 creating a new file doesnt update DUI saved streams

- Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.Utils.cs
Missing application ids on nested instances are now set in the InstanceToNative method. This was resulting in some instances not correctly updating, leading to duplicate instances on update receive mode.
> bug(rhino): missing application ids when converting instances to native

- ConnectorArchicad/AddOn/Sources/AddOn/Commands/CreateCommand.cpp
- ConnectorArchicad/ConnectorArchicad/Converters/Converters/BeamConverter.cs
- ConnectorArchicad/ConnectorArchicad/Converters/Converters/ColumnConverter.cs
- ConnectorArchicad/ConnectorArchicad/Converters/Converters/FloorConverter.cs
- ConnectorArchicad/ConnectorArchicad/Converters/Converters/RoofConverter.cs
- ConnectorArchicad/ConnectorArchicad/Converters/Converters/RoomConverter.cs
- ConnectorArchicad/ConnectorArchicad/Converters/Converters/Utils.cs
- ConnectorArchicad/ConnectorArchicad/Converters/Converters/WallConverter.cs
https://spockle.atlassian.net/browse/CNX-9031
https://spockle.atlassian.net/browse/CNX-9040
1. C# Connector: Improved exception handling around native-to-native conversion from Revit to Archicad.
2. C++ Add-on: Layer attribute search error ignored
> fix(Archicad): CNX-9031 CNX-9040 Missing elements in Archicad from revit/objects stream and between localized versions of Archicads

- DesktopUI2/DesktopUI2/ViewModels/StreamViewModel.cs
Removes an unecessary `index == -1` check made in #3193.
> chore(dui): amends changes in #3193 to remove unecessary index check

- Core/Core/Transports/ServerUtils/ServerAPI.cs
`HttpRequestMessage` already disposes of the `MultiPartDataForm`,
And our excessive disposal of this was causing some nullreference exceptions when sending in Unity
Removing the `using` keyword appears to fix the issue.
https://github.com/microsoft/referencesource/blob/51cf7850defa8a17d815b4700b67116e3fa283c2/System/net/System/Net/Http/HttpRequestMessage.cs#L209
> Reverted disposal of multipart data form

- ConnectorRhino/ConnectorRhino8/ConnectorRhino8.csproj
Previously, the Rhino 8 connector was not building due to invalid paths for some dlls. This is fixed by targeting x64 on build.
> fix(rhino8): adds runtime identifier to rhino 8 connector

- .circleci/config.yml
- .circleci/scripts/config-template.yml
- .circleci/scripts/connector-jobs.yml
- .circleci/scripts/parameters.json
Update ci script to use `digicert-keylocker` context.
Additionally disabled diffing for now
> CI: Use Keylocker to sign releases

- Core/Core/Credentials/AccountManager.cs
- Core/Tests/Speckle.Core.Tests.Unit/Credentials/AccountServerMigrationTests.cs
We're now:
- Comparing same accounts using the user's ID
- Ensuring that when an account is upgraded it will get a new ID
- Fixed unit tests accordingly
> Fixing account equality

- Core/Core/Credentials/AccountManager.cs
Because the account id is changing, we no longer need to update the object. Instead, we delete the old object from the db and then save a new one.
> Feat(Core) : Remove account from db and save new one

- ConnectorRevit/ConnectorRevit/UI/ConnectorBindingsRevit.Receive.cs
When receiving in Revit in update mode, always deletes existing objects in a subtransaction. This fixes a bug where in certain conditions, attempts to delete existing objects are made without any active transaction.
This bug turned out to be completely unrelated to Sketchup direct shape mappings, but direct shapes are one of few objects that are properly "updated" (an existing direct shape object's shape is modified in update mode, vs the existing object being deleted and a new ds being created).
The following reproduction steps create the "failed update" behavior:
1. receive a direct shape
2. receive a new version of the same direct shape (same app id) on update mode -> success
3. receive a new version of a different direct shape (different app id) on update mode -> failure, existing …
> bug(revit): CNX-8730 deletes existing objects in a subtransaction during receive

- DUI3-DX/Connectors/Rhino/Speckle.Connectors.Rhino7/Bindings/RhinoSendBinding.cs
- DUI3-DX/DUI3/Speckle.Connectors.DUI/Bindings/IBasicConnectorBinding.cs
- DUI3-DX/DUI3/Speckle.Connectors.DUI/Bindings/SendBindingUICommands.cs
Fixes progress reporting in Rhino DUI3 DI connector.
The assumption that we could inject BasicBindings into the SendBinding and use the BasicBinding commands is not correct, as they have different bridges and that seems to conflict and error out on the JS side.
Solution I found that was somewhat acceptable is to use inheritance so that `SendBindingCommands` is now also a `BasicBindingCommands` and inherits every available command from it too.
This seems to work as expected, progress is reported on the C# side and shown correctly on the JS side
> fix(dui3): Make all basic binding commands available to sendbindings command type

- Core/Core/Logging/Analytics.cs
- Core/Core/Logging/Setup.cs
The `profile-union` and `profile-set` calls cannot be combined and were failing silently; this fixes that.
I'm pointing to `main` but this can go in any time, also in the next release.
> Fix(logging): profile union and set calls to analytics

- ConnectorRhino/ConnectorRhinoWebUI/Bindings/ReceiveBinding.cs
- ConnectorRhino/ConnectorRhinoWebUI/Bindings/SendBinding.cs
- ConnectorRhino/ConnectorRhinoWebUI/Utils/RawSelectionUnpackerAkaBlockManager.cs
- ConnectorRhino/ConnectorRhinoWebUI/Utils/Utils.cs
- Core/Core/Models/Extras.cs
- Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.Other.cs
It's a shift from the previous implementation. What we're doing: 
On Send: 
- converting atomic elements, and keeping them on their respective layers 
- creating proxies for instances (treated similarly as atomic objects) and instance definitions (held separately in the root object) 
- keeping track of the maximum depth at which an instance/instance definition is found
On Receive: 
- Stage 1: converting all atomic objects to their respective layers
- Stage 2: creating (connector bound) all required instance definitions and instances based on a simple sort order by their maximum depth, starting with definitions always
Works well :) Note the code is a mess and i'd want to port it to the new DI architecture as soon as we've got basic geometry receive conversions in.
> POC/WIP Implementation of Blocks (instances) for Rhino

- ConnectorRevit/ConnectorRevit/TypeMapping/ElementTypeMapper.cs
- DesktopUI2/DesktopUI2/ViewModels/TypeMappingOnReceiveViewModel.cs
As some users have reported, the element type mapper in Revit is not picking up all of the types in the document, only all of the types for the category of incoming object. This works well most of the time, but sometimes incoming types are incorrectly categorized. In this case, a use will not be able to map the type of the incoming object to the desired document type.
For example, foundation slabs in Revit are sent to Revit as floors. On receive, the element type mapper will pull all of the floor types from the document. However, foundation slabs use foundation types, not floor types. For this and other edge cases, this PR attempts to solve the issue by pulling all types from the document instead of just the detected category types.
I was initially worried about the performance of …
> CNX-9163 type mapping dialog not picking up loaded families

- ConnectorAutocadCivil/ConnectorAutocadCivil/UI/ConnectorBindingsAutocadCivil.Receive.cs
- ConnectorAutocadCivil/ConnectorAutocadCivil/UI/ConnectorBindingsAutocadCivil.Send.cs
- ConnectorRevit/ConnectorRevit/UI/ConnectorBindingsRevit.Receive.cs
- ConnectorRevit/ConnectorRevit/UI/ConnectorBindingsRevit.Send.cs
- ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/UI/ConnectorBindingsRhino.Receive.cs
- ConnectorRhino/ConnectorRhino/ConnectorRhinoShared/UI/ConnectorBindingsRhino.Send.cs
- Core/Core/Logging/Analytics.cs
- Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.cs
Adds two new events for mixpanel tracking: `SendObjectReport` and `ReceiveObjectReport`.
Attaches a dictionary containing each Speckle type found in the sent/received commit and their count, and tracks this event separately from send and receive events.
Added for AutoCAD, Rhino, and Revit.
> Hotfix(metrics): CNX-9196 add object type event tracking for mixpanel in autocad, rhino, and revit

- Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.Civil.cs
- Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.Geometry.cs
- README.md
Tested with the small surface test files, and no regressions (object ids perfectly match)
I'm not able to test any large surfaces, due to receive performance being awful still.
> perf(civil): CNX-9178 Civil: Optimised ToSpeckle conversion performance of Tin Surfaces

- DUI3-DX/Connectors/ArcGIS/Speckle.Connectors.ArcGIS3/Config.daml
- DUI3-DX/Connectors/ArcGIS/Speckle.Connectors.ArcGIS3/SpeckleDUI3ViewModel.cs
- DUI3-DX/Connectors/ArcGIS/Speckle.Connectors.ArcGIS3/SpeckleDUI3Wrapper.cs
- DUI3-DX/Connectors/ArcGIS/Speckle.Connectors.ArcGIS3/SpeckleModule.cs
The Esri template build targets would raise a msbuild warning that the namespace defined in the DAML file was misaligned with the default namespace of the project.
```
24>Esri.ArcGISPro.Extensions30.targets(327,6): Warning  : Your value of 'Speckle.Connectors.ArcGIS.HostApp' for the 'defaultNamespace' attribute in the Config.daml does not match the default namespace 'Speckle.Connectors.ArcGIS' set for your project.
```
This was introduced when we moved a couple of the connector UI files into the `HostApp` folder.
This PR moves the required files (the ones referenced in the daml) back into the root of the project, and sets the namespace in the daml file back to the root.
What this means for us: No more build warning for ArcGIS (reducing noise + pathing the way for us to enforce msbuild …
> CNX-9315 resolve warning singular in arc gis d ui3 dx connector

- Automate/Speckle.Automate.Sdk/AutomationContext.cs
Per the issue logged in the Automate Bug reports in February:
https://speckle.community/t/automate-bug-reports/9136/20
The functionality in this PR wasn't hooked up - you can compare it to the same lines in Specklepy: https://github.com/specklesystems/specklepy/blob/6469b6f757f00bb93041a835c04da71ceff1d3d6/src/speckle_automate/automation_context.py#L162 
So the Resulting Models subsection in for automations isn't populating in C#
> Brings CreateNewVersionInProject up to parity with SpeckePy

- DUI3-DX/Connectors/ArcGIS/Speckle.Connectors.ArcGIS3/DependencyInjection/AutofacArcGISModule.cs
- DUI3-DX/Connectors/Autocad/Speckle.Connectors.AutocadShared/Bindings/AutocadSelectionBinding.cs
- DUI3-DX/Connectors/Autocad/Speckle.Connectors.AutocadShared/HostApp/AutocadDocumentModelStore.cs
The previous assumption was that always will have a null doc whenever Bindings are created. But whenever we had a document opened already before bindings were created, we were missing track on the first doc and that's why it was failing to follow selections and feedback to UI with empty state if we're switching to the main screen in AutoCAD.
Another PR on UI side is -> https://github.com/specklesystems/speckle-server/pull/2231
Before
> Fix (autocad): CNX-9346 autocad document states are broken

- ConnectorRevit/ConnectorRevit/Entry/App.cs
- ConnectorRevit/ConnectorRevit/Entry/SpeckleRevitCommand.cs
- ConnectorRevit/ConnectorRevit/UI/ConnectorBindingsRevit.Events.cs
properly initialize revit plugin on file double-click
https://github.com/specklesystems/speckle-sharp/issues/1469
Original issue describing the problem in more detail
https://github.com/specklesystems/speckle-sharp/pull/3255
External PR that figured out how to fix the issue. We let it get too out of date and the logic was fairly straightforward so instead of resolving merge conflicts, I just made a new PR.
> CNX-9205 : Properly initialize connector on Revit file double-click

- DUI3-DX/DUI3/Speckle.Connectors.DUI/Models/Card/ReceiverModelCard.cs
We were seeing this error unnecessarily even if on latest version for saved receiver cards
> CNX-9373 saved model cards doesn t show correct state on latest version state

- Objects/Converters/ConverterRevit/ConverterRevitShared/ConversionUtils.cs
https://speckle.community/t/transferring-problem/10462
Debugging this community-reported bug, I noticed we're sending to Spekcle also any hidden element parameter; in this case, there are hundreds of huge parameters attached to some elements (maybe images or something else?) added, most likely via an adding.
I think we should ignore these props.
Ideally this PR would be released as hotfix sometime soon.
> fix(revit): exclude element params which are not visible

- DUI3-DX/Connectors/Autocad/Speckle.Connectors.AutocadShared/Bindings/AutocadBasicConnectorBinding.cs
- DUI3-DX/Connectors/Rhino/Speckle.Connectors.Rhino7/Bindings/RhinoBasicConnectorBinding.cs
- DUI3-DX/Connectors/Rhino/Speckle.Connectors.Rhino7/Bindings/RhinoReceiveBinding.cs
- DUI3-DX/DUI3/Speckle.Connectors.DUI/Models/Card/ReceiverModelCard.cs
`ReceiveResult` added into `ReceiverModelCard`
Revit doesn't have receive so we can do it later
> CNX 9372 highlighting loaded elements not working

- DUI3-DX/Connectors/ArcGIS/Speckle.Connectors.ArcGIS3/Bindings/ArcGISReceiveBinding.cs
- DUI3-DX/Connectors/Autocad/Speckle.Connectors.AutocadShared/Bindings/AutocadReceiveBinding.cs
- DUI3-DX/Connectors/Rhino/Speckle.Connectors.Rhino7/Bindings/RhinoReceiveBinding.cs
- DUI3-DX/DUI3/Speckle.Connectors.DUI.WebView/DUI3ControlWebView.xaml.cs
- Reintroduced lazy bindings to avoid a race condition (was very common in Rhino) where the document finishes loading before webview
- Removed cancellation swallowing so that DUI3 never gets into a state where the model cards were not updated with either a result or an exception
todo:
> Remove Cancellation Swallowing and re-Lazied the binding registration

- DUI3-DX/Connectors/Revit/Speckle.Connectors.RevitShared/HostApp/RevitDocumentStore.cs
Saving to file should be done even when no models exist.
> fix: Save to file even when no models exist (covers edge-case where last model was removed)

- DUI3-DX/Converters/Autocad/Speckle.Converters.AutocadShared/ToHost/Raw/AutocadPolycurveToHostPolyline2dRawConverter.cs
- DUI3-DX/Converters/Autocad/Speckle.Converters.AutocadShared/ToSpeckle/Geometry/Polyline2dToSpeckleConverter.cs
- DUI3-DX/Converters/Autocad/Speckle.Converters.AutocadShared/ToSpeckle/Geometry/PolylineToSpeckleConverter.cs
- Objects/Objects/Geometry/Autocad/AutocadPolycurve.cs
Guarantees thats autocad polycurves have segments in the correct start point/endpoint orientation sequence
This fixes curve rendering in the viewer:
[https://app.speckle.systems/projects/b53a53697a/models/66aca735ab](https://app.speckle.systems/projects/b53a53697a/models/66aca735ab)
> fix(autocad): CNX-9383 viewer sync for autocad polycurve

- DUI3-DX/Connectors/Autocad/Speckle.Connectors.AutocadShared/Plugin/AutocadCommand.cs
- DUI3-DX/Converters/Autocad/Speckle.Converters.AutocadShared/ToHost/Geometry/PolycurveToHostConverter.cs
- DUI3-DX/Converters/Autocad/Speckle.Converters.AutocadShared/ToHost/Raw/PolycurveToHostPolylineRawConverter.cs
Changes the Speckle DUI3 command in Autocad to "SpeckleNewUI" to align with other connectors
> feat(autocad): CNX-9417 ACAD align Speckle command name

- DUI3-DX/Connectors/Revit/Speckle.Connectors.RevitShared/Bindings/BasicConnectorBindingRevit.cs
- DUI3-DX/Connectors/Revit/Speckle.Connectors.RevitShared/Operations/Send/RootObjectBuilder.cs
- DUI3-DX/Converters/Revit/Speckle.Converters.Revit2023.DependencyInjection/AutofacRevitConverterModule.cs
- DUI3-DX/Converters/Revit/Speckle.Converters.RevitShared/GlobalUsings.cs
- DUI3-DX/Converters/Revit/Speckle.Converters.RevitShared/Helpers/IRevitConversionContextStack.cs
- DUI3-DX/Converters/Revit/Speckle.Converters.RevitShared/Helpers/RevitConversionContextStack.cs
- DUI3-DX/Converters/Revit/Speckle.Converters.RevitShared/Raw/ColumnConversionToSpeckle.cs
- DUI3-DX/Converters/Revit/Speckle.Converters.RevitShared/Raw/Geometry/CurveArrayConversionToSpeckle.cs
- DUI3-DX/Converters/Revit/Speckle.Converters.RevitShared/Raw/Geometry/LineConversionToSpeckle.cs
- DUI3-DX/Converters/Revit/Speckle.Converters.RevitShared/Raw/Geometry/MeshByMaterialDictionaryToSpeckle.cs
- DUI3-DX/Converters/Revit/Speckle.Converters.RevitShared/Raw/Geometry/MeshConversionToSpeckle.cs
- DUI3-DX/Converters/Revit/Speckle.Converters.RevitShared/Raw/Geometry/XyzConversionToPoint.cs
- DUI3-DX/Converters/Revit/Speckle.Converters.RevitShared/Raw/ModelCurveArrayToSpeckleConverter.cs
- DUI3-DX/Converters/Revit/Speckle.Converters.RevitShared/ReferencePointConverter.cs
- DUI3-DX/Converters/Revit/Speckle.Converters.RevitShared/Services/ScalingServiceToSpeckle.cs
- DUI3-DX/Converters/Revit/Speckle.Converters.RevitShared/ToSpeckle/DirectShapeConversionToSpeckle.cs
- DUI3-DX/Converters/Revit/Speckle.Converters.RevitShared/ToSpeckle/HostedElementConversionToSpeckle.cs
- DUI3-DX/Converters/Revit/Speckle.Converters.RevitShared/ToSpeckle/WallConversionToSpeckle.cs
Fixed Document.Document and also changed to always reference stack to always use IRevitConversionContextStack
We were using the UIDocument in the context and NO conversions should care about this document. I've changed this to inject Document instead of UIDocument so we don't have the somewhat silly Document.Document everywhere.
Additionally we added the IRevitConversionContextStack interface some time back to allow conversions to reference this interface instead of the concrete Revit type. I've updated all references and registrations now so they are correct and we now MUST reference IRevitConversionContextStack.
> Document.Document & IRevitConversionContextStack

- Core/Core/Helpers/Crypt.cs
- Core/Tests/Speckle.Core.Tests.Unit/Models/UtilitiesTests.cs
I have this as an alternative to #3282
Unlike #3282, this PR does introduce a breaking change, in that the same input will yield a different output.
This is because (as described by @secretlyagoblin the `BinaryFormatter` gives us more than just the char[] bytes, but also several bytes of type information) With this implementation, I've aligned the hashing behaviour with our Python SDK, which simply gets the UTF-8 encoded bytes.
I think we should consider accepting this breaking change, the implementation here is much simpler than having to patch in prefix as specified here https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-nrbf/eb503ca5-e1f6-4271-a7ee-c4ca38d07996, is already exactly what we're doing in Python SDK, and means there is less code for us to maintain.
---
I have …
> CNX-9158 - Replace `BinaryFormatter` with UTF-8 encoded bytes for SHA256 hash function

- DUI3-DX/Connectors/Revit/Speckle.Connectors.RevitShared/HostApp/RevitDocumentStore.cs
- DUI3-DX/Connectors/Revit/Speckle.Connectors.RevitShared/Plugin/RevitPlugin.cs
I have couple of findings on double-click file open issue,
1. Docable pane didn't register successfully if we try to do registration after `RevitTask.Initialize(uiApplication)`
2. Cef binding registirations didn't catch if we do it before `RevitTask.Initialize(uiApplication)` (causes black screen of UI)
3. There are no Revit event that we can trigger `ReadFromFile` and `OnDocumentChanged` functions after double-click open
1. Creating and registration of ribbons, buttons and panes done as first pass
2. Cef binding registrations done in `PostApplicationInit` function
3. `ReadFromFile` and `OnDocumentChanged` called in the constructor on `RevitDocumentStore`. Even if I don't like it, I couldn't find any other event or way for now
Comments welcome!
> CNX-9199 implement opening revit and dui3 when double clicking a file

- DUI3-DX/Converters/Autocad/Speckle.Converters.AutocadShared/ToHost/Geometry/EllipseToHostConverter.cs
- DUI3-DX/Converters/Autocad/Speckle.Converters.AutocadShared/ToSpeckle/Geometry/EllipseToSpeckleConverter.cs
Autocad Ellipse conversions were not taking into account trim domains before, resulting in incorrect elliptical arc conversions.
NOTE: viewer does not render trims on ellipses correctly: [https://app.speckle.systems/projects/b53a53697a/models/66aca735ab#threadId=29e9388ee4](https://app.speckle.systems/projects/b53a53697a/models/66aca735ab#threadId=29e9388ee4)
Receiving in Autocad:
Receiving in Rhino:
> fix(autocad): CNX-9497 adds trim domains to ellipse conversions

- ConnectorRevit/ConnectorRevit/Entry/App.cs
We've decided that the warning message for dll conflicts may not be necessary because we can rely on only notifying the user when a conflict happens such that an exception is thrown and the Speckle connector cannot be used.
> suppress warning dialog for potential dll conflicts

- DUI3-DX/Connectors/ArcGIS/Speckle.Connectors.ArcGIS3/Utils/ArcGisDocumentStore.cs
The way we can store metadata is writing it as XML. I do read/write metadata with `SpeckleModelCards` element into root metadata XML.
Tested and seems work fine but would be nice double-triple tests.
> CNX-9499 Save model cards into metadata and read/write on map init/switch

- Objects/Converters/ConverterCSI/ConverterCSIShared/ConverterCSIUtils.cs
Conversation on forum (https://speckle.community/t/revit-etabs-connection-scaling-issue/9916/15) revealed that etabs units were not being retreived correctly when the units were a mix of metric and imperial. This is because we were using Model.GetPresentUnits() which returned the following enum
Clearly, there are no options corresponding to mixed unit values such as imperial length and metric temperature. Now, I have switched the database unit retrieval method to Model.GetPresentUnits_2() which separates the units individually.
> CNX-9441-ETABS-to-Revit-Scaling-Issue

- DUI3-DX/Connectors/Rhino/Speckle.Connectors.Rhino7/DependencyInjection/AutofacRhinoModule.cs
- DUI3-DX/Connectors/Rhino/Speckle.Connectors.Rhino7/HostApp/SpeckleRhinoPanelHost.cs
It was painful to spot the problem and solution. Because there is a different behavior on closing and reopening Panels in Rhino.
On re-open --> It creates `SpeckleRhinoPanelHost` object and expects UIElement under `RhinoWindows.Controls.WpfElementHost` is not identical as before or empty. That was the problem before because we register `DUI3ControlWebView` as `SingleInstance` on Autofac. To fix this I've subscribed `Panels.Closed` event to Disconnect previous UIElement from `WpfHostElement`.
On re-open --> It doesn't try to create `SpeckleRhinoPanelHost`
To distinguish these two behaviors, we have static `Panels.IsPanelVisible` function. According to this flag either I disconnect UIElement or not.
Hopefully it is clear enough, otherwise you know my Discord address..
> CNX-9509 RHN opening up plugin panel again results in error

- DUI3-DX/Connectors/ArcGIS/Speckle.Connectors.ArcGIS3/Bindings/ArcGISSelectionBinding.cs
- DUI3-DX/Connectors/ArcGIS/Speckle.Connectors.ArcGIS3/Bindings/ArcGISSendBinding.cs
Currently the change detection only works for the change of the map elements, their properties and names, but NOT the change in the data source (actual features /data rows in the table). This requires dynamic subscription to every new layer on the map, and it is tricky to extract the layer id from the feature-changed event.
> Cnx 9502 agis object tracking change detection

- .circleci/scripts/config-template.yml
- ConnectorAutocadCivil/ConnectorAutocadCivil.sln
- Objects/Converters/ConverterAutocadCivil/ConverterCivil2025/ConverterCivil2025.csproj
- global.json
Prevents dotnet from rolling forward to untested versions. These could (and do) bring in more analyser fixes and edge-cases covered; which means more warnings/errors in code that previously was OK.
The current fix is not really the ideal solution, but rather a temporary measure to prevent CI from running on the latest version of dotnet.
Ideal fix will be described in an incoming ticket (INSERT CODE HERE) but TLDR:
- We should lock our `global.json` version with no rollForward policy, and instead actively choose to upgrade at will.
- We should build all our projects in net8 (where possible, Rhino 8 uses Net7 🤦🏼‍♂️)
**Sneaky addition**
Includes some changes in civil SLN file (was missing some projects) and a typo fix on the converter assembly name to align with the rest of versions
> fix(ci): Install <8.0.300 everywhere

- DUI3-DX/DUI3/Speckle.Connectors.DUI/Bridge/BrowserBridge.cs
Otherwise error message is rendered wrong on UI.
@JR-Morgan happy to consider if you have alternative.
Before
After
> Chore (dui3): error message from inner exception on sync functions

- DUI3-DX/Connectors/ArcGIS/Speckle.Connectors.ArcGIS3/Bindings/ArcGISSendBinding.cs
- DUI3-DX/Connectors/ArcGIS/Speckle.Connectors.ArcGIS3/Operations/Receive/HostObjectBuilder.cs
- DUI3-DX/Connectors/Autocad/Speckle.Connectors.AutocadShared/Operations/Receive/AutocadHostObjectBuilder.cs
- DUI3-DX/Connectors/Revit/Speckle.Connectors.RevitShared/Bindings/BasicConnectorBindingRevit.cs
- DUI3-DX/Connectors/Revit/Speckle.Connectors.RevitShared/Bindings/SendBinding.cs
- DUI3-DX/Connectors/Revit/Speckle.Connectors.RevitShared/Operations/Send/RevitRootObjectBuilder.cs
- DUI3-DX/Connectors/Rhino/Speckle.Connectors.Rhino7/Bindings/RhinoSendBinding.cs
- DUI3-DX/Connectors/Rhino/Speckle.Connectors.Rhino7/Operations/Receive/RhinoHostObjectBuilder.cs
- DUI3-DX/Converters/ArcGIS/Speckle.Converters.ArcGIS3/Utils/NonNativeFeaturesUtils.cs
- DUI3-DX/Converters/Autocad/Speckle.Converters.AutocadShared/ToHost/Raw/PolycurveToHostPolylineRawConverter.cs
- DUI3-DX/Converters/Revit/Speckle.Converters.RevitShared/Helpers/DisplayValueExtractor.cs
- DUI3-DX/Converters/Revit/Speckle.Converters.RevitShared/ReferencePointConverter.cs
In preparation for updating to net8 as our default SDK, there were a bunch of new warnings that appeared in 8.0.300 that needed to be adressed.
These are simple fixes:
- Use TryGetvalue in dictionaries
- Use Length != 0 instead of Any()
> fix: Warnings picked up in net8.0

- ConnectorGrasshopper/ConnectorGrasshopperShared/Extras/Utilities.cs
- ConnectorGrasshopper/ConnectorGrasshopperShared/Loader.cs
- ConnectorGrasshopper/ConnectorGrasshopperShared/SchemaBuilder/CreateSchemaObject.cs
- ConnectorGrasshopper/ConnectorGrasshopperShared/SchemaBuilder/CreateSchemaObjectBase.cs
> [!IMPORTANT]
> This PR targets `main` and should be released as part of the next hotfix `2.19.1`
https://spockle.atlassian.net/browse/CNX-9443
- Adds RHINO7_OR_GREATER to grasshopper
- Fixes GetVersionedAppName to use Loader equivalent. Did not delete it but flagged it as obsolete
- Fixed exception on initial open event in headless document run.
> CNX-9443 Rhino Compute units set as mm

- Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.Civil.cs
- Objects/Objects/Other/Civil/CivilDataField.cs
- Objects/Objects/Other/DataField.cs
Adds parts data to pipes and structures.
This implementation introduces 2 new classes: `DataField` (which functions as a generic `Parameter` class) and `CivilDataField:DataField` which includes civil3d-specific properties.
- Objects
- Civil3D converter
[https://speckle.xyz/streams/b53a53697a/commits/99b6ae2a03](https://speckle.xyz/streams/b53a53697a/commits/99b6ae2a03)
> CNX-9752 add parts data to pipes and structures

- Core/Core/Credentials/Account.cs
- Core/Core/Credentials/AccountManager.cs
- Core/Core/Models/Extensions/BaseExtensions.cs
- Core/Core/Models/GraphTraversal/DefaultTraversal.cs
- Core/Core/Models/GraphTraversal/GraphTraversal.cs
- Core/Core/Models/GraphTraversal/ITraversalRule.cs
- Core/Core/Models/GraphTraversal/RuleBuilder.cs
- Core/Core/Models/GraphTraversal/TraversalContextExtensions.cs
`Main` cherry pick of https://github.com/specklesystems/speckle-sharp/pull/3469
> Copy important changes to core from DUI3/alpha to main

- Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.Civil.cs
- Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.cs
- Objects/Objects/BuiltElements/Baseline.cs
- Objects/Objects/BuiltElements/Civil/CivilAppliedAssembly.cs
- Objects/Objects/BuiltElements/Civil/CivilAppliedSubassembly.cs
- Objects/Objects/BuiltElements/Civil/CivilBaseline.cs
- Objects/Objects/BuiltElements/Civil/CivilBaselineRegion.cs
- Objects/Objects/BuiltElements/Civil/CivilCalculatedLink.cs
- Objects/Objects/BuiltElements/Civil/CivilCalculatedPoint.cs
- Objects/Objects/BuiltElements/Civil/CivilCalculatedShape.cs
- Objects/Objects/Interfaces.cs
- Objects/Objects/Other/Civil/CivilDataField.cs
- Objects/Objects/Other/DataField.cs
This pr adds quite a few new `civil` classes and restructures how `corridor`s are sent from Civil3D:
- CivilBaseline
- CivilBaselineRegion
- CivilAppliedAssembly
- CivilAppliedSubassembly
- CivilCalculatedShape
- CivilCalculatedLink
- CivilCalculatedPoint
- ICivilCalculatedObject interface
Closes #3265
- Objects
- Civil converter
sample corridor commit: [https://app.speckle.systems/projects/bff55266ce/models/763d2dadb7](https://app.speckle.systems/projects/bff55266ce/models/763d2dadb7)
> CNX-9753: Add assembly and subassembly objects to Corridors

- Core/Core/Models/GraphTraversal/TraversalContextExtensions.cs
- Core/Tests/Speckle.Core.Tests.Unit/Models/GraphTraversal/TraversalContextExtensionsTests.cs
- DUI3-DX/Connectors/ArcGIS/Speckle.Connectors.ArcGIS3/Operations/Receive/HostObjectBuilder.cs
- DUI3-DX/Connectors/Rhino/Speckle.Connectors.Rhino7/Operations/Receive/RhinoHostObjectBuilder.cs
- DUI3-DX/Converters/ArcGIS/Speckle.Converters.ArcGIS3/Utils/GISAttributeFieldType.cs
- DUI3-DX/Converters/ArcGIS/Speckle.Converters.ArcGIS3/Utils/INonNativeFeaturesUtils.cs
- DUI3-DX/Converters/ArcGIS/Speckle.Converters.ArcGIS3/Utils/NonNativeFeaturesUtils.cs
- Directory.Build.props
> arc gis traversal cleanup

- ConnectorArchicad/ConnectorArchicad/Communication/Commands/Command_GetElementBaseData.cs
- ConnectorArchicad/ConnectorArchicad/Converters/Converters/DirectShapeConverter.cs
- ConnectorArchicad/ConnectorArchicad/Converters/Converters/Utils.cs
- Objects/Objects/BuiltElements/Archicad/DirectShape.cs
Fix of #3471.
`elementProperties` and `componentProperites` properties added to `Archicad.DirectShape` class
`GetElementBaseData` changed to be able to work with JSON raw data.
> bug(Archicad): Properties not showing in viewer

- ConnectorArchicad/AddOn/Sources/AddOn/AddOnMain.cpp
- ConnectorArchicad/AddOn/Sources/AddOn/Commands/CreateOpening.cpp
- ConnectorArchicad/AddOn/Sources/AddOn/Commands/CreateOpening.hpp
- ConnectorArchicad/AddOn/Sources/AddOn/Commands/CreateOpeningBase.cpp
- ConnectorArchicad/AddOn/Sources/AddOn/Commands/GetDoorData.hpp
- ConnectorArchicad/AddOn/Sources/AddOn/Commands/GetOpeningData.cpp
- ConnectorArchicad/AddOn/Sources/AddOn/Commands/GetOpeningData.hpp
- ConnectorArchicad/AddOn/Sources/AddOn/FieldNames.hpp
- ConnectorArchicad/AddOn/Sources/AddOn/ResourceIds.hpp
- ConnectorArchicad/AddOn/Sources/AddOn/TypeNameTables.cpp
- ConnectorArchicad/AddOn/Sources/AddOn/TypeNameTables.hpp
- ConnectorArchicad/ConnectorArchicad/Communication/Commands/Command_CreateOpening.cs
- ConnectorArchicad/ConnectorArchicad/Communication/Commands/Command_GetOpening.cs
- ConnectorArchicad/ConnectorArchicad/Converters/ConverterArchicad.cs
- ConnectorArchicad/ConnectorArchicad/Converters/Converters/OpeningConverter.cs
- ConnectorArchicad/ConnectorArchicad/Converters/Converters/Utils.cs
- ConnectorArchicad/ConnectorArchicad/Converters/ElementConverterManager.cs
- ConnectorArchicad/ConnectorArchicad/Converters/ElementTypeProvider.cs
- ConnectorArchicad/ConnectorArchicad/Converters/ModelConverter.cs
- Objects/Objects/BuiltElements/Archicad/ArchicadOpening.cs
Support for Archicad Openings (#3267):
* Sending Archicad Openings to Speckle
* openings are sent via the `elements` list of the parent element
* only rectangular and circular openings can be handled by Archicad API
* generating `outline` property for the common Speckle Opening class
* Receiving Archicad Openings from Speckle
* Either from `ArchicadOpening`
* or from Speckle `Opening` using the `outline` property
* Archicad to Revit workflow
* rectangular openings can go through
* Revit to Archicad workflow
* rectangular openings can go through (only rectangular openings are supported in Revit)
Objects:
* `ArchicadOpening` has been introduced
C# Connector:
* Opening converters added
C++ add-on:
* `GetOpening` ommand and `CreateOpening` commands added
- `objects.pln` has been updated with …
> feat(Archicad): Add support for openings

- DUI3-DX/Connectors/ArcGIS/Speckle.Connectors.ArcGIS3/Bindings/BasicConnectorBinding.cs
- DUI3-DX/Connectors/ArcGIS/Speckle.Connectors.ArcGIS3/Operations/Receive/HostObjectBuilder.cs
- DUI3-DX/Converters/ArcGIS/Speckle.Converters.ArcGIS3/Utils/ConversionTracker.cs
- DUI3-DX/Converters/ArcGIS/Speckle.Converters.ArcGIS3/Utils/INonNativeFeaturesUtils.cs
- DUI3-DX/Converters/ArcGIS/Speckle.Converters.ArcGIS3/Utils/NonNativeFeaturesUtils.cs
Restructuring HostObjectBuilder to track Base object ID -> MapLayerURI (including feature index, if applicable)
Visual explanation: https://www.notion.so/speckle/ArcGIS-explainers-e3c2571d0208409fa98fe87d41247c2d?pvs=4
Currenly, report Selection is selecting the entire layer with that feature, not considering the individual feature ID:
> DUI3-295 track non native received objects for the full report

- DUI3-DX/Connectors/ArcGIS/Speckle.Connectors.ArcGIS3/Bindings/ArcGISReceiveBinding.cs
- DUI3-DX/Connectors/ArcGIS/Speckle.Connectors.ArcGIS3/Bindings/ArcGISSendBinding.cs
- DUI3-DX/Connectors/Autocad/Speckle.Connectors.AutocadShared/Bindings/AutocadReceiveBinding.cs
- DUI3-DX/Connectors/Autocad/Speckle.Connectors.AutocadShared/Bindings/AutocadSendBinding.cs
- DUI3-DX/Connectors/Revit/Speckle.Connectors.RevitShared/Bindings/RevitSendBinding.cs
- DUI3-DX/Connectors/Rhino/Speckle.Connectors.Rhino7/Bindings/RhinoReceiveBinding.cs
- DUI3-DX/Connectors/Rhino/Speckle.Connectors.Rhino7/Bindings/RhinoSendBinding.cs
- DUI3-DX/DUI3/Speckle.Connectors.DUI/Bindings/IBasicConnectorBinding.cs
- DUI3-DX/Sdk/Speckle.Connectors.Utils/Cancellation/CancellationManager.cs
UI implementation is ready to merge -> https://github.com/specklesystems/speckle-server/pull/2363
- We have command for each binding to set any message to UI as global toast notification
- I removed all old `ICancelable` interface from send and receive bindings. Which was something talking with @JR-Morgan
- I aligned naming of `_cancellationManager` in bindings. Some of still was having setter on `CancellationManager`
- I have dup code now on RevitSendBinding, AutocadSendBinding and AutocadReceiveBinding for document switch logic to cancel out all active operations and then tell UI to show message.
- Feel free to suggest better "message" on doc switch 🙂
Also would like to sync @clairekuang before merging in!
> DUI3-174 Cancel ops on doc swap

- DUI3-DX/Connectors/ArcGIS/Speckle.Connectors.ArcGIS3/DependencyInjection/ArcGISConnectorModule.cs
- DUI3-DX/Connectors/Autocad/Speckle.Connectors.AutocadShared/DependencyInjection/AutocadConnectorModule.cs
- DUI3-DX/Connectors/Rhino/Speckle.Connectors.Rhino7/DependencyInjection/RhinoConnectorModule.cs
Expected behaviour: get a new root object builder every time we click "send". Reality: we didn't - this fixes that
Previously these components were registered as `InstancePerLifetimeScope` IIRC, they accidentaly became registed as singletons (`SingleInstance`), reverting back to `Scoped` (= `InstancePerLifetimeScope`)
> fix(dui3): corrects IRootObjectBuilder registration

- Core/Core/Serialisation/SerializationUtilities/ValueConverter.cs
- Core/Tests/Speckle.Core.Tests.Unit/Serialisation/SerializerBreakingChanges.cs
- Core/Tests/Speckle.Core.Tests.Unit/Serialisation/SerializerNonBreakingChanges.cs
- Objects/Tests/Objects.Tests.Unit/ModelPropertySupportedTypes.cs
https://github.com/specklesystems/speckle-sharp/pull/3451 introduced an issue where we were successfully serializing, but not  successfully deserializing `IReadOnlyList` properties.
This somehow got through my round of testing.... my bad! but thanks @gjedlicska for spotting this while 2.20 is still in wip! 🙌
---
1. Added support in our deserializer for `IList` and `IReadOnlyList` typed properties
2. Added a unit test for said support
3. Added a test in `Objects.Tests` to test that object model properties are one of the types supported by both our serializer and Deserializer (hard coded right now). Hopefully this will help ensure we never introduce this type of issue again.
> Added support for IReadOnlyList deserialization

- DUI3-DX/Sdk/Speckle.Converters.Common.DependencyInjection/ToHost/ConverterWithFallback.cs
If we don't throw exception here, later in the hostApp converter we won't be able to tell which object was it initially and report properly.
> better fallback reporting

- .github/workflows/ci.yml
- .github/workflows/main.yml
- Build/Program.cs
- DUI3-DX/Connectors/ArcGIS/Speckle.Connectors.ArcGIS3/packages.lock.json
- DUI3-DX/Connectors/Autocad/Speckle.Connectors.Autocad2023/packages.lock.json
- DUI3-DX/Connectors/Revit/Speckle.Connectors.Revit2023/packages.lock.json
- DUI3-DX/Connectors/Rhino/Speckle.Connectors.Rhino7/packages.lock.json
- DUI3-DX/Converters/ArcGIS/Speckle.Converters.ArcGIS3.DependencyInjection/packages.lock.json
- DUI3-DX/Converters/ArcGIS/Speckle.Converters.ArcGIS3/packages.lock.json
- DUI3-DX/Converters/Autocad/Speckle.Converters.Autocad2023.DependencyInjection/packages.lock.json
- DUI3-DX/Converters/Autocad/Speckle.Converters.Autocad2023/packages.lock.json
- DUI3-DX/Converters/Revit/Speckle.Converters.Revit2023.DependencyInjection/packages.lock.json
- DUI3-DX/Converters/Revit/Speckle.Converters.Revit2023/packages.lock.json
- DUI3-DX/Converters/Rhino/Speckle.Converters.Rhino7.DependencyInjection/packages.lock.json
- DUI3-DX/Converters/Rhino/Speckle.Converters.Rhino7/packages.lock.json
- DUI3-DX/DUI3/Speckle.Connectors.DUI.WebView/packages.lock.json
- DUI3-DX/DUI3/Speckle.Connectors.DUI/packages.lock.json
- DUI3-DX/Directory.Build.props
- DUI3-DX/Sdk/Speckle.Autofac/packages.lock.json
- DUI3-DX/Sdk/Speckle.Connectors.Utils/packages.lock.json
- DUI3-DX/Sdk/Speckle.Converters.Common.DependencyInjection/packages.lock.json
- DUI3-DX/Sdk/Speckle.Converters.Common.Tests/packages.lock.json
- DUI3-DX/Sdk/Speckle.Converters.Common/packages.lock.json
enable nuget lock files for dui3
- this will allow us to better monitor change in dependencies
- use lock files for restoration for repeatable builds
- cache nuget and restore for faster builds
> enable lock files for dui3

- DUI3-DX/Connectors/ArcGIS/Speckle.Connectors.ArcGIS3/Bindings/ArcGISSendBinding.cs
- DUI3-DX/Connectors/ArcGIS/Speckle.Connectors.ArcGIS3/Operations/Receive/HostObjectBuilder.cs
- DUI3-DX/Converters/ArcGIS/Speckle.Converters.ArcGIS3/Utils/NonNativeFeaturesUtils.cs
- don't repeatedly create the same layers (register ones already "baked")
- faster lookup & delete of existing datasets
- remove unnecessary subscriptions
> Agis speed improvement

- DUI3-DX/Connectors/ArcGIS/Speckle.Connectors.ArcGIS3/Operations/Receive/HostObjectBuilder.cs
- DUI3-DX/Converters/ArcGIS/Speckle.Converters.ArcGIS3/Utils/ArcGISFieldUtils.cs
- DUI3-DX/Converters/ArcGIS/Speckle.Converters.ArcGIS3/Utils/FeatureClassUtils.cs
- DUI3-DX/Converters/ArcGIS/Speckle.Converters.ArcGIS3/Utils/GISAttributeFieldType.cs
- DUI3-DX/Converters/ArcGIS/Speckle.Converters.ArcGIS3/Utils/IArcGISFieldUtils.cs
- DUI3-DX/Converters/ArcGIS/Speckle.Converters.ArcGIS3/Utils/IFeatureClassUtils.cs
- DUI3-DX/Converters/ArcGIS/Speckle.Converters.ArcGIS3/Utils/NonNativeFeaturesUtils.cs
UPD: receiving of non-native properties has been turned into a placeholder until we find better strategy for sending props from host apps. 
Purpose is to preserve objects properties when placing them into GIS layers(tables).
Current approach is to iterate through all objects that will be placed under the same layer and collect their property names and their Type (e.g. string, int) while defaulting to string if nothing better fits).
The opinionated choice of non-native properties to receive is:
- all properties that are not Base: Dynamic for "Objects.Geometry" and Typed for everything else
- Base properties if its Revit "properties" or Rhino "userStrings"
P.S. atm the following exception is being generated inconsistently, needs better understanding. Thrown during "Conversion" step, so …
> D ui3 123 receiving non native attributes revit params gh attributes etc

- Core/Tests/Speckle.Core.Tests.Integration/ServerTransportTests.cs
Our server transport tests were failing locally because a local SQLite DB was failing to be cleaned up.
However, these tests were not designed to run with a local SQLite DB.
We were explicitly not sending data to a SQLite transport, but we weren't explicitly opting out on the Receive side.
This PR opts us out by specifying a clean MemoryTransport for receives.
> Fixes integration tests

- DUI3-DX/Converters/ArcGIS/Speckle.Converters.ArcGIS3.DependencyInjection/ArcGISConverterModule.cs
- DUI3-DX/Converters/Autocad/2023/Speckle.Converters.Autocad2023.DependencyInjection/AutocadConverterModule.cs
- DUI3-DX/Converters/Autocad/2024/Speckle.Converters.Autocad2024.DependencyInjection/AutocadConverterModule.cs
- DUI3-DX/Converters/Revit/Speckle.Converters.Revit2023.DependencyInjection/RevitConverterModule.cs
- DUI3-DX/Converters/Rhino/Speckle.Converters.Rhino7.DependencyInjection/RhinoConverterModule.cs
- DUI3-DX/Sdk/Speckle.Converters.Common.DependencyInjection/ContainerRegistration.cs
Separates root (top level) converter registration in the container registration from the raw application converters.
Updates all converter dependency injection projects to use this new registration
> DUI3-464: Separates root and raw converter registration

- DUI3-DX/Converters/Revit/Speckle.Converters.RevitShared/Speckle.Converters.RevitShared.projitems
- DUI3-DX/Converters/Revit/Speckle.Converters.RevitShared/ToHost/TopLevel/GridlineToHostTopLevelConverter.cs
Adds gridline convertion to Revit
Can now receive gridlines at various angles
> Dui3 178 gridlines

- Core/Core/Models/Extensions/BaseExtensions.cs
- Core/Tests/Speckle.Core.Tests.Unit/Models/Extensions/DisplayValueTests.cs
hotfix for regression with dynamic displayValues `List<object>` not being picked up by displayValue helper functions
> fix(core): Fixed issue with DisplayValue helper functions

- Core/Core/Helpers/Http.cs
We don't want to see duplicated `/` in uris, like this:
As described in the documentation, the Uri.PathAndQuery will return the leading path separator so the formatting context should not introduce another one: https://learn.microsoft.com/en-us/dotnet/api/system.uri?view=net-8.0#examples
> fix(core/http): log message should not duplicate path separator

- Objects/Converters/ConverterRhinoGh/ConverterRhinoGhShared/ConverterRhinoGh.Other.cs
Running headless, the copy of the RH.Material yields null when passed to RenderMaterial.FromMaterial(material, Doc), which results the conversion throwing since the following calls assume a non nullable Material.
I have tried to make the minimum intervention.
- Check if headless, and if so do not use the copy of the material but the original.
Before and after 💯
https://developer.rhino3d.com/api/rhinocommon/rhino.render.rendermaterial/frommaterial
> fix: if headless use original material

- ConnectorAutocadCivil/ConnectorAutocadCivil/UI/ConnectorBindingsAutocadCivil.Send.cs
- ConnectorAutocadCivil/ConnectorAutocadCivil/Utils.cs
- Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.Civil.cs
community thread: [https://speckle.community/t/property-set-grayed-when-exporting-data-from-civil-3d/12512/4](https://speckle.community/t/property-set-grayed-when-exporting-data-from-civil-3d/12512/4)
This pr changes property sets and parts data on civil3d objects to be sent as `Base` instead of `List`. This better aligns with how we are sending parameters from other applications, and allows for contents to be displayed in the default viewer object explorer mode.
Sample commit: [https://app.speckle.systems/projects/b53a53697a/models/719612f9da](https://app.speckle.systems/projects/b53a53697a/models/719612f9da)
> chore(civil3d): changes property sets and parts data to be a `Base`

- ConnectorArchicad/AddOn/Sources/AddOn/Commands/GetDataCommand.cpp
Xcode interprets C-string as char array (serialises in JSON as array rather than string, breaks deserialisation in connector)
> Fix: Corrects serialised data from Archicad (macOS)

- Objects/Converters/ConverterAutocadCivil/ConverterAutocadCivilShared/ConverterAutocadCivil.Civil.cs
- Objects/Objects/BuiltElements/Baseline.cs
- Objects/Objects/BuiltElements/Civil/CivilAppliedSubassembly.cs
- Objects/Objects/BuiltElements/Civil/CivilBaselineRegion.cs
- Objects/Objects/BuiltElements/Civil/CivilCalculatedLink.cs
- Objects/Objects/BuiltElements/Civil/CivilCalculatedPoint.cs
adds units to some civil classes added in 2.20 that were msising them, as well as the civil3d conversions.
> fix(civil3d): added units to civil classes missing them

- Core/Core/Api/GraphQL/Client.cs
- Core/Core/Helpers/Http.cs
- Core/Core/Transports/ServerUtils/ServerAPI.cs
- Fixed reporting of retries: 
- We were never incrementing the retry number given to the logger, so it was allways reporting as 0 even if it had retried.
- Looks like a regression introduced by https://github.com/specklesystems/speckle-sharp/pull/2305 when we commented out some logging.
- Also fixed the headers which previously were appending new correlation ids with every retry.
- Removed ancient flawed retries loop in ServerAPI
- Clients already retry with proper backoff policy, this naive loop was only causes problems for the server.
> Retry Fixes

- Objects/Converters/ConverterRevit/ConverterRevitShared/ConverterRevit.cs
- Objects/Converters/ConverterRevit/ConverterRevitShared/PartialClasses/ConvertPolygonElement.cs
duplicating attribute receive functionality from GisPolygon to GisFeature
> QGIS attributes in Revit

- ConnectorAutocadCivil/ConnectorAutocadCivil/UI/ConnectorBindingsAutocadCivil.Receive.cs
- ConnectorAutocadCivil/ConnectorAutocadCivil/Utils.cs
Fixes community reported bug on receiving property sets due to change of type to `Base`. 
sample commit: [https://app.speckle.systems/projects/b53a53697a/models/899753a050](https://app.speckle.systems/projects/b53a53697a/models/899753a050)
Also changes the name of property sets to use the definition name instead of the applied set name.
> fix(civil3d): prop sets & changes name to definition name

- ConnectorArchicad/ConnectorArchicad/Converters/ModelConverter.cs
Fix: Change handling of non-polyline openings to throw SpeckleException rather than nulling object refs (which throws an exception terminating the receive)
> Fix: Throw SpeckleException on unhandled elements

- Objects/Converters/ConverterRevit/ConverterRevitShared/PartialClasses/ConvertArea.cs
- Objects/Converters/ConverterTeklaStructures/ConverterTeklaStructuresShared/PartialClasses/ConvertContourPlate.cs
- Objects/Objects/BuiltElements/AdvanceSteel/AsteelPlate.cs
- Objects/Objects/BuiltElements/AdvanceSteel/AsteelSlab.cs
- Objects/Objects/BuiltElements/Area.cs
- Objects/Objects/BuiltElements/TeklaStructures/TeklaContourPlate.cs
Implements `displayValue` to be the Area outline as there is no method to retrieve or generate a `Mesh`
> CNX-9912 - Implement a display fallback for Revit Areas equivalent to the outline.

- ConnectorCore/DllConflictManagement/DllConflictManager.cs
As found here: https://speckle.community/t/dllconflictmanager-throwing-error-in-revit/12589
> add null check around assembly & location

- ConnectorCore/DllConflictManagement/DllConflictManager.cs
This seems to fix the issue with Revit 2025 and AIT mentioned here: https://speckle.community/t/issue-with-revit-2025-will-not-load/12445/26
AIT produces this exception with the conflict manager but isn't a conflict for the speckle plugin on Revit 2025.  The exception is new with .NET Core so swallowing should be safe for v2.
> Swallow an exception specific for .NET Core and other plugins

- Core/Core/Core.csproj
- Core/Core/Logging/SpeckleLog.cs
Removed `Serilog.Enrichers.ClientInfo`
The CVE reported https://github.com/advisories/GHSA-5x5q-cqf6-gj8r is not critical for us, any log IP addresses are not trusted.
But for the sake of us not having to supress warning categories, its easy enough for us just to remove these dependencies.
---
also removed `Serilog.Enrichers.GlobalLogContext` since we aren't using it, and haven't been for several releases
> Removed vulnerable packages

- ConnectorGrasshopper/ConnectorGrasshopperShared/BaseComponents/ComponentTracker.cs
- ConnectorGrasshopper/ConnectorGrasshopperShared/Ops/Operations.SyncReceiveComponent.cs
- ConnectorGrasshopper/ConnectorGrasshopperShared/Ops/Operations.VariableInputReceiveComponent.cs
Fixes tracking in the receive node to use the tracker that has the proper host app and host app versions overloaded
Update tracker class to allow all properties tracked on receive
> fix: Update receive node with proper tracking

- Core/Core/Api/GraphQL/Client.cs
- Core/Core/Api/GraphQL/Models/Project.cs
- Core/Tests/Speckle.Core.Tests.Integration/Speckle.Core.Tests.Integration.csproj
- Core/Tests/Speckle.Core.Tests.Unit/Speckle.Core.Tests.Unit.csproj
- DesktopUI2/DesktopUI2/ViewModels/StreamViewModel.cs
This PR adds `workspace_id` tracking for Receive and Send events.
---
I was going to add support for fetching the workspace id to all of the `ProjectResource` queries, like I've done for the v3 sdk https://github.com/specklesystems/speckle-sharp-sdk/pull/134
But, since its important that the v2 SDK is compatible with older self hosted servers, I thought it would be easiest simply to
add a helper function just for this query. This avoids having to add  a version check in each of the Project resources (which, at least right now in their current form don't have direct access to the underlying `GqlClient`.
---
Needs through testing:
- Test with app.speckle.systems:
- Test with testing1
> Added workspace Id tracking

- ConnectorNavisworks/ConnectorNavisworks/Other/Elements.cs
Modified the LINQ query for property grouping to retain all groups regardless of value uniqueness, rather than filtering out groups with different values. Now takes the first value encountered for each key instead of requiring all values to be identical.
```csharp
.Where(
group => group.Select(
item => item.Value
).Distinct().Count() == 1
)
```
Previously filtered out any groups where values differed, only keeping groups with identical values.
```csharp
// Simplified to just take first value for each key
.ToDictionary(
group => group.Key,
group => group.Select(item => item.Value).First()
)
```
The previous logic was too restrictive, discarding valid property groups just because they had different values. The new approach preserves all property groups while maintaining deterministic value …
> fix(navis): Fixes missing element properties on coalesce from First Selected object.

- Core/Core/Api/GraphQL/Inputs/VersionInputs.cs
- Core/Tests/Speckle.Core.Tests.Integration/Api/GraphQL/Resources/VersionResourceTests.cs
A breaking change was made to our GraphQL api to require project ids on the VersionUpdate, VersionMoveToModel, and VersionDelete inputs.
This PR updates the sharp SDK with this change
see also https://github.com/specklesystems/specklepy/pull/353
> Updated version inputs

- Objects/Converters/ConverterRevit/ConverterRevitShared/PartialClasses/ConvertDirectShape.cs
Fix for: https://speckle.community/t/grasshopper-to-revit-shared-parameters-not-updating/15351/6
> fix: update direct shape parameters when it already exists

- .circleci/scripts/config-template.yml
Deploy is failing because Manager.Feed is still expecting .NET6 SDK
> Revert deploy step to use .NET 6 SDK for Manager Feed

- Core/Core/Api/GraphQL/Models/ServerInfo.cs
- Core/Core/Credentials/AccountManager.cs
- Core/Tests/Speckle.Core.Tests.Integration/Credentials/UserServerInfoTests.cs
#3672 is failing on integration tests since it changes, since we change the ping URL to  `/favicon.ico`, and this doesn't return the `x-speckle-frontend-2` header.
With approval from @gjedlicska, I'm now assuming that all accounts are FE2. Since FE1 is deprecated. This only thing that this affects is:
- DUI2 UI terminology
- StreamWrapper `ToString()` (i.e. we'll be sending people to FE2 formatted urls even if they're on FE1)
> Removed frontend headers check for FE1 servers

- Core/Core/Api/GraphQL/Legacy/Client.GraphqlCleintOperations/Client.StreamOperations.cs
- DesktopUI2/DesktopUI2/Views/Controls/StreamDetails.xaml
This is done for two reasons:
1. Favourited streams was a feature of FE1, thus its visual noise in the UI
2. The query that populates the `HomeView` with stream info is very heavy, and @fabis94 was seeing this lead to hundreds of SQL queries. This was an easy win for us to remove a bit of complexity from that query.
Before:
After:
> Removed favourite stream count from DUI2 stream view

- ConnectorGrasshopper/ConnectorGrasshopperShared/Extras/Utilities.cs
Do not assume internal storage `m_value` will exist in all GH_Goo's, some have varying implementation, but `Value` is usually consistent on all pre-rhino8 GH types
> fix(gh): Use external getter for `Value` property

- Objects/Converters/ConverterCSI/ConverterCSIShared/PartialClasses/Geometry/ConvertFrame.cs
- Objects/Converters/ConverterCSI/ConverterCSIShared/PartialClasses/Loading/Loading1DElements.cs
`Grasshopper` to `ETABS` workflow was broken when it came to assigning of frame loads. Reported in [Grasshopper to Etabs Import- Loads fail to load](https://speckle.community/t/grasshopper-to-etabs-import-loads-fail-to-load/17687/1) .
There were some pretty concerning issues:
- Attempt to assign the wrong load type (`if` statement is just wrong):
```
if (loadBeam.loadType == BeamLoadType.Point)
{
success = Model.FrameObj.SetLoadDistributed(
```` 
- Discarding `name` completely, which is for ETABS' sake very important
- Use the `name` in `FrameToNative`
- Assign the correct load type in `LoadFrameToNative`
https://github.com/user-attachments/assets/999cbd04-a762-497f-a637-0e9ff576a83c
[Grasshopper to Etabs Import- Loads fail to load](https://speckle.community/t/grasshopper-to-etabs-import-l …
> fix: etabs frame loads on receive

- DesktopUI2/DesktopUI2/Views/Windows/Dialogs/NewStreamDialog.xaml
- DesktopUI2/DesktopUI2/Views/Windows/Dialogs/NewStreamDialog.xaml.cs
- Added call to action "Explore Plans" when trying to create a project where workspace limit is reached.
- Ensure cancellation to prevent the UI from showing the wrong servers workspaces when quickly switching between
> feat(ui): Add call to action button for project create

- All.sln
- ConnectorAutocadCivil/ConnectorAutocadCivil/Entry/App.cs
- ConnectorAutocadCivil/ConnectorAutocadCivil/Entry/SpeckleAutocadCommand.cs
Rhino and AutoCAD toolbars also need updating to the changed command name
> chore: Renamed command in Rhino and Autocad toolbars
